### ISSUE TITLE
Update manual page for logging features

### ISSUE THREAD

**Issue by mbr0wn** [gnuradio/gnuradio#1005]
Logging manual page does not discuss how to output variable values in logging messages.

Basically need to add simple examples of using boost::format(xxx).

**Comment by marcusmueller** [comment]
https://wiki.gnuradio.org/index.php/Logging
 would be the new place, maybe?

**Comment by duggabe** [comment]
Since there is an adequate https://wiki.gnuradio.org/index.php/Logging page now, shouldn't this be closed?

**Comment by mbr0wn** [comment]
Yeah let's close.
