### ISSUE TITLE
gr::prefs doesn't look any further after failing to read prefsdir

### ISSUE THREAD

**Issue by mbr0wn** [gnuradio/gnuradio#1013]
Citing prefs.cc

<pre>
  std::vector<std::string>
  prefs::_sys_prefs_filenames()
  {
    std::vector<std::string> fnames;

    fs::path dir = prefsdir();
    if(!fs::is_directory(dir))
      return fnames;
</pre>

@prefsdir@ is defined in constants.cc.in:

<pre>
 43   const std::string
 44   prefsdir()
 45   {
 46     return "@GR_PREFSDIR@";
 47   } 
</pre>

... which is a pity, because this means that a GNU Radio installation with an nonexistant/non-readable @${SYSCONFDIR}/${CMAKE_PROJECT_NAME}/conf.d@ (see main CMakeLists.txt) is unconfigurable. Note: that pathspec might also not be very portable!

Courses of action I think might be viable:
- just ignoring that directory and still reading the user home dir config
- allowing that directory to be set via env variable
- both

**Comment by marcusmueller** [comment]
I *think* we solved this in #2475, #2476
