### ISSUE TITLE
USRP frequency tag shows value before DSP (just LO)

### ISSUE THREAD

**Issue by mbr0wn** [gnuradio/gnuradio#1016]
The tags send by the USRP source are sending the value of the LO and not the effective carrier frequency after digital signal processing in the FPGA.
Further, when looking at it with the tag debug block the value is rounded so much that the problem is not visible.
We found the issue when we used the frequency value from the tag in our python application and it was always slightly different

Here some code to understand the issue:

$> usrp_source.set_center_freq(2510000000)
-- Tune Request: 2510.000000 MHz
--   The RF LO does not support the requested frequency:
--     Requested LO Frequency: 2510.000000 MHz
--     RF LO Result: 2509.999999 MHz
--   Attempted to use the DSP to reach the requested frequency:
--     Desired DSP Frequency: -0.000001 MHz
--     DSP Result: -0.000001 MHz
## --   Successfully tuned to 2510.000000 MHz

$> usrp_source.get_center_freq()
2509999999.9999976
## The rounded information in the tag

Tag Debug:.
Input Stream: 00
  Offset: 0  Source: gr uhd usrp source3     Key: rx_time   Value: {1467142702 0.45}
  Offset: 0  Source: gr uhd usrp source3     Key: rx_rate   Value: 5e+07

**Comment by noc0lour** [comment]
Looking at the corresponding code it looks like `usrp_source` is doing the right thing and returns `multi_usrp->get_rx_freq()`. I suspect this is just the usual float/double rounding error if you try to add "small" number in double representation. Which comes really close to the desired value but is not excatly right.
