### ISSUE TITLE
Writing an optimized LaTeX bot

### ISSUE THREAD

**Issue by mbr0wn** [gnuradio/gnuradio#1022]
As requested:

Tim, please write a better LaTeX bot.

**Comment by mbr0wn** [comment]
Author: Marcus Müller
Date: Wed, 10 August 2016 19:34:38

![][1] 

    

  [1]: http://gnuradio.org/redmine/attachments/download/975/ticket.png

**Comment by marcusmueller** [comment]
This backfired. I have become the LaTeX bot.
