### ISSUE TITLE
Bug (w/fix): performance counters' clock option is honored only when controlport is enabled

### ISSUE THREAD

**Issue by pjlobo** [gnuradio/gnuradio#1035]
Just as the title says. The code that sets the performance counters' clock type is in gr::top_block::setup_rpc(), which is only called if controlport is enabled and active. It should not be that way as performance counters can be used without controlport.

I have sent a pull request ([#1034](https://github.com/gnuradio/gnuradio/pull/1034)) that fixes the problem by moving that code to gr::top_block::start(). It works fine that way, but I'm not sure whether it is the best place to do that.

**Comment by jmcorgan** [comment]
Fixed in #1034
