### ISSUE TITLE
GNU Radio: Add "flow control" mechanism to response port #685

### ISSUE THREAD

**Issue by balister** [gnuradio/gnuradio#1039]
Martin made me do this.

**Comment by jmcorgan** [comment]
@mbr0wn Can you be more descriptive about what this is?

**Comment by mbr0wn** [comment]
This is about querying the buffer fullness of the device e.g. from a message port. For building low-latency apps, this is nice, because source blocks can be smarter about generating data.

**Comment by jmcorgan** [comment]
Ah, got it.  I did something sort of like this once a while back by having a block near the end of a flowgraph send an async message back to a source block advertising its buffer space remaining, like in TCP.

**Comment by douggeiger** [comment]
@mbr0wn: is this something different from the buffer state that is currently available via ctrlport?

**Comment by mbr0wn** [comment]
Yes, this is about the buffer state on the hardware (not the block).

**Comment by douggeiger** [comment]
Ah, understood, thanks!

**Comment by marcusmueller** [comment]
I think this gotten solved through @dkozel & @MattEttus writing that flow control OOT
