### ISSUE TITLE
Raspberry Pi install GnuRadio 3.4.2

### ISSUE THREAD

**Issue by K1two2** [gnuradio/gnuradio#1057]
Raspberry Pi 3 Model B
2016-05-27-raspbian-jessie
USRP1
GnuRadio 3.4.2

> sudo apt-get install libaudio-dev
> sudo apt-get -y install libxi-dev
> 
> sudo apt-get -y install libfontconfig1-dev libxrender-dev libpulse-dev \
> swig g++ automake autoconf libtool python-dev libfftw3-dev \
> libcppunit-dev libboost-all-dev libusb-dev fort77 sdcc sdcc-libraries \
> libsdl1.2-dev python-wxgtk2.8 git-core guile-1.8-dev \
> libqt4-dev python-numpy ccache python-opengl libgsl0-dev \
> python-cheetah python-lxml doxygen qt4-dev-tools \
> libqwt5-qt4-dev libqwtplot3d-qt4-dev pyqt4-dev-tools python-qwt5-qt4
> 
> wget http://gnuradio.org/redmine/attachments/download/798/gnuradio-3.4.2.tar.gz
> tar zxvf gnuradio-3.4.2.tar.gz
> cd gnuradio-3.4.2

Error message：

> root@raspberrypi:/opt/gnuradio-3.4.2# ./configure --disable-all-components --with-fusb-tech=libusb --enable-usrp --enable-gruel --enable-gnuradio-core --disable-gr-usrp --disable-usrp2 --enable-config
checking build system type... armv7l-unknown-linux-gnueabihf
checking host system type... armv7l-unknown-linux-gnueabihf
checking target system type... armv7l-unknown-linux-gnueabihf
checking for git... /usr/bin/git
checking existence of git version control directory... not found
configure: GNU Radio Release 3.4.2
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /bin/mkdir -p
checking for gawk... no
checking for mawk... mawk
checking whether make sets $(MAKE)... yes
checking how to create a ustar tar archive... gnutar
checking for style of include used by make... GNU
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking dependency style of gcc... gcc3
checking how to run the C preprocessor... gcc -E
checking for grep that handles long lines and -e... /bin/grep
checking for egrep... /bin/grep -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking minix/config.h usability... no
checking minix/config.h presence... no
checking for minix/config.h... no
checking whether it is safe to define __EXTENSIONS__... yes
checking for library containing strerror... none required
checking for g++... g++
checking whether we are using the GNU C++ compiler... yes
checking whether g++ accepts -g... yes
checking dependency style of g++... gcc3
checking how to run the C++ preprocessor... g++ -E
checking gr_libdir_suffix... 
checking whether to append 64 to libdir... no
checking whether gcc accepts -Wall... yes
checking whether gcc accepts -Werror-implicit-function-declaration... yes
checking whether g++ accepts -Wall... yes
checking whether g++ accepts -Woverloaded-virtual... yes
checking whether user wants gprof... no
checking whether user wants prof... no
checking dependency style of gcc... gcc3
checking whether ln -s works... yes
checking whether make sets $(MAKE)... (cached) yes
checking for rm... /bin/rm
checking for a sed that does not truncate output... /bin/sed
checking for fgrep... /bin/grep -F
checking for ld used by gcc... /usr/bin/ld
checking if the linker (/usr/bin/ld) is GNU ld... yes
checking for BSD- or MS-compatible name lister (nm)... /usr/bin/nm -B
checking the name lister (/usr/bin/nm -B) interface... BSD nm
checking the maximum length of command line arguments... 1572864
checking whether the shell understands some XSI constructs... yes
checking whether the shell understands "+="... yes
checking for /usr/bin/ld option to reload object files... -r
checking for objdump... objdump
checking how to recognize dependent libraries... pass_all
checking for ar... ar
checking for strip... strip
checking for ranlib... ranlib
checking command to parse /usr/bin/nm -B output from gcc object... ok
checking for dlfcn.h... yes
checking whether we are using the GNU C++ compiler... (cached) yes
checking whether g++ accepts -g... (cached) yes
checking dependency style of g++... (cached) gcc3
checking how to run the C++ preprocessor... g++ -E
checking for objdir... .libs
checking if gcc supports -fno-rtti -fno-exceptions... no
checking for gcc option to produce PIC... -fPIC -DPIC
checking if gcc PIC flag -fPIC -DPIC works... yes
checking if gcc static flag -static works... yes
checking if gcc supports -c -o file.o... yes
checking if gcc supports -c -o file.o... (cached) yes
checking whether the gcc linker (/usr/bin/ld) supports shared libraries... yes
checking whether -lc should be explicitly linked in... no
checking dynamic linker characteristics... GNU/Linux ld.so
checking how to hardcode library paths into programs... immediate
checking whether stripping libraries is possible... yes
checking if libtool supports shared libraries... yes
checking whether to build shared libraries... yes
checking whether to build static libraries... no
checking for ld used by g++... /usr/bin/ld
checking if the linker (/usr/bin/ld) is GNU ld... yes
checking whether the g++ linker (/usr/bin/ld) supports shared libraries... yes
checking for g++ option to produce PIC... -fPIC -DPIC
checking if g++ PIC flag -fPIC -DPIC works... yes
checking if g++ static flag -static works... yes
checking if g++ supports -c -o file.o... yes
checking if g++ supports -c -o file.o... (cached) yes
checking whether the g++ linker (/usr/bin/ld) supports shared libraries... yes
checking dynamic linker characteristics... GNU/Linux ld.so
checking how to hardcode library paths into programs... immediate
checking for python... /usr/bin/python
checking for python version... 2.7
checking for python platform... linux2
checking for python script directory... ${prefix}/lib/python2.7/dist-packages
checking for python extension module directory... ${exec_prefix}/lib/python2.7/dist-packages
checking for Python include path... /usr/include/python2.7
checking Python.h usability... yes
checking Python.h presence... yes
checking for Python.h... yes
checking for guile... /usr/bin/guile
checking for guile-config... /usr/bin/guile-config
checking for library containing lt_dladvise_global... -lltdl
checking for swig... /usr/bin/swig
checking for SWIG version... 2.0.12
checking for xmlto... no
checking for socket in -lsocket... no
checking sys/ipc.h usability... yes
checking sys/ipc.h presence... yes
checking for sys/ipc.h... yes
checking sys/shm.h usability... yes
checking sys/shm.h presence... yes
checking for sys/shm.h... yes
checking for library containing shmat... none required
checking for ANSI C header files... (cached) yes
checking for sys/wait.h that is POSIX.1 compatible... yes
checking fcntl.h usability... yes
checking fcntl.h presence... yes
checking for fcntl.h... yes
checking limits.h usability... yes
checking limits.h presence... yes
checking for limits.h... yes
checking for strings.h... (cached) yes
checking time.h usability... yes
checking time.h presence... yes
checking for time.h... yes
checking sys/ioctl.h usability... yes
checking sys/ioctl.h presence... yes
checking for sys/ioctl.h... yes
checking sys/time.h usability... yes
checking sys/time.h presence... yes
checking for sys/time.h... yes
checking for unistd.h... (cached) yes
checking linux/ppdev.h usability... yes
checking linux/ppdev.h presence... yes
checking for linux/ppdev.h... yes
checking dev/ppbus/ppi.h usability... no
checking dev/ppbus/ppi.h presence... no
checking for dev/ppbus/ppi.h... no
checking sys/mman.h usability... yes
checking sys/mman.h presence... yes
checking for sys/mman.h... yes
checking sys/select.h usability... yes
checking sys/select.h presence... yes
checking for sys/select.h... yes
checking for sys/types.h... (cached) yes
checking sys/resource.h usability... yes
checking sys/resource.h presence... yes
checking for sys/resource.h... yes
checking for stdint.h... (cached) yes
checking sched.h usability... yes
checking sched.h presence... yes
checking for sched.h... yes
checking signal.h usability... yes
checking signal.h presence... yes
checking for signal.h... yes
checking sys/syscall.h usability... yes
checking sys/syscall.h presence... yes
checking for sys/syscall.h... yes
checking malloc.h usability... yes
checking malloc.h presence... yes
checking for malloc.h... yes
checking windows.h usability... no
checking windows.h presence... no
checking for windows.h... no
checking vec_types.h usability... no
checking vec_types.h presence... no
checking for vec_types.h... no
checking netdb.h usability... yes
checking netdb.h presence... yes
checking for netdb.h... yes
checking netinet/in.h usability... yes
checking netinet/in.h presence... yes
checking for netinet/in.h... yes
checking arpa/inet.h usability... yes
checking arpa/inet.h presence... yes
checking for arpa/inet.h... yes
checking for sys/types.h... (cached) yes
checking sys/socket.h usability... yes
checking sys/socket.h presence... yes
checking for sys/socket.h... yes
checking for an ANSI C-conforming const... yes
checking for inline... inline
checking for size_t... yes
checking whether time.h and sys/time.h may both be included... yes
checking whether byte ordering is bigendian... no
checking whether struct tm is in sys/time.h or time.h... time.h
checking for working alloca.h... yes
checking for alloca... yes
checking for posix_memalign... yes
checking for vprintf... yes
checking for _doprnt... no
checking for mmap... yes
checking for select... yes
checking for socket... yes
checking for strcspn... yes
checking for strerror... yes
checking for strspn... yes
checking for getpagesize... yes
checking for sysconf... yes
checking for snprintf... yes
checking for gettimeofday... yes
checking for nanosleep... yes
checking for sched_setscheduler... yes
checking for modf... yes
checking for sqrt... no
checking for sigaction... yes
checking for sigprocmask... yes
checking for pthread_sigmask... no
checking for sched_setaffinity... yes
checking for sincos in -lm... yes
checking for sincosf in -lm... yes
checking for sinf in -lm... yes
checking for cosf in -lm... yes
checking for exp10 in -lm... yes
checking for log2 in -lm... yes
checking whether to try shm vmcircbuf methods... yes
checking for library containing shm_open... -lrt
checking for shm_open... yes
checking for ld used by gcc... (cached) /usr/bin/ld
checking if the linker (/usr/bin/ld) is GNU ld... (cached) yes
checking whether /usr/bin/ld accepts --enable-runtime-pseudo-reloc... no
checking for CreateFileMapping function... no
checking for sys/types.h... (cached) yes
checking for fcntl.h... (cached) yes
checking io.h usability... no
checking io.h presence... no
checking for io.h... no
checking for windows.h... (cached) no
checking for winioctl.h... no
checking for winbase.h... no
checking for getopt... yes
checking for usleep... yes
checking for gettimeofday... (cached) yes
checking for nanosleep... (cached) yes
checking for rand... yes
checking for srand... yes
checking for random... yes
checking for srandom... yes
checking for sleep... yes
checking for sigaction... (cached) yes
checking for struct timezone... yes
checking for struct timespec... yes
checking for ssize_t... yes
checking for getopt... (cached) yes
checking for usleep... (cached) yes
checking for gettimeofday... (cached) yes
checking for Sleep... no
checking for dot... NO
checking for pkg-config... /usr/bin/pkg-config
checking pkg-config is at least version 0.18... yes
checking for FFTW3F... yes
checking for doxygen... /usr/bin/doxygen
checking for dot... no
checking for machine dependent speedups... generic
checking for CPPUNIT... yes
checking for boost >= 1.35... yes
checking for the pthreads library -lpthreads... no
checking whether pthreads work without any flags... no
checking whether pthreads work with -Kthread... no
checking whether pthreads work with -kthread... no
checking for the pthreads library -llthread... no
checking whether pthreads work with -pthread... yes
checking for joinable pthread attribute... PTHREAD_CREATE_JOINABLE
checking if more special flags are required for pthreads... no
checking whether the boost::thread includes are available... yes
configure: error: Could not link against libboost_thread!

**Comment by mbr0wn** [comment]
@K1two2 You're trying to install an ancient version of GNU Radio on a Raspi -- please take this to the mailing list; it's not something we can fix here.
