### ISSUE TITLE
tag_to_pmt newtag.key should be a from_python call

### ISSUE THREAD

**Issue by jaredd** [gnuradio/gnuradio#1072]
See [tag_utils.py:26](https://github.com/gnuradio/gnuradio/blob/master/gnuradio-runtime/python/gnuradio/gr/tag_utils.py#L26) which I think should read 

`newtag.key = pmt.from_python(tag.key)`

otherwise newtag.key will not be a pmt.  Probably just a cut and paste typo.

**Comment by jmcorgan** [comment]
@osh
