### ISSUE TITLE
Messages remain disconnected after flowgraph reconfig

### ISSUE THREAD

**Issue by jaredd** [gnuradio/gnuradio#1073]
This is with reference to [this discuss-gnuradio archive thread](https://lists.gnu.org/archive/html/discuss-gnuradio/2016-09/msg00136.html) where my friend Eugene Grayver pointed out that message passing seemed to fail after a flowgraph reconfiguration.  

A simple solution was proposed at the end of the thread, that was to [add this loop](https://github.com/gnuradio/gnuradio/blob/master/gnuradio-runtime/lib/flat_flowgraph.cc#L78) to [flat_flowgraph::merge_connections](https://github.com/gnuradio/gnuradio/blob/master/gnuradio-runtime/lib/flat_flowgraph.cc#L222).  Unfortunately I'm not familiar enough with that function to recommend where the loop goes.

**Comment by jmcorgan** [comment]
This issue has already been fixed in pull request #1041, and will show up in the pending 3.7.10.2 release.
