### ISSUE TITLE
allocate_buffer, throws std::bad_alloc

### ISSUE THREAD

**Issue by bdyaods** [gnuradio/gnuradio#1078]
I created a python scripts file, with a top_block and some blocks. I run the top block in a loop for many times,  but after loop several times, the script was terminated with the fllowing messages:
gr::vmcircbuf_sysv_shm: shmget (2): No space left on device
gr::buffer::allocate_buffer: failed to allocate buffer of size 64 KB
terminate called after throwing an instance of 'std::bad_alloc'
   I traced into the gnuradio source code and found it seems related to flat_flowgraph::allocate_block_detail and buffer::allocate_buffer

the loop is like:
while True:
   tb.start()
   tb.wait()
   tb.stop()

my question is how to close a top_block and release the resources.
Thanks alot

**Comment by jmcorgan** [comment]
This should be start(), then stop(), then wait().
