### ISSUE TITLE
Deprecate and remove MPSK receiver

### ISSUE THREAD

**Issue by n-west** [gnuradio/gnuradio#1083]
Deprecate and remove the C++ MPSK receiver block

* gr-digital/include/gnuradio/digital/mpsk_receiver_cc.h
* gr-digital/lib/mpsk_receiver_cc_impl.cc
* gr-digital/lib/mpsk_receiver_cc_impl.h
* gr-digital/grc/digital_mpsk_receiver_cc.xml

## Rationale

This is a very specific implementation that would be more useful as an example using filter blocks and a constellation mod/demod pair. When deleting ensure that such an example exists.

**Comment by jmcorgan** [comment]
Implemented in #1097 for master and #1098 for next.

**Comment by jmcorgan** [comment]
Merged.

**Comment by centromere** [comment]
> When deleting ensure that such an example exists.

Where may I find this example? @jmcorgan @n-west

**Comment by intra-au** [comment]
@n-west @jmcorgan can you please point me to the example using filter blocks and a constellation mod/demod pair (migration path from mpsk_receiver_cc if you will?)

**Comment by ecarl65** [comment]
I'm also looking for this example. Was this functionality just removed without the example replacement going in? Despite the original ticket saying not to remove it without preserving the example?

**Comment by cropinghigh** [comment]
Sorry, can you please give an example of creating pi/4 DQPSK receiver without mpsk receiver? It it used in osmo-tetra, and i can't find replacement to mpsk_receiver.

**Comment by Roman-Port** [comment]
For anybody still stuck on this removal like I was, this block essentially just combined a "Costas Loop" block with a "Clock Recovery MM" block. You can mostly copy the parameters directly from the old "MPSK Receiver" block to these two blocks. Here's an example. The top two blocks produce the same output as the bottom block. For me, I was using this block to implement RDS decoding.

![image](https://user-images.githubusercontent.com/34401219/103792134-e52faf00-5008-11eb-93a7-a3fcde5f7513.png)

The ``order`` of the Costas loop will let you pick what kind of PSK signal you're demodulating. I've only tried it with BPSK, order 2, so I might be wrong about this. From the [Costas loop wiki page](https://wiki.gnuradio.org/index.php/Costas_Loop):
* When order=2: used for BPSK where the real part of the output signal is the baseband BPSK signal and the imaginary part is the error signal.
* When order=4: can be used for QPSK where both I and Q (real and imaginary) are outputted.
* When order=8: used for 8PSK.

And finally, here is a full example of demodulating the signal in case it's helpful to anyone. Keep in mind that this example below **has a lot of specific blocks needed just for what I was decoding** that you may not necessarily need. I figure that it might be useful to somebody, though.

![image](https://user-images.githubusercontent.com/34401219/103795058-2032e200-500b-11eb-9b86-6ac644c66b5e.png)

I'm still a little bit frustrated that this block was removed in the first place, though.

**Comment by cropinghigh** [comment]
Very much thanks!

**Comment by cropinghigh** [comment]
Sadly, this simple solution didn't worked in osmo-tetra. Costas Loop + Clock Recovery MM don't have Theta setting, that is set to pi/4 for pi/4 DQPSK

**Comment by javawizard** [comment]
Has the lack of pi/4 DQPSK been resolved? I'm trying to figure out how to demodulate pi/4 DQPSK signals and am having a devil of a time figuring it out without writing my own code to do it.

**Comment by marcusmueller** [comment]
@javawizard this is a bug tracker, and this is specifically an issue tracking the removal of broken and redundant functionality!

If you'd like to discuss your signal processing/radio/GNU Radio problem, please feel wholeheartedly welcome to join our Matrix chat, https://wiki.gnuradio.org/index.php?title=Chat .
