### ISSUE TITLE
Update OOT documentation/tutorial regarding category strings

### ISSUE THREAD

**Issue by jmcorgan** [gnuradio/gnuradio#1087]
See:

http://lists.gnu.org/archive/html/discuss-gnuradio/2016-11/msg00096.html

The use of <category>[HOWTO]</category> in the XML for OOTs is not documented.

**Comment by kartikp1995** [comment]
Hi,
I can help with that.

**Comment by devnulling** [comment]
@duggabe Would you be able to check on this and/or update the tutorial to included this bit of info?

**Comment by duggabe** [comment]
@kartikp1995 If you have access to the #docs channel on Slack or IRC, take a look at the discussion on Jan 15 about XML and YAML in tutorials. then get back with me as 'Barry Duggan' on Slack or 'barry818' on IRC. we appreciate your help!

**Comment by duggabe** [comment]
added Note to clarify this issue in https://wiki.gnuradio.org/index.php/OutOfTreeModules#Making_your_blocks_available_in_GRC
This should be ready to close.

**Comment by 777arc** [comment]
Looks good Barry, thanks!
