### ISSUE TITLE
Locking / unlocking the flowgraph breaks the tag flow

### ISSUE THREAD

**Issue by pcercuei** [gnuradio/gnuradio#1091]
The following test code shows the behaviour I'm seeing in my program:
https://gist.github.com/pcercuei/7de8492e026760b8f8b085ecefa40443

Basically, if I call top_block::lock() then top_block::unlock(), the flow of tags stop. Maybe because the offsets are reset, because 3 seconds after the lock/unlock (in that test program) the tag flow resumes.

**Comment by jmcorgan** [comment]
Flowgraph reconfiguration entails a complete reset of the scheduler for each block; it's not surprising this happens. In fact, unlock() should probably have been named reset_and_restart().

Nonetheless, it's possible something is going awry here.
