### ISSUE TITLE
GFSK mod/demod

### ISSUE THREAD

**Issue by n-west** [gnuradio/gnuradio#1104]
The digital.gfsk_mod block has high functionality and code overlap with analog.cpm_mod and digital.gmsk except for a configurable modulation index. Consider replacing the existing implementation with a thin wrapper around analog.cpm_mod. If this is done we can either keep the gfsk_demod hierblock or move a GFSK loopback in to an example.

Depending on the action taken with gfsk_demod this does not necessarily require an API change because gr-digital which holds gfsk.py already depends on gr-analog.

This has been brought up as part of 3.8 clean up with a weak recommendation to replace the existing implementation for code deduplication.

**Comment by marcusmueller** [comment]
closed as sub-task"y" to #1103
