### ISSUE TITLE
CPM demod

### ISSUE THREAD

**Issue by n-west** [gnuradio/gnuradio#1105]
analog.cpm_demod is likely one of the oldest TODO notes in GNU Radio history going on 9+ years. The digital.gfsk_demod and digital.gmsk_demod blocks are identical hierblocks that will work as a generic analog.cpm_demod. Suggest either scraping the TODO note, implementing the demod and replacing the digital.gHfsk_demod blocks with thin wrappers, or making a generic CPM loopback example.

This is placed in the 3.8 milestone even though it does not involve an API change because the decision should be taken with a holistic API view of what will happen to the digital.gfsk_demod and digital.gmsk_demod blocks in #1103 and #1104.

**Comment by marcusmueller** [comment]
closed as sub-task"y" to #1103
