### ISSUE TITLE
gr-qtgui: TimeRasterSink

### ISSUE THREAD

**Issue by mrlnc** [gnuradio/gnuradio#1120]
I see that TimeRasterSink may not be supported with QWT5:
```
Warning: QWT5 has been found which has serious performance issues with raster plots.
         Consider updating to QWT version 6 to use the time raster GUIs.
```

In my case, TimeRasterSink does not show anything at all. I thought this is because of the QWT issue. Now I noticed that the Waterfall Sink does actually use the same kind of plotting, but works fine aside from performance. So there might be an actual bug here.

![screenshot_20161125_084724](https://cloud.githubusercontent.com/assets/1729953/20617807/cfd442e2-b2eb-11e6-9c48-f55f99628d96.png)
Waterfall Display on top, Time plot and Time Raster Sink.

By hitting "Auto Scale", the Intensity gets scaled and everything in the Time Raster Sink changes colors, but remains at Zero value. Maybe somewhere is data is not correctly handed over.

My QWT_VERSION is 0x050203.

**Comment by mbr0wn** [comment]
Time raster sink is running on master, so I think we can close.
