### ISSUE TITLE
gr-qtgui: Time Sink complex message input can't configure I and Q line styles in GRC

### ISSUE THREAD

**Issue by mhostetter** [gnuradio/gnuradio#1124]
In the qtgui_time_sink block, when configured for "Complex Message" type, you can only configure "Line 1" from the Properties window in GRC.  You can't configure the Q channel or "Line 2".

**Comment by kartikp1995** [comment]
Hi @mhostetter,
Would you please provide more information on this? The Line 2 configuration is already there with Line 1 configuration options in properties box under Config tab.

Thank you.

**Comment by kartikp1995** [comment]
@mhostetter Please check the referenced pull request. Notify me whether the issue is solved by it.

Thank you.

**Comment by jmcorgan** [comment]
Fixed in #1150
