### ISSUE TITLE
How can I generate the C/C++ code? OFDM send/receive in C++

### ISSUE THREAD

**Issue by chakpongchung** [gnuradio/gnuradio#1128]
I am using https://github.com/bastibl/gr-ieee802-11

to send/receive message using OFDM through wifi. Later I may need to use other scheme to send/receive.

How can I generate the C/C++ code? Sth like a main.cpp I can compile and run. I would like to have a flexible send/receive function I can call in C/C++, based on which I can build a protocol like the 3-way-handshake in tcp/ip.

**Comment by mbr0wn** [comment]
@chakpongchung Please don't post support requests here. Instead, post them to the discuss-gnuradio mailing list.
