### ISSUE TITLE
ATSC and GPU Acceleration

### ISSUE THREAD

**Issue by ghostop14** [gnuradio/gnuradio#1134]
I was working with some of the ATSC receiver functions and given the CPU load from the demod process, has anyone considered using OpenCL and GPU acceleration?  Not sure if the processing lends itself to it or not, but it may help offset the process load and actually be able to do reception in realtime?

**Comment by jmcorgan** [comment]
This would be a great question to pose to the GNU Radio mailing list, but not really suitable to report as a software issue here.
