### ISSUE TITLE
SIGSEGV due to QT GUI Constellation Sink with Tag trigger

### ISSUE THREAD

**Issue by awalls-cx18** [gnuradio/gnuradio#1148]
The QT GUI constellation sink can cause a SIGSEGV when using a tag trigger.

The failure happens in work() when calling volk_32fc_deinterleave_64f_x2() with the nitems argument in error (it appears to be MAX_INT-1).  The problem is more easily reproduced with lots of tagged portions of the stream and/or with a short update period on the GUI.

Here is what I deem useful from a gdb backtrace:

(gdb) frame 1
#1  volk_32fc_deinterleave_64f_x2_u_avx (iBuffer=0x5603cb27a368, 
    qBuffer=0x5603cb27ab68, complexVector=<optimized out>, 
    num_points=4294967295)
    at /home/andy/target/src/gnuradio/volk/kernels/volk/volk_32fc_deinterleave_64f_x2.h:99
99	    cplxValue = _mm256_loadu_ps(complexVectorPtr);
(gdb) frame 2
#2  0x00007f3d4235f829 in gr::qtgui::const_sink_c_impl::work (
    this=0x5603cb278910, noutput_items=<optimized out>, 
    input_items=std::vector of length 1, capacity 1 = {...}, output_items=...)
    at /home/andy/target/src/gnuradio/gr-qtgui/lib/const_sink_c_impl.cc:519
519	                                      &in[0], nitems);
(gdb) info locals
n = 0
in = <optimized out>
nfill = <optimized out>
(gdb) print nitems
$2 = <optimized out>
(gdb) print noutput_items
$3 = <optimized out>
(gdb) print this->d_index
$4 = 125
(gdb) print this->d_size
$5 = 125
(gdb) print this->d_end
$6 = 124

 numpoints in frame 1 is obviously a problem.
Those values of d_end, d_index, and d_size suggest to me that there may be a problem in  const_sink_c_impl::_test_trigger_tags() or where nfill and nitems are computed in work.

**Comment by jmcorgan** [comment]
Fixed in #1148
