### ISSUE TITLE
grc: Virtual sink ignores multiple message connections

### ISSUE THREAD

**Issue by mhostetter** [gnuradio/gnuradio#1166]
I discovered a bug with a virtual sink with multiple message input connections from blocks with the same output port name.  GRC will only connect one message port and ignore the rest.

Here's an example flowgraph:
![screenshot from 2017-01-13 11-54-13](https://cloud.githubusercontent.com/assets/12112573/21937949/2a28f8de-d987-11e6-816a-85dc01bd77a8.png)

The output is:
![screenshot from 2017-01-13 11-56-02](https://cloud.githubusercontent.com/assets/12112573/21937966/48406438-d987-11e6-8f1c-c67fcc6626b0.png)

The .grc and .py files are attached in the zip.  You can see in the GRC-generated .py file only the first message strobe is connected to the debug print.

[test.zip](https://github.com/gnuradio/gnuradio/files/704847/test.zip)

**Comment by mhostetter** [comment]
Upon further examination, even ports with unique names are ignored.  It appears GRC only uses the first connection when generating the python.

Adding an extra message port, shown below, will also get ignored in the .py file.
![screenshot from 2017-01-13 12-08-16](https://cloud.githubusercontent.com/assets/12112573/21938356/016a6a84-d989-11e6-9cc0-8fd425153ff3.png)

The modified .grc and .py are attached.

[test.zip](https://github.com/gnuradio/gnuradio/files/704871/test.zip)

**Comment by skoslowski** [comment]
Virtual connections were never meant to handle multiple upstream blocks. I guess messages can after.
That feature has been on my "to-be-rewritten" for 3.8 for a while. Might as well start now...

This is the first half of it. Your test-cases runs as expected:
https://github.com/skoslowski/gnuradio/tree/fix_virtual_connection_1166

I might do another iteration on it before putting it in a PR. Feedback welcome, though.

**Comment by jmcorgan** [comment]
Fixed in #1168
