### ISSUE TITLE
Gnuradio maintains a lock on the file behind an "Embedded Python Block" even when you use Gnuradio to open the file for editing (on windows).

### ISSUE THREAD

**Issue by fake-name** [gnuradio/gnuradio#1169]
If I use the "Embedded Python Block" gnuradio block, in the properties, there is a button to open the file in an editor.

However, if you open the file in an external editor, GNURadio locks the file for writing, so any changes made to the file cannot be saved without closing gnuradio companion.

From the comment at the top of the file:

> Embedded Python Blocks:
> 
> Each time this file is saved, GRC will instantiate the first class it finds
> to get ports and parameters of your block. The arguments to __init__  will
> be the parameters. All of them are required to have default values!

It sounds like the idea is that the file can be edited interactively while gnuradio companion is open, and changes are synchronized back into the GRC block. However, if it's locked for writing, this isn't possible.

This is supported by the fact that there is a "Open in Editor" button in the block properties. If it's intended to be read-only, the button should probably say "*View* in editor", at the minimum.

![image](https://cloud.githubusercontent.com/assets/1401239/22003879/e3de5ec8-dc0b-11e6-9b53-54781f600051.png)

------

If I use an external tool ([IOBit Unlocker](http://www.iobit.com/en/iobit-unlocker.php) ) to forcefully break the lock while keeping GRC open, it appears to crash the file monitoring system: 

> file monitor crashed: [Error 2] The system cannot find the file specified: 'c:\\users\\durr\\appdata\\local\\temp\\epy_block_0_l3jomx.py'

**Comment by skoslowski** [comment]
This seems to be a Windows problem. The external editor used `tempfile.NamedTemporaryFile()` to manage that tempfile. This keeps a lock on the file.

**Comment by fake-name** [comment]
Yeah, I suspect it's a function of how windows manages open files, vs how linux does.

**Comment by skoslowski** [comment]
I'd appreciate it if you could try my fix on your Windows machine. GRC can run directly from a source checkout (at least on Linux)

**Comment by fake-name** [comment]
Is python3K functional enough for that test yet? I've been trying really, really hard to not install a general python2k setup on my machine.

**Comment by fake-name** [comment]
Ok, yeah. that fixes the issue.

I just took the lazy way out, and splatted the new `external_editor.py` on top of the old one in my working install, but it now works and synchronizes correctly. Thanks!

**Comment by khanfar** [comment]
when i add python module and try to open in editor , i chose use default , i got error opening an external editor please select different editor !  , i try chose editor , but what should i chose ?? i use win 10 64 bit gnu-radio companion , any help ????

**Comment by Moussawi90** [comment]
> when i add python module and try to open in editor , i chose use default , i got error opening an external editor please select different editor ! , i try chose editor , but what should i chose ?? i use win 10 64 bit gnu-radio companion , any help ????

Same problem
