### ISSUE TITLE
Much of the GNURadio Wiki implicitly assumes a linux platform.

### ISSUE THREAD

**Issue by fake-name** [gnuradio/gnuradio#1170]
Basically the title. 

http://gnuradio.org/redmine/projects/gnuradio/wiki/Guided_Tutorial_GNU_Radio_in_Python and probably many other pages of the wiki assume you're on linux, but don't mention this fact.

It'd be nice to have windows instructions too, or at least have the `Prerequisites` section mention "Linux Platform" or similar.

**Comment by mbr0wn** [comment]
@fake-name You can also edit the wiki :)

**Comment by jmcorgan** [comment]
As @mbr0wn mentioned, please feel free to update the wiki.
