### ISSUE TITLE
SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by ayserafettin** [gnuradio/gnuradio#1174]
Hi,
i have installed gnuradio with the help of a script and i gat this error while running the examples  and also graph that i want to create. What can i do? any help will be appriciated.
thanks.

  File "/home/seref/Gnuradio/gnuradio/gr-digital/examples/packet/example_corr_est_and_clock_sync.py", line 177
    self.qtgui_time_sink_x_0_0 = Template error: #set $win = 'self._%s_win'%$id
                                              ^
SyntaxError: invalid syntax

Regards

**Comment by mbr0wn** [comment]
@ayserafettin Please take this to discuss-gnuradio. We don't have enough info here, and besides, this looks like a support request, not a bug report. Thanks!
