### ISSUE TITLE
Additive scrambler off by one error when reset is tag triggered

### ISSUE THREAD

**Issue by v1bri** [gnuradio/gnuradio#1198]
When the additive scrambler's reset is tag triggered, it looks like the reset occurs one item after the appropriate place. This makes it difficult to use in a packet centric mode as would be the case when the trigger tag is "packet_len" or something similar. 

**Example flow graph**
![scramble_test](https://cloud.githubusercontent.com/assets/18292307/22477723/0e6fc6fe-e79c-11e6-9aec-705ccd184e98.png)

**Output**
(Note the first byte which should not change, but does.)
```
* MESSAGE DEBUG PRINT PDU VERBOSE *
()
pdu_length = 10
contents = 
0000: 00 01 02 03 04 05 06 07 08 09 
***********************************
* MESSAGE DEBUG PRINT PDU VERBOSE *
()
pdu_length = 10
contents = 
0000: 7f 7e 12 45 7d 74 d4 69 5e 36 
***********************************
* MESSAGE DEBUG PRINT PDU VERBOSE *
()
pdu_length = 10
contents = 
0000: 00 01 02 03 04 05 06 07 08 09 
***********************************
* MESSAGE DEBUG PRINT PDU VERBOSE *
()
pdu_length = 10
contents = 
0000: 08 7e 12 45 7d 74 d4 69 5e 36 
***********************************
* MESSAGE DEBUG PRINT PDU VERBOSE *
()
pdu_length = 10
contents = 
0000: 00 01 02 03 04 05 06 07 08 09 
***********************************
* MESSAGE DEBUG PRINT PDU VERBOSE *
()
pdu_length = 10
contents = 
0000: 08 7e 12 45 7d 74 d4 69 5e 36 
***********************************
```
The scrambler resets the LFSR after the byte associated with the "packet_len" tag instead of before it. I believe the correct scrambled output should be `7f 11 44 7a 75 d7 68 51 37 01` for this example.

To fix tag triggered reset, the if statement at https://github.com/gnuradio/gnuradio/blob/master/gr-digital/lib/additive_scrambler_bb_impl.cc#L131 should be moved to the top of the for loop. Probably in another for loop selected by an if statement. The current logic works well for "count" triggered operation (reset the LFSR after "count" bytes).

Happy to make a pull request if this sounds good.

**Comment by jmcorgan** [comment]
I know this has been open a long time without comment--I'd like to see a suggested PR, bonus points for a QA test that would fail without the changes and succeed with them.
