### ISSUE TITLE
CGRAN: cgran.org should link to official tutorials

### ISSUE THREAD

**Issue by marcusmueller** [gnuradio/gnuradio#1202]
rather than the dated "how to write an OOT":

![cgran](https://cloud.githubusercontent.com/assets/958972/22618393/35b35af4-eadb-11e6-9f81-2e945f458dd3.png)

**Comment by mbr0wn** [comment]
@n-west

**Comment by marcusmueller** [comment]
bumping this, as URLs have changed anyway due to wiki migration.
@nwest

**Comment by devnulling** [comment]
Closing this issue as it no longer applies with the new CGRAN design.
