### ISSUE TITLE
variable maybe not initialized

### ISSUE THREAD

**Issue by maddin200** [gnuradio/gnuradio#1204]
gr-audio\lib\osx\osx_impl.cc line 46
char format_id[sizeof(asbd.mFormatID)+1];
better:
char format_id[sizeof(asbd.mFormatID)+1] = {0};

**Comment by jmcorgan** [comment]
@michaelld Let me know if this is an issue or if it should be closed.

**Comment by bastibl** [comment]
I think at least the `memcpy` arguments should be swapped. If I'm not mistaken it copies the uninitialized array into the variable.
https://github.com/gnuradio/gnuradio/blob/master/gr-audio/lib/osx/osx_impl.cc#L46

**Comment by michaelld** [comment]
I think @bastibl is correct, that we need to swap the first 2 arguments. Glad it's just for debug purposes & not critical runtime! I'll verify & do a PR.

**Comment by mbr0wn** [comment]
Looks like @michaelld fixed, and we can close?

**Comment by michaelld** [comment]
Yes! Someone please do close this issue. I'm not given this option.
