### ISSUE TITLE
Possible resource leak: socket not closed in tuntap_pdu_impl.cc, set_mtu

### ISSUE THREAD

**Issue by jaredd** [gnuradio/gnuradio#1210]
In gr-blocks at [tuntap_pdu_impl.cc](https://github.com/gnuradio/gnuradio/blob/master/gr-blocks/lib/tuntap_pdu_impl.cc#L161) a socket is created but not closed before the function exits.  Recommend add close(sfd) before every return call.

**Comment by k6nick** [comment]
I believe the socket should be closed only at the error code, not when the socket is returned without an error. Basically this:

      /* try to set MTU */
      if ((err = ioctl(sfd, SIOCSIFMTU, (void *) &ifr)) < 0)
        /* add this
           close(fd);
        */
        return err;

Simple enough fix, but I am not familiar at all with what's required to make this change. First time here, first time looking into the GNU radio code...

**Comment by k6nick** [comment]
I made the fix and this is the pull request: https://github.com/k6nick/gnuradio/pull/1

I hope I didn't mess up anything, I'm just getting started with github.

**Comment by marcusmueller** [comment]
> Recommend add `close(sfd)` before every return call.

That's been implemented, far as I can tell!
