### ISSUE TITLE
Impossibility to disable DC filtering for USRP source in GRC

### ISSUE THREAD

**Issue by pelijah** [gnuradio/gnuradio#1236]
There is an error in the script _gr-uhd/grc/gen_uhd_usrp_blocks.py_. To disable DC filtering user needs to enter _False_ in the field  _$dc_offs_enbXX_. In this case _set_auto_dc_offset_ will not be called because condition "if False" is always false.
```
	\#if \$dc_offs_enb$(n)()
self.\$(id).set_auto_dc_offset(\$dc_offs_enb$(n), $n)
	\#end if
```
It needs to be changed on something like this
	`\#if \$dc_offs_enb$(n)() != ""`

**Comment by mbr0wn** [comment]
Yep, that's legit. @pelijah do you want to submit a PR for this?

**Comment by pelijah** [comment]
@mbr0wn No

**Comment by marcusmueller** [comment]
closing this two years after a fix was merged (if it wasn't fixed by that fix, the bug reporter would probably have spoken out?)
