### ISSUE TITLE
Problem with ADSB.py and adsb.py Modules 

### ISSUE THREAD

**Issue by mariam2017** [gnuradio/gnuradio#1241]
When trying to run the GNU radio using the block diagram, we get an error called "No Name ADSB module"

Please advice us with the solution for this problem. 

Thank you

**Comment by jmcorgan** [comment]
Sorry to hear you are having difficulty.

The issue tracker here is for reporting bugs.  For general support questions, please use either the gnuradio-discuss mailing list, the #gnuradio IRC channel on freenode, or the GNU Radio slack.
