### ISSUE TITLE
GRC scripts will not compile with QT_GUI option & RDS Panel enabled

### ISSUE THREAD

**Issue by christhephish** [gnuradio/gnuradio#1255]
example - make working script w/ WX_GUI option set and incorpoorating RDS_PANEL block - script compiles, runs and produces (soon to be deprecated?) WX_GUI panel w/ attached RDS output.

bug - rebuild exact script w/ QT_GUI option set w/ incorporating RDS_PANEL block - script starts to compile, crashes , throws trace

`
**_File "/home/chris/sdr/FM_RDS.py", line 129, in __init__
    self.gr_rds_panel_0 = rds.rdsPanel(var_fm_freq, self.GetWin())
  File "/usr/lib/python2.7/dist-packages/gnuradio/gr/hier_block2.py", line 92, in __getattr__
    return getattr(self._impl, name)
AttributeError: 'top_block_sptr' object has no attribute 'GetWin'_**
'

Disable RDS_PANEL block - script runs sans RDS Panel (&output) / change script options to run WX_GUI options - enable RDS_PANEL...script runs.

**Comment by skoslowski** [comment]
Well, GUI blocks are build for a specific framework - WX in this case.
This fact doesn't seem to be communicated with GRC here, else it wouldn't even let you Generate in QtGui mode.

To be usable with QtGui it has to be rewritten using Qt. Best continue this discussion the/a gr-rds tracker.

**Comment by bastibl** [comment]
Just for reference, the `next` branch of the RDS module has a QT panel.
