### ISSUE TITLE
grc: Add hide option to GRC Parameter

### ISSUE THREAD

**Issue by mhostetter** [gnuradio/gnuradio#1263]
This is a feature request.

I think it would be nice to add a "Hide" field in the Parameter block beneath "Short ID". This way certain fields don't have to appear on a hierarchical block. Hide could be an enum with options `None`, `Part`, or `All` and maybe default to `None`.

![image](https://cloud.githubusercontent.com/assets/12112573/24725641/aeedc8ac-1a1d-11e7-9e85-4b32906687cf.png)

What do you think @skoslowski?

**Comment by skoslowski** [comment]
I think, the the "Part" option is a great idea. I not sure I understand the use-case for 'All'. Why not use a variable instead of a hidden parameter? Anyway, this would have to be an enum entry.

If you want to go ahead and implement this, I'll be looking forward to your PR =)

**Comment by kartikp1995** [comment]
I can work on this. If @mhostetter, hasn't started yet. 

I believe we need to update in [this file](https://github.com/gnuradio/gnuradio/blob/master/grc/core/generator/Generator.py#L291). Am I correct?

Once I get confirmation from @mhostetter, I will make the PR asap.

**Comment by kartikp1995** [comment]
Added PR #1265

Kindly review it.

**Comment by mhostetter** [comment]
@skoslowski you're right. The `All` option doesn't make any sense.

@kartikp1995 thanks! I would've submitted a PR, but I'm less familiar with where all the code lives in GRC land.

**Comment by skoslowski** [comment]
Glad everybody's happy, but, @kartikp1995, you did indeed jump the gun a little...
@mhostetter, you're welcome to comment on or review the pr

**Comment by mhostetter** [comment]
I'm building and testing the code right now.

**Comment by skoslowski** [comment]
FYI, with gr installed you can run grc straight from the source tree.

**Comment by kartikp1995** [comment]
@skoslowski Sorry for rushing up. I will wait for the signal next time. :)

**Comment by mhostetter** [comment]
@skoslowski thanks for the tip!

**Comment by mhostetter** [comment]
#1265 is now merged. Thanks @kartikp1995!
