### ISSUE TITLE
gtqui: Num Rows disappears with Byte Message in Time Raster Sink

### ISSUE THREAD

**Issue by mhostetter** [gnuradio/gnuradio#1267]
When the block is created with the `Byte` type, both `Num. Rows` and `Num. Cols` are configurable.
![image](https://cloud.githubusercontent.com/assets/12112573/24821202/440621b6-1bbb-11e7-8ca5-c01806b8ebea.png)

When switching to `Byte Message`, `Num. Rows` disappears.
![image](https://cloud.githubusercontent.com/assets/12112573/24821239/6e2d0fd6-1bbb-11e7-868e-8377a3f1ee71.png)

I learned about this when immediately switching to `Byte Message`. After I configured then the block it complained about `Num. Rols` being invalid.

I will submit a PR for this.

**Comment by mhostetter** [comment]
I just realized usage of the `Byte Message` option only prints 1 row at a time, which is different from what I expected. I achieve my desired usage by putting a PDU to Tagged Stream block between my PDU source and a `Byte` type Time Raster Sink.

Maybe this block error could be avoid if the default `Num. Rows` was `1`. Then there wouldn't be a `<check>` error.

**Comment by marcusmueller** [comment]
Seems to be fixed in main
