### ISSUE TITLE
rx_ofdm.grc is blank

### ISSUE THREAD

**Issue by muhantu** [gnuradio/gnuradio#1273]
![screenshot from 2017-04-12 00-41-57](https://cloud.githubusercontent.com/assets/25543023/24922532/e0013e10-1f18-11e7-9aa6-fbc6b427d7bf.png)

I just open and execute the flow graph, and just appear a blank window..

**Comment by jmcorgan** [comment]
So, this example actually doesn't have any graphical displays, and its output is entirely in the tag debug output you see in the reports part of GRC.  The actual bug is that the options block has this set to QTGUI, but instead this should be a No GUI app.

**Comment by jmcorgan** [comment]
Fixed in #1274
