### ISSUE TITLE
change variable from terminal PYTHON GNURADIO

### ISSUE THREAD

**Issue by Toutoupou** [gnuradio/gnuradio#1296]
Hi, i wouldlike to change variable (like variable slider : frequence, gain etc...) from the command line on GNU RADIO .
For example : i run the GRC file with terminal : `./test.py` and with another command, i change frequence or any variables sliders.

Thanks for any help !

**Comment by jmcorgan** [comment]
The issue tracker is for reporting bugs in gnuradio--please take this support issue to the GNU Radio mailing list, the IRC channel, or Slack, thanks.

https://wiki.gnuradio.org/index.php/ReportingErrors
