### ISSUE TITLE
No menus in QT GUI Sink

### ISSUE THREAD

**Issue by vmartyanov** [gnuradio/gnuradio#1305]
Gnuradio companion 3.7.10.2, Gentoo Linux
I used QT GUI Sink, switched to Time Domain Display tab and a middle mouse button wasn't work. If I used QT GUI Time Sink the middle button works as expected. I think it should work in QT GUI Sink too...

**Comment by mbr0wn** [comment]
The QT GUI Sink is older than the rest, and won't be getting updates. I think we can close this.

**Comment by vmartyanov** [comment]
So, it's recommended to use individual sinks instead of QT GUI sink?

**Comment by jmcorgan** [comment]
Yes.
