### ISSUE TITLE
SWIG version check failed

### ISSUE THREAD

**Issue by kangqf** [gnuradio/gnuradio#1306]
I use ubuntu 14.04  with swig 3.0.2, But when I build the latest source code, It can't check pass the swig version.I check the cmake file, I find that the version 3.0.2 can't grater than 2.0.4. And I use the 3.7.10 version to build , It's doesn't show any error.

**Comment by jmcorgan** [comment]
Can you post the output of your cmake execution for both cases?

**Comment by kangqf** [comment]
I change the cmake modules then I pass the error! :)
