### ISSUE TITLE
Total Fail...

### ISSUE THREAD

**Issue by jamieduk** [gnuradio/gnuradio#1319]
i just installed volk from git hub source because gnuradio wont install and still get this message CMake Error at CMakeLists.txt:428 (message):
  VOLK required but not found.

sort it out ffs linux winds me right up incompetent devs need to make prerequisites install automatically i have not got time to waste like this ffs!

**Comment by pwicks86** [comment]
You need to check out the volk submodule. The easiest way to do this is 

```
git submodule init 
git submodule update
```

**Comment by mbr0wn** [comment]
@jamieduk Please keep the tone civilized here. I'll be closing this issue because it's not actually a bug.

**Comment by mbr0wn** [comment]
Also, see @pwicks86 helpful response which should resolve your issues.
