### ISSUE TITLE
multiply_matrix_XX: can't simply use magic value in place of `enum`, C++ doesn't allow that

### ISSUE THREAD

**Issue by marcusmueller** [gnuradio/gnuradio#1337]
https://github.com/gnuradio/gnuradio/blob/master/gr-blocks/lib/multiply_matrix_cc_impl.cc#L182 👍
```
[793/2135] Building CXX object gr-blocks/lib/CMakeFiles/gnuradio-blocks.dir/multiply_matrix_cc_impl.cc.o
../gr-blocks/lib/multiply_matrix_cc_impl.cc:184:15: warning: comparison of constant 999 with expression of type 'gr::block::tag_propagation_policy_t' is always false [-Wtautological-constant-out-of-range-compare]
      if (tpp == TPP_SELECT_BY_MATRIX) {
          ~~~ ^  ~~~~~~~~~~~~~~~~~~~~
1 warning generated.
```

Simply because you might in practice be able to cast the `tag_propagation_policy_t` argument to `set_tag_propagation_policy` to an `int` doesn't mean you can just set it to `999`. That's not how `enum`s work (C++ standard, highlight mine):

> [expr.static.cast]/10

>    A value of integral or enumeration type can be explicitly converted to an enumeration type. The value is unchanged if the original value is within the range of the enumeration values (7.2). **Otherwise, the resulting value is unspecified (and might not be in that range).**

So, yay, undefined behaviour occurs whenever one tries to actually pass `TPP_SELECT_BY_MATRIX` to `set_tag_propagation_policy` (which isn't that surprising, considering enums were meant to suppress the usage of numeric literals as magic numbers without compile-time range checking).

Another issue is that `tag_propagation_policy()` will return `TPP_DONT` instead of `TPP_SELECT_BY_MATRIX` after `set_tag_propagation_policy(TPP_SELECT_BY_MATRIX)`, which is a breach of contract.

So, I'm not sure how to proceed. Options:

1. extend `tag_propagation_policy_t` to include `TPP_SELECT_BY_MATRIX`. That demonstrates that we can't keep the number of possible TPPs limited.
2. extend `tag_propagation_policy_t` to include `TPP_CUSTOM`, and change `multiply_matrix` + docs to react to that
3. ???

**Comment by gigabyte1023** [comment]
i need help

**Comment by mbr0wn** [comment]
We actually had a discussion about this when this block was first merged. The `TPP_CUSTOM` solution was the one that I preferred at the time.

**Comment by marcusmueller** [comment]
Ok, then I'll just go ahead and implement that – Thanks for the feedback!

**Comment by mbr0wn** [comment]
I think @jmcorgan should weigh in here before you go on a coding spree.

**Comment by jmcorgan** [comment]
I think I agree with the TPP_CUSTOM solution myself.

**Comment by marcusmueller** [comment]
@jmcorgan (hopefully) ready for maint-merge (#1341)

**Comment by noc0lour** [comment]
@marcusmueller This is done, I guess?

**Comment by marcusmueller** [comment]
@noc0lour as far as I can see, yes, the fix has been merged into maint, which, I think, in the GNU Radio dev model, means it'll end up (or already has ended up) in master and next.
