### ISSUE TITLE
UHD: USRP source block does not generate stream tags when RX frequency changed via its message port.

### ISSUE THREAD

**Issue by vermillionsands** [gnuradio/gnuradio#1357]
Generally, if the USRP source block's centre frequency is altered then the output stream is tagged with the current time, frequency, and rate. However, if the centre frequency is altered via messages received on its command port then these  tags are not generated. This seems like a bug.

The root cause is that command messages use the SET_CENTER_FREQ_FROM_INTERNALS macro to set the RX frequency instead of the set_center_freq() function. The macro does not set the _tag_now flag, so no tags are generated.

**Comment by dkozel** [comment]
@vermillionsands Thanks for opening this issue and for having taken a look into the root issue. The creation of a tag with the center frequency does seem like a behavior which should be consistent no matter which API is used to set the frequency.

**Comment by fedjo** [comment]
+1 
I also experience the same behavior.
It would be nice to resolve this issue.  Any news about it?

Otherwise is any workaround to periodically change the RX freq of USRP source and recognize it in a way (with a tag, witha custom block) ?

**Comment by seldad8** [comment]
I'm able to work around this issue by sending a "tag" command on the message port, after sending the "tune" message.

**Comment by marcusmueller** [comment]
Closed per #4259
