### ISSUE TITLE
Tun/Tap block for MacOS

### ISSUE THREAD

**Issue by vamsi765** [gnuradio/gnuradio#1367]
@michaelld 
I get the following error when I have tun tap_pdu block in grc. The error persists even after installing tuntap related files from MacPort.

`
Traceback (most recent call last):
  File "gen_sink.py", line 58, in <module>
    main()
  File "gen_sink.py", line 47, in main
    tb = top_block_cls()
  File "gen_sink.py", line 30, in __init__
    self.blocks_tuntap_pdu_0 = blocks.tuntap_pdu('tap0', 10000, False)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/gnuradio/blocks/blocks_swig6.py", line 1042, in make
    return _blocks_swig6.tuntap_pdu_make(dev, MTU, istunflag)
RuntimeError: tuntap_pdu not implemented on this platform
`

**Comment by michaelld** [comment]
@mbr0wn : There is no "tuntap" directly on OSX like there is on Linux. There is a "tuntaposx" project that adds this capability, somehow. I've never used it, but it might be worth investigating to see if it can be used to expand the functionality of the tuntap block. Do you want me to give it a try & see what I can do for an hour or 2?

**Comment by mbr0wn** [comment]
@michaelld Go for it!

**Comment by jmcorgan** [comment]
@mbr0wn Same issue here; @michaelld does not show up in the list of people I can assign this to.

**Comment by michaelld** [comment]
@mbr0wn OK thx I'll take a look-see.

**Comment by devnulling** [comment]
@michaelld is this still an issue?

**Comment by michaelld** [comment]
yes ... I've never found/made time to look into this.

**Comment by michaelld** [comment]
There is no good way to do TAP/TUN on macOS that I know of. I never had time to deal with this, and will not any time in the near future. Given how old this issue is and the lack of traction on it, I'm closing it. If someone truly wants this to work, go ahead and reopen and please suggest a solution!
