### ISSUE TITLE
gr-digital: persistent logging in correlate_access_code_bb_impl.cc

### ISSUE THREAD

**Issue by LaughingCabbage** [gnuradio/gnuradio#1379]
Created to track pull request #1354 . Critical performance issue. Persistent logging to console on each packet in packet decode as a result of new_flag calls in correlate_access_code_bb_impl.cc. Test flow: File source -> packet encoder -> dpsk mod -> dpsk demod -> packet decoder -> time sink.

**Comment by jmcorgan** [comment]
Normally we track pull requests within the PR itself; if there was an issue opened prior to that we can reference it, but there's no need to open a new one here.
