### ISSUE TITLE
Validation Failed, gnuradio-iqbalance.dll was not found and is required

### ISSUE THREAD

**Issue by ariasorhab** [gnuradio/gnuradio#1441]
I got many errors till now to successfully download gnu radio source on windows, 
but this last one is not solving by any means.

**Comment by mbr0wn** [comment]
gnuradio-iqbalance is not part of GNU Radio, it's a separate module. Not sure if this is really a GNU Radio issue or if we can close this. @ariasorhab please provide more info, or we'll close this.
