### ISSUE TITLE
integrate has `int vlen` parameter; should be `unsigned`; check other block's

### ISSUE THREAD

**Issue by marcusmueller** [gnuradio/gnuradio#1459]
There's a lot of blocks that take `vlen` parameters. This is a reminder to myself (please assign to me) to go through the tree and identify all places where we should've used unsigned int instead of int.

This might look cosmetic (it's unlikely someone would want a vector half of MAX_INT in size, and the scheduler and buffer allocator might reasonably break on that), but it actually gives compiler warnings when trying to parameterize a block with a signed vlen, so it's actually a code quality issue.

**Comment by vamsi765** [comment]
@marcusmueller Do you want to me to take a look at the issue?

**Comment by nishithshah2211** [comment]
@marcusmueller Does this issue still need work? Some more info to identify such occurrences of `int` usage instead of `unsigned int` would also help.
