### ISSUE TITLE
403 Forbidden nginx - https://gnuradio.org/

### ISSUE THREAD

**Issue by saydulk** [gnuradio/gnuradio#1460]
showing 403 Forbidden nginx at gnuradio.org website, please fix nginx 
check - service nginx status or ps waux | grep nginx

**Comment by BrashEndeavours** [comment]
Works for me.

**Comment by saydulk** [comment]
![screenshot from 2017-09-08 17 58 32](https://user-images.githubusercontent.com/1058663/30210709-6a3869d4-94bf-11e7-838c-7a3ab853d77e.png)

**Comment by marcusmueller** [comment]
Works for me, too, so, I'd assume you, @saydulk, you might be 

* behind a misconfigured proxy or
* you might be blocked.

Either case can't be solved via the source code issue tracker. I'm recommending closing this issue. 

If you are being blocked, we, or our CDN, might have been seeing attacks or Spam coming from your general direction. @noc0lour might have more insight on how to assess that, please contact him on IRC via freenode in #gnuradio .
