### ISSUE TITLE
gr-blocks: moving average test case not sufficient

### ISSUE THREAD

**Issue by marcusmueller** [gnuradio/gnuradio#1461]
MA test case only tests whether the output of the block is "roughly equal":

        expected_result = N*[0,]
        …
        self.assertFloatTuplesAlmostEqual(expected_result, dst_data, 1)

and I *mean* roughly. 1 significant digit roughly, for a sum over 100 random floats divided by 100. 

That's not a very good test case, because it doesn't catch *any* numerical error that is not blatant, anyway.

**Comment by marcusmueller** [comment]
Ceterum censeo medium movens in gr-filter ponendum esse.

**Comment by sbmueller** [comment]
So I think this was fixed in #1475
