### ISSUE TITLE
python3: build failures with py3 interpreter, build success with py2 interpreter

### ISSUE THREAD

**Issue by noc0lour** [gnuradio/gnuradio#1482]
See https://ci.gnuradio.org/buildbot/#/builders/12/builds/49/steps/4/logs/stdio for the latest build results (tip of python3). Somehow the code generation with python3 fails because of some encoding errors. 
Python2 on the other hand succeeds and just fails a test.

Someone a clue why this fails?

**Comment by mormj** [comment]
@noc0lour - is this issue still relevant post 3.8 release?
