### ISSUE TITLE
Modal dialogs in GRC may allow selecting the parent window, confusing users

### ISSUE THREAD

**Issue by courtarro** [gnuradio/gnuradio#1494]
In different environments, the behavior of modal dialogs in GRC varies. In `xfce`, for instance, most dialogs are truly modal. In KDE, however, most (if not all) dialogs allow clicking the main window "behind" the dialog, which results in the dialog being hidden, yet the main window does not respond to any input. Instead, it is stalled waiting for the result of the dialog. In KDE Neon, a workaround is to Alt-Tab back to the dialog and close it. It is my understanding that the same thing occurs on in MacOS. Even in `xfce`, the "Choose Editor" dialog that exists for the Python block can be hidden, resulting in the same problem. The issue is especially egregious because GRC in this state makes no indication that clicks on the main window are "invalid" - there is no error tone, no visual cue, etc. The user simply perceives an unresponsive program.

Best I can figure, the proper way to fix this is to include a `parent` object reference in all GTK `Dialog` references. In other places, this is referred to as the `transient_for` property, meaning the dialog exists as a transient window on behalf of some other window (the parent). I am working on a pull request with this solution and will contribute it soon.

**Comment by marcusmueller** [comment]
Solved by merging PR.
