### ISSUE TITLE
GR Host cleanup

### ISSUE THREAD

**Issue by noc0lour** [gnuradio/gnuradio#1507]
Cleanup current docker config on GR host.

- [ ] Monitoring for running services
- [ ] Reasonable Mail Infrastructure for Management purpuoses
- [ ] Docker/Service cleanup

**Comment by devnulling** [comment]
@noc0lour are these still outstanding issues?

**Comment by noc0lour** [comment]
yeah, but they don't belong in the repository per se.

**Comment by devnulling** [comment]
Closing this as its mostly continuous work.
