### ISSUE TITLE
Can I use gnuradio on 32-bit Ubuntu14.04 ?

### ISSUE THREAD

**Issue by TriLoo** [gnuradio/gnuradio#1508]
Hi there, 
   I want install uhd  @'release_003_010_001_001 ' & gnuradio @'3.7.12git' on my 32-bit 14.04 Ubuntu, however, I got a "Illegal Instruction" when i used 'from gnuradio import uhd'.

  Anyone had seen this problem and any advise? Thanks in advance.

**Comment by mbr0wn** [comment]
Can you comment on how you installed uhd and gnu radio? Also I don't think this is a gnu radio bug. Will close now, you or someone else can reopen if I'm wrong. Please ask on the uhd or gnu radio list for advice.
