### ISSUE TITLE
Overlapping blocks and wires bug

### ISSUE THREAD

**Issue by abaxi** [gnuradio/gnuradio#1511]
Often times when one adds a block to the flow graph in GRC, it'll go over a wire or under another block.

---When it goes over a wire, often times clicking on the block will select the wire underneath it, and move or disconnect it. The block on top should always be selected, not the obscured part of the wire.

---When it goes under existing blocks, it's just hard to find.

screen capture of block over wire, but wire still gets selected.

![under_wire](https://user-images.githubusercontent.com/26046328/32398020-febb0952-c0c2-11e7-8270-9e56127f7611.png)

I'm experiencing this in version 3.7.10.1.

Thanks,

**Comment by NeuroForLunch** [comment]
I have attempted to replicate this and been unable to. Perhaps it has been fixed since Nov 2017?

**Comment by marcusmueller** [comment]
Specific to 3.7 anyways,  since the whole connection logic has changed since then.
