### ISSUE TITLE
gr-pager: FLEX implementation is missing BCH ECC

### ISSUE THREAD

**Issue by broglek** [gnuradio/gnuradio#1512]
The current implementation of the FLEX demodulator in gr-pager is missing the implementation of the BCH(31,21) error correcting code.  When using gr-pager to demodulate FLEX messages, the lack of ECC results in the occasional garbled message.

**Comment by broglek** [comment]
Fixed in https://github.com/gnuradio/gnuradio/pull/1513

**Comment by devnulling** [comment]
Closing this issue as gr-pager is no longer included in GR and we would need a CLA in order to per your prior PR.
