### ISSUE TITLE
Variables not being recognized

### ISSUE THREAD

**Issue by Brett99** [gnuradio/gnuradio#1520]
I have a simple flowchart here, and the `samp_rate` variable is not being recognized by the blocks. 
![image](https://user-images.githubusercontent.com/8924477/32836606-3db696bc-c9bf-11e7-9f88-3cca6f35addd.png)
Am I doing something wrong, or is this a GRC bug?

**Comment by Brett99** [comment]
I can get the blocks to recognize `samp_rate` by deleting it and manually adding it again.

**Comment by bastibl** [comment]
The gray blocks are disabled. Enable them with the corresponding option in the menu bar or by pressing 'e'.

**Comment by Brett99** [comment]
Wow, thanks. I've done this twice now. Perhaps there should be some kind of warning printed so new users like me have a more helpful error message when a block is disabled.
