### ISSUE TITLE
Eanble another gnuradio

### ISSUE THREAD

**Issue by lshangguan** [gnuradio/gnuradio#1524]
Hi all,

I installed two Gnuradio, 
 1) gnuradio @3.7.11_4+docs+grc+jack+log4cpp+logging+portaudio+qtgui+sdl+swig+uhd+wavelet+wxgui+zeromq
 2) gnuradio @3.7.11_4+docs+grc+jack+log4cpp+logging+portaudio+qtgui+sdl+swig+uhd+wavelet+zeromq (active)

The second one is activated, my question is how to activate the first one instead? I'm using Mac OS.\

Thanks!

**Comment by marcusmueller** [comment]
It's sadly not clear what the bug/issue described here is. Please note that this is essentially a bug tracker, so you might much rather discuss this on [our mailing list](https://lists.gnu.org/mailman/listinfo/discuss-gnuradio).
