### ISSUE TITLE
gnuradio version  3.7.11.1 Installation

### ISSUE THREAD

**Issue by Alhamzi** [gnuradio/gnuradio#1538]
Hallo
 I have a basic question. I am a beginner with GNURadio and I want to work on version 3.7.11.1 but when I install it through pybombs I get the latest version 3.7.12. How can I install a specific version like 3.7.11.1
thanks in advance

**Comment by BrashEndeavours** [comment]
Edit the PyBombs config in ~/.pybombs/config.yml and add specific package flags for gnuradio to point to a specific commit to build from.

packages:
    gnuradio:
        gitbranch: Whateverbranch
        gitrev: 012345abc

**Comment by mbr0wn** [comment]
@BrashEndeavours thanks for answering this! @Alhamzi the issue tracker is for tracking bugs and issues with the GNU Radio code base, so please direct such questions to the mailing list.
