### ISSUE TITLE
Memory Allocation Bug

### ISSUE THREAD

**Issue by silidan** [gnuradio/gnuradio#1541]
gnuradio fails to allocate memory of size 1048576 KB or larger.

gr::vmcircbuf_sysv_shm: shmget (1): Invalid argument
gr::vmcircbuf_sysv_shm: shmget (1): Invalid argument
gr::vmcircbuf_sysv_shm: shmget (1): Invalid argument
gr::buffer::allocate_buffer: failed to allocate buffer of size 1048576 KB
gr::vmcircbuf_sysv_shm: shmget (1): Invalid argument
gr::vmcircbuf_sysv_shm: shmget (1): Invalid argument
gr::vmcircbuf_sysv_shm: shmget (1): Invalid argument
gr::buffer::allocate_buffer: failed to allocate buffer of size 1048576 KB
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc

>>> Done

Ubuntu 16.06 64bit, 4.4.0-103-lowlatency,
kernel.shmall = 18446744073692774399
kernel.shmmax = 18446744073692774399
kernel.shmmni = 4096

[memory_allocation_bug.grc.log](https://github.com/gnuradio/gnuradio/files/1572795/memory_allocation_bug.grc.log)

![memory_allocation_bug_flowgraph](https://user-images.githubusercontent.com/4339095/34172407-3fd451de-e4f2-11e7-94fc-a1490267f57f.png)
[memory_allocation_bug.log](https://github.com/gnuradio/gnuradio/files/1572783/memory_allocation_bug.log)

**Comment by thasti** [comment]
To add some information to this:

- The flowgraph tries to create a vector with 1024*1024*64 complex values, which will cause a gr::buffer allocation for 2^30 elements. 
- gr::buffer implements this as a gr::vmcircbuf, with the size argument passed as an int (which is still okay so far). 
- gr::vmcircbuf_sysv_shm will try to allocate a shared memory buffer (shmget) with int(2 * size + 2 * pagesize) as an argument. This becomes greater than 2^31, overflows to negative number, which is in turn converted to size_t by being passed as an argument to shmget
- the cast to size_t causes the argument to become a huge positve number (close to 2^64 on 64 bit systems) and therefore being larger than either SHMMAX or the available system memory.

One can see multiple problems:
- gr::buffer should restrict the size of allocated buffers (maybe)
- gr::vmcircbuf checks for size to be negative, but then tries to shmget 2*size+2*pagesize, which might cause an overflow itself.
- in general, maybe size_t types should be used here and there.

**Comment by marcusmueller** [comment]
vlosed per #4460

**Comment by willcode** [comment]
The change to size_t should make it work up to 2GB, if the system can provide 2x that much consecutive virtual memory. Things will always fail for a high enough value.
