### ISSUE TITLE
Scipy needed for make test; not checked for, hence inexplicable test failures

### ISSUE THREAD

**Issue by c0debreaker** [gnuradio/gnuradio#1545]
The `make` was fine. Running `make test` failed on few items

Here is the output

```
The following tests FAILED:
	 91 - qa_polar_decoder_sc (Failed)
	 92 - qa_polar_decoder_sc_list (Failed)
	 93 - qa_polar_decoder_sc_systematic (Failed)
	 94 - qa_polar_encoder (Failed)
	 95 - qa_polar_encoder_systematic (Failed)
	209 - qa_zeromq_pub (Failed)
Errors while running CTest
make: *** [test] Error 8
```
What am I missing?

**Comment by c0debreaker** [comment]
I fixed it after installing scipy. :)

**Comment by marcusmueller** [comment]
Changing title, reopening: this is actually an issue, and unless you submitted a pull request with a fix for that issue (namely, need for scipy not tracked for `make test`), it shouldn't be closed.

**Comment by noc0lour** [comment]
Replacing scipy with something else already present would be a viable solution imho.

**Comment by marcusmueller** [comment]
I'd argue that if someone builds GNU Radio, then having scipy as *build-time* dependency (just like CMake, SWIG, …) really isn't much of a burden. Packaging systems track these separately from run-time deps, anyway.

The question is whether it should be a run-time dependency, too, is a different one. None of our `gr_plot_**` tools work without, nor does `gr_filter_design`, and a lot of the gr-digital and -dtv and -filter examples depend on it, too. In many cases, I'd agree, all that's used is `fftpack`.... which does come with numpy.

**Comment by jdemel** [comment]
SciPy use should actually be reduced to a minimum. Here in paticular, polar codes actually use specific SciPy function. 
I agree that making SciPy a build/run-time requirement does not hurt. Especially because almost everyone will need it and it is quite tightly bundled with NumPy anyways.

**Comment by marcusmueller** [comment]
Just having had a night of rest about this: don't underestimate the effort that goes into packaging Python packages for embedded platforms. If we do make scipy a runtime req, we should really very clearly define the affected components -maybe even in finer granularity than "gr-utils".

Am 18. Februar 2018 23:44:19 MEZ schrieb jdemel <notifications@github.com>:
>SciPy use should actually be reduced to a minimum. Here in paticular,
>polar codes actually use specific SciPy function. 
>I agree that making SciPy a build/run-time requirement does not hurt.
>Especially because almost everyone will need it and it is quite tightly
>bundled with NumPy anyways.
>
>-- 
>You are receiving this because you modified the open/close state.
>Reply to this email directly or view it on GitHub:
>https://github.com/gnuradio/gnuradio/issues/1545#issuecomment-366554981

-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.

**Comment by jdemel** [comment]
I had this discussion in mind, when I added a comment to GREP0001.
The SciPy import should be in a try/except clause and the corresponding code should offer a fallback solution and a warning in case SciPy is not available.
I assume this'll fix these test case failures.

**Comment by nickoe** [comment]
It looks like the fixes mentioned above are on all branches now, master, maint-3.7 and maint-3.8. I think we can close this relic.
