### ISSUE TITLE
RTL-SDR ERROR: Port number 0 exceeds max of (none)

### ISSUE THREAD

**Issue by Yaoshicn** [gnuradio/gnuradio#1556]
Hi, 

When I tried to run a simple flowchart (see screenshot below) with RTL-SDR dongle on Ubuntu 16.04 LTS, the program threw an error "what():  port number 0 exceeds max of (none)". The output is attached below for your kind perusal. I have checked with my installation of all dependencies and the udev permission. Would you please give me some help on this issue?

Thanks in advance.

```
linux; GNU C++ version 5.4.0 20160609; Boost_105800; UHD_003.010.002.HEAD-0-gbd6e21dc

gr-osmosdr v0.1.4-98-gc653754d (0.1.5git) gnuradio 3.7.11
built-in source types: file fcd rtl rtl_tcp uhd rfspace redpitaya 
Using device #0 Realtek RTL2838UHIDIR SN: 00000001
Found Rafael Micro R820T tuner
[R82XX] PLL not locked!
Exact sample rate is: 1000000.026491 Hz
[R82XX] PLL not locked!
terminate called after throwing an instance of 'std::invalid_argument'
  what():  port number 0 exceeds max of (none)
```
![screenshot from 2018-01-23 21-14-18](https://user-images.githubusercontent.com/5865630/35277638-67696850-0082-11e8-8bd3-9454bd30f310.png)

Best Regards,
Xuanliang

**Comment by marcusmueller** [comment]
I'm afraid this isn't an issue with GNU Radio, but with librtlsdr or gr-osmosdr. I'll have to refer you to them.
