### ISSUE TITLE
WAV file sink append file option

### ISSUE THREAD

**Issue by diazm** [gnuradio/gnuradio#1569]
Hi, it is possible to add the append file option to wav file sink block?. It would be very useful feature.

 Regards.

**Comment by mbr0wn** [comment]
Sure, it's possible. Do you want to take a stab?

**Comment by marcusmueller** [comment]
@diazm we're actually still waiting for a reply from you here – it would be very exciting if you added that functionality, and you could build upon our support while doing so!

**Comment by japm48** [comment]
I am working on this.
