### ISSUE TITLE
Recored Splited Audio Files

### ISSUE THREAD

**Issue by techuss** [gnuradio/gnuradio#1578]
I want to build a project to record audio and/or IQ stream of PMR Walkie-talkie.
I use USRP N210 and build the flow graph as shown in picture:
https://ibb.co/i68vAc

It is work well, But all speech will recorded in the same file. I want to record a stand-alone call in one file. i.e: if there is a call, it recorded in new file. when call ended, then the file closed (new call in new file), and so on.
what will I modify for make my project?

**Comment by mbr0wn** [comment]
This is more of a question for the mailing list. Please direct your inquiries there.
