### ISSUE TITLE
Hardware Impairment Block adds phase noise regardless of configuration

### ISSUE THREAD

**Issue by dkozel** [gnuradio/gnuradio#1579]
The Hardware Impairment block adds a lot of phase noise to the signal regardless of the Phase Noise value being set to 0.

Blue is the input signal, Red is the output of the HW impairments block.

![hw-impairments](https://user-images.githubusercontent.com/253888/35778013-3079d598-09b8-11e8-8853-d22317a7f979.png)

**Comment by dkozel** [comment]
Theory from last night, the setting of "0" on the phase noise is 0 dBc.

**Comment by noc0lour** [comment]
Does it make sense to give the value in `dB` and not in linear scale?

**Comment by mbr0wn** [comment]
I took a look and it is the noise power (in dB) of the analog noise source that is used to generate faux phase noise. Pretty convoluted. We can probably do better. But I think just improving the label for this will be sufficient.

**Comment by marcusmueller** [comment]
Bug: Hardware impairment block brings undesired hardware impairment

Mental Category: Hyperrealism.

S,CNR.
