### ISSUE TITLE
modtool: add tests

### ISSUE THREAD

**Issue by noc0lour** [gnuradio/gnuradio#1580]
Having tests creating/deleting a module would be great to test if code runs (and we can even expect a "known good" result).

**Comment by marcusmueller** [comment]
love the idea. Let's work on something like a minimal QA that makes a module, adds a python source to it, fills that source with a `range(1000)` generator, adds a python QA that checks that, runs that test and then deletes the directory. For 3.8.

**Comment by swap-nil7** [comment]
I guess we have the tests in the current version. Don't we?

**Comment by mormj** [comment]
Yes, I believe the modtool tests that are currently in place are sufficient
