### ISSUE TITLE
objective_fct.c and whatever is not needed from the gen_interpolator_taps directory should be removed

### ISSUE THREAD

**Issue by marcusmueller** [gnuradio/gnuradio#1585]
@awalls-cx18 pointed out there might be licensing problems surrounding that code.

**Comment by awalls-cx18** [comment]
Technically simpson.[ch] needs to be removed.  objective_fct.c can stay, but it won't work until it is ported to use numerical integration routines from the GSL library.

I recall looking at praxis.f and thinking it was OK.  Someone should take another look at it and the associated README file.

**Comment by marcusmueller** [comment]
closed by #1605, as far as I can see. A **huge** thank goes out to the ever competent @awalls-cx18!
