### ISSUE TITLE
gr-newmod: Should not contain "This file is part of GNU Radio"

### ISSUE THREAD

**Issue by marcusmueller** [gnuradio/gnuradio#1587]
Instead, something like @awalls-cx18 does: "This file was generated by gr_modtool, a tool from the GNU Radio framework", or so.

**Comment by noc0lour** [comment]
We could add a `This file is part of $module_name` as a convenience function. Since this is probably the case if people add blocks with `gr_modtool`.

**Comment by marcusmueller** [comment]
Indeed, that would be a great thing to do!

**Comment by mbr0wn** [comment]
modtool could default to asking for a copyright holder.

**Comment by marcusmueller** [comment]
I like that idea, @mbr0wn.

**Comment by marcusmueller** [comment]
In the interest of GSoC, postponing this to 3.8, if there's no objections from you two!

**Comment by primercuervo** [comment]
@marcusmueller this and all the other ones labeled with "modtool"?

**Comment by marcusmueller** [comment]
No, only this.
