### ISSUE TITLE
cleanup gru Python module

### ISSUE THREAD

**Issue by marcusmueller** [gnuradio/gnuradio#1591]
I'm generally not a big fan of "misc" namespaces, and I'm pretty sure that there's a few things in there that no-one uses.

Notice that formally, `gnuradio.gru` is external API, but honestly... There's so little in there that was ever meant to be API that I don't think we'd break anything external if we deleted that whole module today.

Obviously, low prio.

**Comment by bravech** [comment]
Hi, I'm looking to get started with contributing to open source (hopefully joining GNURadio for GSoC 2020!). Is this change still something that's needed? If not, could you please point me in the direction of an issue to get started with.

**Comment by gateship1** [comment]
Hello, I am looking for a first issue. I noticed this is still under "To do" in Release 3.9. Can i take a crack at this one?

**Comment by dkozel** [comment]
@gateship1 Yes, please do. I'm not clear whether there are only some unused functions that can be deleted, the entire module should be deprecated, or the functions should be moved into the calling functions. You'll have to see what's still in there as this issue is over two years old.

**Comment by argilo** [comment]
Re-opening, since gru isn't removed yet.

**Comment by marcusmueller** [comment]
With #3896, we have but left in actual use:

- [ ] `daemonize` in the dialtone example. Do we really need to use that? It feels like it was some Python <2.5-era hack
- [ ] `freqz`/`gnuplot_freqz`: used only in commented out code in `fm_emph`, and honestly, what about `scipy.signal`? 
- [ ] `hexshort`: unused
- [ ] `hexint`: used in crc32. `hexint = lambda mask: (mask - 2**32) if (mask >= 2**31) else mask`.
- [ ] `msgq_runner`: single-point usage in `uhd_app.py`. @mbr0wn is moving it to that app itself sensible?

**Comment by marcusmueller** [comment]
Thanks, @argilo! Awesome!
