### ISSUE TITLE
RTL-SDR Error :  No supported tuner found

### ISSUE THREAD

**Issue by Lidoro** [gnuradio/gnuradio#1592]
Hello,

I try to install rtl-sdr and gnuradio on my computer, on Linux mint 18.1 cinnamon 3.2.7 64 bits.
the installation is going well but when I try to execute rtl_test :

Found 1 device(s):
  0:  Realtek, RTL2838UHIDIR, SN: 00000001

Using device 0: Generic RTL2832U OEM
No supported tuner found
Enabled direct sampling mode, input 1
Supported gain values (1): 0.0 
Sampling at 2048000 S/s.

I try intallling with a script and with pybombs, i have the same issue.

My dongle have  RTL2832 chip and FC0012 tuner

it works on windows, and it works when i use "linux live gnuradio dvd".

And it works if I start on "linux live gnuradio dvd" and reboot after on linux mint.

Thank you for your help
Best Regards
Lidoro

Edit : Nobody to help me ?

**Comment by marcusmueller** [comment]
Lidoro, hi!

This is a bug tracker, and not a help forum; I'll hence have to close your issue. Also, this is not a GNU Radio issue, but if anything a versioning issue of your rtl-sdr.

You might need to uninstall the librtlsdr you've got from mint, and build librtlsdr as well as gr-osmosdr from source. Please do not follow up here, but use the RTL-SDR specific mailing ists.
