### ISSUE TITLE
pmt: len_y, len_x: unitialized use

### ISSUE THREAD

**Issue by noc0lour** [gnuradio/gnuradio#1598]
In [pmt.cc#L1133](https://github.com/gnuradio/gnuradio/blob/da0a102e9b076db83fe5a63b3730ac39b588eb92/gnuradio-runtime/lib/pmt/pmt.cc#L1133) the comparison of vectors is most likely false since uninitialized memory is used to compare them.

This breaks the fix in #1597, Initializing with `length()` or not using this helper variable at all would help.

**Comment by noc0lour** [comment]
Ok, wait this is even better, maybe not even a bug. The variables are initalized inside `uniform_elements`.

**Comment by noc0lour** [comment]
Quick test revealed `len_x` and `len_y` have the correct value after `memcmp` but probably are still undefined during `memcmp`.

**Comment by marcusmueller** [comment]
> Quick test revealed len_x and len_y have the correct value after memcmp but probably are still undefined during memcmp.

Exactly.

**Comment by noc0lour** [comment]
The commit should have closed this?
