### ISSUE TITLE
Get rid of all the `fprintf(stderr`, replace with logging

### ISSUE THREAD

**Issue by marcusmueller** [gnuradio/gnuradio#1599]
Same goes for `cerr`, and also `stdout`/`cout`, but I consider the error cases the most important (because these are things that almost certainly should end up in logs).

**Comment by gvanhoy** [comment]
Would this include perror(*) as well?

**Comment by marcusmueller** [comment]
I think the cerr / fprintf(stderr is done by #3339; so closing this.
