### ISSUE TITLE
tunnel.py: planned obsolescence

### ISSUE THREAD

**Issue by marcusmueller** [gnuradio/gnuradio#1600]
Old users will remember how much fun we've had supporting `tunnel.py`. It's much, much better now, but:

tunnel.py still uses the now deprecated python packetizers, it's got hard-coded UHD transmit chain but doesn't use any of the packet-friendly gr-uhd features, it's still using OptionParser (and #947 points out there's an option handling bug), no-one would advocate its usage over the gr-digital header/payload (de)mux centric GRC flow graphs:

Let's get rid of it. By 3.8, so that we don't have to port it to Py3.

I'd want @mbr0wn's agreement on this.

**Comment by noc0lour** [comment]
No tunnel.py in tree found.
