### ISSUE TITLE
`d_found` unused in gr::blocks::peak_detector_XX_impl

### ISSUE THREAD

**Issue by marcusmueller** [gnuradio/gnuradio#1621]
Clean up.

**Comment by talih0** [comment]
I can take this on

**Comment by talih0** [comment]
@marcusmueller, should I work of the 'next' branch?

**Comment by marcusmueller** [comment]
yes, please.

**Comment by talih0** [comment]
@marcusmueller 
Before making any changes I ran make test on 'master' and 'next'. 
Unfortunately, the test failed. Is this a problem with my compilation, or are these fails expected? 

Total Test time (real) = 141.71 sec

The following tests FAILED:
         91 - qa_polar_decoder_sc_list (Failed)
         95 - qa_polar_decoder_sc (Failed)
         96 - qa_polar_decoder_sc_systematic (Failed)
         97 - qa_polar_encoder_systematic (Failed)
         98 - qa_polar_encoder (Failed)
        214 - qa_zeromq_sub (Failed)
Errors while running CTest
Makefile:61: recipe for target 'test' failed

**Comment by noc0lour** [comment]
I guess you're missing scipy for the `qa_polar` tests and `zeromq_sub` is unfortunately a flaky test.

**Comment by talih0** [comment]
thanks, qa_polar test was fixed by installing scipy
