### ISSUE TITLE
Remove unused members

### ISSUE THREAD

**Issue by marcusmueller** [gnuradio/gnuradio#1624]
compiler's getting really verbose about unused private members; run with `-Wunused-private-field` and clean up.

**Comment by tpalmerstudios** [comment]
I  don't know much about this project, but I'll start working on it

**Comment by marcusmueller** [comment]
@tpalmerstudios that's great! 

Have you built GNU Radio from source before? You'll need a relatively recent Clang or GCC (which version does `gcc -v` or `clang -v` give you?). Fedora 27 might be a good choice to run this on.

In the CMake step, you'd do something like 

```
cmake -DCMAKE_BUILD_TYPE=RelWithDebInfo "-DCMAKE_CXX_FLAGS=-Wunused-private-field -Wno-deprecated-declarations" ..
```

to get all the compiler warnings about unused private field. For example, I picked from that long list to get you started: #1621, #1622, #1623 .

In essence, you find these fields in the header, remove them, and `make; make test` to make sure you didn't break anything.

Feel like taking this up?

**Comment by chaithyagr** [comment]
I'll work on this.. will get back with any issues
