### ISSUE TITLE
too many arguments to function volk_32f_8u_polarbutterfly_32f

### ISSUE THREAD

**Issue by Red-Owl** [gnuradio/gnuradio#1647]
[ 39%] Building CXX object gr-fec/lib/CMakeFiles/gnuradio-fec.dir/polar_decoder_common.cc.o
/usr/src/gnuradio/gr-fec/lib/polar_decoder_common.cc: In member function ‘void gr::fec::code::polar_decoder_common::butterfly_volk(float*, unsigned char*, int, int, int)’:
/usr/src/gnuradio/gr-fec/lib/polar_decoder_common.cc:128:95: error: too many arguments to function
         volk_32f_8u_polarbutterfly_32f(llrs, u, block_size(), block_power(), stage, u_num, row);

polar_decoder_common.cc
128:95

**Comment by noc0lour** [comment]
Will be fixed by #1640 . You can apply that patch locally if you like. Thanks for reporting :)

**Comment by noc0lour** [comment]
This was fixed with 00c6f258259c61f25dc220402a9d07544942b414 on next. If `volk` is released for the `3.7.12` release the outstanding PR will be merged into master.

**Comment by marcusmueller** [comment]
@Red-Owl just for records: Now fixed on master, and will be fixed in release 3.7.12

**Comment by pswiatki** [comment]
Interestingly I now get:

[...]/gnuradio/gr-fec/lib/polar_decoder_common.cc: In member function 'void gr::fec::code::polar_decoder_common::butterfly_volk(float*, unsigned char*, int, int, int)':
[...]/gnuradio/gr-fec/lib/polar_decoder_common.cc:128:81: error: too few arguments to function
         volk_32f_8u_polarbutterfly_32f(llrs, u, block_power(), stage, u_num, row);

I pulled the latest commits from master.

**Comment by BeamPower** [comment]
I'm getting the same error.
Can someone provide details on how to fix it?
Thank you.

**Comment by noc0lour** [comment]
Update to the newest release on volk & GNU Radio.

**Comment by barcating** [comment]
> This was fixed with [00c6f25](https://github.com/gnuradio/gnuradio/commit/00c6f258259c61f25dc220402a9d07544942b414) on next. If `volk` is released for the `3.7.12` release the outstanding PR will be merged into master.

It works, Thanks.
