### ISSUE TITLE
OFDM carrier allocator causes invisible SIGFPE with certain input

### ISSUE THREAD

**Issue by m3x1m0m** [gnuradio/gnuradio#1648]
Using twice () to signal, that no pilot carriers and no pilot symbols are desired causes a SIGFPE, which is not even visible in grc. Long-term a solution might be to make the constructor saver, but shot-term changing 
`<value>()<\value>`
to 
`<value>((),)<\value>`

in the XML file should suffice to not mislead users to trust the presetting.

**Comment by marcusmueller** [comment]
That's a nice recommendation, so far! Could you make a quick PR against master for this?

I'd agree, however, that we should probably have a check in there somewhere. But, just doing this is basically "small scale documentation", so I'd say: go for it!
