### ISSUE TITLE
CMake: Be sure we still need all checks we do in 3.8

### ISSUE THREAD

**Issue by marcusmueller** [gnuradio/gnuradio#1674]

**Comment by jdemel** [comment]
Did you add the `Release 3.9` milestone by accident? I'd argue unnecessary checks in 3.8 should be removed in 3.8 and thus, this issue should be part of the `Release 3.8` milestone.

**Comment by marcusmueller** [comment]
No, this was intentional! There's a truckload of dependency in movement for 3.8, and I'd like to let the dust settle on that before we spend too much time on cleaning up checks; it's a configure-time performance enhancement, only, after all.

Which really doesn't mean that if you see a check we don't need, you shouldn't be removing it right now :)

It's just that I can't assign priority to this right now.

**Comment by marcusmueller** [comment]
I think I'm through the thick of this, especially in gr-digital
