### ISSUE TITLE
HackRF does not stop sending or receiving after pressing stop or close the application

### ISSUE THREAD

**Issue by Epios** [gnuradio/gnuradio#1684]
When I start my HackRF on (e.g.) 95 Mhz (receive) within GQRX the RX led is on. By quitting or pressing stop within GQRX, the RX led turns off. Normal behaviour. 

Within gnuradio-companion (v 3.7.11) the led stays on. I am listening on (e.g.) 95 Mhz and even after pressing stop or closing gnuradio-companion, the led stays on. The same for transmitting (TX). If I listen with a second SDR, I can see that my hackrf is still transmitting and did not shut down the command. But when I enter "hackrf_info" in a terminal, the led (RX/TX) turns off and the signal does not get transmitted anymore. Is this a bug or a configuration issue and how can I proper shut down the hackrf interace? because I do not know, if this device might get damaging by interrupting it with the cli while sending all the time.

Here are the details:

Operating System (Pentoo)
`Linux pentoo 4.14.15-pentoo #1 SMP Tue Jan 30 01:15:18 UTC 2018 x86_64 Intel(R) Core(TM) i5-2520M CPU @ 2.50GHz GenuineIntel GNU/Linux`

hackrf_info
`hackrf_info version: 2017.02.1
libhackrf version: 2017.02.1 (0.5)
Found HackRF
Index: 0
Serial number: 0000000000000000a06XXXXXXXX
Board ID Number: 2 (HackRF One)
Firmware Version: 2018.01.1 (API:1.02)
Part ID Number: 0xa000XbXX 0x00X047XX`

Within gnuradio-companion I am using absolute basic blocks like osmocom source and file sink. Also if I set reapeat to "no" it makes no difference. Thanks in advance.

**Comment by noc0lour** [comment]
This might be a bug in the `osmocom_source` or related libraries missing out on stopping the hardware if the application is closed.

Probably the osmosdr mailing list is of more help here: https://lists.osmocom.org/mailman/listinfo/osmocom-sdr.

If you can provide more debug information actually pinpointing GNU Radio (or at least prove that osmosdr/hackrf libraries are not to blame) you are welcome to reopen the bug report.

Note: Under the hood GQRX is using GNU Radio for some parts, but might fiddle with it to get it right.
