### ISSUE TITLE
gr-uhd: command tags are broken

### ISSUE THREAD

**Issue by mrjacobagilbert** [gnuradio/gnuradio#1688]
Part of the effort to reduce runtime creation of interned strings has caused UHD CMD_xxx PMTs to be uninitialized causing runtime segmentation fault when used by the command handler. It looks like they are declared in the header, initialized in the implementation class file but for whatever reason the don't seem to be when used.

**Comment by marcusmueller** [comment]
Closed by #1697, right, @mrjacobagilbert?

**Comment by mrjacobagilbert** [comment]
@marcusmueller sorry! close this one out it's good.
