### ISSUE TITLE
GRC Options should allow specifying copyright holder

### ISSUE THREAD

**Issue by dkozel** [gnuradio/gnuradio#1704]
The GRC Options block currently allows setting the Author which results in a comment at the top of the file. I suggest that the header always include the GPL-3.0 SPDX header and a copyright line if a copyright holder is specified.

https://spdx.org/licenses/GPL-3.0-only.html

``` python
#!/usr/bin/env python2
# -*- coding: utf-8 -*-
#
# SPDX-License-Identifier: GPL-3.0
#
##################################################
# GNU Radio Python Flow Graph
# Title: Example Title
# Author: Derek Kozel
# Copyright: 2018 Ettus Research, a National Instruments Company
# Generated: Fri Mar 23 11:16:05 2018
# GNU Radio Version: 3.7.12git-337-g76f8abeb
##################################################
```

**Comment by marcusmueller** [comment]
I like that it's a sane default and helpful. Can we also include a "generated using GRC {version}" thing?

**Comment by dkozel** [comment]
Yes! I had that in my mind this morning but it didn't make it into this issue. That would be very useful information for anyone running the flowgraph three years later.

**Comment by haakov** [comment]
I submitted a pull request for this issue above.

How does this look?

```
#!/usr/bin/env python2
# -*- coding: utf-8 -*-
#
# SPDX-License-Identifier: GPL-3.0
#
##################################################
# GNU Radio Python Flow Graph
# Title: Example Title
# Author: Example Author
# Copyright: Example Copyright
# Description: Example Description
#
# Generated: Wed Apr 25 21:29:30 2018
# Generated using GRC version 3.7.12.0
##################################################
```

**Comment by dkozel** [comment]
Yes, that output looks good to me. Thanks for the PR!

@marcusmueller There isn't actually a difference between GR version and GRC version right? I want to make sure there's a git hash (when relevant), but looking at the code it should be correct.

**Comment by haakov** [comment]
https://github.com/gnuradio/gnuradio/pull/1745 has been merged, I believe this issue can be closed.

**Comment by mbr0wn** [comment]
Well then....
