### ISSUE TITLE
Update gr-tutorial *simultaneously to* 3.8 release

### ISSUE THREAD

**Issue by marcusmueller** [gnuradio/gnuradio#1712]
https://github.com/gnuradio/gr-tutorial/issues/11

This is a heavily multi-faceted thing, as it also includes the guided tutorials in the wiki.

We'll need previously non-user beta testers.

**Comment by marcusmueller** [comment]
This would be a very fine thing to encourage development beginners to work on during GRCon

**Comment by duggabe** [comment]
Based on my recent revisions to the Tutorials, gr-tutorial has been deprecated. The one remaining flowgraph for Guided_Tutorial_PSK_Demodulation (mpsk_stage6.grc) has been moved to gr-digital/examples with https://github.com/gnuradio/gnuradio/pull/3430
