### ISSUE TITLE
Launching gnuradio after installing from source

### ISSUE THREAD

**Issue by jabirshabbir** [gnuradio/gnuradio#1729]
Hi,
I installed gnu radio from source in the next branch of git.I am not able to launch it by gnuradio-companion command.I am unable to find gnuradio-companion by which command but locate command shows it is in /usr/bin

**Comment by marcusmueller** [comment]
Closing, as doesn't seem to be a bug report against GNU Radio. There's something wrong with your system if the executable is in a directory that you expect to be in $path, but can't be found.
