### ISSUE TITLE
Eye Diagram plot (eye.py) from gr-baz with WX-GUI

### ISSUE THREAD

**Issue by RonalMontoya** [gnuradio/gnuradio#1731]
When I tried to use the eye diagram block from the library gr-baz, which uses WX-GUI, I obtained this error message:

File "/usr/local/lib/python2.7/dist-packages/gnuradio/wxgui/plot.py", line 211, in draw
 if coord == None:
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

I solved this issue changing the checks located in lines 211 and 274:

coord == None

in the file /gnuradio/wxgui/plot.py by

_numpy.equal(coord, None).all()

**Comment by dkozel** [comment]
@RonalMontoya Sorry for the long delay in reviewing this issue. This strongly sounds like either a bug in gr-baz or in how you were using the eye diagram block in it. I realize this is from a few months ago, but do you still have the flowgraph that causes that error? If so, I'd suggest posting an an issue in https://github.com/balint256/gr-baz.

Additionally, the WX-GUI blocks are deprecated and will be removed soon. While we will happily merge any fixes to the blocks as part of supporting the 3.7-maint branch, we do not plan on doing additional development of the blocks in the future.
