### ISSUE TITLE
wildcard pad sink connected to message port: `Generate Error: invalid literal for int() with base 10: 'in'`

### ISSUE THREAD

**Issue by marcusmueller** [gnuradio/gnuradio#1741]
![grcbug](https://user-images.githubusercontent.com/958972/39048315-4c3be5e4-449d-11e8-8500-9e2d8dac5c55.png)

When generating above flowgraph, you get

    Generate Error: invalid literal for int() with base 10: 'in'

which happens because `#set key = $flow_graph.get_pad_port_global_key($port)` tries to convert the port key to an integer, but that seems to fail.

**Comment by skoslowski** [comment]
Yes, it fails to resolve the wildcard correctly and assumes a stream port. 
I will have to look into this some more...

**Comment by marcusmueller** [comment]
I believe this has been resolved
