### ISSUE TITLE
Need help customizing osmocom source and file sink

### ISSUE THREAD

**Issue by mehrdaddavoody** [gnuradio/gnuradio#1767]
Hi

Is there any way to define an osmocom source which has 4 different central frequencies in GNU radio companion? And respectively a file sink that has 4 different file saving directories in order for the final flow graph to be smaller in size.

Another question that I have is that can we customize a file sink in GNU radio companion that is triggered only when a signal is received? (in order to make the saved capture file smaller in size)

**Comment by marcusmueller** [comment]
This is a bug tracker, not a help forum; hence, I'm closing this. Please refer to the mailing list for discussion! Thank you very much for your understanding.

**Comment by dkozel** [comment]
@mehrdaddavoody The mailing list Marcus is referring to is located at the below link. I hope we can help there.
https://lists.gnu.org/mailman/listinfo/discuss-gnuradio
