### ISSUE TITLE
FFT Plot not Showing Frequency

### ISSUE THREAD

**Issue by haryows** [gnuradio/gnuradio#1782]
Greeting sir,

i have to try make a simple fm receiver using gnuradio+hackrf one n already use many example of grc flow graph but all of them just showing blank graph like this: 

![selection_001](https://user-images.githubusercontent.com/30684427/40134278-1f2e482e-596c-11e8-8ad6-6e71c8755b1a.png)
![selection_002](https://user-images.githubusercontent.com/30684427/40134288-2690c2ea-596c-11e8-805f-5b73c341579b.png)
![selection_003](https://user-images.githubusercontent.com/30684427/40134296-2c58cad8-596c-11e8-8a73-6faa26929327.png)

im using ubuntu 16.04, what should i do for fix this issue?please help me

**Comment by dkozel** [comment]
Hello @haryows. Thanks for including as much information as you have. The Mailing list is the right place to ask for help like this. Could you please send an email to the list with your screenshots and flowgraph?
https://lists.gnu.org/mailman/listinfo/discuss-gnuradio

Also, in your email can you say if you have received anything using your HackRF in the past? As much information as you can include is always helpful.
https://wiki.gnuradio.org/index.php/ReportingErrors#Checklist:_Asking_a_question_on_the_mailing_list

Thanks!
