### ISSUE TITLE
GRC: Function probes are broken

### ISSUE THREAD

**Issue by paurea** [gnuradio/gnuradio#1783]
I am not sure if this is the place for issues in the wiki with tutorials, let me know if it is not. There is a bug in the code for the tutorial. In the code for section 3.1.5 in the code for switching between the two amplitudes  depending on the control signal, the try should include the if above. I have tested it with gnuradio 3.7.11 (included with the latest ubuntu 18).

       def _variable_function_probe_0_probe():
            while True:
                val = self.probe.level()
                print val
                if val == 1:
                    self.set_ampl(1)
                    self.set_freq(1000)
                else:
                    self.set_ampl(.3)
                    self.set_freq(100)
                try:
                    self.set_variable_function_probe_0(val)
                except AttributeError:
                    pass
                time.sleep(1.0 / (10))

should be:

       def _variable_function_probe_0_probe():
            while True:
                val = self.probe.level()
                print val
                try:
                if val == 1:
                    self.set_ampl(1)
                    self.set_freq(1000)
                else:
                    self.set_ampl(.3)
                    self.set_freq(100)
                    self.set_variable_function_probe_0(val)
                except AttributeError:
                    pass
                time.sleep(1.0 / (10))

The problem is the first sample comes before the attribute analog_sig_source_x_1 is created and it is used in set_ampl. The error with the code as it is is:

Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "./probep.py", line 92, in _variable_function_probe_0_probe
    self.set_ampl(.3)
  File "./probep.py", line 211, in set_ampl
    self.analog_sig_source_x_1.set_amplitude(self.ampl)
  File "/usr/lib/python2.7/dist-packages/gnuradio/gr/hier_block2.py", line 92, in __getattr__
    return getattr(self._impl, name)
AttributeError: 'top_block_sptr' object has no attribute 'analog_sig_source_x_1'

**Comment by dkozel** [comment]
Thanks @paurea. Here or the mailing list is a reasonable place.

**Comment by mormj** [comment]
The block_id indeed gets unnecessary quotes.  Not sure yet exactly why this changed from 3.7 to 3.8 - looks like the _stringify_flag for parameters where dtype = string adds additional quotes, which makes sense when the parameter is a function argument, but less sense when the string is the name of a block in the flowgraph. 

Changing the dtype to 'raw' in variable_function_probe yaml will make the issue go away, but not being an expert in the grc codebase i'm not sure if this is the correct fix.  Will have to at a minimum try some others.

There are other 3.7-3.8 conversions missing in gr-tutorial that need to be addressed separately from this bug
