### ISSUE TITLE
digital: Add Constellation Encoder implementation

### ISSUE THREAD

**Issue by noc0lour** [gnuradio/gnuradio#1801]
Currently the only way to convert bytes to symbols using a constellation object is either using the `chunks_to_symbols` or the `constellation_modulator`. 

The former is not intuitive and won't work for differential phase modulation. The latter is applying pulse shaping which might not be desired (and is a python hier block).

A simple Constellation Encoder (the inverse to the Constellation Decoder) might be worth the effort. 
I can implement that one and deprecate the others.  According to: https://docs.google.com/spreadsheets/d/1Yty89iTZbr1zM_2M8NyypdNz-P5TN2IvgXApDf94rsk/edit#gid=0

**Comment by marcusmueller** [comment]
@noc0lour keep this as a 3.8 milestone or postpone to 3.9?

**Comment by noc0lour** [comment]
This should be doable in a afternoon session, since the way is now rather paved to the 3.8 release I could throw that in, if you don't mind?
