### ISSUE TITLE
float32->char conversion block fails

### ISSUE THREAD

**Issue by marcusmueller** [gnuradio/gnuradio#1820]
since I assume this is a VOLK bug, see:

https://github.com/gnuradio/volk/issues/188

still tracked here until a new VOLK release containing a fix for above issue is released.

**Comment by krk** [comment]
https://github.com/gnuradio/volk/pull/199 is merged but the referenced issue is still open.

**Comment by devnulling** [comment]
@marcusmueller @michaelld can this issue be closed out?

**Comment by michaelld** [comment]
I'm voting yes, and closing accordingly.
