### ISSUE TITLE
When building gnuradio, it installs and removes system-wide packages without asking for confirmation

### ISSUE THREAD

**Issue by lgommans** [gnuradio/gnuradio#1823]
It's nice that gnuradio tries to install all required packages without having to look for the package name myself, but I'd rather get a list and get a prompt to confirm. As it is, it had to remove libcurl3 and it just went ahead and did that. I think removing system-wide packages automatically is a bug.

This happened when running `pybombs install gnuradio` as my local user. Apparently it uses a previous sudo session, so I again had no interaction in which I might have chosen not to allow it.

**Comment by dkozel** [comment]
Hi @lgommans 
Thanks for the report. I've moved it to the PyBOMBS repository as it is more relevant there.
