### ISSUE TITLE
Replace cppunit by Boost everywhere

### ISSUE THREAD

**Issue by marcusmueller** [gnuradio/gnuradio#1836]
What #1765 did for analog, blocks, digital and filter should be done to all of GNU Radio – it'll do the project good. And, big bonus, getting rid of a dependency. And big bonus, @mbr0wn reports a decrease in build time :)

@mbr0wn would you want me to add this to a specific milestone?

**Comment by mbr0wn** [comment]
https://github.com/gnuradio/gnuradio/pull/1837

**Comment by mbr0wn** [comment]
It's almost done -- so let's add it to the 3.8 milestone.

**Comment by mbr0wn** [comment]
I'm not sure about build time, BTW, but the time to execute 'make test' definitely did go down.

**Comment by mbr0wn** [comment]
Done!
