### ISSUE TITLE
Problem in cmake .. (PLEASE HELP)

### ISSUE THREAD

**Issue by sabakali** [gnuradio/gnuradio#1860]
Hello,
i was following tutorials and at a point i have to execute this command in terminal : cmake ..

Here is the output : 

shaheer@shaheer-HP-Notebook:~/gnuradio/build$ cmake ..
CMake Error at CMakeLists.txt:22 (message):
  Prevented in-tree build.  This is bad practice.

-- Configuring incomplete, errors occurred!

PLEASE HELP !!!

-Shaheer

**Comment by mbr0wn** [comment]
Please take this to the mailing list.

**Comment by dkozel** [comment]
@sabakali Here is a link to the mailing list
https://wiki.gnuradio.org/index.php/MailingLists
