### ISSUE TITLE
Blank graph display in Performance Monitor window

### ISSUE THREAD

**Issue by n7ihq** [gnuradio/gnuradio#1904]
I compiled GNU Radio version 3.7.12 using PyBombs on Ubuntu 18.04 with config_opt
-DENABLE_PERFORMANCE_COUNTERS=ON. I created a simple flow graph with the CtrlPort Performance Monitor block:

Signal Source > Throttle > Null Sink
[perfmon.txt](https://github.com/gnuradio/gnuradio/files/2203844/perfmon.txt)

Running the flow graph in GNU Radio Companion displays a blank graph in the Performance Monitor window. Running "python top_block.py" from the command line displays the following message:

jim@vmware:~/gnuradio$ python top_block.py
ControlPort Monitor running.
gr::log :INFO: controlport - Apache Thrift: -h vmware -p 44937
monitor::endpoints() = -h vmware -p 44937
running: ['gr-perf-monitorx', 'vmware', '44937']
Press Enter to quit: QPaintDevice: Cannot destroy paint device that is being painted
Traceback (most recent call last):
  File "/home/jim/.local/lib/python2.7/site-packages/matplotlib/backends/backend_qt5agg.py", line 72, in paintEvent
    painter.drawImage(origin / self._dpi_ratio, qimage)
  File "/home/jim/.local/lib/python2.7/site-packages/matplotlib/backends/backend_qt5.py", line 273, in _dpi_ratio
    return self.devicePixelRatio() or 1
RuntimeError: wrapped C/C++ object of type FigureCanvasQTAgg has been deleted

**Comment by greciamontoya** [comment]
I'm having the same problem, were you able to solve this?

**Comment by marcusmueller** [comment]
This was a SWIG problem; it might manifest in other ways, but for now, closing the issue as 3.7-era
