### ISSUE TITLE
Remove generated_time from all GRC-generated Python files

### ISSUE THREAD

**Issue by marcusmueller** [gnuradio/gnuradio#1923]
We can't include build times in files generated at build time, and that includes GRC->py compilation.

The reason is simply that it breaks reproducible builds. Same build, same software, same compiler should yield exactly the same code.

Assigning @skoslowski (because he's competent) and me (because I raise this, and because reproducible builds are a maintainer effort).

**Comment by skoslowski** [comment]
AFAIK this was always in there https://github.com/gnuradio/gnuradio/blob/14d2bfac73193bf36c32d5ae009b31786b1ed510/grc/core/generator/flow_graph.tmpl#L33

Let's remove it.
