### ISSUE TITLE
grc next generates wrong code if realtime scheduling is selected

### ISSUE THREAD

**Issue by dl1ksv** [gnuradio/gnuradio#1924]
If in the flowgrap options realtime scheduling is selected grc generates:

     def main(top_block_cls=APRS, options=None):
        if gr.enable_realtime_scheduling() != gr.RT_OK:
            print "Error: failed to enable real-time scheduling."

which results in:

     SyntaxError: Missing parentheses in call to 'print'. Did you mean print("Error: failed to enable real-time scheduling.")?

**Comment by haakov** [comment]
Great catch, thanks!

**Comment by haakov** [comment]
Fixed in https://github.com/gnuradio/gnuradio/pull/1951/commits/5de45dc2499022687cd063c1ff30ac288945b99f.

**Comment by marcusmueller** [comment]
Closing, as 5d445dc is merged per #1962
