### ISSUE TITLE
cannot open file gnuradio-grc-png when on custom prefix

### ISSUE THREAD

**Issue by gesterdj** [gnuradio/gnuradio#1928]
Built gnuradio with pybombs, configuring the prefix to a path inside the home directory.

Running a config with WX GUI shows this error:
01:20:52: can't open file '/usr/share/icons/hicolor/32x32/apps/gnuradio-grc.png' (error 2: No such file or directory)
01:20:52: Failed to load image from file "/usr/share/icons/hicolor/32x32/apps/gnuradio-grc.png".

**Comment by marcusmueller** [comment]
Interesting!

As a honest recommendation (we'll still investigate this!): Keep away from WX GUI. We're unable to maintain it anymore, it's been deprecated, and will not be part of GNU Radio 3.8.

Qt GUI doesn't have every single feature that WX had, but most of the things work at least as good. And much faster, using much less CPU. Try it, my guess is you'll like it :smile:! Try to click with the _middle_ mouse button on a Qt GUI plot to open the menu.

**Comment by devnulling** [comment]
Closing this issue. WX widget have been removed from the mainline GR. Please use QT instead of WX widgets.
