### ISSUE TITLE
GRC: py2/py3 compat

### ISSUE THREAD

**Issue by noc0lour** [gnuradio/gnuradio#1929]
Follow up of #1915.

Using json `dump(s)`/`load(s)` Python2/Python3 has some incompabilities regarding strings/unicode. 
We need to solve them for GRC & in other places in the codebase.

**Comment by noc0lour** [comment]
#1930 solves the issue for the GRC block cache

**Comment by marcusmueller** [comment]
Does that imply that merging #1930 closes this?

**Comment by noc0lour** [comment]
Need to look through the code if we have some more dump/load things we did not hit yet.

**Comment by dkozel** [comment]
Pretty sure this is long solved. `maint-3.8` has been working py2/3 and `master` is Python 3 only.
