### ISSUE TITLE
typo in `filter_band_pass_filter.block.yml`

### ISSUE THREAD

**Issue by dl1ksv** [gnuradio/gnuradio#1931]
Ther is still a type in filter_band_pass_filter.block.yml

line 74 is
    firdes.type.fcn(

sholud be
    firdes.${type.fcn}(

**Comment by haakov** [comment]
Great, thanks!

**Comment by haakov** [comment]
Fixed in https://github.com/gnuradio/gnuradio/pull/1951/commits/b32f7053c79befb023dd3c572152ef935d92e26d.

**Comment by marcusmueller** [comment]
@haakov does that mean it's in a PR?

**Comment by marcusmueller** [comment]
Closing, as b32f705 is contained and merged in #1962.
