### ISSUE TITLE
grc 3.8 requires the xterm variable to be set 

### ISSUE THREAD

**Issue by dl1ksv** [gnuradio/gnuradio#1937]
Trying to execute a flowgraph from grc requires the xterm variable to be set even if the variable is set.

Application.py line 690 -699

                Actions.FLOW_GRAPH_GEN()
                xterm = self.platform.config.xterm_executable
                Dialogs.show_missing_xterm(main, xterm)
                if self.config.xterm_missing() != xterm:
                    if not os.path.exists(xterm):
                        Dialogs.show_missing_xterm(main, xterm)
                    self.config.xterm_missing(xterm)

Dialogs.show_missing_xterm(main, xterm) is called before xterm is checked.

So just remove line 692.

**Comment by noc0lour** [comment]
:+1: thanks for the report. sounds like a bug.

**Comment by marcusmueller** [comment]
Closed via #1937, right @dl1ksv ?
