### ISSUE TITLE
qtgui freq-sink and waterfall-sink need a bandwidth message port

### ISSUE THREAD

**Issue by jjhein** [gnuradio/gnuradio#1952]
Per an email thread to the development alias, we need an additional message port for the frequency and waterfall sink blocks within the qtgui library.

**Comment by jjhein** [comment]
Attached is the patch for issue #1952.  I'm happy to do this different if need as this is my first contribution.  

[0001-Issue-1952-qtgui-freq-sink-and-waterfall-sink-need-a.patch.zip](https://github.com/gnuradio/gnuradio/files/2291052/0001-Issue-1952-qtgui-freq-sink-and-waterfall-sink-need-a.patch.zip)

@dkozel

**Comment by mbr0wn** [comment]
@jjhein Can you please submit a pull request onto master or next branch, and then close this issue? Thanks a lot for contributing!

**Comment by jjhein** [comment]
Martin,

Will do.  Is there a particular naming convention for my feature branch that will allow me to push to the gnuradio repo?  I tried the other day, but got a permission denied error.

Jason

**Comment by noc0lour** [comment]
@jjhein A typical workflow is to `fork` the gnuradio repo to your personal account, push a feature branch there, create a pull-request based on your personal feature branch
