### ISSUE TITLE
New Narrowband examples necessary

### ISSUE THREAD

**Issue by marcusmueller** [gnuradio/gnuradio#1958]
Removal of `message_sink` / `_souce` broke nearly all narrowband examples.

a) we should have unit tests for examples

b) we need new examples.

The current nonfunctional examples bear no educational value and can / will be removed (#1959)

**Comment by marcusmueller** [comment]
Discussing this with #docs and especially @duggabe : I think we're covering this with the new tutorials.

**Comment by duggabe** [comment]
Since this issue was not tagged as Documentation, I had not seen it before.
Yes, the current tutorials cover all the narrow band modulation methods.
I recommend closing this issue, pull/1959, and issue/1024.
