### ISSUE TITLE
Stream demux block

### ISSUE THREAD

**Issue by MattEttus** [gnuradio/gnuradio#1995]
There is a very useful stream mux block, but there is no corresponding stream demux block.  It would be very useful for simple fixed-sized packets.

**Comment by dave-pi** [comment]
I've implemented this block OOT. It's at https://github.com/dave-pi/gr-stream_demux.

**Comment by dkozel** [comment]
Hi @dave-pi, that looks good!

@marcusmueller how do you feel about bringing this block in tree? The only thing I can see needed is tests.
