### ISSUE TITLE
Conditional statements in <source> fields of GRC XML file with variables

### ISSUE THREAD

**Issue by tfcollins** [gnuradio/gnuradio#1996]
The conditional statement of issue is here: https://github.com/analogdevicesinc/gr-iio/blob/794c2fdcae36bc0e4a153f23ec52f2127cfe5aeb/grc/iio_attr_source.xml#L137

When placing this block in a flowgraph GRC produces an error relating to $attr_type() == 'NoneType' which breaks the conditional statement.  This error reappears when reopening a flowgraph containing this block.  Basically, GRC doesn't resolve what that variable is within that statement even though it is defined above.

Simply opening the block mask then closing it removes the error for that session.

**Comment by marcusmueller** [comment]
was solved when GRC changed from XML to YML
