### ISSUE TITLE
grc file <var_make> and <var_value> documentation

### ISSUE THREAD

**Issue by darsor** [gnuradio/gnuradio#2007]
I can't find any documentation on the <var_make> and <var_value> xml tags in block grc files.

I understand <var_make> can be used to define a variable if the variable's name is the block id, and the block key starts with "variable". Are there other possible use cases? For example, is it possible to have a regular block define a variable named something other than the block ID?

I've seen the <var_value> tag used in several variable blocks, but there is no description of its purpose or usage anywhere. Could the documentation be updated?

[This wiki page](https://wiki.gnuradio.org/index.php/GNURadioCompanion#Creating_the_XML_Block_Definition) might be a good place for it.

**Comment by 777arc** [comment]
I'll update that wiki page, but does anyone know the answer to @darsor 's questions?  I'm not sure if there are any other use cases.
