### ISSUE TITLE
gr-uhd GRC integration in next and merge_next

### ISSUE THREAD

**Issue by smunaut** [gnuradio/gnuradio#2008]
The whole 'grc' directory is excluded from the build. The commit that did that mention Cheetah but the template have been moved to mako now. However uncommenting it leads to pretty broken blocks.

**Comment by argilo** [comment]
I bumped into this as well. No UHD blocks appear in GRC.

**Comment by phansel** [comment]
@smunaut Do you have the hash for that commit? Updated+recompiled GR on my end and I no longer have functioning UHD blocks.

**Comment by haakov** [comment]
@phansel I suppose this is the commit: https://github.com/gnuradio/gnuradio/commit/331ccf8ab9e60ba33d7a311003d4ee6bc642a2d4

**Comment by mbr0wn** [comment]
The blocks seems functional, and I'm submitting a PR to re-enable them (#2072). However, they need some more attention, we added some LO controls on maint that we don't currently have, and the new blocks are a bit rough around the edges.

**Comment by mbr0wn** [comment]
See also #2073.

**Comment by mbr0wn** [comment]
This was fixed.
