### ISSUE TITLE
fm emphasis deemphasis documentation is missing

### ISSUE THREAD

**Issue by noc0lour** [gnuradio/gnuradio#2009]
Documentation is hidden in code comments instead of python docstrings.

**Comment by 777arc** [comment]
I'll convert them over, thanks for pointing it out

**Comment by 777arc** [comment]
fixed, see #2017

**Comment by 777arc** [comment]
@noc0lour you can close this

**Comment by noc0lour** [comment]
You can put a `fixes #2009` into your commit message description to actually close this issue automatically when the PR is merged.
