### ISSUE TITLE
grc fails to process older grc files

### ISSUE THREAD

**Issue by dl1ksv** [gnuradio/gnuradio#2023]
Version: 3.7.12git-1842-g267d669e

Loading older grc files all connections are lost. The blocks themselves are displayed.
grc reports:

>>> Error: Connection between analog_sig_source_x_0(out0) and blocks_throttle_0(in0) could not be made.
	source key 'out0' not in source block keys
Traceback (most recent call last):
  File "/usr/local/gnuradio/lib/python3.6/dist-packages/gnuradio/grc/core/FlowGraph.py", line 402, in import_data
    source_port = verify_and_get_port(src_port_id, source_block, 'source')
  File "/usr/local/gnuradio/lib/python3.6/dist-packages/gnuradio/grc/core/FlowGraph.py", line 384, in verify_and_get_port
    raise LookupError('%s key %r not in %s block keys' % (dir, key, dir))
LookupError: source key 'out0' not in source block keys
>>> Done

**Comment by argilo** [comment]
I've observed this as well. Also, some files completely fail to open with various errors. The problem can be reproduced simply by opening the example flowgraphs included with GNU Radio itself.

**Comment by 777arc** [comment]
Are there any differences in the new (working) and old (not working) grc files?
