### ISSUE TITLE
Despite binary available

### ISSUE THREAD

**Issue by Testato** [gnuradio/gnuradio#2034]
During installation by PyBombs you receive this message, but if you try to install the binaries it fail ?
Is it true or not that you have a binaries in this moment ? If not maybe is better to remove this question from the install process ?

```
Install gnuradio from source despite binary install available Y/[N]? N
PyBOMBS.install_manager - ERROR - Error installing package gnuradio. Aborting.
```

**Comment by dkozel** [comment]
Hello @Testato 
Can you please let us know what OS you were running this on? There are `gnuradio` binaries on most of the common Linux distros.

**Comment by Testato** [comment]
UbuntuBudgie 18.04
One of the official Ubuntu distro

**Comment by mbr0wn** [comment]
This is better suited for the mailing list.
