### ISSUE TITLE
Trying to use a Random source fails

### ISSUE THREAD

**Issue by dl1ksv** [gnuradio/gnuradio#2036]
Using a simple flowgraph with a random source of type int  fails with:

    File "/usr/local/gnuradio/lib/python3.6/dist-packages/gnuradio/blocks/blocks_swig1.py", line 6302, in make
    return _blocks_swig1.vector_source_i_make(*args, **kwargs)
    TypeError: in method 'vector_source_i_make', argument 1 of type 'std::vector< std::int32_t,std::allocator< std::int32_t > > const &'

**Comment by noc0lour** [comment]
Could you show the part in python where the vector source is instantiated? 

Do you mean random source as in `random noise` or as in any source?

**Comment by dl1ksv** [comment]
I generated the flowgraph with grc and took the Random Source from Waveform Generators. 

The code is:

self.analog_random_source_x_0 = blocks.vector_source_i(map(int, numpy.random.randint(32, 127, 1000)), True)

Probaply removing the map function resolves the problem.

**Comment by noc0lour** [comment]
If you use Python3 `map()` returns a generator object and probably swig can't resolve that easily.

**Comment by btashton** [comment]
@noc0lour This is fixed in my PR, I also fixed up a bunch of the decoder and encoder blocks in gr-fec that had this same issue.

**Comment by noc0lour** [comment]
@btashton Pretty cool, I'll try your PR.
