### ISSUE TITLE
Drop-down menus on GRC toolbar have poor contrast

### ISSUE THREAD

**Issue by argilo** [gnuradio/gnuradio#2041]
On the master branch, the drop-down menus in GRC to create a new flowgraph or open a recent one are displayed with grey text on a grey background:

![screenshot from 2018-09-24 18-53-08-2](https://user-images.githubusercontent.com/583749/45983712-c077bf00-c02b-11e8-847d-7242cc93c56a.png)

![screenshot from 2018-09-24 18-53-25-2](https://user-images.githubusercontent.com/583749/45983716-c2da1900-c02b-11e8-84d0-40ca8f9762b3.png)

This gives the impression that the menu items are disabled.

**Comment by btashton** [comment]
@argilo are you still seeing this on master?  Building on Fedora 29 I they have the proper black text, might be a GTK theme issue?

**Comment by argilo** [comment]
@btashton Indeed, the problem is gone on the latest master. I now see black text instead of grey. I'll close this off.
