### ISSUE TITLE
No default flowgraph type in GRC

### ISSUE THREAD

**Issue by argilo** [gnuradio/gnuradio#2042]
In GNU Radio 3.7, clicking the "Create a new flowgraph" button in the toolbar or pressing Ctrl+N creates a new QT GUI flowgraph.

On the master branch, the "Create a new flowgraph" button is greyed out, and pressing Ctrl+N produces the following error:

`(gnuradio-companion:28864): Gtk-WARNING **: 08:22:04.035: Accelerator '<Primary>n' tries to invoke action 'app.flowgraph.new' without target, but action expects parameter with type 's'`

To create a new flowgraph, a type must be explicitly chosen from the list.

**Comment by haakov** [comment]
Can be fixed by removing this line https://github.com/gnuradio/gnuradio/blob/bd26b0d1dca6fb4a250bf53016702f7cdbc35b47/grc/gui/Actions.py#L230

but then the dropdown menu is greyed out instead.

**Comment by haakov** [comment]
@argilo I've created a PR for this issue: https://github.com/gnuradio/gnuradio/pull/2067
