### ISSUE TITLE
Opening the parameters window for a disabled block results in an error

### ISSUE THREAD

**Issue by haakov** [gnuradio/gnuradio#2045]
`TypeError: not all arguments converted during string formatting`
(I don't have GNU Radio installed on this computer so I can't post the full traceback)

I believe this is caused by the following line:
https://github.com/gnuradio/gnuradio/blob/007923c64d2505b37dffb8e11cb1e3ecf4e489eb/grc/core/params/param.py#L233

This error can be reproduced by running the following in Python:
`'' % 'some string'`

**Comment by btashton** [comment]
@haakov I could not reproduce this can you give any more details?

**Comment by haakov** [comment]
Actually, I'm not able to reproduce either. Closing!
