### ISSUE TITLE
GRC parameter window's Apply button does not work properly

### ISSUE THREAD

**Issue by haakov** [gnuradio/gnuradio#2061]
The Apply button only works once for every time you open the parameter window.

Steps to reproduce:
- Add a block
- Open its parameter window
- Change a parameter and press Apply (this works)
- Change another parameter and press Apply again (this doesn't)

Update:
Actually, the Ok button does not work either once you've pressed Apply.

**Comment by btashton** [comment]
Made some progress on this one today.  It looks like there are a couple things that are causing this behaviour.

**Comment by haakov** [comment]
@btashton what did you find?

**Comment by haakov** [comment]
Can't reproduce, closing
