### ISSUE TITLE
Protocol Parser not working. How to decode a packet to pdu?

### ISSUE THREAD

**Issue by armleo** [gnuradio/gnuradio#2084]
latest 3.7.
Protocol Parser inputs bytes and outputs PMT_F for incorrect packets and dictinary with payload symbols set to number of symbols, but the problem is that it does not output payload. How to get payload?

Is this a bug that protocol parser output PMT_F? Why there is no examples on how to decode packet without OFDM?

**Comment by mgarrett1955** [comment]
I have this exact question!! How do I look at the contents, or the dictionary that comes out of the parser without making a custom block?

**Comment by michaelld** [comment]
Best advice: search through the GNU Radio source code and find that for the Protocol Parser, then poke through that code to figure out how it work. Maybe there are examples in GR or some GR OOT? I don't know! Good luck!
