### ISSUE TITLE
Problems building an RPM of maint-3.7 for Centos 7.5

### ISSUE THREAD

**Issue by wrthissell** [gnuradio/gnuradio#2096]
Dear Colleagues,
     I tried to build a Centos 7.5 rpm from the maint-3.7 branch today and it is not build-able because it does not include all of the required code.  
     The current implementation of the github code webpage does not include the specific dates and times of the commits for me to determine which patches I need to include in a new build.
     I recommend that you include in the available branches all of the official releases, or at least the relevant recent official releases.
    Thank you in advance for making these modifications so that one may incorporate patches to the current release.

**Comment by dkozel** [comment]
@wrthissell I'm afraid I don't understand. What code is missing? 

All commits have date/time information and a list of all releases is available on the site. The maint-3.7 branch has the latest stable code. All releases are tagged so you can do a `git checkout` of any release.
https://github.com/gnuradio/gnuradio/releases

**Comment by wrthissell** [comment]
Dear dkozel,
     Thank you for your prompt reply.  VOLK for one is missing.  See the attached text file of my rpmbuild record:

[20181017 gnuradio maint rpmbuild issue.txt](https://github.com/gnuradio/gnuradio/files/2493850/20181017.gnuradio.maint.rpmbuild.issue.txt)

**Comment by wrthissell** [comment]
Dear dkozel,
      I downloaded the file from:

https://github.com/gnuradio/gnuradio/tree/maint-3.7

**Comment by dkozel** [comment]
VOLK is a separate library from GNU Radio.
https://github.com/gnuradio/volk

Interestingly, it seems to have been packaged inside the GNU Radio RPM for Centos 7.
https://centos.pkgs.org/7/epel-x86_64/gnuradio-3.7.11-7.el7.x86_64.rpm.html

I hope this helps.

**Comment by nickoe** [comment]
@wrthissell The volk library source is not included if you use the tarballs from the tags as volk is a git submoule.

Either use git to update the submodule, or download the volk tarball separately.

I think you can close this issue.
