### ISSUE TITLE
Could NOT find MPLIB

### ISSUE THREAD

**Issue by kewenkang** [gnuradio/gnuradio#2105]
when I run "cmake .." in build/, an error occurred.
-- Checking for module 'gmp'
--   No package 'gmp' found
-- Could NOT find GMP (missing:  GMPXX_LIBRARY GMP_INCLUDE_DIR) 
-- Checking for module 'mpir >= 3.0'
--   
-- Could NOT find MPIR (missing:  MPIRXX_LIBRARY MPIR_INCLUDE_DIR) 
CMake Error at /usr/share/cmake-3.5/Modules/FindPackageHandleStandardArgs.cmake:148 (message):
  Could NOT find MPLIB (missing: MPLIBXX_LIBRARY MPLIB_INCLUDE_DIR)
Call Stack (most recent call first):
  /usr/share/cmake-3.5/Modules/FindPackageHandleStandardArgs.cmake:388 (_FPHSA_FAILURE_MESSAGE)
  cmake/Modules/FindMPLIB.cmake:26 (find_package_handle_standard_args)
  gnuradio-runtime/CMakeLists.txt:26 (find_package)
How to resolve it?

**Comment by 777arc** [comment]
try sudo apt-get install libgmp-dev

**Comment by Ghaz75** [comment]
Yes there is a serious compatibility issue of gr-gsm with gnuradio 3.8. I hope gr-gsm will be updated for the new version of GR. Best of luck.
