### ISSUE TITLE
docs: remove deprecated & removed blocks from sphinx documentation

### ISSUE THREAD

**Issue by noc0lour** [gnuradio/gnuradio#2118]
Quite some blocks are still referenced in the sphinx documentation and thus the sphinx build fails. 
Cleaning up of `docs/sphinx/` is necessary to fix that.

**Comment by 777arc** [comment]
I'll take a look

**Comment by 777arc** [comment]
To anyone else trying to build the sphinx docs, make sure to apt-get install python3-sphinx, then go into the build directory and run ./run_sphinx_build.sh

Editing run_sphinx_build.sh and adding -vvv to the sphinx-build will show what went wrong

**Comment by 777arc** [comment]
To get it to build I had to:

- index.rst- delete the whole "Video Blocks" section
- delete the video_sdl_blocks.rst file

**Comment by marcusmueller** [comment]
Closed per #2222
