### ISSUE TITLE
Fix compiler warnings about unsigned / signed comparisons

### ISSUE THREAD

**Issue by marcusmueller** [gnuradio/gnuradio#2120]
#2069, as desired, introduced a lot of warnings into the build process, essentially everywhere we should've been using `unsigned` vs `signed`.

Now that we identified these places, we need to fix' em.

Essentially, this is the process of:

* pick one compiler warning about signed/unsigned comparison
* track down which side of the comparison is right, i.e. should the data types compared be signed or unsigned
* modify the types not to eliminate the warning but to make sure the comparison is logically sound.

**Comment by Fadila82** [comment]
Hello, is this done ? I tried to do it as my first issue, but the only warnings I got were from Volk. Should I do it in volk then ?

**Comment by noc0lour** [comment]
@Fadila82 building with `-DCMAKE_BUILD_TYPE=Debug` might reveal those warnings

**Comment by Fadila82** [comment]
Of course, it makes sense. Thank you.

**Comment by noc0lour** [comment]
Sure, thank you for looking at this!

**Comment by kaydeetwo** [comment]
Hi - is there still need for help here? I'd be keen to tackle it.

**Comment by michaelld** [comment]
@kaydeetwo There is -always- a need for help fixing warnings! Each compiler suite provides similar yet different warnings, even between same-compiler but different versions (e.g., GCC7 versus GCC8). Whatever help you want to provide would be awesome! If you think you'll participate in GR development beyond just a few such warnings fixed here and there, then you'll need a "CLA" (license assignment) allowing you to commit code to the project; if so let us know & we'll get you in touch with the correct GR person to do so. Thx!

**Comment by kaydeetwo** [comment]
@michaelld - thanks and sounds great!!
