### ISSUE TITLE
GRC: PyQt5 ImportError with Python 3.5.2 and PyQt5 5.11.2

### ISSUE THREAD

**Issue by phansel** [gnuradio/gnuradio#2132]
Probably the same issue as this one: https://github.com/mu-editor/mu/issues/575

Version is 3.8tech-preview-56-gabd594ae (Python 3.5.2) with [this patch](https://github.com/gnuradio/gnuradio/pull/2024) applied.

When executing any flowgraph with a Qt component, this error is raised:

```
Traceback (most recent call last):
  File "/gnuradio/top_block.py", line 25, in <module>
    from gnuradio import qtgui
  File "/usr/local/lib/python3.5/dist-packages/gnuradio/qtgui/__init__.py", line 38, in <module>
    from .range import Range, RangeWidget
  File "/usr/local/lib/python3.5/dist-packages/gnuradio/qtgui/range.py", line 24, in <module>
    from PyQt5 import Qt, QtCore, QtWidgets
ImportError: /home/paul/.local/lib/python3.5/site-packages/PyQt5/QtCore.so: undefined symbol: PySlice_AdjustIndices

```

This occurs when PyQt5==5.11.2 is installed with pip; the issue does not appear to occur when PyQt5==5.11.3 is installed from [here](https://pypi.org/project/PyQt5/#files).

**Comment by nickoe** [comment]
@phansel is this issue relevant anymore as pyqt 5.12 is out? I assume it was really a bug in pyqt and not really gnuradio.
