### ISSUE TITLE
CMake enables gr-uhd but compilation fails due to missing Python module mako

### ISSUE THREAD

**Issue by rear1019** [gnuradio/gnuradio#2154]
On a system without `python-mako` CMake enables `gr-uhd`, however compilation fails due to missing Python module `mako`. I can reproduce this error on Ubuntu 18.04 LTS and Arch Linux.

**Comment by noc0lour** [comment]
Hi @rear1019 which version of GNU Radio and UHD are you trying to build?

**Comment by rear1019** [comment]
Ubuntu 18.04 LTS: GNU Radio git revision 97903bc3d, libuhd-dev 3.10.3.0 (from Ubuntu’s repository)
Arch Linux: GNU Radio git revision 5823f31 and 97903bc3d, libuhd 3.13.0.1 (from Arch Linux’ repository)
Looking more carefully at CMakes’s output I have discovered that CMake actually detects that `mako` ist missing:
```
-- Configuring gr-uhd support...
--   Dependency Boost_FOUND = 1
--   Dependency UHD_FOUND = TRUE
--   Dependency ENABLE_GNURADIO_RUNTIME = ON
--   Dependency ENABLE_GR_FILTER = ON
--   Dependency ENABLE_GR_BLOCKS = ON
--   Dependency ENABLE_GR_ANALOG = ON
--   Enabling gr-uhd support.
--   Override with -DENABLE_GR_UHD=ON/OFF
--   UHD Version: 3.13.0.1-0-unknown
-- Python checking for Mako >= 0.4.2 - not found
```

**Comment by noc0lour** [comment]
Hm, maybe we need to manually add some required flag there, too.

**Comment by marcusmueller** [comment]
Might already be solved in UHD itself. Mbr0wn?

**Comment by noc0lour** [comment]
GNU Radio is not calling UHDs `CMakeLists.txt` and shouldn't care about any Python dependencies UHD has. The fact that cmake is not stopping if `mako` is not found is a problem. Since it's a build dependency for UHD blocks (and for volk).

**Comment by mbr0wn** [comment]
Gr-uhd uses mako during build time.

**Comment by mbr0wn** [comment]
So here's what's going on: You can build GNU Radio without mako, you just don't get GRC in that case. However, the grc/ subdirectories of all components get touched even if GRC is disabled. gr-uhd/grc assumes that mako is there, because GRC does.

**Comment by rsandler00** [comment]
`pip install mako` solved this for me
