### ISSUE TITLE
tag propagation and stream_to_vector/vector_to_stream

### ISSUE THREAD

**Issue by adisuciu** [gnuradio/gnuradio#2201]
I think there is a bug with how tag propagation is handled in stream_to_vector / vector_to_stream blocks - It does not propagate in GNURadio 3.8

I attached a few screenshots from my machines (same flowgraph)

- one is from an older windows build (which works just fine) 
![python_2018-11-26_15-05-47](https://user-images.githubusercontent.com/8676912/49016818-f0f4ea00-f18f-11e8-9dfa-7b0030bc2c1b.png)

- the other is from GR 3.8 which only captures the first tag
![screenshot from 2018-11-26 15-20-31](https://user-images.githubusercontent.com/8676912/49016826-f7836180-f18f-11e8-9f39-e9ece95077e9.png)

**Comment by noc0lour** [comment]
For the `3.8` build can you give me the commit-hash you built this off? We recently had several commits working on tag propagation using multi-precision arithmetic.

**Comment by noc0lour** [comment]
Also tags on the `3.7` version look like they are on the wrong offset after conversion to and from the stream to vector / vector to stream operations. (But that might be due to "alignment" issues)

**Comment by adisuciu** [comment]
The 3.8 is built off this - 8dc5fa49dc4c669c28ffb1216625ae92475c4ec9
The Windows build which works fine(ish) is 3.7.12

**Comment by noc0lour** [comment]
Ok, strange. Testing this locally yields: default values for num_items on vector->stream (num_items: 2) works flawlessly. Every other value for num_items results in only the first tag arriving.

**Comment by noc0lour** [comment]
Can you test with #2202?  This should fix the tag propagation.
