### ISSUE TITLE
RuntimeError: Failed to create FFTW wisdom lockfile

### ISSUE THREAD

**Issue by madatr** [gnuradio/gnuradio#2212]
Hello,

I am trying to use the LimeSDR-mini with gnu radio to capture wifi data.

My set up is:
LimeSDR-mini
OS Ubuntu 18.04.1
Downloaded Gnuradio using pybombs.
Downloaded gr-foo, gr-ieee802-11
Trying to run wifi_loopback.grc example found in gr-ieee802-11 to test the setup results in the following:

`
Executing: /usr/bin/python2 -u /home/user/gr-ieee802-11/examples/wifi_loopback.py
Gtk-Message: 18:20:14.245: Failed to load module "canberra-gtk-module"
MAPPER: encoding: 0
set_min_output_buffer on block 9 to 397056

Traceback (most recent call last):
  File "/home/user/gr-ieee802-11/examples/wifi_loopback.py", line 350, in <module>
    main()
  File "/home/user/gr-ieee802-11/examples/wifi_loopback.py", line 338, in main
    tb = top_block_cls()
  File "/home/user/gr-ieee802-11/examples/wifi_loopback.py", line 149, in __init__
    sensitivity=0.56,
  File "/home/user/.grc_gnuradio/wifi_phy_hier.py", line 59, in __init__
    self.fft_vxx_0_1 = fft.fft_vcc(64, True, (window.rectangular(64)), True, 1)

  File "/home/user/prefix/lib/python2.7/dist-packages/gnuradio/fft/fft_swig.py", line 154, in make
    return _fft_swig.fft_vcc_make(fft_size, forward, window, shift, nthreads)

RuntimeError: Failed to create FFTW wisdom lockfile: /home/user/.gr_fftw_wisdom.lock
 Done
` 
I have tried looking on the interweb and could not find any similar issues.
Please Help.

**Comment by michaelld** [comment]
FFTW tries to create a "wisdom" file that contains the FFT info for the specific lengths being requested, a soft of cache that is faster to read in and parse than to compute. For some reason this file doesn't already exist and it is not able to create the file in the directory `/home/user/`. Maybe this directory isn't writeable? What does `/bin/ls -dlAF /home/user/` return?

**Comment by madatr** [comment]
/bin/ls -dlAF /home/mohamed/ returns
drwxr-xr-x 38 mohamed mohamed 4096 Dec  4 01:26 /home/mohamed//

**Comment by michaelld** [comment]
So is your home directory `/home/user/` (literally), or `/home/mohamed/`? In the traceback above it lists the former, which is (literally) different than the latter.

**Comment by michaelld** [comment]
OK so I take is that the `/home/user/` in the traceback should actually read `/home/mohamed` ...

The `ls` looks about right. Not sure about the group ... some OSs setup a "staff" group, some use "admin", and others use the user's username (in this case "mohamed").

Does the file `~/.gr_fftw_wisdom.lock` exist? If so, what does `/bin/ls -lAFd ~/.gr_fftw_wisdom.lock` return?

**Comment by madatr** [comment]
/bin/ls -lAFd ~/.gr_fftw_wisdom.lock
returns

`-rw-r--r-- 1 root root 0 Nov 11 12:58 /home/mohamed/.gr_fftw_wisdom.lock
`

**Comment by madatr** [comment]
`mohamed@MMBP:~$ ~/.gr_fftw_wisdom.lock
`returns:
`bash: /home/mohamed/.gr_fftw_wisdom.lock: Permission denied
`

**Comment by michaelld** [comment]
OK so there's your issue: the file requires root (admin) privileges. When executing anything without such privileges, you won't be able to modify this file. You can either `sudo chmod a+rw /home/mohamed/.gr_fftw_wisdom.lock`, or `sudo rm -f /home/mohamed/.gr_fftw_wisdom.lock`. If there are any other files such as `/home/mohamed/.gr_fftw_wisdom`, you'll want to do the same with them.

**Comment by madatr** [comment]
Oh man, that worked! 
Thank you very much, I've been trying to fix this for a day and you managed to do it.

**Comment by michaelld** [comment]
Great! You're very welcome!

**Comment by Yacinetel** [comment]
think you
