### ISSUE TITLE
File Source block doesn't work with files over 4GB

### ISSUE THREAD

**Issue by drmpeg** [gnuradio/gnuradio#2245]
Using size_t for the new offset and length features is no bueno.

**Comment by marcusmueller** [comment]
@drmpeg any suggestions from your experience? I'll go with `std::ifstream::pos_type` or `off_type` for the offset. For the length, I'll go with "`uint64_t` needs to be enough for everyone", would that sit well with you?

**Comment by noc0lour** [comment]
That's if you work on 32-bit machines (or architectures), right?

**Comment by marcusmueller** [comment]
argh. I remember slowly. The darkness creeps in...

So, POSIX' `fseek()` takes a `long` as argument. Meaning that the POSIX functions actually only support seeking to 2³¹-1, i.e. 2 GiB - 1B on 32 bit systems and … enough on 64 bit systems, AS long as `long` is actually 64 bit on these systems (it typically is, but not always, there is practically no beauty in this world).

Same for C++ `<cstdio>`: https://en.cppreference.com/w/cpp/io/c/fseek

We can rewrite, replacing `std::fseek` with `std::fsetpos`, which takes `std::fpos_t*` as argument, and **might** (not: is necessarily) cooler. But it's the best we can do without resorting to become platform-specific.

**Comment by marcusmueller** [comment]
No, we can't use `std::fsetpos`, because there's no way to construct or modify an `fpos_t`. So, `std::ifstream::seekg` it is, which is bad because it amounts to rewriting from C-style file IO to `ifstream`.

**Comment by noc0lour** [comment]
Hmmm you can construct it and fill it with fgetpos? That's how it's recommended

**Comment by drmpeg** [comment]
Fixed with commit https://github.com/gnuradio/gnuradio/commit/addf04b9c51779a423a4795f02c941eaff5a33a1
