### ISSUE TITLE
grc/gui/Application.py: "some blocks have non-standard type names e.g. uhd"

### ISSUE THREAD

**Issue by marcusmueller** [gnuradio/gnuradio#2255]
Investigate whether that's actually the case in-tree. It shouldn't be.

If there's no in-tree occurrence, kill that clause with fire.

**Comment by marcusmueller** [comment]
Oh if there's in-tree deviating type names, of course, kill these with fire first. Then kill clause with fire.

Generally: More flames. Christmas is upon us.

**Comment by noc0lour** [comment]
Maybe that?
```
gen_uhd_usrp_blocks.py
32:    options: [fc32, sc16, item32]
35:        type: [fc32, sc16, s32
```

**Comment by marcusmueller** [comment]
Seems to be solved
