### ISSUE TITLE
GRC: Polar Encoder Definition block is broken

### ISSUE THREAD

**Issue by jdemel** [gnuradio/gnuradio#2260]
If you try to run e.g. `gr-fec/examples/polar_code_example.grc` it won't work because `POLAR Encoder Definition` is broken. The issue comes up with the blocks `Packed Bits` attribute. GRC is not able to run `eval` against this block. The attribute is not recognized as a boolean. Though, the Python interface to instantiate this block seems to work fine.

**Comment by haakov** [comment]
https://github.com/gnuradio/gnuradio/pull/2265

Does this PR fix the problem?

**Comment by jdemel** [comment]
This did fix the issue. Thanks. Also, it lead me in the right direction to fix some more issues. This issue can be closed. @marcusmueller

**Comment by jdemel** [comment]
@marcusmueller I assume this means yes. The issue can be closed.
