### ISSUE TITLE
The GR DTV blocks SSE2 tests succeeds also when building on ARM

### ISSUE THREAD

**Issue by ast** [gnuradio/gnuradio#2262]
Tested on Raspberry Pi with clang 3.8.

**Comment by ast** [comment]
Should it be flagged as a bug?

**Comment by balister** [comment]
So the problem is the sse2 test succeeds when run with an arm compiler?

**Comment by ast** [comment]
Same things happen in volk but then they filter it out because arch is not x86. I think default clang is multiarch and compiles it just fine... Not sure, have to test more.

**Comment by balister** [comment]
Sounds like a clang bug :) Or you are running clang that is producing x86 output. Define CC to have the right arch flags. Something like this:
export CC="arm-oe-linux-gnueabi-gcc  -march=armv7-a -mfloat-abi=hard -mfpu=neon --sysroot=$SDKTARGETSYSROOT"
export CXX="arm-oe-linux-gnueabi-g++  -march=armv7-a -mfloat-abi=hard -mfpu=neon --sysroot=$SDKTARGETSYSROOT"
export CPP="arm-oe-linux-gnueabi-gcc -E  -march=armv7-a -mfloat-abi=hard -mfpu=neon --sysroot=$SDKTARGETSYSROOT"

**Comment by drmpeg** [comment]
@balister Passing the correct flags doesn't help. Already tried that.

**Comment by drmpeg** [comment]
BTW, I'm using clang-6.0 on arm.

**Comment by balister** [comment]
This looks bad:
https://github.com/gnuradio/gnuradio/blob/master/gr-dtv/lib/CMakeLists.txt#L120
I'd replace that with a try compile to see if the compiler can build sse2 code. Using flags to check for the presence of simd is not great, use try_compile blocks.

**Comment by drmpeg** [comment]
@balister Agreed, although that's been in there since 10/2015. I guess there's not too many clang users on arm.

**Comment by drmpeg** [comment]
Pull request submitted. See https://github.com/gnuradio/gnuradio/pull/2266

**Comment by ast** [comment]
There is a very similar bug in libvolk I submitted, not sure if you are also involved in that?
https://github.com/gnuradio/volk/issues/221

Thanks for the quick fix!
