### ISSUE TITLE
CMake: Convert from `find_package` + `set(GR_REQUIRED_COMPONENTS)` + `target_link_libraries${GNURADIO_FOO_LIBRARIES}` by modern CMake

### ISSUE THREAD

**Issue by marcusmueller** [gnuradio/gnuradio#2282]
As @noc0lour has prepared work (https://github.com/noc0lour/gnuradio/tree/update_cmake) to convert from the slightly backward way we let our users detect and link against GR components to modern CMake, where you just tell CMake to link against `gnuradio::digital`, we should be getting this out the door for 3.8.

*  makes things better debuggable
* reduces redundant code
* eases gr-modtool 3.8-porting

**Comment by noc0lour** [comment]
Input from @michaelld very much appreciated.

**Comment by michaelld** [comment]
Very cool! Is there a formal PR for this work yet? Should I comment directly in @noc0lour 's branch? I need to do actual testing / verification, but I like what I'm seeing during a brief read-through!

**Comment by noc0lour** [comment]
Oh, I can post it as wip PR, comments in branches are very hard to work on.

**Comment by michaelld** [comment]
I'd say to do the WIP PR then & we'll work on it via comments and some more commits.

**Comment by noc0lour** [comment]
oh, it's already open. I just forgot: https://github.com/gnuradio/gnuradio/pull/2230

**Comment by michaelld** [comment]
OK I've done a first read-through & commenting. I'll try out the PR sometime soonish to verify that the "modern CMake" stuff works. I love the code simplification & hierarchal nature of "modern CMake" and how you're using it here!
