### ISSUE TITLE
Test all flow graphs, make sure they're converted to YAML

### ISSUE THREAD

**Issue by mbr0wn** [gnuradio/gnuradio#2285]
Let's make sure we've gone over all the flow graphs. Please help update this. If you can't edit the first comment (i.e., this one), post below and I or someone else will update this.

### gr-uhd

- [x] uhd_const_wave.grc
- [ ] uhd_fft.grc: Problems with function probe
- [ ] uhd_msg_tune.grc: Problems with GUI hints and the message passing
- [ ] uhd_normalized_gain.grc
- [ ] uhd_siggen_gui.grc
- [ ] uhd_two_tone_loopback.grc
- [ ] uhd_wbfm_receive.grc

### gr-fec

- [ ] ber_curve_gen.grc: **bus ports missing**
- [ ]  ber_curve_gen_ldpc.grc: **bus ports missing**
- [x] ber_test.grc
- [x] fecapi_async_decoders.grc: float division bug, FECAPI parallelism broken #2276
- [x] fecapi_async_encoders.grc: float division bug
- [x] fecapi_async_ldpc_decoders.grc: float division bug
- [ ] fecapi_async_ldpc_encoders.grc: float division bug, **encoder results differ** #2274 
- [x] fecapi_async_packed_decoders.grc: float division bug
- [x] fecapi_async_to_stream.grc: float division bug
- [x] fecapi_cc_decoders.grc: float division bug
- [x] fecapi_decoders.grc: float division bug
- [x] fecapi_encoders.grc: float division bug
- [x] fecapi_ldpc_decoders.grc: float division bug
- [x] fecapi_ldpc_encoders.grc: float division bug
- [x] fecapi_polar_async_packed_decoders.grc: float division bug
- [x] fecapi_polar_decoders.grc: float division bug
- [x] fecapi_polar_encoders.grc: float division bug
- [ ] fecapi_tagged_decoders.grc: error on open `TypeError: string indices must be integers`
- [x] fecapi_tagged_encoders.grc
- [x] fecapi_tagged_ldpc_decoders.grc: float division bug
- [x] fecapi_tagged_ldpc_encoders.grc: float division bug
- [ ] polar_ber_curve_gen.grc: **bus ports missing**
- [x] polar_code_example.grc: float division bug
- [ ] tpc_ber_curve_gen.grc: **bus ports missing**

### gr-analog

- [x] noise_power.grc

### gr-audio

- [x] cvsd_sweep.grc
- [x] dial_tone.grc

### gr-channels

- [x] demo_ofdm.grc
- [x] demo_qam.grc
- [x] demo_quantization.grc
- [x] demo_spec_an.grc
- [x] demo_two_tone.grc

### gr-filter

- [x] channelizer_demo.grc
- [x] filter_taps.grc
- [x] resampler_demo.grc

**Comment by haakov** [comment]
I'm sure you've figured it out, but just in case anyone else is wondering what this "float division bug" is:

Python 2 returns an integer when dividing integers, whereas Python 3 returns a float. This causes expressions' types to change for some flowgraphs when opened in 3.8, and typically results in an error like "Expression X is invalid for type Y"

**Comment by jdemel** [comment]
Exactly. In order to make it compatible across Py2k and Py3k, it is sufficient to add `//` instead of `/` for integer divisions. Also, this makes the command more verbose.

**Comment by mbr0wn** [comment]
@jdemel Yes, that's exactly what I propose.

**Comment by drmpeg** [comment]
I have all the DTV examples regenerated, but I'm waiting on PR https://github.com/gnuradio/gnuradio/pull/2258 to get the layouts nice and pretty.

**Comment by jdemel** [comment]
**gr-analog** 

- [x] noise_power.grc

**Comment by jdemel** [comment]
**gr-zeromq**

- [x] zeromq_pubsub.grc
- [x] zeromq_pushpull.grc
- [x] zeromq_reqrep.grc
- [x] zmq_msg.grc
- [x] zmq_stream.grc

**Comment by jdemel** [comment]
Regarding the current state of this issue:
If you run `find . -type f -name "*.grc" -print0 | xargs -0 grep -in xml`, the result will be:

```
./grc/tests/resources/test_compiler.grc:1:<?xml version='1.0' encoding='utf-8'?>
./docs/exploring-gnuradio/fm_tx.grc:1:<?xml version='1.0' encoding='ASCII'?>
./docs/exploring-gnuradio/fm_rx.grc:1:<?xml version='1.0' encoding='ASCII'?>
./gr-trellis/examples/grc/tcm.grc:1:<?xml version='1.0' encoding='utf-8'?>
./gr-trellis/examples/grc/sccc.grc:1:<?xml version='1.0' encoding='utf-8'?>
./gr-trellis/examples/grc/turbo_equalization.grc:1:<?xml version='1.0' encoding='utf-8'?>
./gr-trellis/examples/grc/viterbi_equalization.grc:1:<?xml version='1.0' encoding='utf-8'?>
./gr-trellis/examples/grc/pccc.grc:1:<?xml version='1.0' encoding='utf-8'?>
./gr-trellis/examples/grc/interference_cancellation.grc:1:<?xml version='1.0' encoding='utf-8'?>
./gr-fec/examples/ber_curve_gen_ldpc.grc:1:<?xml version='1.0' encoding='utf-8'?>
./gr-fec/examples/fecapi_tagged_decoders.grc:1:<?xml version='1.0' encoding='utf-8'?>
./gr-fec/examples/ber_test.grc:1:<?xml version='1.0' encoding='utf-8'?>
./gr-fec/examples/tpc_ber_curve_gen.grc:1:<?xml version='1.0' encoding='ASCII'?>
```

- the `*_curve_gen.grc` examples are converted in #2615.
- `gr-fec/examples/fecapi_tagged_decoders.grc`: this `TypeError: string indices must be integers` needs to be fixed.
- `grc/tests/resources/test_compiler.grc` should not be converted. Or should it?
- the 2 files in `docs` should be converted.
- the `gr-trellis` examples need to be updated to only use 3.8 blocks and then should be converted.

**Comment by marcusmueller** [comment]
current state, remaining XML FGs:

- gr-trellis/examples/grc/viterbi_equalization.grc
- gr-trellis/examples/grc/tcm.grc
- gr-trellis/examples/grc/sccc.grc
- gr-trellis/examples/grc/pccc.grc
- gr-trellis/examples/grc/turbo_equalization.grc
- gr-trellis/examples/grc/interference_cancellation.grc
- gr-fec/examples/ber_test.grc

Since opening them, running them, saving them and making a commit should be straightforward: tagging as good first issue
