### ISSUE TITLE
modtool requires click dependencies

### ISSUE THREAD

**Issue by jdemel** [gnuradio/gnuradio#2292]
The new modtool version requires click as a dependency. On Ubuntu 18.04, it was enough to run 
`apt install python3-click python3-click-plugins`

**Comment by marcusmueller** [comment]
Has this been addressed? We probably only have to add this as dependency to CMakeLists.txt

**Comment by jdemel** [comment]
@marcusmueller Not that I'm aware of. And yes, this is probably the only change that is required.
