### ISSUE TITLE
GRC: QtGui: Widgets missing

### ISSUE THREAD

**Issue by jdemel** [gnuradio/gnuradio#2307]
If you run a flowgraph from GRC, e.g. `qtgui_tags_viewing.grc`, The `Qt GUI Range` widget will not show up. Thus, you can't control its value during runtime. It is missing from the generated Python file as well.

This happens with  _3.8tech-preview-231-g2826fd09 (Python 3.6.7)_

**Comment by haakov** [comment]
I'll put up a PR for it tomorrow :)

**Comment by drmpeg** [comment]
@haakov probably already knows this, but it's a regression in a recent commit. It was working fine not long ago.

![image](https://user-images.githubusercontent.com/5397196/51082717-d9cb7680-16c1-11e9-98dc-318a8bce6cd7.png)

gr-digital/python/digital/utils/tagged_streams.py needs to be fixed also.

-        tag.value = pmt.from_long(length / vlen)
+        tag.value = pmt.from_long(length // vlen)

There's another divide in that file that may need changing.

**Comment by mbr0wn** [comment]
Looks like this is fixed.
