### ISSUE TITLE
Filter Design Tool PyQt4 removal

### ISSUE THREAD

**Issue by pauledd** [gnuradio/gnuradio#2315]
Gentoo maintainers decided in 2018 to remove Qt4/PyQt4 completely from the packages list so installing this dependencies besides gentoo package manager system is not an trivial task and not an option for me. So gentoo users are not able to use the filter design tool... are there efforts planed to port it to pyqt5?

**Comment by noc0lour** [comment]
Efforts are described here: #1634 I don't know if the CLA is already through.

**Comment by noc0lour** [comment]
If you are willing & able to help, that's very much appreciated.
