### ISSUE TITLE
Prefixes for numeric values (M - million, k - thousand)

### ISSUE THREAD

**Issue by zhovner** [gnuradio/gnuradio#2322]
There is confusion in numeric value prefixes. You cannot set the same value as in preview block.
For example I have a simple numeric variable block `sample_rate` with value  `2M` that means `2000000`. 

<img width="150" src="https://user-images.githubusercontent.com/774290/51269610-ed355500-19d3-11e9-931b-1b277e7de12f.png" />

But I can't use the same prefix when editing value, `2M` will be invalid value.  
The only way is to type `2e6`. 
<img width="200" src="https://user-images.githubusercontent.com/774290/51269943-c4618f80-19d4-11e9-967f-cfd369c4a79a.png" />

I think it will be reasonable to accept the same value prefixes for display and for editing.

**Comment by noc0lour** [comment]
If we already have the `eng_*` modules for displaying we should provide a way to parse arguments as well ;)

**Comment by skoslowski** [comment]
GRC does/should not depend on gnuradio modules - only the code it loads/generates. A simple function like that could be reimplement as a utility for the eval of the appropriate parameter dtypes

**Comment by noc0lour** [comment]
@skoslowski true

**Comment by 777arc** [comment]
Should just need a bit lot logic added right before this line https://github.com/gnuradio/gnuradio/blob/7074f054c25a69392e7ae4e1f0204a1c5ce242f8/grc/core/params/param.py#L194

**Comment by aru31** [comment]
@skoslowski @noc0lour please review this PR

**Comment by aru31** [comment]
This issue can be closed now :)
