### ISSUE TITLE
CC Encoder is limited to K <= 8

### ISSUE THREAD

**Issue by michael-roe** [gnuradio/gnuradio#2344]
cc_encoder doesn't work if K > 8, because it uses a 256 element lookup table to compute the parity.

a) Ideally, I'd like it to support values of K up to 32. Some protocols commonly used in Amateur Radio, such as WSPR, use K=32. (I believe that K values that large can't be decoded with the Viterbi decoder, and a different algorithm is needed), At the very least, I'd like encode to be supported for K up to 32, even if decode isn't.

b) If the limitation to K <= 8 is part of the spec, then the documentation should state this and the implementation should check that K is in range.

I consider the current behavior - silently generating the wrong answer, rather than giving the right answer or an error message - is a bug,

**Comment by noc0lour** [comment]
Thank you for reporting this issue. I think in short-term just adding a check for K <= 8 will be a good addition. Enabling more encoding modes will be a valuable addition as well, but it will take a bit more time and wor.
