### ISSUE TITLE
GRC's block hotkeys don't work

### ISSUE THREAD

**Issue by haakov** [gnuradio/gnuradio#2346]
At the moment, none of these work in in 3.8:

https://github.com/gnuradio/gnuradio/blob/aea2810b64a68ae63d12b9f5438174d82f75ff39/grc/gui/DrawingArea.py#L95-L116

**Comment by aru31** [comment]
Can I work on this issue?

**Comment by drmpeg** [comment]
I was going to mention this myself. I use the block disable and enable a lot, and not having the hotkeys is annoying.

**Comment by haakov** [comment]
@aru31 absolutely :+1:
