### ISSUE TITLE
Crash in pause and start  uhd usrp source in windows

### ISSUE THREAD

**Issue by FONQRI** [gnuradio/gnuradio#2351]
Hi.
I created a simple flowgraph : 
https://imgur.com/sakXgjw
and a gui check box : 
https://imgur.com/4Ro2Av2
and i assigned it to run in properties options like this : 
https://imgur.com/3PbrliP
when i run it with usrp b210 it's working but when i uncheck checkbox and check again  it crashes.
https://imgur.com/u7eTcvq
I'm using windows 10 and gnuradio version 3.7.13.4.
(I used checkbox to stop and start the flowgraph)
also when I connect gnuradio blocks from my c++ code and I try to use stop of top_block and start it again it crashes.

**Comment by devnulling** [comment]
Closing this issue, it is fixed with https://github.com/EttusResearch/uhd/pull/289
