### ISSUE TITLE
add_const_bb in GRC

### ISSUE THREAD

**Issue by michael-roe** [gnuradio/gnuradio#2354]
In gnuradio-companion, there are addition blocks for complex, float, integer and short but not byte,

But there is a byte addition in add_const_v_impl.cc and add_const_bb_impl.cc

I think a byte version of the block needs to be added to gr-blocks/grc/blocks_add_const_vxx.block.yml

**Comment by marcusmueller** [comment]
Hi @michael-roe,

are you willing to add that to the YAML file, and test it?
