### ISSUE TITLE
gnuradio 3.7.13.4, volk submodule 17277ed -  volk_32fc_x2_conjugate_dot_prod_32fc u_avx and a_avx bug.

### ISSUE THREAD

**Issue by mfogle** [gnuradio/gnuradio#2370]
The conj-dot-prod for the unaligned and aligned avx kernels appears to have a bug.  If the num_points in-param is not divisible by 4, a for-loop will perform the calculation on the remaining input and taps values.  The calculations in this for-loop are not accessing the input pointer (a_p) and taps pointer (b_p) correctly.  The attached patch file shows the issue and the fix.
[volk_32fc_x2_conjugate_dot_prod_32fc__17277ed.txt](https://github.com/gnuradio/gnuradio/files/2881277/volk_32fc_x2_conjugate_dot_prod_32fc__17277ed.txt)

**Comment by noc0lour** [comment]
@mfogle can you submit an issue (or better, a pull request) in the https://github.com/gnuradio/volk repo?

**Comment by mfogle** [comment]
Mission accomplished.

_____________________
Michael Fogle
Signalscape, Inc.
mikef@signalscape.com
direct: (919)678-6581
_____________________

**Comment by noc0lour** [comment]
Thanks a lot! :)
