### ISSUE TITLE
Support for std::vector<int64_t> for ControlPort registration

### ISSUE THREAD

**Issue by gr-sp** [gnuradio/gnuradio#2372]
While attempting to export some statistics from our application, we were surprised by the fact that the RPC registration facilities in GNURadio don't seem to support exporting vectors of int64_t. We really needed uint64_t, but it seems this isn't supported due to Thrift type limitations (unsigned integers aren't supported).

I have attached a patch (for GNURadio 3.7.13.4) that attempts to add this support.
[rpc-int64-vector.patch.txt](https://github.com/gnuradio/gnuradio/files/2881752/rpc-int64-vector.patch.txt)

After applying this patch, I was able to perform something akin to the following:
```
add_rpc_variable(
   rpcbasic_sptr(new rpcbasic_register_get<MyObject, std::vector<int64_t> > (...))
);
```

**Comment by dkozel** [comment]
@gr-sp Would you be able to open up a pull request with the contents of the patch? That will help the review and merge process.
