### ISSUE TITLE
GRC: Dark theme not working well, input box text is white

### ISSUE THREAD

**Issue by nickoe** [gnuradio/gnuradio#2374]
I use dark gtk theme and for me I can't see text in white input boxes as the text becomes white as well. I can see it in the inputboxes that are colored. Is there somewhere that text color is hardcoded?

![image](https://user-images.githubusercontent.com/352202/53048557-56a5f900-3495-11e9-940a-2a8eba6eddfd.png)

I selected the rest of the test in the "Extra Dict." field, such that you can see that there are text input.

3.8tech-preview-280-g3a533f78

**Comment by nickoe** [comment]
On a related note; the tabs in GRC to choose the active canvas has black text which does not work well on dark tabs.

**Comment by chuangzhu** [comment]
Still doesn't work on KDE Plasma (5.20.5) when GTK theme set to `Breeze` and color scheme set to `Breeze Dark`. GRC version v3.8.2.0.

![image](https://user-images.githubusercontent.com/31200881/104962544-9b38c700-5a13-11eb-935a-f21a7791b3e9.png)

Here's my `~/.config/gtk-3.0/settings.ini`:

```ini
[Settings]
gtk-application-prefer-dark-theme=true
gtk-theme-name=Breeze
```

It seems that an unintentional mistake in #3017 resulted in `gtk-application-prefer-dark-theme` field not affecting the color:

```python
    prefer_dark = config.get(
        'Settings', Constants.GTK_INI_PREFER_DARK_KEY, fallback=None)
    if prefer_dark in ('1', 'yes', 'true', 'on'):
        theme_name = config.get(
            'Settings', Constants.GTK_INI_THEME_NAME_KEY, fallback=None)
-       return is_dark_theme(theme_name)
+       return True
    theme = subprocess.check_output(
        ["gsettings", "get", "org.gnome.desktop.interface", "gtk-theme"]
    ).decode('utf-8').strip().replace("'", "")
    return is_dark_theme(theme)
```
