### ISSUE TITLE
GnuradioConfig.cmake should contain list of available components, and Python version

### ISSUE THREAD

**Issue by mbr0wn** [gnuradio/gnuradio#2377]
When OOTs use GnuradioConfig.cmake (aka `find_package(Gnuradio)`), then there should be variables available that tell the OOT module whether or not modules are available (instead of just doing the required components thing).

- [x] In particular, right now, there's a bug in gr-utils (somewhat related to this) that assumes ENABLE_GRC exists. That's a separate bug, because it shouldn't do that, but also, there's no good fix because OOTs have no way of knowing if GRC is available.
- [x]  Also, the OOT needs to know which Python version was used to compile GNU Radio and default to that.

**Comment by noc0lour** [comment]
Hm, this is a bit the other way around. Tools are allowed to depend on variables from the config (also we should prefix them with e.g. GR_). Also if you build a library depending on a certain GNU Radio component it must be sufficient to specify `REQUIRED COMPONENTS` and then the build process will fail if the component is not available. Otherwise without the required parameter you will get back a list of components that were found (subset of the specified list)'

**Comment by bastibl** [comment]
At the moment modtool uses `ENABLE_GRC`, which is not propagated to OOTs, effectively disabling GRC bindings.
https://github.com/gnuradio/gnuradio/blob/master/gr-utils/python/modtool/templates/gr-newmod/CMakeLists.txt#L197-L199

So you would either introduce a GRC component or set it to `GR_ENABLE_GRC` in runtime?

**Comment by noc0lour** [comment]
I think for that particular issue setting `GR_ENABLE_GRC` or similar would be best, since there is no real "GRC" target anyway.

**Comment by noc0lour** [comment]
@marcusmueller is working on a solution for the python variables.

**Comment by marcusmueller** [comment]
> At the moment modtool uses `ENABLE_GRC`, which is not propagated to OOTs, effectively disabling GRC bindings.
> https://github.com/gnuradio/gnuradio/blob/master/gr-utils/python/modtool/templates/gr-newmod/CMakeLists.txt#L197-L199
> 
> So you would either introduce a GRC component or set it to `GR_ENABLE_GRC` in GnuradioConfig?

In the meantime, I've merged a patch by drmpeg that includes the grc/ subdir in gr-newmod unconditionally – that's really suboptimal, but there's probably no harm done aside from modules which need to build hier blocks from GRC flow graphs at build time (which fail for less-than-clear reasons).

**Comment by marcusmueller** [comment]
I believe this is fixed now, but @mbr0wn [could ideally](https://github.com/gnuradio/gnuradio/blob/master/cmake/Modules/GnuradioConfig.cmake.in#L57) verify (and if so, close), please?
