### ISSUE TITLE
Python String Formatting: Switch to f-strings

### ISSUE THREAD

**Issue by swap-nil7** [gnuradio/gnuradio#2383]
We should change the string formatting from `%s` or `str.format` to `f-strings` in the `Release 3.9`. It makes the code looks much cleaner.

**Comment by jdemel** [comment]
This is a great Python feature. Though, the [Python f-string PEP](https://www.python.org/dev/peps/pep-0498/) says it was added as part of Python3.6. Thus, GR we'll only be able to use this feature as soon as we bump the minimum Python version to 3.6.

**Comment by haakov** [comment]
So, now that the minimum Python version is 3.6, what exactly is the policy on f-strings? Should we modify existing code to use them or just start using them from now on?

**Comment by devnulling** [comment]
I'd say new code should use f-strings.

I also think we should have a mega commit that switches all the existing strings to f-strings. This however though will make backporting fixes a bit more of a chore.

**Comment by ritvikjain99** [comment]
@swap-nil7 I would like to take up this task.

**Comment by swap-nil7** [comment]
@ritvikjain99 : Yeah, sure. To start with you can change the string formatting in the `gr-modtool`. Most of the changes will be there in the `core` directory of the tool.

**Comment by mbr0wn** [comment]
@ritvikjain99 very cool! You might want to get your CLA process started so we don't have hold-ups down the line, if you haven't done so. Email bhilburn at gnuradio dot org to request a CLA form.

**Comment by devnulling** [comment]
So for a follow up to this, we had more internal discussion and decided that:

- We wont have a mega commit at this time to convert to f-strings
- We will change the coding standards so new commits should use f-strings
- We will likely need to revisit this at some point in the future, but for now I'm going to close this issue.
