### ISSUE TITLE
GNU Radio 3.8 Python 2.7 build fails with "hide" YAML attributes.

### ISSUE THREAD

**Issue by drmpeg** [gnuradio/gnuradio#2389]
The easiest way to show this is with some screenshots.

![image](https://user-images.githubusercontent.com/5397196/53964282-e1950f00-40a3-11e9-9b35-6d9747a9cf69.png)

![image](https://user-images.githubusercontent.com/5397196/53964305-efe32b00-40a3-11e9-85a4-527d5da54e2f.png)

**Comment by drmpeg** [comment]
Can be replicated by just opening one of the DTV example flow graphs (that use lots of "hide" attributes). The example above was vvv011-1kfft.grc.

**Comment by nickoe** [comment]
Does this work with pyhon3 or is the same issie observed?

**Comment by drmpeg** [comment]
@nickoe Python 3 works fine.

**Comment by nickoe** [comment]
Hmm, ok I just tried to test this and certainly confirm your observation.
