### ISSUE TITLE
grc: gnuradio-companion script doesn't work in gnuradio/grc/core directory

### ISSUE THREAD

**Issue by aru31** [gnuradio/gnuradio#2404]
`gnuradio-companion` script doesn't work when called in `gnuradio/grc/core` directory and raises this error:
```
Fatal Python error: Py_Initialize: can't initialize sys standard streams
AttributeError: module 'io' has no attribute 'OpenWrapper'

Current thread 0x00007f98d4f69740 (most recent call first):
Aborted (core dumped)
```

This is probably because `gnuradio-companion` script calls for python io module and gets confused with io directory defined in `gnuradio/grc/core` so the above error.

**Comment by marcusmueller** [comment]
Hm, that sounds like you've got `.` in your `PYTHONPATH`, is that possible?
