### ISSUE TITLE
How I can provide multiple input data file in sequence to the GNU radio signal source block

### ISSUE THREAD

**Issue by dinesh0612** [gnuradio/gnuradio#2410]
Hi,

I am not able to collect data into one file because of this I have several input data file and that files I want to process using GNU radio, So I want to know how I can read multiple input data file in sequence. If I understand correctly then I think GNU radio takes only one file and process it. 
As I am new to this topic, so kindly give me any suggestions

Thanks in advance

**Comment by dkozel** [comment]
@dinesh0612 It's much better to ask for advice and help on the mailing list or the IRC/Slack channel. This bug tracker is for issues and discussions about changing code in GNU Radio itself. In this case, it could go either way.

The built in File Source can only take one file name in it. However, you could change the File Source to accept a list of file paths and read from them sequentially. I believe that we would merge such an enhancement into the main code.

If you choose to develop the new feature in the File Source, please open a new issue to track the development. If you have more questions about your specific application, please send a message to the mailing list or IRC channel and we'll do our best to help there!
https://wiki.gnuradio.org/index.php/Main_Page#Community_.26_Communicating

Thanks.
