### ISSUE TITLE
Recompile fails after `gr_modtool add`

### ISSUE THREAD

**Issue by jdemel** [gnuradio/gnuradio#2421]
After an OOT is built and a new block is added subsequently, CMake seems to be missing Thrift again. This error may be fixed with a new build folder. 

**Edit**: This issue arises during the 'generator' CMake stage. It is sufficient to delete `CMakeCache.txt` in the current build folder. Though, just running `cmake .. && cmake ..` triggers the issue as well.

`gr_modtool newmod testmod`
`cd testmod`
`gr_modtool add testblock [sync block, python or cpp, no arguments]`
`mkdir build`
`cd build`
`cmake ..`
`make`
`cd ..`
`gr_modtool add anotherblock [sync block, python or cpp, no arguments]`
`cd build`
`make`

> -- Configuring done
> CMake Error at lib/CMakeLists.txt:37 (add_library):
>   Target "gnuradio-testmod" links to target "Thrift::thrift" but the target was
>   not found.  Perhaps a find_package() call is missing for an IMPORTED
>   target, or an ALIAS target is missing?
> 
> CMake Error at [prefix]/lib/cmake/gnuradio/UseSWIG.cmake:573 (add_library):
>   Target "testmod_swig" links to target "Thrift::thrift" but the target was not
>   found.  Perhaps a find_package() call is missing for an IMPORTED target, or
>   an ALIAS target is missing?
> Call Stack (most recent call first):
>   [prefix]/lib/cmake/gnuradio/GrSwig.cmake:133 (swig_add_library)
>   swig/CMakeLists.txt:51 (GR_SWIG_MAKE)
> 
> CMake Error at lib/CMakeLists.txt:37 (add_library):
>   Target "gnuradio-testmod" links to target "Thrift::thrift" but the target was
>   not found.  Perhaps a find_package() call is missing for an IMPORTED
>   target, or an ALIAS target is missing?
> -- Generating done

`make` notices that some `CMakeLists.txt` files were updated and reruns `cmake`. Unfortunately, this seems to fail.

**Comment by noc0lour** [comment]
Weird issue. Needs investigation what happens there exactly.

**Comment by jdemel** [comment]
This issue arises after the configuration stage and only during the cmake generation stage.

**Comment by jdemel** [comment]
In case @marcusmueller proposal to remove ctrlport/Thrift is passed, this issue would be solved as well.

**Comment by noc0lour** [comment]
I could reproduce this issue locally, but after several iterations of wiping my build dir & cmake & ninja building succeeded. Something is definitely not right with thrift.

**Comment by NeuroForLunch** [comment]
Stale issue. No version information. Should be closed.

**Comment by jdemel** [comment]
> Stale issue. No version information. Should be closed.

I agree. Closing it now.
