### ISSUE TITLE
there was an error when excute gr::make_top_block("gqrx") command

### ISSUE THREAD

**Issue by quanpm4900** [gnuradio/gnuradio#2428]
when excute command: tb = gr::make_top_block("gqrx") I got an error:
Exception thrown at 0x00007FFCC2EAA388 in gqrx.exe: Microsoft C++ exception: std::bad_alloc at memory location 0x000000910B6FF560.
in detail I found:
 	KernelBase.dll!00007ffcc2eaa388()	Unknown
 	vcruntime140.dll!00007ffc9fad3361()	Unknown
 	ntdll.dll!00007ffcc60fed63()	Unknown
>	gnuradio-runtime.dll!`std::basic_string<char,std::char_traits<char>,std::allocator<char> >::_Copy'::`1'::catch$107() Line 2200	C++
 	vcruntime140.dll!00007ffc9fad1030()	Unknown
 	vcruntime140.dll!00007ffc9fad32f8()	Unknown
 	ntdll.dll!00007ffcc60fed63()	Unknown
 	[Inline Frame] gnuradio-runtime.dll!std::_Allocate(unsigned __int64) Line 69	C++
 	[Inline Frame] gnuradio-runtime.dll!std::allocator<char>::allocate(unsigned __int64) Line 725	C++
 	[Inline Frame] gnuradio-runtime.dll!std::_Wrap_alloc<std::allocator<char> >::allocate(unsigned __int64 _Count) Line 976	C++
 	gnuradio-runtime.dll!std::basic_string<char,std::char_traits<char>,std::allocator<char> >::_Copy(unsigned __int64 _Newsize, unsigned __int64 _Oldlen) Line 2196	C++
 	[Inline Frame] gnuradio-runtime.dll!std::basic_string<char,std::char_traits<char>,std::allocator<char> >::_Grow(unsigned __int64) Line 2228	C++
 	gnuradio-runtime.dll!std::basic_string<char,std::char_traits<char>,std::allocator<char> >::assign(const std::basic_string<char,std::char_traits<char>,std::allocator<char> > & _Right, unsigned __int64 _Roff, unsigned __int64 _Count) Line 1155	C++
 	[Inline Frame] gnuradio-runtime.dll!std::basic_string<char,std::char_traits<char>,std::allocator<char> >::{ctor}(const std::basic_string<char,std::char_traits<char>,std::allocator<char> > &) Line 782	C++
 	gnuradio-runtime.dll!gr::basic_block::basic_block(const std::basic_string<char,std::char_traits<char>,std::allocator<char> > & name, boost::shared_ptr<gr::io_signature> input_signature, boost::shared_ptr<gr::io_signature> output_signature) Line 48	C++
 	gnuradio-runtime.dll!gr::hier_block2::hier_block2(const std::basic_string<char,std::char_traits<char>,std::allocator<char> > & name, boost::shared_ptr<gr::io_signature> input_signature, boost::shared_ptr<gr::io_signature> output_signature) Line 49	C++
 	gnuradio-runtime.dll!gr::top_block::top_block(const std::basic_string<char,std::char_traits<char>,std::allocator<char> > & name) Line 44	C++
 	gnuradio-runtime.dll!gr::make_top_block(const std::basic_string<char,std::char_traits<char>,std::allocator<char> > & name) Line 39	C++
 	gqrx.exe!receiver::receiver(const std::basic_string<char,std::char_traits<char>,std::allocator<char> > audio_device, unsigned int decimation) Line 79	C++
 	gqrx.exe!main(int argc, char * * argv) Line 11	C++
 	[External Code]	
* Could anyone help me to fix this, thank in advanced!

**Comment by marcusmueller** [comment]
Since this seems to be from a binary build of GQRX for windows, I don't think we should be dealing with this in the GNU Radio bug tracker, I'm afraid.
