### ISSUE TITLE
FIR Filter randomly drops samples

### ISSUE THREAD

**Issue by JRock007** [gnuradio/gnuradio#2449]
## Issue
When using FIR filters, some samples are dropped during the filtering. I noticed this using RRC Filter taps (see how to reproduce below).
This causes what looks like a gradual phase shift over time in the output:
![drops](https://user-images.githubusercontent.com/7504819/56155495-5456ab80-5fbb-11e9-88fb-74b8e3b74062.png)
I have not been able to notice a pattern in the drops (e.g. every N samples).

## Environment
Ubuntu 18.04.2 LTS
GNU Radio Companion 3.7.11

## How to reproduce
I built a simple flow graph with the following elements:

- RRC Filter Taps with 16 samples per symbole, and 176 (11*sps) taps. The symbol rate is thus set to samp_rate / sps, and the gain to sps**0.5 to compensate for the filters,
- Interpolating FIR Filter and Decimating FIR Filter using the defined taps and respectively set with interpolation to sps and decimation to sps,
- A (custom made) resampler, which in this case is simply used to drop the first 11 (nbr_taps / sps) samples, as they are not representative since the filters are not "initialised" yet. The issue occurs without this block, but it's simpler to visualise like this,
- A signal source outputting a square signal to see when samples are being dropped,
- And a time sink to compare the source and the filtered output.

![drops_flowgraph](https://user-images.githubusercontent.com/7504819/56154809-bc0bf700-5fb9-11e9-810a-15c52ff15f22.png)

With this setup, the output looks like this:
![drops](https://user-images.githubusercontent.com/7504819/56155495-5456ab80-5fbb-11e9-88fb-74b8e3b74062.png)
At first, the source and output are perfectly synchronised but, after some time, they become out of sync. Here's a closeup of the moment this occurs:
![drops_closeup](https://user-images.githubusercontent.com/7504819/56155536-75b79780-5fbb-11e9-98a3-1cf0c0a3e01f.png)
Since it may not be obvious that a sample is being dropped, I used the same flowgraph but simply tweaked the source and time sink parameters to visualise the following:
![drops_closeup_dots](https://user-images.githubusercontent.com/7504819/56156311-499d1600-5fbd-11e9-98dc-483ddd85155e.png)

I have tried lowering the samp_rate (though it's only at 32k), but it hasn't fixed the issue.
Moreover, I don't think it's an underflow issue since my CPU is far from being overused.

**Comment by marcusmueller** [comment]
Thanks for the bug report. I don't mean to be mean, but typically such bugs really appear in custom written blocks – can you replace your custom block with "skip head", which does exactly what you describe?

**Comment by JRock007** [comment]
Thanks for your reply.

After testing with the "skip head" bloc, I don't seem to be able to reproduce the issue anymore. I thought I had replicated the issue without my custom block, but I guessed I hadn't tested properly.

Thanks again for your help!

**Comment by marcusmueller** [comment]
I didn't do anything! If you happen to stumble across this again, please do not hesitate to reopen this issue, and/or to ping us on the mailing list! (if this really happens, it's a severe bug)
