### ISSUE TITLE
Boost 1.7x compat

### ISSUE THREAD

**Issue by marcusmueller** [gnuradio/gnuradio#2452]
@michaelld raised the point that 1.7 doesn't work with master right now (as indicated by bug reports). He'll try locally and report.

**Comment by michaelld** [comment]
The good news is that UHD and Volk GIT master both work with Boost 1.70.0 without further modifications, at least in my testing on OSX 10.14 and 10.6. I haven't tested the most recent releases yet, but I'm working my way there. More as I know it.

**Comment by michaelld** [comment]
Ref GR issue #2451, which I just closed since it's not the correct solution here. I'll get a PR in place tomorrow with a more robust solution, once I've had time to test / verify on a few different Boost versions.

**Comment by michaelld** [comment]
Also: with this fix, GR builds fully using Boost 1.70.0, so this should be the only fix required for building. It is entirely possible that GR (and, possibly, UHD and/or Volk) are using deprecated interfaces that may be removed in some future Boost. We can only future-proof so much ... but we'll do what we can when we find it, as I'll do with the more robust solution I came up with for the boost::asio issue.

**Comment by michaelld** [comment]
With my changes, GR builds cleanly using 1.70.0 and also passes make test for all tests that usually pass (e.g., sometimes the zmq tests fail, sometimes they don't). In particular, the socket_pdu passes, and that's where these changes would impact GR.

**Comment by michaelld** [comment]
I still need to do testing with Boost back to 1.65.0 ... luckily MacPorts can easily handle those multiple Boost version installs ... just takes a little work & time on my part to get them in place.
