### ISSUE TITLE
Implement blks2 Selector replacement

### ISSUE THREAD

**Issue by marcusmueller** [gnuradio/gnuradio#2460]
We've deprecated and finally removed `blks2_selector`, and we're not fixing its bugs anymore.

Thus, we need a replacement. Typically, a simple copy block that copies (and consumes) from either input. Shouldn't be too hard.

Also, needs a 3.7 backport.

**Comment by mormj** [comment]
pull request pending for this one.

**Comment by mormj** [comment]
https://github.com/gnuradio/gnuradio/pull/2483
