### ISSUE TITLE
something's fishy in blocks_add_const_vxx.block.yml

### ISSUE THREAD

**Issue by marcusmueller** [gnuradio/gnuradio#2461]
Notice duplicate entries in:

```yaml
        vconst_type: [complex_vector, real_vector, int_vector, int_vector]
        const_type:  [complex, real, int, int]
```

noticed via #2354 

maybe the last `int` should be `byte` or smth?

**Comment by noc0lour** [comment]
Nope. This is only for type checking in GRC and only "int" is available to check for integer numbers. The important addition is "bb" in the list below that statement.
