### ISSUE TITLE
"Installing GNU Radio From Source" wiki insecure instructions

### ISSUE THREAD

**Issue by piru** [gnuradio/gnuradio#2468]
The wiki page [Installing GNU Radio From Source](https://wiki.gnuradio.org/index.php/InstallingGRFromSource#Using_the_build-gnuradio_script) has the following insecure command:

`wget http://www.sbrac.org/files/build-gnuradio && chmod a+x build-gnuradio && ./build-gnuradio`

The script is fetched over http and then executed. The script also requests root privileges via sudo. Anyone in a Man in The Middle position can replace the script with arbitrary content and  gain root privileges on the target system.

### Recommended fix
- Use https://www.sbrac.org/files/build-gnuradio URL

**Comment by dkozel** [comment]
URLs changed, thanks!

If you notice anything else let us know, or register for the wiki and you can edit directly.
