### ISSUE TITLE
Analog AM Demod Block Silently Fails with Bad Passband

### ISSUE THREAD

**Issue by bhilburn** [gnuradio/gnuradio#2493]
Per the thread "free(): invalid pointer for AM demod block at Gnuradio 3.7.13.5" on the list, if a passband of `0` is used (thus making the passband from "zero to zero"), this block will silently fail with a `free()` error. A parameter check should be added to this block to catch this instance.

**Comment by dl1ksv** [comment]
Same problem exists in the master branch and should fixed.

**Comment by rear1019** [comment]
Closing, fixed both on maint-3.7 (pull request #2773) and on master (commit 27dd99e49a7d).
