### ISSUE TITLE
grc fails to build constellation object if constellation != variable constellation

### ISSUE THREAD

**Issue by dl1ksv** [gnuradio/gnuradio#2494]
grc fails with

Value "digital.constellation_calcdist(const_points, sym_map, rot_sym, dims) if (str(type) == "calcdist") else digital.constellation_type" cannot be evaluated:
module 'gnuradio.digital' has no attribute 'constellation_type'

This is due to https://github.com/gnuradio/gnuradio/blob/c7780bb2abaebd4a0a3ce0ada5d446d554b8adcc/gr-digital/grc/digital_constellation.block.yml#L42

as at this point type cannot be evaluated which probably is intended.

**Comment by dl1ksv** [comment]
Just open a new flowgraph in grc and add a Constellation object from Modulators . Then you get immediately:

ERROR:gnuradio.grc.core.FlowGraph:Failed to evaluate variable block variable_constellation_0
Traceback (most recent call last):
  File "/usr/local/gnuradio/lib/python3.7/dist-packages/gnuradio/grc/core/FlowGraph.py", line 226, in renew_namespace
    value = eval(variable_block.value, namespace, variable_block.namespace)
  File "<string>", line 1, in <module>
AttributeError: module 'gnuradio.digital' has no attribute 'constellation_type'

**Comment by dj0abr** [comment]
the problem still exists if the output language is switched to C++. While it work in Python.
