### ISSUE TITLE
python2: realloc  invalid pointer

### ISSUE THREAD

**Issue by z00254829** [gnuradio/gnuradio#2509]
**I  compile gnuradio source code with following condition:**
_________________________________________
gnuradio release version :  3.7.13.5
uhd release version:           3.14.0.0
volk release version:          1.4.0
cmake comandline:            cmake -DPYTHON_EXECUTABLE=/usr/bin/python2 -DQWT_INCLUDE_DIRS=/usr/local/qwt-6.1.3/include -DQWT_LIBRARIES=/usr/local/qwt-6.1.3/lib/libqwt.so ../ 
______________________________________________
**but when I run gnuradio-companion,throw following exception,Please help me,thanks**

>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
root@lixf-ThinkPad-X240:~# gnuradio-companion 
<<< Welcome to GNU Radio Companion 3.7.13.5 >>>

Block paths:
	/usr/local/share/gnuradio/grc/blocks
*** Error in `/usr/bin/python2': realloc(): invalid pointer: 0x00007f3025a65820 ***
======= Backtrace: =========
/lib/x86_64-linux-gnu/libc.so.6(+0x777e5)[0x7f3039bd97e5]
/lib/x86_64-linux-gnu/libc.so.6(realloc+0x348)[0x7f3039be6a08]
/opt/Qt5.9.1/5.9.1/gcc_64/lib/libQt5Core.so.5(_ZN9QListData12realloc_growEi+0x31)[0x7f3023842f31]
/opt/Qt5.9.1/5.9.1/gcc_64/lib/libQt5Core.so.5(_ZN9QListData6appendEi+0x4f)[0x7f3023842fcf]
/opt/Qt5.9.1/5.9.1/gcc_64/lib/libQt5Core.so.5(+0x1c4cf8)[0x7f3023905cf8]
/opt/Qt5.9.1/5.9.1/gcc_64/lib/libQt5Core.so.5(_Z21qRegisterResourceDataiPKhS0_S0_+0x31c)[0x7f302390170c]
/opt/Qt5.9.1/5.9.1/gcc_64/lib/libQt5Core.so.5(+0x7d3d3)[0x7f30237be3d3]

**Comment by mbr0wn** [comment]
Not enough info, closing.
