### ISSUE TITLE
vocoder: examples need updating for 3.8

### ISSUE THREAD

**Issue by mormj** [gnuradio/gnuradio#2531]
grc examples have all kinds of issues, referencing deprecated and missing blocks, etc.

![image](https://user-images.githubusercontent.com/34754695/58982353-42ff7380-87a2-11e9-8b7b-0844d1fb975a.png)

Also needs conversion to YAML

**Comment by 777arc** [comment]
Note that vocoder_gsm_fr_decode_ps and several other vocoder blocks are only installed if LIBGSM or LIBCODEC2 are found by cmake, which they aren't if you're using the current pybombs installer for 3.8 like me.  So those missing is expected.  

Someone should probably go through and change every flowgraph that uses the old selector block to the new one you made =P
