### ISSUE TITLE
grc: variable id is hidden on canvas

### ISSUE THREAD

**Issue by mormj** [gnuradio/gnuradio#2537]
Cosmetic issue, but in the master branch (3.8), variables appear as follows (three variables: samp_rate, tmp, and xyz):
![image](https://user-images.githubusercontent.com/34754695/59076109-424e0680-88a2-11e9-875e-9f6e447461b7.png)

The expected behavior is as on the maint-3.7 branch, where the id is not hidden:
![image](https://user-images.githubusercontent.com/34754695/59076103-39f5cb80-88a2-11e9-9e6c-a8e079c9e400.png)

Probably a simple fix.

**Comment by drmpeg** [comment]
This is a duplicate of #2235.

**Comment by mormj** [comment]
Thanks - couldn't find that when searching.  closing this one.
