### ISSUE TITLE
E and D hotkeys are activated while typing into block search bar when blocks are selected

### ISSUE THREAD

**Issue by btlvr** [gnuradio/gnuradio#2551]
GNU Radio Companion exhibits a somewhat annoying behavior when blocks are selected and I am searching the list of blocks. 

I am using version `3.7.13.5`. 

### Example steps to reproduce:
select all blocks (`ctrl + a`)
focus block search textbox (`ctrl + f`)
type `debug`

### What happens:
Selected blocks are disabled
Selected blocks are enabled
`bug` is entered into the textbox

### Possible alternative behaviors:
* Automatically deselect all blocks on `ctrl+f`
* Ignore `e` and `d` hotkeys when typing into the box

**Comment by haakov** [comment]
I believe deselecting all blocks can be done by adding a call to `flow_graph.unselect()` to this function:
https://github.com/gnuradio/gnuradio/blob/667677789009d8814341a035ce9fd3ec11ad2723/grc/gui/Application.py#L737-L740
