### ISSUE TITLE
GR 3.7/3.8 | top_block.wait() does not flush/close open file

### ISSUE THREAD

**Issue by fmagno** [gnuradio/gnuradio#2590]
I believe that `wait()` should not return until all files have been flushed/closed. Do you guys agree?

Follows an example:

![image](https://user-images.githubusercontent.com/3079603/60501060-4c053700-9cb3-11e9-8f9d-316dac3658fb.png)

```python
# my_app.py

from foo2 import foo2

f = foo2()
f.start()
f.wait()
# foo2.dat is an empty file at this point
del f    # flush occurs now
# foo2.dat has now the expected content
```

**Comment by bastibl** [comment]
AFAIS, the underlying problem is that the file sink does not implement `stop()` to close the file.

**Comment by mormj** [comment]
I can't repeat this - from both 3.7 and 3.8 I get a 3 byte file with the automatically generated flowgraph top_block.py

which just has this: 
```
def main(top_block_cls=top_block, options=None):
    tb = top_block_cls()
    tb.start()
    tb.wait()
```

![image](https://user-images.githubusercontent.com/34754695/60517639-06923b00-9cae-11e9-930a-645f78bd18a8.png)

**Comment by mormj** [comment]
Ooooh I get it now.  In my case, the file is only written when the flowgraph exits, but if I put a sleep after the wait, there is an empty file until the flowgraph exits.  Not sure what the desired behavior should be in this case.

**Comment by mormj** [comment]
And same behavior on 3.7 - probably can remove the 3.8 from the title

**Comment by fmagno** [comment]
Hi @mormj, IMO as soon as `wait`, `run` or `stop` return all tasks related to the execution of the fg should be finished, including flushing and closing files.

**Comment by mormj** [comment]
@fmagno - I agree - that is what I would expect the behavior to be

**Comment by rear1019** [comment]
Mh, this is not a matter of simply calling ``file_sink_base::close()``. ``file_sink_base`` (base class for ``file_sink_impl``) maintains two file descriptors and a state variable. I am afraid to touch any of them given that I don’t understand the code completely. 

PS: ``wavfile_sink_impl`` contains a copy of ``file_sink_base``’s code.
