### ISSUE TITLE
Latest Windows Installer Breaks RTL-SDR source

### ISSUE THREAD

**Issue by bobasaurus** [gnuradio/gnuradio#2596]
I found a problem with the latest Windows installer of GNU Radio (v3.7.13.5/v1.6 64-Bit Any CPU) from here:

http://www.gcndevelopment.com/gnuradio/downloads.htm

The RTL-SDR source block (and osmocom source block) is broken.  Trying to use it just crashes python without any error messages.  I was able to get around this by installing the older v3.7.11.1/v1.3 version which works perfectly with the RTL-SDR source.

**Comment by tinkrmind** [comment]
I had the same issue, downloading the older version to see if it resolves the issue.

**Comment by tinkrmind** [comment]
Thanks, that worked for me as well!
