### ISSUE TITLE
"LOG4CPPS_NAMES" in  gnuradio/cmake/Modules/FindLOG4CPP.cmake a typo?

### ISSUE THREAD

**Issue by rosecitytransit** [gnuradio/gnuradio#2599]
Searching why I get a `Could NOT find LOG4CPP library` error and noticed that the output line second above is `-- Looked for LOG4CPP libraries named .`.

Looking at the code, I see that the code is `message(STATUS "Looked for LOG4CPP libraries named ${LOG4CPPS_NAMES}.")` and that it's the only instance of `LOG4CPPS_NAMES`.  Should it be  `LOG4CPP_NAMES` to match what's used elsewhere?  When I change it, the variable does populate with `log4cpp`.

If anyone has any suggestions about the original `Could NOT find LOG4CPP library` error that would be appreciated too.  I am trying to install GNURadio from source on Ubuntu 18.04.2 LTS as I don't want any of the GUI libraries that the package depends on.  I did install liblog4cpp5-dev and liblog4cpp5v5 from apt and manually build log4cpp from http://log4cpp.sourceforge.net/

**Comment by nickoe** [comment]
@robotastic That does certainly look strange. Did you try to remove the S and see what it would write in your situation?
