### ISSUE TITLE
grc: block search applies hotkeys to flowgraph

### ISSUE THREAD

**Issue by mormj** [gnuradio/gnuradio#2610]
If a block is selected on the flowgraph, then typing a search in the block tree that includes the letters {'e','d','b', etc} applies those hotkeys to the flowgraph

E.g. if I search for 'digital' entering the 'd' will disable the block that is selected, then 'igital' in the search bar

**Comment by drmpeg** [comment]
How do you get focus on both the block and the search bar at the same time? I can't do that on Linux/Ubuntu.

**Comment by mormj** [comment]
This is how it looks from me pulling the latest upstream master @ cff05c36dfc3908c3:

![image](https://user-images.githubusercontent.com/34754695/61129671-e1a68080-a482-11e9-9e7b-5ce382ff60c1.png)

Variable block is selected, went over to type "digital" in search box:

**Comment by drmpeg** [comment]
Okay. I have to try it on Gnome then. I was SSH'ing to an 18.04 box from a 16.04 box with Unity.

**Comment by mormj** [comment]
That's exactly the setup I was using too (16.04 ssh'd into 18.04).  I'll try on a different machine as well

**Comment by drmpeg** [comment]
I was able to reproduce it. I think it only happens if you have "sloppy" focus enabled. You have to deselect the main window (by moving the mouse pointer off the window) with a block selected and then return the mouse pointer to the main window and click on the search bar.

**Comment by haakov** [comment]
An earlier version of this bug: https://github.com/gnuradio/gnuradio/issues/2551

**Comment by mormj** [comment]
This one still bothers me, but it looks like the underlying issue is that the hotkeys are global to the application, so when e,d,or b get pressed, the key press never makes its way into the search window.  

This could probably be solved by something kludgey such as in the ENABLE/DISABLE/BYPASS action handler, if the btwin has the focus, put the key in the search window and trigger the changed event

A cleaner solution is probably to make the e,d,b hotkey actions local only to the canvas??
