### ISSUE TITLE
Add Issue and PR templates

### ISSUE THREAD

**Issue by devnulling** [gnuradio/gnuradio#2611]
The awesome folks over at Ettus Research have a fancy Issue and PR template. We should use one like it. 

https://raw.githubusercontent.com/EttusResearch/uhd/master/.github/ISSUE_TEMPLATE.md

https://raw.githubusercontent.com/EttusResearch/uhd/master/.github/pull_request_template.md

**Comment by mbr0wn** [comment]
Duplicate of #4525. I'm closing this (and not the other one) because the other one is higher in the list and people are more likely to see it.
