### ISSUE TITLE
Document C++ code gen caveats 

### ISSUE THREAD

**Issue by devnulling** [gnuradio/gnuradio#2613]
Testing out the new C++ code gen feature on master, ran into a few caveats that should be documented:

- The `Options` block ID must be changed to something other than `top_block`
- Within the `CMake options` field, CMake parameters must be separated by semicolons. 

For example:

`CMAKE_INSTALL_PREFIX=/path/to/prefix;UHD_DIR=/path/to/lib/cmake/uhd/;UHD_INCLUDE_DIRS=/path/to/include/;`

**Comment by haakov** [comment]
Can be assigned to me

**Comment by marcusmueller** [comment]
@haakov done assigning to you.

**Comment by haakov** [comment]
About the CMake options, I'd like to drop the semicolons and just do:
`-DCMAKE_INSTALL_PREFIX=/path/to/prefix - DUHD_DIR=/path/to/lib/cmake/uhd/ - DUHD_INCLUDE_DIRS=/path/to/include/`
Which seems like the natural way to do it. I can't understand why I thought semicolons would be a good idea in the first place.

**Comment by marcusmueller** [comment]
through multiple iterations of how to handle the id
