### ISSUE TITLE
Make API calls that obviously only take non-negatives (finally) unsigned int

### ISSUE THREAD

**Issue by marcusmueller** [gnuradio/gnuradio#2664]
- [ ] `io_signature` port numbers
- [ ] `noutput_items`
- [ ] return value of (`general_`)work (caveat: `DONE` needs to be handled separately. But that would be good, anyways, since our "this is done" handling is an inconsistent nightmare, and there's far too many "done" states and far too many ways to get into these)

**Comment by michaelld** [comment]
Again: Love the idea! I think some of those changes should be pretty straight forward, while tweaking `*_work` is nontrivial due to `DONE` and such. There are, of course, ways to work around this issue to some degree, but doing so I think will be a major API change -- guessing 3.9 worthy!

**Comment by michaelld** [comment]
@marcusmueller Guessing you're adding these issues mostly for the purpose of noting them in some "official" / "public" capacity for anyone to search, find, comment, and so forth for future reference ... yes?

**Comment by marcusmueller** [comment]
Not gonna happen on 3.x, happened on 4.x
