### ISSUE TITLE
gnuradio-companion with USRP N210 - Port is not connected

### ISSUE THREAD

**Issue by Titi9237** [gnuradio/gnuradio#2692]
Hi everyone,

I am just beggining with gnuradio and an USRP N210 that I would like to use. After installing gnuradio and uhd on my Ubuntu 18.04, I can connect the N210 using an Ethernet connection (1GB/s), the uhd_find_device and uhd_usrp_probe commands are successfull.

But when I open gnuradio and I try to use a block "UHD: USRP Source" (following this [tutorial](https://www.youtube.com/watch?v=KWeY2yqwVA0)) I end up with a connection error.
> Error 0:
> Block - uhd_usrp_source - UHD: USRP Source(uhd_usrp_source):
>   Source - out(0):
>     Port is not connected.

![Capture d’écran de 2019-07-31 16-32-44](https://user-images.githubusercontent.com/22113749/62220740-d921d580-b3b0-11e9-99da-83329ed549af.png)

What am I doing wrong ? 
Thanks

**Comment by mormj** [comment]
The better place for this type of discussion is the mailing list:
https://wiki.gnuradio.org/index.php/MailingLists
or the GNU Radio slack/IRC

But I would have to see the flowgraph in grc to see why the port is not connected

**Comment by Titi9237** [comment]
It was an awful noob mistake.
Sorry for the inconvenience...

**Comment by mashfique1** [comment]
@Titi9237 what fixed it? what was the noob mistake? some how i had the same error and but went away after restarting. I am not sure if same happened with you

**Comment by marcusmueller** [comment]
@mashfique1 please don't try to figure out such things 6 years after the fact on a bug tracker! That will never work out. We have a very active mailing list and a chat server, which both would love to help you.
