### ISSUE TITLE
Upstream gr-iio

### ISSUE THREAD

**Issue by marcusmueller** [gnuradio/gnuradio#2717]
Working together with @tfcollins, we'll make the IIO interface part of mainline GNU Radio.

**Comment by 777arc** [comment]
Looking forward to it!

**Comment by michaelld** [comment]
I like the idea, generally. Wondering if ADI be mostly in charge of keeping it up to date / bug fixes / etc? Or, us GR devs? We don't need more work ... so hoping Travis/ADI will take on that burden.

**Comment by tfcollins** [comment]
@michaelld Yes, I will take care of maintenance.

**Comment by michaelld** [comment]
> @michaelld Yes, I will take care of maintenance.

@tfcollins Excellent! I'm sold! Let's do this!
