### ISSUE TITLE
GRC38 OSX +Quartz refresh window content with 2:1 zoom on block port selection

### ISSUE THREAD

**Issue by eblot** [gnuradio/gnuradio#2736]
When one input or output block is selected in GRC, the drawing area is refreshed with a 2:1 copy of the actual content (100% reproducible). See attached screenshot:

<img width="501" alt="grc-zoom" src="https://user-images.githubusercontent.com/172423/63042042-7e689d80-bec9-11e9-8cd6-9fbb3af82c0d.png">

Another symptom is a 2:1 full window redraw, including the menu bar & icon bar, although it is less likely.

<img width="625" alt="grc-zoom2" src="https://user-images.githubusercontent.com/172423/63042343-12d30000-beca-11e9-83bf-3ef3056055c2.png">

**Comment by eblot** [comment]
It looks like another symptom of #2726. Whenever #2726 is worked around, this symptom disappears as well.

**Comment by iracigt** [comment]
I also encountered this issue, but only while running in retina (HiDPI) mode. I was able to reliably work around it by launching GRC from an app bundle with "Open in Low Resolution" set.

**Comment by jwanga** [comment]
> I also encountered this issue, but only while running in retina (HiDPI) mode. I was able to reliably work around it by launching GRC from an app bundle with "Open in Low Resolution" set.

Thanks for this advise. How did you create a GRC app bundle?

**Comment by rgov** [comment]
I am not seeing anything suddenly resize when I click on a block under Big Sur. Does this issue still repro?

If anything, the canvas area is probably half the size it should be, because the text is a bit difficult to read.

**Comment by NeuroForLunch** [comment]
> I am not seeing anything suddenly resize when I click on a block under Big Sur. Does this issue still repro?
> 
> If anything, the canvas area is probably half the size it should be, because the text is a bit difficult to read.

I can't reproduce this issue and I think #4814 fixes this

**Comment by michaelld** [comment]
Yes I think the generic fix in #4814 addresses this issue. I'm going to go ahead and close; please reopen if it's still an issue & post more info about what's going on.

**Comment by m-anish** [comment]
FWIW. I'm seeing something like this happen with a recent install #5429
