### ISSUE TITLE
Up-down and side-side scrolling in canvas area broken

### ISSUE THREAD

**Issue by MattEttus** [gnuradio/gnuradio#2759]
You can scroll by moving the scrollbars, but not by scroll wheel or two-finger scroll on a touchpad.  This happens with GR 3.8 and Python 2.7

**Comment by devnulling** [comment]
Tested this on Ubuntu with 3.8 + Python 3.6, and the canvas scrolls as expected with the mouse wheel for up+down, and using the mouse pad it'll scroll left+right and up+down.

**Comment by mormj** [comment]
@MattEttus - I remember you mentioning this at grcon - is this a mac thing?

**Comment by MattEttus** [comment]
No longer relevant, 3.9 and 3.10 work fine.
