### ISSUE TITLE
Tabs in GRC canvas area disappear

### ISSUE THREAD

**Issue by MattEttus** [gnuradio/gnuradio#2760]
Happens after a little while on GR 3.8 and Python 2.7.  Sometimes it looks like the tab bar is just shrunken down to 1/4 size, sometimes almost completely gone.

**Comment by NeuroForLunch** [comment]
What system? Does this still happen? Close issue if stale and no reproduction?

**Comment by MattEttus** [comment]
Looks to be gone in 3.9 with python 3.8
