### ISSUE TITLE
grc: embedded python parameter values disappear

### ISSUE THREAD

**Issue by mormj** [gnuradio/gnuradio#2765]
When using an embedded python block in a flowgraph, editing the block causes the values for the parameters to be cleared out when the block is changed.

Steps to reproduce:
1) Create an embedded block in the flowgraph
2) Give the block properties

![image](https://user-images.githubusercontent.com/34754695/63723410-6414b500-c823-11e9-8abd-ea548280ae81.png)

3) assign the properties to variables in the flowgraph:

![image](https://user-images.githubusercontent.com/34754695/63723424-71ca3a80-c823-11e9-8e56-7e6af95337c7.png)

4) Edit the block's python code and save

The values entered are wiped away:

![image](https://user-images.githubusercontent.com/34754695/63723485-93c3bd00-c823-11e9-87fd-85643e91e850.png)

**Comment by skoslowski** [comment]
Relevant code https://github.com/gnuradio/gnuradio/blob/822aedb5b8934549a10b70dc602a178f9765eef0/grc/core/blocks/embedded_python.py#L149

**Comment by cbdonohue** [comment]
> Relevant code
> 
> https://github.com/gnuradio/gnuradio/blob/822aedb5b8934549a10b70dc602a178f9765eef0/grc/core/blocks/embedded_python.py#L149

Thanks,
It looks like the self.params is an ordereddict that isn't being iterated correctly.
https://github.com/gnuradio/gnuradio/blob/822aedb5b8934549a10b70dc602a178f9765eef0/grc/core/blocks/embedded_python.py#L152-L155
