### ISSUE TITLE
QT GUI Tab Widget does not show Id field

### ISSUE THREAD

**Issue by jdemel** [gnuradio/gnuradio#2766]
If you want to organize your Qt GUI you may want to use the `QT GUI Tab Widget`. Other QT GUI blocks are placed inside this Widget with  `tab_widget_id@<tabnumber>: 0, 2, 2, 2` (values are examples) in the `GUI Hint` field.

Just like any other `Variable` block, the QT GUI Tab Widget needs to show the `Id` field. Otherwise, you'd need to guess from the generated code tab what the actual ID is and you cannot alter it. Which may place a significant burden on users with those auto-generated IDs.

At this point, I wonder how the decision to hide the ID field by default was made. This does make the function probe mostly useless or very complicated to use. Also, issues like the one described above pop up.

**Comment by dl1ksv** [comment]
I plead to show the Id field for all blocks as in older versions. I see no benefit tho show the id only for special blocks.
By the way the option block shows the id, too.

**Comment by dl1ksv** [comment]
Looking into the code , I saw that it's possible to conigure the visibility of the id in the yml file.
I did this for the Tab Widget #2767

**Comment by jdemel** [comment]
@dl1ksv Thanks for taking care of this.

**Comment by ThomasHabets** [comment]
`Probe signal` also needs to make this visible.

**Comment by haakov** [comment]
@dl1ksv's PRs (for `master` and `maint-3.8`) have been merged, closing.
