### ISSUE TITLE
GRC38 Band pass filter does not validate parameter

### ISSUE THREAD

**Issue by eblot** [gnuradio/gnuradio#2777]
When low/high frequency or transition width is not fill in (left blank), GRC does not detect the missing parameters and generates invalid Python code such as:

      self.band_pass_filter_0 = filter.fir_filter_ccf(
            1,
            firdes.band_pass(
                1,
                samp_rate,
                ,
                ,
                1000,
                firdes.WIN_HAMMING,
                6.76))

*i.e.* several comma separator in a row.

**Comment by mbr0wn** [comment]
Fixed by https://github.com/gnuradio/gnuradio/pull/2832
