### ISSUE TITLE
grc: add ability to force blocks to show id

### ISSUE THREAD

**Issue by mormj** [gnuradio/gnuradio#2780]
There are some blocks where the show_id field is not set, nor is it desired to be set, but I might want to see/change the block id in GRC. Could be for various reasons

1) clean up the automatic naming so that the generated .py is cleaner
2) reference the block by id from some other part of the flowgraph
3) the show_id didn't get set properly in the yml, and as a workaround I can change it, not wait until it is fixed.

This could be a context menu --> show block id

Thoughts?

**Comment by jdemel** [comment]
I can see at least one use case for this. The function probe block needs to know block IDs of all blocks. If you want to generate a flowgraph that you want to embed in a project, it might be really useful to be able to set those block IDs. Though, you break encapsulation in this case.

**Comment by Logismos** [comment]
As a new user, I've come across this issue while following the tutorials. The tutorial has us place a probe signal and a function probe block. Without an ID for the probe signal, I can't get the function probe to work in grc. @mormj, what was the workaround you used?

**Comment by mormj** [comment]
There are 2 possible workarounds currently:
1) add the "show_id" into the yml for the block you need the id for
    -- have to go into the dir where the grc blocks are installed, modify, then relaunch grc
2) generate the flowgraph and note what the block id is

What I'm suggesting is we do one of the following:
1) have a way to display it in grc when it is hidden (right click --> show id)
    -- feature would need to be added
2) just show id for every block by default (pre-3.8 behavior)
   -- decision would need to be made to revert this behavior

**Comment by jdemel** [comment]
I'd argue that it is not a good a idea to revert this behavior in 3.8. The decision was made for better or worse. But it would be a good enhancement to add an 'always show block ID' Option in GRC. Just like those snap to grid or hide port ID options.
This might even be easier than changing this on a block by block basis.

**Comment by mormj** [comment]
I like that suggestion - will give that a go and see what folks think
