### ISSUE TITLE
grc: show message ports option in blocks does nothing

### ISSUE THREAD

**Issue by mormj** [gnuradio/gnuradio#2859]
In GR 3.8, at least several blocks (copy, selector, qt gui frequency sink, probably more) with the show message ports option - the option has no effect.  (reported by @devnulling)

![image](https://user-images.githubusercontent.com/34754695/67498657-d0f2d280-f64d-11e9-84bf-932e42e3a87c.png)

![image](https://user-images.githubusercontent.com/34754695/67498746-fd0e5380-f64d-11e9-8358-01f3cb835823.png)

**Comment by mormj** [comment]
Fixed on 3.9/master - still exists on 3.8 - need to find and backport the commit that fixed it

**Comment by mormj** [comment]
I think it is this PR that fixed the issue (3.9 and beyond)
https://github.com/gnuradio/gnuradio/pull/3934

@willcode - good candidate for backport?

**Comment by dkozel** [comment]
@willcode Was this backported?

**Comment by willcode** [comment]
Already in 3.9 (#3934) and 3.8 (#4556).
