### ISSUE TITLE
Text box colors in gnuradio-companion

### ISSUE THREAD

**Issue by cclamb** [gnuradio/gnuradio#2862]
I use a dark GTK theme, and the text boxes do not follow the theme colors. Specifically, some text boxes are programmed to be white, which will fail with white text in a dark theme. Other colors are problematic as well, especially when they're relatively light.

**Comment by marcusmueller** [comment]
duplicates #2398

**Comment by dkozel** [comment]
Fixed in master and maint-3.8.
