### ISSUE TITLE
Audio after decode by CVSD is noise

### ISSUE THREAD

**Issue by tientuyen07** [gnuradio/gnuradio#2872]
I used code of CVSD decoder and fixed according to link https://lists.gnu.org/archive/html/discuss-gnuradio/2010-12/msg00289.html. But audio was be noise after decoding.
Input: RAW file (bytes file)
Output: RAW file. Using Audacity programs to read RAW file.
Whether I am using CVSD decoder right???
Thanks for help!

**Comment by marcusmueller** [comment]
This is no help forum, but a bug tracker. I'm afraid you're not supplying nearly enough information to pinpoint a bug here – might be as much a usage error as bad signal.
