### ISSUE TITLE
runtime: remove unused circular_file.cc

### ISSUE THREAD

**Issue by marcusmueller** [gnuradio/gnuradio#2874]
* and all references to it in CMake
* and all qa_circular_file
* and the header checks from gnuradio-runtime/ConfigChecks.cmake `GR_CHECK_HDR_N_DEF(io.h HAVE_IO_H)` isn't necessary afterwards

**Comment by michaelld** [comment]
Aw yeah! [Here comes coolaid!](https://www.youtube.com/watch?v=XOySePkkUbI) Breaking down walls and code, that's the way to go!

:+1: from me ... removing unused code is always a good thing!

**Comment by grant-cox** [comment]
I'd like to take care of this one. I removed the files and references, and make and make test succeed.

**Comment by grant-cox** [comment]
@marcusmueller I wanted to clarify before I re-open my merge request: there is another check for `GR_CHECK_HDR_N_DEF(io.h HAVE_IO_H)` in gr-blocks/lib/ConfigChecks.cmake . Should this be removed as well?

**Comment by marcusmueller** [comment]
Hey, @grant-cox, sorry for being late. Nope, that should not be removed, because HAVE_IO_H is still used in gr-blocks!

**Comment by grant-cox** [comment]
@marcusmueller no worries! To make sure I understand you correctly: I'm going to add back **both** instances of `GR_CHECK_HDR_N_DEF(io.h HAVE_IO_H)` to the cmake files since they are both used. Thank for getting back to me!
