### ISSUE TITLE
python3.7 issues

### ISSUE THREAD

**Issue by kdtmac** [gnuradio/gnuradio#2881]
Followed tips below
![图片](https://user-images.githubusercontent.com/22338707/68111738-d512d000-ff2a-11e9-90b9-3b269e00e05d.png)

i present my every step.
1.Change the PYTHONPATH line in setup_env.sh, to just 3.x paths.
I did like
![图片](https://user-images.githubusercontent.com/22338707/68112270-f1fbd300-ff2b-11e9-9e8b-dbef8bfba898.png)

2.Find the PyBOMBS recipe "gnuradio.lwr" in .pybombs directory, check this for reference
I found and went in
3.Change the "gitbranch" to "master".

![图片](https://user-images.githubusercontent.com/22338707/68112472-59198780-ff2c-11e9-9a94-ccb5acdc5838.png)

4.In gnuradio.lwr recipe file, add "-DENABLE_CTRLPORT_THRIFT=OFF" in "config_opt".
in step3 that picture.
5.Clear out your prior GR PyBOMBS build(s) and tell PyBOMBS to install via this recipe.

![图片](https://user-images.githubusercontent.com/22338707/68112560-92ea8e00-ff2c-11e9-9ce2-8c86a2937c78.png)
![图片](https://user-images.githubusercontent.com/22338707/68112599-a269d700-ff2c-11e9-932e-cb5c197dfb48.png)
![图片](https://user-images.githubusercontent.com/22338707/68112622-b281b680-ff2c-11e9-8dbd-1b4677ac3e0c.png)
![图片](https://user-images.githubusercontent.com/22338707/68112653-c3322c80-ff2c-11e9-83c5-579157b1869c.png)

**Comment by dkozel** [comment]
@kdtmac Were you able to solve this problem? If not, I'd strongly recommend asking on the mailing list or chat channel. I'd be happy to help you get your installation working on either of those. Just looking at your log output I can see that you have Anaconda Python installed. I've frequently seen that interfere with Python applications, extra work needs to be done to change installtion and search paths.

https://wiki.gnuradio.org/index.php/MailingLists
https://wiki.gnuradio.org/index.php/IRC
