### ISSUE TITLE
Default Audio Source utilizes 100% of CPU core

### ISSUE THREAD

**Issue by Vort** [gnuradio/gnuradio#2885]
When Audio Source is used in schematic, running program starts to consume 100% of 1 CPU core.
![gr_audio](https://user-images.githubusercontent.com/1242858/68202658-c8df4f00-ffcc-11e9-8eb4-938914795060.png)

If I switch to `portaudio` audio module, CPU usage drops down to 0-1%.

So please either fix default module or make `portaudio` as default.

Version tested: `gnuradio_3.7.13.5_win64_avx2.msi`
OS: Windows 7 SP1 x64

**Comment by alexcolpitts96** [comment]
I am guessing that default audio on your computer is non-blocking. Looking at the documentation for [portaudio](http://portaudio.com/docs/v19-doxydocs/api_overview.html) I found this:

> To write audio data to a Stream call Pa_WriteStream() and to read data call Pa_ReadStream(). These functions will block if the internal buffers are full, making them safe to call in a tight loop.

**Comment by Vort** [comment]
@alexcolpitts96 do you mean this modification?
![grt](https://user-images.githubusercontent.com/1242858/72781262-8de2d400-3c29-11ea-97bc-4397047b296b.png)
It is wrong because of two reasons:
1. ```Warning: This flow graph contains a throttle block and another rate limiting block, e.g. a hardware source or sink. This is usually undesired. Consider removing the throttle block.```
2. It does not fix 100% core usage.

**Comment by alexcolpitts96** [comment]
@Vort I was not 100% sure it would work but I thought it might be worth a shot. I will take a look at some more stuff to see what I can find.

**Comment by Vort** [comment]
Ok, thanks. I can test binaries if needed.

**Comment by alexcolpitts96** [comment]
When you are looking at your CPU usage what is the specific process with high CPU usage? Is it GNU Radio, Windows audio service, or both?

**Comment by Vort** [comment]
It is `D:\GNURadio\gr-python27\python.exe -u E:\top_block.py`
Maybe this screenshot can help:
![grpe](https://user-images.githubusercontent.com/1242858/72818632-7aa92600-3c74-11ea-8751-4fbb77fd37fc.png)
(I have 4 core, so 25% = 100% of 1 core)

**Comment by marcusmueller** [comment]
Fixed as of 3.9.1.0
