### ISSUE TITLE
3.8.0.0 german hyphenation patterns -' dehypht.tex' missing - breaks build 

### ISSUE THREAD

**Issue by barjac** [gnuradio/gnuradio#2889]
------------------------snip-----------------------
`EC Galician hyphenation patterns
(/usr/share/texmf-dist/tex/generic/hyph-utf8/conversions/conv-utf8-ec.tex)
(/usr/share/texmf-dist/tex/generic/hyph-utf8/patterns/tex/hyph-gl.tex))
(/usr/share/texmf-dist/tex/generic/hyph-utf8/loadhyph/loadhyph-ka.tex
T8M Georgian hyphenation patterns
(/usr/share/texmf-dist/tex/generic/hyph-utf8/conversions/conv-utf8-t8m.tex)
(/usr/share/texmf-dist/tex/generic/hyph-utf8/patterns/tex/hyph-ka.tex))
(/usr/share/texmf-dist/tex/generic/hyph-utf8/loadhyph/loadhyph-de-1901.tex
EC German hyphenation patterns (traditional orthography)
! I can't find file `dehypht.tex'.
l.29     \input dehypht.tex
                           
(Press Enter to retry, or Control-D to exit)
Please type another input file name: 
! Emergency stop.
l.29     \input dehypht.tex
                           
No pages of output.
Transcript written on latex.log.
mktexfmt [ERROR]: running `pdftex -ini   -jobname=latex -progname=latex -translate-file=cp227.tcx *latex.ini >&2 </dev/null' return status 1
mktexfmt [ERROR]: return error due to options --strict
mktexfmt [INFO]: Disabled formats: 6
mktexfmt [INFO]: Not selected formats: 44
mktexfmt [INFO]: Failed to build: 1 (pdftex/latex)
mktexfmt [INFO]: Total formats: 51
mktexfmt [INFO]: exiting with status 1
I can't find the format file `latex.fmt'!
error: Problems running latex. Check your installation or look for typos in _formulas.tex and check _formulas.log!
dvips: DVI file can't be opened: _formulas.dvi: No such file or directory
error: Problems running dvips. Check your installation!
/home/baz/rpmbuild/BUILD/gnuradio-3.8.0.0/gr-channels/include/gnuradio/channels/selective_fading_model2.h:65: warning: argument 'mags' from the argument list of gr::channels::selective_fading_model2::make has muliple @param documentation sections
/home/baz/rpmbuild/BUILD/gnuradio-3.8.0.0/gnuradio-runtime/include/gnuradio/thrift_application_base.h:158: warning: unable to resolve reference to `page_logger' for \ref command
/home/baz/rpmbuild/BUILD/gnuradio-3.8.0.0/gr-uhd/include/gnuradio/uhd/usrp_sink.h:58: warning: unable to resolve reference to `page_tagged_stream_blocks' for \ref command
/home/baz/rpmbuild/BUILD/gnuradio-3.8.0.0/gr-digital/docs/packet_comms.dox:164: warning: unable to resolve reference to `page_tagged_stream_blocks' for \ref command
/home/baz/rpmbuild/BUILD/gnuradio-3.8.0.0/gr-digital/docs/packet_comms.dox:622: warning: unable to resolve reference to `page_pmt' for \ref command
/home/baz/rpmbuild/BUILD/gnuradio-3.8.0.0/gr-fec/docs/fec.dox:131: warning: unable to resolve reference to `page_tagged_stream_blocks' for \ref command
/home/baz/rpmbuild/BUILD/gnuradio-3.8.0.0/gr-fec/docs/fec.dox:173: warning: unable to resolve reference to `page_msg_passing' for \ref command
/home/baz/rpmbuild/BUILD/gnuradio-3.8.0.0/gr-filter/docs/filter.dox:59: warning: unable to resolve reference to `pfb_arb_resampler' for \ref command
/home/baz/rpmbuild/BUILD/gnuradio-3.8.0.0/gr-uhd/docs/uhd.dox:34: warning: unable to resolve reference to `msg_passing_commands' for \ref command
`

**Comment by marcusmueller** [comment]
That's a strange Linux distro issue; I hope it's solved "upstream" by now; anyways, we couldn't fix it in GNU Radio!
