### ISSUE TITLE
OpenBSD: thread.cc doesn't build

### ISSUE THREAD

**Issue by ThomasHabets** [gnuradio/gnuradio#2902]
Existing [downstream patch for 3.7](https://cvsweb.openbsd.org/ports/comms/gnuradio/patches/patch-gnuradio-runtime_lib_thread_thread_cc?rev=1.1&content-type=text/x-cvsweb-markup).

I believe only the first part is needed.

Really `thread.cc` is all wrong and should not look for OS names but rather the presence of specific functionality. E.g. OpenBSD has `pthread_self()` and `pthread_set_name_np()`, which should be used instead of giving up.

**Comment by marcusmueller** [comment]
No `*BSD` CI infrastructure exists; I think we're at a point that GR builds on OpenBSD again, but I haven't tested.

**Comment by marcusmueller** [comment]
I've heard from a competent source that NetBSD builds are possible

**Comment by marcusmueller** [comment]
#6689 shows we build on OpenBSD
