### ISSUE TITLE
parse_file_metadata.py loss in timestamp precision

### ISSUE THREAD

**Issue by ks0ze** [gnuradio/gnuradio#2919]
The metadata for "rx_time" is a pmt pair with a uint64 representing the whole seconds and a double representing the fractional seconds. When these values are read in by parse_file_metadata.py, they are added together to form a double precision output. During this operation, precision is lost resulting in incorrect timestamps being reported.

For example, if the whole seconds field is  1574265869 and the fractional field is 0.9411768823529413 the resulting double upon addition is 1574265869.9411768**91326904296875** rather than 1574265869 .9411768**823529413**.

My recommendation would be to change parse_file_metadata.py to return a whole second field and a fractional second field as they are produced rather than adding them together.

**Comment by marcusmueller** [comment]
problematic precision-reducing code still persists:

```python
    if(pmt.dict_has_key(p, pmt.string_to_symbol("rx_time"))):
        r = pmt.dict_ref(p, pmt.string_to_symbol("rx_time"), dump)
        secs = pmt.tuple_ref(r, 0)
        fracs = pmt.tuple_ref(r, 1)
        secs = pmt.to_uint64(secs)
        fracs = pmt.to_double(fracs)
        t = float(secs) + fracs
        info["rx_time_secs"] = secs
        info["rx_time_fracs"] = fracs
        info["rx_time"] = t
```

> My recommendation would be to change parse_file_metadata.py to return a whole second field and a fractional second field as they are produced rather than adding them together. 

that however, does happen:

```python
        info["rx_time_secs"] = secs
        info["rx_time_fracs"] = fracs
```

So, good.
