### ISSUE TITLE
 Please help

### ISSUE THREAD

**Issue by kabzonkill** [gnuradio/gnuradio#2930]
Can't find flow graph for Michael Osman's lessons. Installed version of GNU Radio Companion
3.9.0.0-git (Python 3.6.8).  flow graph Source, WX, wxGui.

**Comment by yaaseen-dev** [comment]
WX GUI support has been removed from gnuradio 3.8 and higher. You have to use QT GUI blocks.

**Comment by kabzonkill** [comment]
they are not there either ((
