### ISSUE TITLE
make error: too many arguments to function  volk_32f_8u_polarbutterfly_32f(llrs, u, block_size(), block_power(), stage, u_num, row);

### ISSUE THREAD

**Issue by kewenkang** [gnuradio/gnuradio#2937]
/home/tk/gnuradio/gr-fec/lib/polar_decoder_common.cc: In member function ‘void gr::fec::code::polar_decoder_common::butterfly_volk(float*, unsigned char*, int, int, int)’:
/home/tk/gnuradio/gr-fec/lib/polar_decoder_common.cc:126:95: error: too many arguments to function
         volk_32f_8u_polarbutterfly_32f(llrs, u, block_size(), block_power(), stage, u_num, row);

**Comment by velichkov** [comment]
Hi @kewenkang,

You are probably trying to compile an older version of gnuradio with newer version of volk. 

Try updating your git repo to the latest commit
```
$ git fetch origin 
$ git rebase @{u}
$ git submodule update
```
The polarbutterfly API was changed in https://github.com/gnuradio/volk/pull/155 and later gnuradio usage was updated in https://github.com/gnuradio/gnuradio/pull/1640
