### ISSUE TITLE
gr3.8 | Stream mux | Dispatches items from input N to the output even if input N+1 does not have items anymore

### ISSUE THREAD

**Issue by fmagno** [gnuradio/gnuradio#2940]
May be arguable whether this is a bug or a feature. IMO, `stream mux` may be more useful if it stops producing output items when these two conditions are simultaneously met:
1. The output produced Nm items relative to the last input stream
2. Any one of the input streams no longer have available items to be sent to the output

Example: consider the following FG.
![image](https://user-images.githubusercontent.com/3079603/69901949-fcb95480-137f-11ea-88b5-a3f96ff43caf.png)

- With the current implementation, the content of the output file `stream_mux.dat` is: `0x01 0x01 0x01 0x01`.
- With the above proposed change the content of the file would be: `0x01 0x01 0x01`

**Comment by mormj** [comment]
I can see the merits of the suggestions, but I could also see where the naiive implementation of stream mux could be desirable.  For instance if I'm trying to generate a fixed size output file, and bursty input, I wouldn't want stream mux to stop producing outputs if there is not a fixed multiple.  Seems like changing the behavior could break things.

**Comment by fmagno** [comment]
I see your point. That makes sense. 👍

[closing the issue]
