### ISSUE TITLE
Default "myootConfig.cmake created by modtool searches for non-existent pkg-config file

### ISSUE THREAD

**Issue by smunaut** [gnuradio/gnuradio#2942]
The logic in there includes :

```
INCLUDE(FindPkgConfig)
PKG_CHECK_MODULES(PC_MYOOT myoot)
```

but modtool generates nothing that would create a pkg-config `.pc` file anywhere so this whole logic is unecessary and confusing when trying to understand how this thing works.

**Comment by smunaut** [comment]
Is that file even needed at all ? I mean cmake will create a myootConfig.cmake by default automatically and if you remove the useless .pc logic from the manual one, I don't really see what's left of interest ?

**Comment by marcusmueller** [comment]
to figure out whether we still need that, we should probably test whether we can make a new module, add a C++ block, build and install the whole shabang, then use the resulting cmake config file in another cmake project.

**Comment by marcusmueller** [comment]
Obsoleted by the move towards modern CMake
