### ISSUE TITLE
cmake: duplicate icons, desktop and MIME files installed in ${GR_PKG_DATA_DIR}/grc/freedesktop

### ISSUE THREAD

**Issue by cjmayo** [gnuradio/gnuradio#2948]
78ba4b8794339f8efabf85123a2f249cdb787bfa introduced installing gnuradio-grc.desktop, gnuradio-grc.xml and icons directly into the standard directories but the code that installs the same files in ${GR_PKG_DATA_DIR}/grc/freedesktop and the script `grc_setup_freedesktop` was left in.

**Comment by marcusmueller** [comment]
Fixed since at least 3.8.1.0
