### ISSUE TITLE
canvas size doesn't seem to work

### ISSUE THREAD

**Issue by cmrincon** [gnuradio/gnuradio#2951]
Canvas size atribute in grc options block is useless, i can modify the parameter to (300,300) and still, i can drop any block beyond that limit.

**Comment by mormj** [comment]
You are correct this doesn't change the canvas visually as in GNU Radio 3.7 (which was fixed size canvas).   You can drag a block and the canvas will auto-resize.

Looks like either the canvas size option needs to be removed, or made to work (and update when blocks are dragged)

**Comment by dkozel** [comment]
I'd like to see it removed as a setting. Auto-resizing seems preferable in every way. We need to check on whether auto-downsizing happens.
