### ISSUE TITLE
Blocks, Properties dialog too small in size

### ISSUE THREAD

**Issue by Phil67ago** [gnuradio/gnuradio#2953]
It is often too small. The drawback for me is that I always try to scroll with the wheel button.
What often happens is nothing, no scrolling. What I did was changing some drop down box under the cursor.
Annoying because to get back I have to Cancel and open the Dialog again.
This is on Fedora 30.

I have tested a patch against maint-3.8
[gnuradio-prop-dialog-size_maint-3.8.patch.txt](https://github.com/gnuradio/gnuradio/files/3938723/gnuradio-prop-dialog-size_maint-3.8.patch.txt)

Very dirty, someone with better QT knowledge should do it better.

**Comment by dkozel** [comment]
@Phil67ago Thanks again for the report and patch. I'm not sure I understand the issue, can you add some screenshots?

**Comment by Phil67ago** [comment]
This is from 3.7.13.5
![image](https://user-images.githubusercontent.com/16326974/70450731-84037800-1aa4-11ea-8390-de8019c1e6d0.png)

And this is 3.8.0.0 with patch
![image](https://user-images.githubusercontent.com/16326974/70450835-b1e8bc80-1aa4-11ea-8eb3-76f885416d04.png)

Above is as they are displayed without resizing the Dialog frame.

If I scroll the mouse wheel above 'Window Type' I will change 'Backman-harris' to something else!

**Comment by dkozel** [comment]
I see! Yes, this seems like a reasonable change. We'll get a review of the implementation and check what happens on blocks with lots of properties.

**Comment by devnulling** [comment]
Testing is needed for this patch. It may cause issues when the window size is larger than the screen, for example with a UHD source/sink that has 32 channels.

**Comment by devnulling** [comment]
@Phil67ago I'm going to close this issue as this change will produce undesired behavior when used with a properties dialog that has more options than fit within the screen, for example with a USRP source that has 20 channels, it'll force the top/bottom off screen.

I would like to note though that we are working on porting GRC to use QT, so it will likely have better default behavior with that switch.
