### ISSUE TITLE
grc: DeprecationWarning: 'encoding' is ignored and deprecated. It will be removed in Python 3.9

### ISSUE THREAD

**Issue by nickoe** [gnuradio/gnuradio#2962]
I get this error spammed when running grc, on archlinux with python 3.8.0 and gnuradio  3.8.0.0. I could not see any issue or pull request specifically addressing this issue, so I assume it is still an issue on `master` and the `maint-3.8` branch, but I didn't verify this.

```
/usr/lib/python3.8/site-packages/gnuradio/grc/core/utils/extract_docs.py:201: DeprecationWarning: 'encoding' is ignored and deprecated. It will be removed in Python 3.9
  key, cmd, args = json.loads(line.decode('utf-8'), encoding='utf-8')

```

**Comment by skoslowski** [comment]
https://github.com/gnuradio/gnuradio/pull/2913

**Comment by nickoe** [comment]
@skoslowski thank you. But should't this be cherry picked to maint-3.8 as well?

**Comment by devnulling** [comment]
Closing this as it was back ported to maint-3.8 with https://github.com/gnuradio/gnuradio/pull/2994
