### ISSUE TITLE
"Symbol Sync" block can't be added to GRC flowgraph

### ISSUE THREAD

**Issue by RedStone002** [gnuradio/gnuradio#2985]
Dear all,
I did a fresh install of GNURadio v3.8.0.0/v1.7 BETA for Windows from the link in GNURadio wiki.
It works almost perfectly, but I noticed one issue:
I can't add the Core-Synchronizers->Symbol Sync to my GRC flowgraph.
When I double click the "Symbol Sync" nothing happens. 

Adding the other synchronizers works fine, just the "Symbol Sync" block can't be added to the flowgraph.

The following error is written in the command-prompt window:
> C:\gnuradio\bin>run_GRC.bat
> WARNING:gnuradio.grc.core.platform:Slow YAML loading (libyaml not available)
> Traceback (most recent call last):
>   File "C:\gnuradio\lib\site-packages\gnuradio\grc\gui\MainWindow.py", line 158, in _add_block_to_current_flow_graph
>     self.current_flow_graph.add_new_block(key)
>   File "C:\gnuradio\lib\site-packages\gnuradio\grc\gui\canvas\flowgraph.py", line 175, in add_new_block
>     block = self.new_block(key)
>   File "C:\gnuradio\lib\site-packages\gnuradio\grc\core\FlowGraph.py", line 269, in new_block
>     block = self.parent_platform.make_block(self, block_id, **kwargs)
>   File "C:\gnuradio\lib\site-packages\gnuradio\grc\core\platform.py", line 428, in make_block
>     return cls(parent, **kwargs)
>   File "C:\gnuradio\lib\site-packages\gnuradio\grc\gui\canvas\block.py", line 46, in __init__
>     super(self.__class__, self).__init__(parent, **n)
>   File "C:\gnuradio\lib\site-packages\gnuradio\grc\core\blocks\block.py", line 78, in __init__
>     for data in self.parameters_data
>   File "C:\gnuradio\gr-python27\lib\collections.py", line 57, in __init__
>     self.__update(*args, **kwds)
>   File "C:\gnuradio\bin\..\gr-python27\lib\_abcoll.py", line 568, in update
>     for key, value in other:
>   File "C:\gnuradio\lib\site-packages\gnuradio\grc\core\blocks\block.py", line 78, in <genexpr>
>     for data in self.parameters_data
>   File "C:\gnuradio\lib\site-packages\gnuradio\grc\core\platform.py", line 432, in make_param
>     return cls(parent, **kwargs)
>   File "C:\gnuradio\lib\site-packages\gnuradio\grc\core\params\param.py", line 59, in __init__
>     option_attributes or {})
>   File "C:\gnuradio\lib\site-packages\gnuradio\grc\core\params\param.py", line 99, in _init_options
>     label = str(labels[i])
> UnicodeEncodeError: 'ascii' codec can't encode character u'\xfc' in position 13: ordinal not in range(128)

**Comment by RedStone002** [comment]
Poking a little bit around, I think this happens when the text
Mueller and M?ller
should be displayed in the drop-down list. The correc text would be "Mueller and Müller" with an the german Umlaut ü.

**Comment by RedStone002** [comment]
I found the offending string in the file
`gnuradio\share\gnuradio\grc\blocks\digital_symbol_sync_xx.block.yml`

In line 22 it reads:
> option_labels: ["Mueller and M\xFCller", "Modified Mueller and M\xFCller",
If I change it to this, the block can be inserted without eror:
>option_labels: ["Mueller and Mueller", "Modified Mueller and Mueller", ... ...
 
The underlying issue is a little deeper. Is the YML file supposed be ASCII or UTF-8?
Is the data read byte-wise or as strings? Is the encoding handled consistently?
Further problems ahead: Python 2.7 to Python 3
The str() in python 2.7 behaves differently than in Python3. In Python 2.7 there is also unicode() which is missing in Python3. So there has to be some thought-through approach to path the source-line in
gnuradio\lib\site-packages\gnuradio\grc\core\params\param.py , line 99
`label = str(labels[i])`

**Comment by rear1019** [comment]
> I found the offending string in the file
> `gnuradio\share\gnuradio\grc\blocks\digital_symbol_sync_xx.block.yml`
> 
> The underlying issue is a little deeper. Is the YML file supposed be ASCII or UTF-8?
> Is the data read byte-wise or as strings? Is the encoding handled consistently?
> Further problems ahead: Python 2.7 to Python 3
> The str() in python 2.7 behaves differently than in Python3. In Python 2.7 there is also unicode() which is missing in Python3. So there has to be some thought-through approach to path the source-line in
> gnuradio\lib\site-packages\gnuradio\grc\core\params\param.py , line 99
> `label = str(labels[i])`
> 
> I propose the following patch
> In line 22 it reads:
> 
> > option_labels: ["Mueller and M\xFCller", "Modified Mueller and M\xFCller",
> > If I change it to this, the block can be inserted without eror:
> > option_labels: ["Mueller and Mueller", "Modified Mueller and Mueller", ... ...

With all due respect, the proposed fix is the wrong way to go. The underlying issue(s) should be fixed (see the remarks above), not the symptoms.

Note: The bug does not appear in GNU Radio 3.8 built with Python 3.

**Comment by RedStone002** [comment]
I agree.
I'm just not versed enough in GNURadio development to figure out the whole chain of encoding from the yml file to QT.
I don't have access to a py3 build of GNURadio (Windows), but I believe you that the problem will go away. So maybe my patch should not be merged.

**Comment by mbr0wn** [comment]
Closed by https://github.com/gnuradio/gnuradio/pull/2986.
