### ISSUE TITLE
GRC: Errors in Symbol Sync block parameters parser

### ISSUE THREAD

**Issue by RedStone002** [gnuradio/gnuradio#2987]
I'm refering to a fresh install of GNURadio v3.8.0.0/v1.7 BETA for Windows from the link in GNURadio wiki.

After adding an "Core->Synchronizers->Symbol Sync" block to my GRC flowgraph, I can't use it, because there is validation error on the following fields:
```
Param TED Slicer Constellation' Can not cast evaluated value 'part' to type <type 'str'>
Param 'Filterbank Arms' Can not cast evaluated value ‘all' to type <type 'str'>
Param 'PFB MF Taps' Can not cast evaluated value ‘all' to type <type 'str'>
```
This has nothing to do with the text or value that is entered in the properties dialog.
I traced the problem to the definition in 

> gnuradio\share\gnuradio\grc\blocks\digital_symbol_sync_xx.block.yml 

If the line
```
    option_attributes:
        hide_constellation: [part, part, part, all, all, all, all, all, all]
```
is replaced by:
```
    option_attributes:
        hide_constellation: ['part', 'part', 'part', 'all', 'all', 'all', 'all', 'all', 'all']
```
the validation will succeed.

**Comment by marcusmueller** [comment]
Examples involving the Symbol Sync block seem to work – closing as fixed, somewhen.
