### ISSUE TITLE
Make GR OOT top-level GR components equivalent

### ISSUE THREAD

**Issue by devnulling** [gnuradio/gnuradio#3006]
Place holder for 3.9 project

- Not in GR proper; still OOT
- the min-in-tree route requires a robust OOT setup
- installing OOT Python into “${GR_PYTHON_DIR}/gnuradio/OOT”

For examples on how to find or use:
- Python: from gnuradio import blocks, fosphor, iqbal
- CMake: find_package(gnuradio COMPONENTS blocks fosphor iqbal)
- Have to update modtool
- Has other benefits for where Python files are installed, library names, etc.

**Comment by mormj** [comment]
The bulk of these changes were implemented in 3.10 release
