### ISSUE TITLE
How fix : Error: symbol(s) not found for architecture x86_64

### ISSUE THREAD

**Issue by gsong2014** [gnuradio/gnuradio#3014]
patch :
https://github.com/gnuradio/gnuradio/commit/9498f70d4934b844061fc83d62771257ec923fdb

[1141/1208] Linking CXX shared library gr-digital/lib/libgnuradio-digital.3.8.0.0.dylib
FAILED: gr-digital/lib/libgnuradio-digital.3.8.0.0.dylib 
: && /usr/local/Homebrew/Library/Homebrew/shims/mac/super/clang++ -fvisibility=hidden -Wsign-compare -Wall -Wno-uninitialized -DNDEBUG  -dynamiclib -Wl,-headerpad_max_install_names -compatibility_version 3.8.0 -current_version 3.8.0 -o gr-digital/lib/libgnuradio-digital.3.8.0.0.dylib -install_name /usr/local/Cellar/gnuradio@3.8/3.8.0.0/lib/libgnuradio-digital.3.8.0.dylib gr-digital/lib/CMakeFiles/gnuradio-digital.dir/additive_scrambler_bb_impl.cc.o gr-digital/lib/CMakeFiles/gnuradio-digital.dir/binary_slicer_fb_impl.cc.o gr-digital/lib/CMakeFiles/gnuradio-digital.dir/burst_shaper_impl.cc.o gr-digital/lib/CMakeFiles/gnuradio-digital.dir/chunks_to_symbols_impl.cc.o gr-digital/lib/CMakeFiles/gnuradio-digital.dir/clock_recovery_mm_cc_impl.cc.o gr-digital/lib/CMakeFiles/gnuradio-digital.dir/clock_recovery_mm_ff_impl.cc.o gr-digital/lib/CMakeFiles/gnuradio-digital.dir/clock_tracking_loop.cc.o gr-digital/lib/CMakeFiles/gnuradio-digital.dir/cma_equalizer_cc_impl.cc.o gr-digital/lib/CMakeFiles/gnuradio-digital.dir/constellation.cc.o gr-digital/lib/CMakeFiles/gnuradio-digital.dir/constellation_decoder_cb_impl.cc.o gr-digital/lib/CMakeFiles/gnuradio-digital.dir/constellation_receiver_cb_impl.cc.o gr-digital/lib/CMakeFiles/gnuradio-digital.dir/constellation_soft_decoder_cf_impl.cc.o gr-digital/lib/CMakeFiles/gnuradio-digital.dir/corr_est_cc_impl.cc.o gr-digital/lib/CMakeFiles/gnuradio-digital.dir/correlate_access_code_bb_impl.cc.o gr-digital/lib/CMakeFiles/gnuradio-digital.dir/correlate_access_code_tag_bb_impl.cc.o gr-digital/lib/CMakeFiles/gnuradio-digital.dir/correlate_access_code_tag_ff_impl.cc.o gr-digital/lib/CMakeFiles/gnuradio-digital.dir/correlate_access_code_bb_ts_impl.cc.o gr-digital/lib/CMakeFiles/gnuradio-digital.dir/correlate_access_code_ff_ts_impl.cc.o gr-digital/lib/CMakeFiles/gnuradio-digital.dir/costas_loop_cc_impl.cc.o gr-digital/lib/CMakeFiles/gnuradio-digital.dir/cpmmod_bc_impl.cc.o gr-digital/lib/CMakeFiles/gnuradio-digital.dir/crc32.cc.o gr-digital/lib/CMakeFiles/gnuradio-digital.dir/crc32_bb_impl.cc.o gr-digital/lib/CMakeFiles/gnuradio-digital.dir/crc32_async_bb_impl.cc.o gr-digital/lib/CMakeFiles/gnuradio-digital.dir/descrambler_bb_impl.cc.o gr-digital/lib/CMakeFiles/gnuradio-digital.dir/diff_decoder_bb_impl.cc.o gr-digital/lib/CMakeFiles/gnuradio-digital.dir/diff_encoder_bb_impl.cc.o gr-digital/lib/CMakeFiles/gnuradio-digital.dir/diff_phasor_cc_impl.cc.o gr-digital/lib/CMakeFiles/gnuradio-digital.dir/fll_band_edge_cc_impl.cc.o gr-digital/lib/CMakeFiles/gnuradio-digital.dir/framer_sink_1_impl.cc.o gr-digital/lib/CMakeFiles/gnuradio-digital.dir/glfsr.cc.o gr-digital/lib/CMakeFiles/gnuradio-digital.dir/glfsr_source_b_impl.cc.o gr-digital/lib/CMakeFiles/gnuradio-digital.dir/glfsr_source_f_impl.cc.o gr-digital/lib/CMakeFiles/gnuradio-digital.dir/hdlc_deframer_bp_impl.cc.o gr-digital/lib/CMakeFiles/gnuradio-digital.dir/hdlc_framer_pb_impl.cc.o gr-digital/lib/CMakeFiles/gnuradio-digital.dir/header_buffer.cc.o gr-digital/lib/CMakeFiles/gnuradio-digital.dir/header_payload_demux_impl.cc.o gr-digital/lib/CMakeFiles/gnuradio-digital.dir/kurtotic_equalizer_cc_impl.cc.o gr-digital/lib/CMakeFiles/gnuradio-digital.dir/lms_dd_equalizer_cc_impl.cc.o gr-digital/lib/CMakeFiles/gnuradio-digital.dir/map_bb_impl.cc.o gr-digital/lib/CMakeFiles/gnuradio-digital.dir/modulate_vector.cc.o gr-digital/lib/CMakeFiles/gnuradio-digital.dir/mpsk_snr_est.cc.o gr-digital/lib/CMakeFiles/gnuradio-digital.dir/mpsk_snr_est_cc_impl.cc.o gr-digital/lib/CMakeFiles/gnuradio-digital.dir/msk_timing_recovery_cc_impl.cc.o gr-digital/lib/CMakeFiles/gnuradio-digital.dir/ofdm_carrier_allocator_cvc_impl.cc.o gr-digital/lib/CMakeFiles/gnuradio-digital.dir/ofdm_chanest_vcvc_impl.cc.o gr-digital/lib/CMakeFiles/gnuradio-digital.dir/ofdm_cyclic_prefixer_impl.cc.o gr-digital/lib/CMakeFiles/gnuradio-digital.dir/ofdm_equalizer_base.cc.o gr-digital/lib/CMakeFiles/gnuradio-digital.dir/ofdm_equalizer_simpledfe.cc.o gr-digital/lib/CMakeFiles/gnuradio-digital.dir/ofdm_equalizer_static.cc.o gr-digital/lib/CMakeFiles/gnuradio-digital.dir/ofdm_frame_equalizer_vcvc_impl.cc.o gr-digital/lib/CMakeFiles/gnuradio-digital.dir/ofdm_serializer_vcc_impl.cc.o gr-digital/lib/CMakeFiles/gnuradio-digital.dir/ofdm_sync_sc_cfb_impl.cc.o gr-digital/lib/CMakeFiles/gnuradio-digital.dir/header_format_base.cc.o gr-digital/lib/CMakeFiles/gnuradio-digital.dir/header_format_default.cc.o gr-digital/lib/CMakeFiles/gnuradio-digital.dir/header_format_counter.cc.o gr-digital/lib/CMakeFiles/gnuradio-digital.dir/header_format_crc.cc.o gr-digital/lib/CMakeFiles/gnuradio-digital.dir/header_format_ofdm.cc.o gr-digital/lib/CMakeFiles/gnuradio-digital.dir/protocol_formatter_async_impl.cc.o gr-digital/lib/CMakeFiles/gnuradio-digital.dir/protocol_formatter_bb_impl.cc.o gr-digital/lib/CMakeFiles/gnuradio-digital.dir/protocol_parser_b_impl.cc.o gr-digital/lib/CMakeFiles/gnuradio-digital.dir/packet_header_default.cc.o gr-digital/lib/CMakeFiles/gnuradio-digital.dir/packet_header_ofdm.cc.o gr-digital/lib/CMakeFiles/gnuradio-digital.dir/packet_headergenerator_bb_impl.cc.o gr-digital/lib/CMakeFiles/gnuradio-digital.dir/packet_headerparser_b_impl.cc.o gr-digital/lib/CMakeFiles/gnuradio-digital.dir/packet_sink_impl.cc.o gr-digital/lib/CMakeFiles/gnuradio-digital.dir/pfb_clock_sync_ccf_impl.cc.o gr-digital/lib/CMakeFiles/gnuradio-digital.dir/pfb_clock_sync_fff_impl.cc.o gr-digital/lib/CMakeFiles/gnuradio-digital.dir/pn_correlator_cc_impl.cc.o gr-digital/lib/CMakeFiles/gnuradio-digital.dir/probe_density_b_impl.cc.o gr-digital/lib/CMakeFiles/gnuradio-digital.dir/probe_mpsk_snr_est_c_impl.cc.o gr-digital/lib/CMakeFiles/gnuradio-digital.dir/scrambler_bb_impl.cc.o gr-digital/lib/CMakeFiles/gnuradio-digital.dir/simple_correlator_impl.cc.o gr-digital/lib/CMakeFiles/gnuradio-digital.dir/simple_framer_impl.cc.o gr-digital/lib/CMakeFiles/gnuradio-digital.dir/interpolating_resampler.cc.o gr-digital/lib/CMakeFiles/gnuradio-digital.dir/symbol_sync_cc_impl.cc.o gr-digital/lib/CMakeFiles/gnuradio-digital.dir/symbol_sync_ff_impl.cc.o gr-digital/lib/CMakeFiles/gnuradio-digital.dir/timing_error_detector.cc.o  -Wl,-rpath,/usr/local/Cellar/gnuradio@3.8/3.8.0.0/lib  gr-analog/lib/libgnuradio-analog.3.8.0.0.dylib  gr-filter/lib/libgnuradio-filter.3.8.0.0.dylib  gr-fft/lib/libgnuradio-fft.3.8.0.0.dylib  /usr/local/lib/libfftw3f.dylib  /usr/local/lib/libfftw3f_threads.dylib  gr-blocks/lib/libgnuradio-blocks.3.8.0.0.dylib  gnuradio-runtime/lib/libgnuradio-runtime.3.8.0.0.dylib  gnuradio-runtime/lib/pmt/libgnuradio-pmt.3.8.0.0.dylib  -lboost_thread-mt  /usr/local/lib/libboost_program_options.dylib  /usr/local/lib/libboost_filesystem.dylib  /usr/local/lib/libboost_system.dylib  /usr/local/lib/libboost_regex.dylib  /usr/local/lib/libboost_thread-mt.dylib  /usr/local/lib/liblog4cpp.dylib  /usr/local/opt/gmp/lib/libgmpxx.dylib  /usr/local/opt/gmp/lib/libgmp.dylib  volk/lib/libvolk.2.0.dylib  /usr/local/lib/liborc-0.4.dylib  -lm && :
Undefined symbols for architecture x86_64:
  "gr::digital::map_bb_impl::s_map_size", referenced from:
      gr::digital::map_bb_impl::set_map(std::__1::vector<int, std::__1::allocator<int> > const&) in map_bb_impl.cc.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by marcusmueller** [comment]
This doesn't seem to be a bug report. Closing.
