### ISSUE TITLE
Alsa sink: use VOLK to do the float->audio sample format conversion

### ISSUE THREAD

**Issue by marcusmueller** [gnuradio/gnuradio#3025]
the work_s32, work_s16,… functions do things in unaccelerated code, but should be using the appropriate VOLK functions instead – this might not be a large issue, since audio rates are by definition low, but it reduces code duplication and has potential for speedup, especially on embedded platforms.

**Comment by 85ayush** [comment]
I would love to work on this issue, I am new to open source contribution, can you please guide me?
