### ISSUE TITLE
QT gui time sink doesn't validate missing input connections

### ISSUE THREAD

**Issue by mormj** [gnuradio/gnuradio#3036]
The QT GUI time sink doesn't complain that nothing is connected to it:

![image](https://user-images.githubusercontent.com/34754695/71913104-b5737000-3144-11ea-8a15-acf64e324d70.png)

which means that missing connections throw exceptions at runtime, but should be prevented in GRC:

![image](https://user-images.githubusercontent.com/34754695/71913199-e5bb0e80-3144-11ea-9000-a206e9825f48.png)

The above flowgraph throws a topology error at runtime.

**Comment by dkozel** [comment]
The port is labeled as optional. Took a quick look and the UHD blocks just don't declare the optional attribute so the multiplicity param is correctly handled by GRC.
https://github.com/gnuradio/gnuradio/blob/master/gr-qtgui/grc/qtgui_time_sink_x.block.yml#L996
