### ISSUE TITLE
GRC disabling a block remove it and its connections

### ISSUE THREAD

**Issue by ChristopheSeguinot** [gnuradio/gnuradio#3091]
Hi, 
This bug affect GRC 3.9 (not tested for GRC 3.8)
When a block was disabled in older GRC, this block and its connections were greyed. 
At present the block is completely removed (we need ctrl Z to revert deletion)
Is this a bug ? 

Regards, Christophe

**Comment by ekigwana** [comment]
I have noticed this behavior occasionally as well.

**Comment by haakov** [comment]
Certainly sounds like a bug! I can't say I've run into this problem myself though.

Are you able to reproduce this behaviour consistently? If so, can you share .grc file? :)

**Comment by ChristopheSeguinot** [comment]
Hi, 
I can confirm that this bug occurs on both 3.8 and 3.9 versions running under Ubuntu 18.04. It occurs on all my .grc files like the one attached. Every time I disable a block, it is removed from the graph and its connections as well. I never succeeded in correctly disabling a block.
Question: is this issue only related to Ubuntu or Linux? 
I can provide more information on my config if needed.  
Regards , Christophe 

[test_disabling_a_block.py.zip](https://github.com/gnuradio/gnuradio/files/4116129/test_disabling_a_block.py.zip)

**Comment by ChristopheSeguinot** [comment]
I discovered that this bug: 

- does not affect gnuradio 3.8 obtained from debian repository (https://wiki.gnuradio.org/index.php/InstallingGR#Ubuntu_PPA_Installation)
- affect GNURadio 3.8 and 3.9 build from source
did not had time to investigate further...

**Comment by velichkov** [comment]
Hi @ChristopheSeguinot,

> It occurs on all my .grc files like the one attached.
> test_disabling_a_block.py.zip

The attached archive contains only the python file. Can you attach one of the grc files that you've used to reproduce this issue?

I'm not able to reproduce it with both 3.8 and 3.9 compiled from source on Fedora 29 with QT 5.11.3. I've tested with several of the example flowgraphs in the gnuradio's repository, disabling several blocks and it works like expected without removing the disabled block nor its connections.

**Comment by ChristopheSeguinot** [comment]
Hi 
It really seems that this is related to my installation (I was using gnuradio 3.7 before and may be I made a mistake while removing older package ...). Here is the correct grc file. 
[test_disabling_a_block.grc.zip](https://github.com/gnuradio/gnuradio/files/4158281/test_disabling_a_block.grc.zip)

**Comment by aru31** [comment]
Hi,
I also face this bug occasionally, on disabling (pressing d) or bypassing (pressing b), the block gets completely removed.

**Comment by velichkov** [comment]
Hi @ChristopheSeguinot, @aru31,

It turns out there is a View -> "Hide Disabled Blocks" (Ctrl + D) setting. This setting has been added in gnuradio 3.7.5 (ab10b5bc162)

Can you check whether this is enabled on your system and try disabling it?

**Comment by aru31** [comment]
Hi @velichkov 
You are right, it was because of the "Hide Disabled Blocks" setting.
Thanks. :)
