### ISSUE TITLE
Windows MME Audio Source not working

### ISSUE THREAD

**Issue by dbnut** [gnuradio/gnuradio#3121]
Hi, sorry if this has been dealt with before...
The latest 3.7 Windows installer still seems to have only a mono Audio Source.
It works OK in mono (as long as I supply an explicit MME device name), but complains about port index >0.

**Comment by marcusmueller** [comment]
Hi @dbnut,

Bad news:
it's very likely we'll not fix that: GNU Radio 3.7 is in "legacy" mode, and we have practically zero developers that use it on Windows.

Good news: It took me quite a bit of brains to fix the cascading issues needed to circumvent the limitations of the windowsmm audio source, but [I wrote it down a while ago](https://lists.gnu.org/archive/html/discuss-gnuradio/2019-05/msg00268.html).

This should fix your issue.
