### ISSUE TITLE
Icons missing from gnuradio-companion

### ISSUE THREAD

**Issue by jwanga** [gnuradio/gnuradio#3124]
After successfully building and installing gnuradio/maint-3.8 from source on MacOS Catalina. None of the application icons are visible in gnuradio-companion. I'm unsure how to further diagnose this:

![Screen Shot 2020-01-25 at 1 15 10 PM](https://user-images.githubusercontent.com/903165/73127690-24d8c480-3f79-11ea-8919-bbd38ca100ad.png)

**Comment by jwanga** [comment]
Problem solved. Needed to install GTK icon theme

`brew install adwaita-icon-theme`

**Comment by patrickBerry** [comment]
This also solved my issue thanks! 👍
