### ISSUE TITLE
The input boxes do not have different colors for different data types.

### ISSUE THREAD

**Issue by caoyuchencn** [gnuradio/gnuradio#3133]
![2020-01-28 20-51-54屏幕截图](https://user-images.githubusercontent.com/43954645/73265571-312a7f00-4210-11ea-90be-20e332d5f52b.png)

**Comment by devnulling** [comment]
I built the latest master and am not seeing this issue.

What version/commit of GR are you using? 

What OS?

**Comment by caoyuchencn** [comment]
maint3. 8 from ppa Ubuntu

**Comment by marcusmueller** [comment]
As the colors were often making it impossible to read on non-light color schemes, I'd say this is a bug, but a low-priority one.

**Comment by marcusmueller** [comment]
colorless boxes is now the correct behaviour, as per #6888
