### ISSUE TITLE
Pybombs setting incorrect python path

### ISSUE THREAD

**Issue by ghostop14** [gnuradio/gnuradio#3150]
When installing pybombs, setup_env.sh may include the wrong python path.  If installing on a system with python3.7, PYTHONPATH has python3.6.  Also, PYTHONPATH may not include python3, just python3.<minor ver>.

**Comment by duggabe** [comment]
In my case, GR was installed in ~/gr38/lib/python3/dist-packages, so the 3.6 vs 3.7 was not a factor.
See https://pastebin.com/NAp4mH3Y for what I did.

**Comment by mormj** [comment]
I believe this is covered in the pybombs github issues https://github.com/gnuradio/pybombs/issues/570  Closing in favor of having the issue logged in the pybombs github.  Please re-open if you think it belongs here.
