### ISSUE TITLE
For GNU 3.8 and beyond.  What was 'message_source.h' replaced with?

### ISSUE THREAD

**Issue by mwk088** [gnuradio/gnuradio#3181]
I currently have c++ code which uses various gnuradio blocks and I noticed that a header file I used to include, **message_source.h**, is no longer available.  Is there an equivalent header file which has replaced it?

Thank you
Mark

**Comment by marcusmueller** [comment]
Not an issue for a bug tracker, but a question for discuss-gnuradio@gnu.org <discuss-gnuradio@gnu.org> . Please keep this issue tracker clean!

>What was 'message_source.h' replaced with?

with nothing. That functionality has long been deprecated and then removed.
