### ISSUE TITLE
backport #3184 to 3.8

### ISSUE THREAD

**Issue by marcusmueller** [gnuradio/gnuradio#3185]
#3184  is a good patch, but I'm nervous merging it straight to 3.8; let's have the patch sit on master till 2020-02-14 and then merge without questions asked if nothing broke on the way.

**Comment by nickoe** [comment]
#3184 is merged on maint-3.8 in a65d1d1c236f95e4a106db6431ff4d51021dc29c

Lets close this issue and be happy.
