### ISSUE TITLE
Comments break matlab code in gr_utils/octave

### ISSUE THREAD

**Issue by dmalmodovar** [gnuradio/gnuradio#3195]
The comments are made using "#" instead of "%" which causes the code to be nonfunctional in matlab. Octave can use either symbol so using "%" will only expand functionality and not remove it.

ex:
"# Copyright 2008 Free Software Foundation, Inc."
should be replaced with 
"% Copyright 2008 Free Software Foundation, Inc."

**Comment by marcusmueller** [comment]
Well, to be honest, this wasn't intended. But on the other hand, these _are_ octave scripts. The Matlab compatibility is kind of coincidental.

Could you quickly whip up a Pull Request that fixes these couple of lines, @dmalmodovar? For anything below 10 lines of code, we don't even need a CLA.
