### ISSUE TITLE
GRC: Error in FFT block for GNURadio 3.8

### ISSUE THREAD

**Issue by lunar-mosiur** [gnuradio/gnuradio#3196]
Problems in issue [#2158](https://github.com/gnuradio/gnuradio/issues/2158) comes back again in GR 3.8. This time it is occuring for CL-FFT blocks. 

Fixes in [#1925](https://github.com/gnuradio/gnuradio/pull/1925) is already implemented in GR 3.8. However still the problem exists like before.
![Selection_002](https://user-images.githubusercontent.com/9780881/74273005-49e96900-4cd5-11ea-873d-4d9ffeb04789.png)

**Comment by drmpeg** [comment]
That's an OOT block. You have to submit an issue to https://github.com/ghostop14/gr-clenabled

**Comment by devnulling** [comment]
Tagging @ghostop14 , but I'm going to close this issue.

**Comment by ghostop14** [comment]
Fixed in clenabled.  Just pushed an updated yml.  This crops up every once in a while when gr_modtool converted xml to yml going from 3.7 to 3.8, it ignored the real variable name and always wrote it as vlen.  Not sure if that's been fixed yet or not.
