### ISSUE TITLE
Replace NumPy FFT with GR interface

### ISSUE THREAD

**Issue by michaelld** [gnuradio/gnuradio#3235]
As noted in https://github.com/gnuradio/gnuradio/pull/3069 and maybe elsewhere, NumPy changed their FFT interface from 'fftpack' to 'pocketfft' starting in 1.17.1. GR Leads discussion today on this topic resulted in a decision to create a GR interface to NumPy FFT and then change all internal references to be `from gnuradio import fft` or the like; which would then internally do something like from https://github.com/gnuradio/gnuradio/pull/2755 . We don't want to make SciPy a configure-time requirement.

**Comment by nickoe** [comment]
With https://github.com/gnuradio/gnuradio/pull/3291 (master) and https://github.com/gnuradio/gnuradio/pull/3259 (maint-3.8) merged, which essentially included the proposal to use `numpy.fft` directly https://github.com/gnuradio/gnuradio/pull/3291/commits/d3cffa3580a5377c48c313d628c298c81cee7573#diff-aa15db7a96c16ff668fd14aa585dfb90R29 I think we can close this one.
