### ISSUE TITLE
Vector Source does not accept a list of lists

### ISSUE THREAD

**Issue by All3xJ** [gnuradio/gnuradio#3251]
![Schermata 2020-03-06 alle 19 15 45](https://user-images.githubusercontent.com/20903913/76110646-27e6bc00-5fdf-11ea-82f9-afb157d20c50.png)

![Schermata 2020-03-06 alle 19 11 08](https://user-images.githubusercontent.com/20903913/76110719-4e0c5c00-5fdf-11ea-9391-0a342029c213.png)

![Schermata 2020-03-06 alle 19 13 29](https://user-images.githubusercontent.com/20903913/76110686-3df47c80-5fdf-11ea-90f6-17221eb4b396.png)

I am using "**Vector Source**" block. As you know, it's used with a **list of ints**. Of course, if I try to use more than a list, so if I use a list of lists, it gives me error:

```
Traceback (most recent call last):
  File "/Users/user/top_block.py", line 160, in <module>
    main()
  File "/Users/user/top_block.py", line 148, in main
    tb = top_block_cls()
  File "/Users/user/top_block.py", line 90, in __init__
    self.blocks_vector_source_x_0 = blocks.vector_source_c([x for x in sequence], True, 1, [])
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/gnuradio/blocks/blocks_swig1.py", line 1593, in make
    return _blocks_swig1.vector_source_c_make(*args, **kwargs)
TypeError: in method 'vector_source_c_make', argument 1 of type 'std::vector< gr_complex,std::allocator< gr_complex > > const &'

>>> Done (return code 1)


```

I also tried with:
![Schermata 2020-03-06 alle 19 12 37](https://user-images.githubusercontent.com/20903913/76110759-63818600-5fdf-11ea-91d9-3d12a5c21407.png)
But it doesn't work neither (same error of before)

Obviously if I write `sequence[0]` to select _only the first_ sequence, it works, and no errors:

![Schermata 2020-03-06 alle 19 13 06](https://user-images.githubusercontent.com/20903913/76110879-975cab80-5fdf-11ea-8dfe-695f59e52f1a.png)

**So my question is, how can I use more lists with "Vector Source" block?**

**Comment by velichkov** [comment]
Hi @All3xJ,

> [x for x in sequence] 

Try converting the list of lists to a list (e.g. flattening the list)
```
[item for sublist in sequence for item in sublist]
```

**Comment by dkozel** [comment]
I'm not sure if this is a useful feature to add. @All3xJ could you give some detail about why a list of lists was the natural answer here? I think Vasil's advice is the short term, and maybe long term, answer.

`[sample for sublist in [[0,1],[1,0],[1,1],[0,0]] for sample in sublist]`

**Comment by mormj** [comment]
Closing, as list of lists is not the desired functionality of the vector source, and would be inconsistent with the rest of the api
