### ISSUE TITLE
grc: Check for Python version is wrong and duplicate

### ISSUE THREAD

**Issue by noc0lour** [gnuradio/gnuradio#3264]
1. Python version check is already done in the toplevel GNU Radio CMakeLists and there should be no need to repeat it in the grc sub-tree (maybe just check if python is available & the check succeeded in the top-level cmakelists)

2. String comparison is just plain wrong as '3.6.10' < '3.6.5'. Python has built-in version check functions.

https://github.com/gnuradio/gnuradio/blob/master/grc/CMakeLists.txt#L15

**Comment by mbr0wn** [comment]
Fixed by https://github.com/gnuradio/gnuradio/pull/3284
