### ISSUE TITLE
gnuradio companion: “sources” branch does not appear in blocks menu in Ubuntu 18.04

### ISSUE THREAD

**Issue by Allasso** [gnuradio/gnuradio#3271]
Ubuntu 18.04.  

I have done the following:

```
sudo apt install gnuradio
sudo apt install gr-osmosdr
sudo apt install hackrf
sudo apt install libhackrf-dev
```

Following the gnuradio tutorial here:

https://greatscottgadgets.com/sdr/1/

After launching gnuradio companion, I am unable to add a source as "sources" does not appear in the blocks menu.

**Comment by Allasso** [comment]
Additional info, I am trying to use HackRF One device.  All appropriate lights are lit.  Tried resetting the device.

**Comment by drmpeg** [comment]
Take a look in the "(no module specified)" category.

**Comment by Allasso** [comment]
Thanks, there it is.  I set up companion on MacOS and it was in the Core list, so was looking for it there.
