### ISSUE TITLE
set_block_alias() not exposed for python blocks

### ISSUE THREAD

**Issue by jacobgilbert-snl** [gnuradio/gnuradio#3277]
Calling `set_block_alias()` on a python block fails as this is not exposed to python directly, as GRC expects it to be. Adding this to gnuradio-runtime/include/gnuradio/block_gateway.h seems to address this.

I'll get a PR together as soon as I can; documenting this for now.

**Comment by nickoe** [comment]
@jacobgilbert-snl Did you manage to throw together a PR?

**Comment by mrjacobagilbert** [comment]
No, I got pulled in another direction. Ill check back when I get time and do so if nobody has beat me to it.

**Comment by mrjacobagilbert** [comment]
addressed in https://github.com/gnuradio/gnuradio/pull/3318

in addition to set_block_alias() this exposes alias() and set_processor_affinity()

**Comment by mormj** [comment]
Closed with #3318
