### ISSUE TITLE
Tutorial incorrect fft size

### ISSUE THREAD

**Issue by hwpfeil** [gnuradio/gnuradio#3278]
QT GUI Frequency Sink image.
https://wiki.gnuradio.org/index.php/Guided_Tutorial_GRC and
https://wiki.gnuradio.org/index.php/Sample_Rate_Tutorial

Both show the same` FFT size: 1.024k` Of course that should be 1024k, not 1.024k.
![tutorial_two_3](https://user-images.githubusercontent.com/38633913/77454413-bb790480-6db5-11ea-8155-586659f1f725.png)

**Comment by dkozel** [comment]
@hwpfeil That value is correct. It isn't possible to have a 1024000 point FFT in GNU Radio and it isn't necessary here. 1.024k is 1024.

I hope the rest of the tutorial works for you.
