### ISSUE TITLE
blocks::rotator kernel is broken before volk 893d8981

### ISSUE THREAD

**Issue by jacobgilbert-snl** [gnuradio/gnuradio#3308]
There is a workaround here https://github.com/gnuradio/gnuradio/commit/0cec8b9c30548d40d09ff8c794d87b5b9de163e4 but this does not address other blocks using the blocks::rotator kernel.

This can be fixed by updating volk or by forcing generic kernels in the volk_config file:

`volk_32fc_s32fc_x2_rotator_32fc generic generic`

**Comment by jacobgilbert-snl** [comment]
Possibly redundant to https://github.com/gnuradio/gnuradio/pull/3062

**Comment by michaelld** [comment]
Not redundant.

**Comment by michaelld** [comment]
Fixed by #3311.

**Comment by michaelld** [comment]
It's a workaround, but it does work. Hopefully we'll deal with updating the Volk submodule & then the faster version of this will be used (automatically).
