### ISSUE TITLE
Error while building GNU Radio from master branch

### ISSUE THREAD

**Issue by alekhgupta1441** [gnuradio/gnuradio#3327]
I was building GNU Radio from master branch on Ubuntu 18.04 for testing.
Some changes in gr-digital may be causing this. 
    
                                      Error Log
![first](https://user-images.githubusercontent.com/43706342/78949160-6d1f7180-7ae8-11ea-80f2-c4532dab1870.jpg)
![secc](https://user-images.githubusercontent.com/43706342/78949168-701a6200-7ae8-11ea-97af-ee2564c18170.jpg)

**Comment by mormj** [comment]
This looks like a swig issue.  It happens when  the api is changed and cached swig-generated files are used as part of the compile.  Try a 'make clean' then make again.

**Comment by marcusmueller** [comment]
Agreeing with @mormj 100% here. Closing unless not solved by completely emptying the build directory.
