### ISSUE TITLE
remove remaining compile warnings in 3.9

### ISSUE THREAD

**Issue by japm48** [gnuradio/gnuradio#3349]
I thought it makes sense to gather this all in a global "tracking" issue (I know labels exist, but still...).

Here is the list of what I have ([build log](https://gist.github.com/japm48/4a77604329f6b8eb398cec000e8a5b99); I used ninja for an easier to parse output).

--------------

- [ ] cmake: `find_package_handle_standard_args` (PkgConfig)

```
  The package name passed to `find_package_handle_standard_args` (XYZ) does
  not match the name of the calling package (Xyz).  This can lead to
  problems in calling code that expects `find_package` result variables
  (e.g., `_FOUND`) to follow a certain pattern.
  [...]
```

Appears multiple times.
I don't know enough CMake to make a judgment here. I guess most people use `-Wno-dev` anyways. Apparently casing should match.

--------------

- [ ] cmake: `CheckIncludeFileCXX`

```
  Policy CMP0075 is not set: Include file check macros honor
  CMAKE_REQUIRED_LIBRARIES.  Run "cmake --help-policy CMP0075" for policy
  details.  Use the cmake_policy command to set the policy and suppress this
  warning.

  CMAKE_REQUIRED_LIBRARIES is set to:

    -lpthread

  For compatibility with CMake 3.11 and below this check is ignoring it.
Call Stack (most recent call first):
  gnuradio-runtime/lib/CMakeLists.txt:216 (check_include_file_cxx)
```

Ditto.
Documentation: https://cmake.org/cmake/help/v3.17/policy/CMP0075.html

--------------
- [x] tuntap: `strncpy` (PR: #3384)

```
gnuradio/gr-blocks/lib/tuntap_pdu_impl.cc:151:12: warning: ‘char* strncpy(char*, const char*, size_t)’ specified bound 16 equals destination size [-Wstringop-truncation]
  151 |     strncpy(ifr.ifr_name, dev, IFNAMSIZ);
      |     ~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

`strncpy` does not guarantee null termination in this case.
Trivial fix: replace with
```c++
strncpy(ifr.ifr_name, dev, IFNAMSIZ-1);
ifr.ifr_name[IFNAMSIZ-1] = '\0';
```
See also: https://godbolt.org/z/eppdz4; apparently the kernel already does this ([proof](https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/tree/drivers/net/tun.c?id=refs/tags/v5.6#n3084)).

--------------
- [x] Qt (PR: #3439)

### `QString::null`

`warning: ‘QString::null’ is deprecated: use QString()`

Trivial fix. `QString()` was already there in Qt4 ([context](https://lists.qt-project.org/pipermail/development/2018-January/031890.html)).

 ### `QFontMetrics::width`

In `gr-qtgui/lib/DisplayPlot.cc`/`edit_box_msg_impl.cc`
```
warning: ‘int QFontMetrics::width(const QString&, int) const’ is deprecated: Use QFontMetrics::horizontalAdvance [-Wdeprecated-declarations]
```
I'm not a fan of function renames 'just because'. Trivial fix.
New API introduced in Qt 5.11 ([source](https://doc.qt.io/qt-5/qfontmetrics.html#horizontalAdvance))

 ### `QPixmap::grabWidget`
```‘static QPixmap QPixmap::grabWidget(QObject*, int, int, int, int)’ is deprecated: Use QWidget::grab() instead```

This one makes more sense (static to member function). Trivial fix.

###  `QString::sprintf`

```‘QString& QString::sprintf(const char*, ...)’ is deprecated: Use asprintf(), arg() or QTextStream instead```

Qt [recommends](https://doc.qt.io/qt-5/qstring.html#arg-12) `arg()` chaining instead of `asprintf`, it also worked in Qt4.

--------------
 - [ ] Doxygen and latex noise.

This one needs a separate issue, and I feel most of it is just because of my setup.
Related: #2707.

Edit: I realized a big chunk was already solved in #3083.

--------------
- [x] swig-generated noise

Hopefully fixed by PyBind migration :smiley: (#3004).

But in particular: 
```
/usr/include/uhd/types/sensors.hpp:133: Warning 362: operator= ignored
/usr/include/uhd/types/dict.hpp:144: Warning 503: Can't wrap 'operator std::map<std::string,std::string>' unless renamed to a valid identifier.
```
Is there a way to force swig to ignore these?
Overloading `=` in Python would be... an interesting choice to say the least.

**Comment by mbr0wn** [comment]
We are now building 3.9
 with `-Werror` so I think we can close this.
