### ISSUE TITLE
PMT: Serialization using endian.h does not work on windows

### ISSUE THREAD

**Issue by mrjacobagilbert** [gnuradio/gnuradio#3366]
The move to speed up serialization using endian.h in #3320 appears to be broken on windows as endian.h does not exist.

**Comment by hcab14** [comment]
Maybe one of the following can help?
https://github.com/mikepb/endian.h
https://github.com/majn/tgl/blob/master/tl-parser/portable_endian.h
https://github.com/search?q=endian.h

I have no idea of how correct they are though.

**Comment by mrjacobagilbert** [comment]
im not much help here with anything windows unfortunately. i can submit a PR to revert that change, or modify that change so it just fixes the f32/c32 using f64/c64.

**Comment by citizenrich** [comment]
I’m also seeing this error on a build from master on Mac. Not using macports though. Do you see this on macports @michaelld ?

**Comment by mrjacobagilbert** [comment]
this will be moved to boost::endian soon; you should be able to revert without too much pain.

`git revert c1c56d2d149fa1663e0d41b7f50ad60f67258ce9`

sorry about that.

**Comment by mrjacobagilbert** [comment]
Solved in PR #3369 - backport updated also.

**Comment by michaelld** [comment]
Yes this is an issue for OSX too: https://github.com/gnuradio/gnuradio/issues/3401

**Comment by michaelld** [comment]
This is why we need -any- functional CI/QA for OSX and Windows for PRs. It doesn't have to be amazing; it just has to be sufficient.

**Comment by michaelld** [comment]
Closed by #3369 .
