### ISSUE TITLE
Add "Get Involved" shortcut to GRC's Help menu

### ISSUE THREAD

**Issue by dkozel** [gnuradio/gnuradio#3368]
Part of a larger set of changes/additions to encourage folks to contribute and get involved.

Should link to a new page at https://www.gnuradio.org/get-involved which summarizes and then link to https://wiki.gnuradio.org/index.php/Development

Inspired by KiCad.

**Comment by alekhgupta1441** [comment]
@dkozel  I will be glad to work on this issue. I have made a ![PR]([https://github.com/gnuradio/gnuradio/issues/3368) for the website. Although I am not a very creative guy. So, I will require your views for Get-Involved contents on website. I am making a PR for changing in GRC too.
