### ISSUE TITLE
'endian.h' file not found on MacOS 10.15.4 and Xcode 11.4.1

### ISSUE THREAD

**Issue by vermicelli** [gnuradio/gnuradio#3401]
I got the following error when I make the gnuradio on the newest release MacOS
`/.../gnuradio/gnuradio-runtime/lib/pmt/pmt_serialize.cc:17:10: fatal error: 'endian.h' file not found`

**Comment by michaelld** [comment]
Yup ... that's an issue with MacOS of any version! This is why we need -any- MacOS CI/QA up and running!

The commit is recent: https://github.com/gnuradio/gnuradio/commit/c1c56d2d149fa1663e0d41b7f50ad60f67258ce9

The fix is in this PR: https://github.com/gnuradio/gnuradio/pull/3369

**Comment by michaelld** [comment]
Closed by #3369 .
