### ISSUE TITLE
Log Power FFT

### ISSUE THREAD

**Issue by cclamb** [gnuradio/gnuradio#3438]
This generates an error:

Param - FFT Size(fft_size):
	Failed to eval ''part' if vlen == 1 else 'none'': name 'vlen' is not defined

This line in 

 -   id: fft_size                                                                                                     
     label: FFT Size                                                                                                  
     dtype: int                                                                                                       
     default: '1024'                                                                                                  
     hide: ${ 'part' if vlen == 1 else 'none' }    

is the cause, doesn't seem that the vlen variable exists.

**Comment by haakov** [comment]
Fixed in master (but not in maint-3.8): https://github.com/gnuradio/gnuradio/pull/3130

**Comment by dkozel** [comment]
@cclamb Thanks for posting the issue! @alekhgupta1441 has backported the fix and it's merged into maint-3.8 now.
