### ISSUE TITLE
QT GUI Range block is set for a vertical slider, but at run time it is horizontal

### ISSUE THREAD

**Issue by duggabe** [gnuradio/gnuradio#3449]
A QT GUI Range block is used in the reference flowgraph as a volume control. Even though the orientation is selected as 'vertical', the run time window has a horizontal slider. See FM_receive.grc: https://pastebin.com/xU9hS0Z1 and FM_receive.py: https://pastebin.com/YjE68pRT

**Comment by mormj** [comment]
@duggabe - looks like the vertical enum wasn't tied in anywhere for this.  I've got a fix and will push the PR tomorrow morning
