### ISSUE TITLE
CentOS gnuradio yum out of date

### ISSUE THREAD

**Issue by BanditSpark** [gnuradio/gnuradio#3460]
Yum's latest version of gnuradio is 3.7.11.

The installation site said to contact the package maintainer, but I couldn't find one for RHEL/CentOS.

**Comment by marcusmueller** [comment]
That maintainer would be the same as on fedora. However, we're on this! The situation looks much better now

A note, though: rhel/centos value proposition is stability. If you want bleeding edge versions of things, they're by design not the right choice.
