### ISSUE TITLE
DVB-T reciprocity issue

### ISSUE THREAD

**Issue by therman89** [gnuradio/gnuradio#3495]
Hi,
I have a recorded IQ stream, which can be demodulated with the dvb-t RX demo just fine. However, when I try to modulate and transmit the resulting MPEG-2 stream, the end result does not correlate with the original IQ stream. I narrowed down the possibilities and I think the "Demod reference signals" - "Reference Signals" blocks might be the problem. If I run the block diagram below, and I do a cross correlation on the input and the output, I see that they are not correlated. However, if I bypass the 2 blocks, I get the same output, as seen on the corresponding figure.

Block diagram with reference signal blocks bypassed:
![image](https://user-images.githubusercontent.com/10553343/82567671-f9a85f80-9b7d-11ea-8e7b-9c445494eef9.png)

Correlation with everything enabled:
![image](https://user-images.githubusercontent.com/10553343/82567836-396f4700-9b7e-11ea-801a-6955c7c31983.png)

Correlation of input and output when reference signals are skipped:
![image](https://user-images.githubusercontent.com/10553343/82567356-8b639d00-9b7d-11ea-96b8-3b977fbc44eb.png)

It might be possible that I'm doing something wrong or I misunderstand something in the working principle, but in my opinion the input and the output shall correlate with the whole chain enabled.
What am I missing?

**Comment by drmpeg** [comment]
It's probably just an alignment issue. The Demod Reference Signals block waits for a sync_start tag from the OFDM Symbol Acquisition block (indicating the beginning of a symbol). Before it receives that tag for the first time, it just discards the samples.

**Comment by therman89** [comment]
The correlator does not care about the alignment as it is a cross correlator, so every tick on the X axis is one sample shift. If you look at the X axis of the correlation, that shows that the symmetrical correlator takes 2^24(33,554,432 / 2) samples, which contains about 1638 symbols. I expect that from that many symbols there should be a correlation peak.

**Comment by drmpeg** [comment]
If you run the remodulated file back through the receiver flow again, does it decode to the same video/audio?

**Comment by therman89** [comment]
Good argument, because that produces seemingly the same MPEG-2 stream, but it is shorter, because of the syncing delay. And if I do this whole round again, so:
- demodulate &rarr; MPEG-2 stream
- modulate &rarr; 1st_remodulated_iq
- demodulate &rarr; bit shorter MPEG-2 stream
- modulate &rarr; 2nd_remodulated_iq

The 2 remodulated IQ streams correlate and the peak is at 2088960 sample offset.
![image](https://user-images.githubusercontent.com/10553343/82680543-b36e0180-9c4c-11ea-82a3-cf80f421fe46.png)

It is still a mistery to me, why it would not correlate with the original IQ stream, though...
For the record: The IQ file was recorded with a B200 Mini SDR and was resampled to match the DVB-T sampling frequency of 8/7*8MHz.

**Comment by drmpeg** [comment]
I think it's just a matter of small changes to the input of an inverse FFT can cause large changes in the output.

**Comment by dkozel** [comment]
This is an interesting discussion and it would be educational to see an example showing the effect on the correlation of small changes to the input of the second IFFT (maybe adding some noise?), but I don't think this is a bug or issue with the DVB implementation. I'm going to close the issue but *please* feel very welcome to ask for it to be reopened if you believe there is more investigation needed.

Herman, If you are not already on the chat channel or mailing list I hope you will join. This conversation would be fun to continue and I'd enjoy seeing the results of any further work you do on it.
https://wiki.gnuradio.org/index.php/IRC
https://wiki.gnuradio.org/index.php/MailingLists
