### ISSUE TITLE
OOT isn't working as it should be....

### ISSUE THREAD

**Issue by riatankarsahu** [gnuradio/gnuradio#3513]
Hi,
I am a new developer in this field. I was trying to create a very simple 'OOT' block by following the guideline of "QPSK" Demodulator. The block has been created, added to tree, and QA passed perfectly. And here the problem arises. Whenever I am pulling the block to the GNU Radio workspace, it's not showing up there. Being more precise nothing happens. Do any of you know how to solve this situation? Is it somehow related to "YAML" configuration? 
I am using GNU Radio version - 3.8
Python Version 3.9
Best Regards
-- Ritam

**Comment by dkozel** [comment]
Hi @riatankarsahu 

Yes, this could be an issue with the block description file for GRC, the YAML file. Without seeing exactly your code that's probably as much advice as we're able to give. Can you make a repository with your OOT and post a link to it?

OOTs are definitely working on the 3.8 branch (maint-3.8) so this discussion is probably better done interactively on https://chat.gnuradio.org, the #gnuradio-dev channel on the Freenode IRC server, or the discuss-gnuradio mailing list.
https://wiki.gnuradio.org/index.php/MailingLists

I'm going to close this issue and ask you to move to one of those places. If a code issue with GNU Radio is found we can definitely reopen this with the specific issue described.

Thanks and welcome to the project!
