### ISSUE TITLE
flow_graph.py.mako will not generate hier blocks

### ISSUE THREAD

**Issue by cclamb** [gnuradio/gnuradio#3527]
Fresh install via pybombs, version maint-3.8; Error: 

<>---<>
cclamb@muertos:~$ grcc sad_mean_hier.grc 
<<< Welcome to GNU Radio Companion Compiler 3.8.1.0 >>>

Block paths:
	/home/cclamb/.grc_gnuradio
	/home/cclamb/gnuradio/share/gnuradio/grc/blocks

>>> Loading: /home/cclamb/Work/Army/master_dev/gr-bc_spcom/examples/sad_mean_hier.grc
>>> Generating: /home/cclamb/.grc_gnuradio/sad_mean_hierarchical_block.py
>>> Generate Error: /home/cclamb/Work/Army/master_dev/gr-bc_spcom/examples/sad_mean_hier.grc: local variable 'python_version' referenced before assignment
Compilation error
<>---<<>

Current version on master works. Removing references to python_version eliminates the error as well.

**Comment by cclamb** [comment]
Seems this commit broke this: 

 d28f4f3c57d4c312f1ab4e7b77d7ceabe557f9fd

removing this commit fixes the problem.

**Comment by cclamb** [comment]
Also, removing this line:

% if python_version == 2:
from __future__ import print_function
% endif

and moving the import to the upper section under the first python version check fixes as well.

**Comment by willcode** [comment]
Fixed by PR above, closing.
