### ISSUE TITLE
QA failures on pybind branch

### ISSUE THREAD

**Issue by mormj** [gnuradio/gnuradio#3530]
The following tests FAILED:
- [ ] qa_uncaught_exception (Failed)
- [ ] qa_header_payload_demux (Failed)
- [ ] qa_uhd (Failed)
- [x] test_modtool (Failed)
- [x] qa_video_sdl (Failed)
- [x] qa_codec2_vocoder (Failed)
- [x] qa_gsm_full_rate (Failed)

These need to be fixed so the branch can pass qa after merging into master

**Comment by dkozel** [comment]
The pybind branch has been merged and there are other issues tracking the status of test failures.
