### ISSUE TITLE
cmake: Check for PyQtGraph as a runtime dependency of gr_filter_design

### ISSUE THREAD

**Issue by noc0lour** [gnuradio/gnuradio#3542]
As we do this for other Python runtime dependencies: Check if pyqtgraph is available and fail otherwise.

**Comment by mbr0wn** [comment]
We do this: https://github.com/gnuradio/gnuradio/blob/21a409fb7526609bd234c1e6c7f5bd2ddf0c6d74/gr-filter/python/filter/design/filter_design.py#L45-L48
