### ISSUE TITLE
macOS Mojave rendering artifacts and assertion crashes

### ISSUE THREAD

**Issue by ageorgo** [gnuradio/gnuradio#3549]
Storing the context in `self._current_cr` between draws seems to be causing rendering artifacts and crashes on macOS.

https://github.com/gnuradio/gnuradio/blob/5a2983534fa1faac49528aa41c6cacad806a70d8/grc/gui/canvas/connection.py#L131

**Comment by luzpaz** [comment]
Needs `macos` label

**Comment by marcusmueller** [comment]
Hi @ageorgo, we've never gotten around to asking you which version of GNU Radio this is, or how you've installed it. I'm adding the "needs clarification" tag – if this is solved for you (or just obsolete), we'll probably close this issue.
