### ISSUE TITLE
nothing provides libcodec2.so.0.9()(64bit) (updating)

### ISSUE THREAD

**Issue by bichomen** [gnuradio/gnuradio#3550]
The problem updating:

Problema 1: cannot install the best update candidate for package gnuradio-3.8.1.0-1.fc32.x86_64
  - nothing provides libcodec2.so.0.9()(64bit) needed by gnuradio-3.8.1.0-3.fc32.x86_64
 Problema 2: cannot install the best update candidate for package python3-gnuradio-3.8.1.0-1.fc32.x86_64
  - nothing provides libcodec2.so.0.9()(64bit) needed by python3-gnuradio-3.8.1.0-3.fc32.x86_64

I'm used Fedora32 64bits

**Comment by noc0lour** [comment]
Hm, this seems more suitable for the Fedora bugtracker at https://bugzilla.redhat.com
