### ISSUE TITLE
Python3 collections DeprecationWarning

### ISSUE THREAD

**Issue by duggabe** [gnuradio/gnuradio#3559]
`pyparsing.py` produces the following errors:
<pre>
/usr/lib/python3/dist-packages/pyparsing.py:943: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated since Python 3.3,and in 3.9 it will stop working
  collections.MutableMapping.register(ParseResults)
/usr/lib/python3/dist-packages/pyparsing.py:3245: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated since Python 3.3,and in 3.9 it will stop working
  elif isinstance( exprs, collections.Iterable ):
</pre>

**Comment by ptmcg** [comment]
This was fixed in pyparsing 2.2.1, in Sept 2018. Please update to the latest released version 2.4.7.

**Comment by duggabe** [comment]
I am using GR, GRC 3.8.1.0
Shouldn't that fix be included? How can I determine what version of pyparsing.py I have?

**Comment by ptmcg** [comment]
To get the pyparsing version, open a python interpreter session in a console window, and enter:
```
from pyparsing import __version__ as pp_version
print(pp_version)
```

From your error message, it looks like pyparsing is just coming from your global `dist-packages`, so you can update it using `pip3 install -U pyparsing`. If that introduces incompatible API changes, you can name a specific version in the pip command, using `pip3 install -U pyparsing==2.2.1`.

**Comment by duggabe** [comment]
That fixed it. So I guess that was an Ubuntu issue. I am running 19.10, so I'm surprised that it didn't have a later version. I had 2.2.0; updated to 2.4.7
