### ISSUE TITLE
OOT block input vector length is 64

### ISSUE THREAD

**Issue by pikachupikaqiu** [gnuradio/gnuradio#3564]
How to modify the corresponding code in *.cc file if the input vector length is 64?  
![q1](https://user-images.githubusercontent.com/55220316/84418785-09035180-abee-11ea-8344-8f83d05f816e.png)

**Comment by dkozel** [comment]
Hello @pikachupikaqiu 

The issue tracker isn't a good place to ask questions about writing an application, I recommend joining the chat channel for that. Please describe what issue you're facing, what isn't working, and what you have tried.
https://wiki.gnuradio.org/index.php/Chat
