### ISSUE TITLE
runtime/blocks (?): tag propagation anomalies when selectively dropping data

### ISSUE THREAD

**Issue by mrjacobagilbert** [gnuradio/gnuradio#3569]
While debugging a simple block, we noticed some unusual tag propagation behavior when dropping large amounts of data. This can be demonstrated using the in-tree selector block as follows:

![image](https://user-images.githubusercontent.com/7121282/84568097-62789700-ad3a-11ea-8c8a-dc7ce9070547.png)

Initially, the tags are correct:

![image](https://user-images.githubusercontent.com/7121282/84568183-ee8abe80-ad3a-11ea-836a-1319e3c8e80e.png)

However, by selecting and deselecting the `Enabled` check box a couple times, its clear the tag propagation has some errors:

![image](https://user-images.githubusercontent.com/7121282/84568263-5d681780-ad3b-11ea-826a-a966adc0cc59.png)

This example was put together with only in-tree blocks, but using the `tag_uhd_offset_f` block from gr-timing_utils, its possible to see that old tags remain in the output buffer with newer data (runtime does not account for the updated tag placement in the output buffer now that some data has been dropped?).

We attributed this to a runtime issue, as it appears that runtime appears to have sufficient information to propagate tags correctly (consuming X samples, producing 0 samples), though this is a bit of a special case of `general_work()` and propagation can also be fixed in the block directly via manual tag propagation in the selector block.

Regardless, tags should propagate correctly through this block. Thoughts on the correct approach?

This affects 3.7 (after the new selector was added), 3.8, and master. Flowgraph is here: [tagpropagation.zip](https://github.com/gnuradio/gnuradio/files/4774544/tagpropagation.zip)

**Comment by jacobgilbert-snl** [comment]
I now think runtime is behaving as expected, and tag offsets need to be modified manually based on how many samples have been dropped on each output stream.

This gets more complicated if the input streams can be at different rates, however it does not appear this block will function under those conditions.

I’ll get a PR together.

**Comment by rear1019** [comment]
This reminds me of an issue concerning tag propagation I have been hit with twice some time ago. I remember tracking it down to a (IMO) questionable behavior in tag propagation, but I never got around to reporting the error… The code in `selector_impl.cc` is probably affected: It boils down to the fact that tags are forwarded even if the following conditions apply:
* `general_work()` consumes *all* input items
* `general_work()` produces *no* output items, i.e. either `return 0` or `produce(output_index, 0) + return  WORK_CALLED_PRODUCE` is executed.

These conditions can occur in the selector block.

I’ll try to come up with code to test this.

**Comment by rear1019** [comment]
Follow-up: I should have read the first comment more carefully:
> […] its possible to see that old tags remain in the output buffer with newer data (runtime does not account for the updated tag placement in the output buffer now that some data has been dropped?).

Yes, that’s exactly what happens. 

> We attributed this to a runtime issue, as it appears that runtime appears to have sufficient information to propagate tags correctly (consuming X samples, producing 0 samples), though this is a bit of a special case of general_work() and propagation can also be fixed in the block directly via manual tag propagation in the selector block.

Manual tag propagation (accounting for dropped samples) does solve the issue. However, this is a runtime issue (in my opinion).

**Comment by mrjacobagilbert** [comment]
For now, this has been resolved by manual tag propagation with offsets adjusted to compensate for dropped data.

I go back and forth on whether or not runtime can solve this effectively for general blocks... this is a specific case so its easy to define the desired behavior here but I am not sure in general. Either way TPP_ALL_TO_ALL makes no sense for a block like the selector.
