### ISSUE TITLE
gr-meidiatools and gr-mapper installed failed.No package 'gmp' found

### ISSUE THREAD

**Issue by zkmartin** [gnuradio/gnuradio#3570]
I installed gnuradio using following commands:
sudo apt-get install python-pip
pip install --upgrade pip
pip install git+https://github.com/gnuradio/pybombs.git
pybombs recipes add gr-recipes git+https://github.com/gnuradio/gr-recipes.git
pybombs recipes add gr-etcetera git+https://github.com/gnuradio/gr-etcetera.git
pybombs prefix init /usr/local -a myprefix -R gnuradio-stable
pybombs install osmo-sdr rtl-sdr gnuradio dump1090 hackrf bladeRF airspy gr-iqbal libosmo-dsp gr-osmosdr gqrx
pybombs install gr-mediatools
pybombs install gr-mapper

pybombs install dump1090 makefile dose not find.

And pybombs install gr-mediatools failed.
-- Checking for module 'gmp'
--   No package 'gmp' found
-- Checking for module 'mpir >= 3.0'
--   No package 'mpir' found
 GnuRadio Runtime required to compile mediatools
And I installed the gmp and mpir with the package from official website using the following commands:
$tar -jvxf gmp-6.1.2.tar.bz2
$cd gmp-6.1.2
$./configure --enable-cxx
$make
$make check
$sudo make install

But the report still shows that no package ‘gmp found  and  no package ‘mpir’ found。
What should I do with this？’
Thanks a lot！

**Comment by noc0lour** [comment]
I've already posted an answer at the same issue in `gr-recipes`, pleas don't double post. Also your issue seems to be an installation issue, you will get better & faster help in our chat at https://chat.gnuradio.org and on the mailinglist discuss-gnuradio@gnu.org
