### ISSUE TITLE
Replace wavfile_sink/_source with more capable alternative

### ISSUE THREAD

**Issue by marcusmueller** [gnuradio/gnuradio#3577]
WAV is actually just a container, and the types of contained formats that our wavfile source reads is pretty restricted.

I'd propose a libsndfile-based audio file source and sink. Since 2009, libsndfile can also read and write FLAC and Vorbis files, and the ability to work with compressed audio is a frequenty requested feature.

As benign a dependency libsndfile is, it's still a new dependency.

If we add new blocks, we should deprecate the current wavfile blocks.

**Comment by drmpeg** [comment]
I have the source block working (with 24-bit 96K FLAC) already.

**Comment by marcusmueller** [comment]
> I have the source block working (with 24-bit 96K FLAC) already.

Hah! Awesome!
