### ISSUE TITLE
GrPybind.cmake style/formatting/...

### ISSUE THREAD

**Issue by skoslowski** [gnuradio/gnuradio#3586]
Some thought on GrPybind.cmake 
* (lots of trailing whitespace, indentation errors)
* these marcos should really be functions
* as this is gonna be used in OOTs, a proper API using `cmake_parse_arguments` would ensure future extensibility and improve readability

**Comment by marcusmueller** [comment]
should be dealt with using our current cmake-format infrastructure in af78fad
