### ISSUE TITLE
qtgui: number_sink not binded with pybind

### ISSUE THREAD

**Issue by mormj** [gnuradio/gnuradio#3607]
Running examples/analog/noise_power.grc throws the error

```
AttributeError: module 'gnuradio.qtgui' has no attribute 'number_sink'
```

**Comment by ekigwana** [comment]
I have tested this patch and it works with master

**Comment by drmpeg** [comment]
Fixed with https://github.com/gnuradio/gnuradio/commit/c2f42238032e2315371aaec8a64687d99028ccd2
