### ISSUE TITLE
gr_modtool newmod gives vague error messages 

### ISSUE THREAD

**Issue by ewhite42** [gnuradio/gnuradio#3616]
When I attempted to install an out of tree module using the command: **gr_modtool newmod gr-newname** (not the actual name, just an example), the exception "ModToolException: Invalid module name" was thrown. It was not clear to me until asking a member of the GR community that this error was a result of the fact that I had included "gr-" at the beginning of the name. Just thought it might be useful for the program to print a more informative error, specifying why the module name is invalid. Thanks so much for considering this, take care!

**Comment by fgerlits** [comment]
fixed in https://github.com/gnuradio/gnuradio/pull/4555
