### ISSUE TITLE
IP mesh network over GNU radio

### ISSUE THREAD

**Issue by roboticsai** [gnuradio/gnuradio#3628]
I am working in a dron project where we need a mesh network for multiple drones to communicate with each other. Right now we'r trying to implement this network with lora [sx1276](https://www.semtech.com/products/wireless-rf/lora-transceivers/sx1276) module and implement a gnu radio block i.e OOT block for this module. I want to ask how practical is it to use this radio module for this task?

**Comment by dkozel** [comment]
Hi @roboticsai

That sounds like a cool project. A gr-lora OOT module exists which could be a useful starting place for your work.

Discussions about applications though are best had in the chat room or mailing list. Please go to one of them, I look forward to chatting there!
https://chat.gnuradio.org
https://lists.gnu.org/mailman/listinfo/discuss-gnuradio
