### ISSUE TITLE
Configuration files should be stored following the XDG Base Directory Specification

### ISSUE THREAD

**Issue by Avamander** [gnuradio/gnuradio#3631]
For some reason gnuradio creates a folder `~/.gnuradio` and uses it for configuration. That's not in-line with [XDG Base Directory Specification](https://wiki.debian.org/XDGBaseDirectorySpecification) and clutters people's home directories.

gnuradio should follow XDG base directory specification and use `~/.config/gnuradio` for configuration files

**Comment by DC7IA** [comment]
> gnuradio should follow XDG base directory specification and use `~/.config/gnuradio` for configuration files

gnuradio should take the path from the appropriate variable

**Comment by DC7IA** [comment]
Here's the link to the spec, as you only linked to the Debian wiki: https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html

**Comment by ostrich** [comment]
Thanks @willcode. `gnuradio-config-info --userprefsdir` shows the value of $GR_PREFS_PATH but GNU Radio Companion is still creating grc.conf in ~/.gnuradio. Does GRC have support for a different environment variable?

**Comment by willcode** [comment]
GRC_PREFS_PATH. Please use chat or the mailing list for any further help. This github issue is about a specific feature request.

**Comment by marcusmueller** [comment]
still desirable, still sensible, still something worth doing in both 3.x and 4.x development
