### ISSUE TITLE
Weird toolbar scaling on GRC

### ISSUE THREAD

**Issue by ruilvo** [gnuradio/gnuradio#3635]
The toolbar on GRC is too large, and icons are inconsistent in size.

OS information: Manjaro KDE 20.0.3 fresh install, persistent after full update.
GNURadio installed from pacman, reproducible also with gnuradio-git from AUR.

What I did also:
This is a laptop with a small display, so I tried with 125% scaling on KDE, and text DPI only scaling. Neither affected the bug. 
Messing with DPI_SCALING in grc/gui/Constants.py didn't seem to have any effect. 

Screenshots:
Notice how the "printer" icon is larger than the others. The bar can't fit all icons.
![34NPWyd](https://user-images.githubusercontent.com/8402646/87139757-5e3b8d00-c298-11ea-8e5e-d9f5ec813b3e.png)
After reinstalled the OS the icons that got large changed seemingly arbitrary. 
![ujjZmaR](https://user-images.githubusercontent.com/8402646/87139767-609de700-c298-11ea-940e-1996d2e5696d.png)

**Comment by tanaxer01** [comment]
I was having the same issue, but after changing the icons to the ones used in GNOME the problem stopped

Before:
![image](https://user-images.githubusercontent.com/2672077/130815259-ab4ab8f9-3587-4291-bb2d-386ea57e0cf7.png)

After:
![image](https://user-images.githubusercontent.com/2672077/130815803-f983a4b4-2b56-4b48-b3dc-a13faea51c14.png)

After tinkering with different icon sets , I only saw this issue with the Breath2 icons

Hope it helps!

**Comment by marcusmueller** [comment]
I'm going to close this issue as solved – this seems to be a bug in the breath2 gnome icon theme.
