### ISSUE TITLE
No video output with module "video SDL sink"

### ISSUE THREAD

**Issue by MKesenheimer** [gnuradio/gnuradio#3669]
I can't get the video output of the module "video SDL sink" on macOS Catalina (10.15.6) to work.
I generated a flow graph which passes random values to the video SDL sink. However, no video is shown.

This is the flow graph I tested the issue with:
[video_sdl_test.zip](https://github.com/gnuradio/gnuradio/files/4974348/video_sdl_test.zip)

And this is the result (the colors of the screenshot are a bit off. But no worries, in reality the windows look a lot better).
![Screenshot 2020-07-24 at 23 40 04](https://user-images.githubusercontent.com/1159298/88437612-1f184a80-ce07-11ea-8e29-6f88ce346200.png)

gnuradio was installed with macports and has version number 3.8.1.0 (python 3.7.8). I tested the exact same flow graph on a linux machine and the video is displayed correctly.

**Comment by MKesenheimer** [comment]
With the update to  gnuradio 3.8.2.0 and Python 3.8.5, now a more meaningful error message is displayed:

```
Unable to obtain graphics context for NSWindow (Mojave behavior)
SDL screen_mode 32 bits-per-pixel
SDL overlay_mode 842094169 
```

Maybe someone can deal with this error message.

**Comment by MKesenheimer** [comment]
I may have the answer to this problem: The issue lies not in gnuradio per se but in the incompatibility of SDL and macOS Mojave and Catalina.
The solution would be to upgrade to SDL2.

**Comment by MKesenheimer** [comment]
I created a simple SDL2 program which reads data from a named pipe and displays the data as a video. Exactly how it is done with the SDL video sink of gnuradio, however this program relies on SDL2. This program is not part of gnuradio and can be used as a standalone program.

https://github.com/MKesenheimer/SDLDisplay

You have to create a named pipe (mkfifo </path/to/named/pipe>) and write the video data to the named pipe with the file sink block. More information can be found on my github page.

**Comment by michaelld** [comment]
@MKesenheimer thanks for the sleuthing work. I'm going to close this issue since it doesn't seem to be with GR per se. If anyone disagrees, please reopen and post info about what's going on.
