### ISSUE TITLE
Release artifacts for 3.8.1.0 missing on www.gnuradio.org/releases

### ISSUE THREAD

**Issue by SeekingMeaning** [gnuradio/gnuradio#3672]
Hi, it seems version 3.8.1.0 is not uploaded to https://www.gnuradio.org/releases/gnuradio/

**Comment by mohmmadd** [comment]
You can download from here:
https://github.com/gnuradio/gnuradio/releases/tag/v3.8.1.0

**Comment by dkozel** [comment]
@SeekingMeaning Thanks for pointing that out. We'll get the release artifacts copied over to there.
