### ISSUE TITLE
TypeError: __init__(): incompatible constructor arguments

### ISSUE THREAD

**Issue by ephraimon** [gnuradio/gnuradio#3706]
Can someone help with this:
```
TypeError: __init__(): incompatible constructor arguments. The following argument types are supported:
    1. gnuradio.qtgui.qtgui_python.freq_sink_c(fftsize: int, wintype: int, fc: float, bw: float, name: str, nconnections: int = 1, parent: gnuradio.qtgui.qtgui_python.QWidget = 0)

Invoked with: 1024, win_type.WIN_BLACKMAN_hARRIS, 0, 25000, '', 1
```
Is there a way I can change the win_type box to use numbers instead of choosing from the drop down list?

**Comment by marcusmueller** [comment]
Too little actual information on what was done to produce this error to help – but guessing this is from the time where we namespace-shifted the window functions
