### ISSUE TITLE
network: UDP header types not accessible in Python by name

### ISSUE THREAD

**Issue by ncorgan** [gnuradio/gnuradio#3708]
Since the UDP header types in gr-network ([here](https://github.com/gnuradio/gnuradio/blob/master/gr-network/include/gnuradio/network/udp_header_types.h)) are declared as ints rather than enums, there are no enums generated for the Python API. This leads to an inconsistent user experience in that in C++, the header type can be specified as `HEADERTYPE_SEQNUM`, but it must be specified as the literal `1` in Python.

**Comment by marcusmueller** [comment]
yeah let's fix that before it becomes a widespread API.

**Comment by marcusmueller** [comment]
still there, but widespread API now. Can't fix in GR 3.10, and low prio for (if ever existing) 3.11
