### ISSUE TITLE
gnuradio-companion 3.8.10 (Arch) (Python 3.8.5) buses behave strangely 

### ISSUE THREAD

**Issue by mwsltn** [gnuradio/gnuradio#3725]
I am trying to run the following flowgraph: 

![image](https://user-images.githubusercontent.com/605414/90984860-e1adf680-e545-11ea-9bba-e07eb9e2a515.png)

According to this document: http://www.trondeau.com/blog/2014/2/27/working-with-grc-busports.html I imagine I need to set the `bus_structure_source` to the value `[[0]]` but there doesn't seem to be a way to do so. 

Even with the 3 buses, I've tried enabling the source bus on a couple of variables and feeding them in, but no matter how I try and connect those to the 3 buses every connection to the last bus gets forced to the first bus connection: 

![image](https://user-images.githubusercontent.com/605414/90984969-a2cc7080-e546-11ea-83bb-a510405823f2.png)

**Comment by marcusmueller** [comment]
Buses recently fixed in #7079; other than that, well known that buses are still very strange!
