### ISSUE TITLE
Python crash with windows installer for 3.8

### ISSUE THREAD

**Issue by j1s1e1** [gnuradio/gnuradio#3755]
I tried the latest version of gnuradio from this link:
http://www.gcndevelopment.com/gnuradio/downloads/installers/v1.7.0/gnuradio_3.8.1.0_win64.msi
When I create a simple flow graph with the signal source, throttle, and time sink, and try to execute the flow graph, the python script crashes.  I added python debugging to the run script and found that it crashed here:

> c:\program files\gnuradio-3.8\lib\site-packages\gnuradio\qtgui\qtgui_swig.py(446)make()
-> def make(size, samp_rate, name, nconnections=1, parent=None):
(Pdb) s
> c:\program files\gnuradio-3.8\lib\site-packages\gnuradio\qtgui\qtgui_swig.py(469)make()
-> return _qtgui_swig.time_sink_c_make(size, samp_rate, name, nconnections, parent)
(Pdb) s

I wasn't sure where to go from there, so I tried a previous version:
http://www.gcndevelopment.com/gnuradio/downloads/installers/v1.2.0/gnuradio_3.7.11_win64.msi
which worked fine.

I can probably just use the earlier version, but I wanted to report it in case others have the same issue.  If there are steps I should try to correct this or generate more information, please let me know.

Thanks,

James

**Comment by dkozel** [comment]
Hello @j1s1e1 
Can you please post your issue to the repository for those installers? Geoff is certainly the expert in these scripts and the environment that they create.
https://github.com/gnieboer/GNURadio_Windows_Build_Scripts/issues

Thanks
