### ISSUE TITLE
Selector Block does not work when unused input has no data

### ISSUE THREAD

**Issue by heliochronix** [gnuradio/gnuradio#3762]
Hello all,

I'm running GR 3.8.1, and it seems the Selector block does not operate as one would expect it to. This simple Hier Block flowgraph I have is meant to select between one of 4 different modulation schemes and output the resulting modulation to the output pad. However, it seems the selector block does not output unless data is flowing into all input pads.

For example, I might have NBFM Transmit selected on the selector block, and one would expect that the modulated signal would then be passed to the output of the block regardless of the state of unused inputs. However, nothing gets through the selector block until I start sending bytes to the data input as well. It seems like the selector block should pass the selected input regardless of data availability on the unused inputs, especially since all unused inputs are discarded anyway.

![image](https://user-images.githubusercontent.com/1733202/92771088-7179e000-f34f-11ea-9e0a-d1f98c7f6333.png)

**Comment by mormj** [comment]
I think this is a bug that can be easily remedied in the forecast function.  See #3763
