### ISSUE TITLE
mpsk_stage6.grc functions differently on Raspberry Pi 4 and x86 

### ISSUE THREAD

**Issue by guokr321** [gnuradio/gnuradio#3768]
Hello everybody,

Running environment:
    X86 OS: 
Linux ThinkPad-W541 5.4.0-47-generic #51~18.04.1-Ubuntu SMP Sat Sep 5 14:35:50 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux; DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=18.04
DISTRIB_CODENAME=bionic
DISTRIB_DESCRIPTION="Ubuntu 18.04.2 LTS"

Raspberry Pi 4 OS:
Linux raspberrypi 5.4.59-v7l+ #1338 SMP Fri Aug 28 11:55:37 BST 2020 armv7l GNU/Linux
Raspbian GNU/Linux 10 \n \l

gnuradio and uhd:
GRC 3.9.0.0-git
UHD_4.0.0.0

The attached flowgraph can run correctly on X86, but on Raspberry Pi 4  it runs wrong.

Would someone can help this？

[mpsk6a.zip](https://github.com/gnuradio/gnuradio/files/5229354/mpsk6a.zip)

**Comment by marcusmueller** [comment]
Suspect the same as #3882, please reopen if not actually just performance-issues.
