### ISSUE TITLE
packet_loopback_hier.grc in gr-digital/examples/packet

### ISSUE THREAD

**Issue by csylvain** [gnuradio/gnuradio#3775]
no PDUs pass the CRC32 check. "Message Debug" block produces no output unless its input is moved to "precrc" instead of "pkt_out". GR 3.8.1 in use.

ps: Message Debug block emits CRC32-checked blocks when "Repetition" Encoder and Decoder Definitions are used for the payload, but none when "CC" Encoder and Decoder Definitions are used. suspect some part of the full FEC 'CC' coding and decoding has an implementation error

**Comment by marcusmueller** [comment]
Can't reproduce; works on main.
