### ISSUE TITLE
make fails when module is Python only

### ISSUE THREAD

**Issue by ShaneFlandermeyer** [gnuradio/gnuradio#3782]
On the latest master build, make fails with the following error when trying to build Python-only OOT modules

[ 42%] Built target pygen_python_6b7f4
make[2]: *** No rule to make target '../python/bindings/gnuradio-dragon', needed by 'python/bindings/extracted_docstrings.json'.  Stop.
make[1]: *** [CMakeFiles/Makefile2:350: python/bindings/CMakeFiles/extracted_docstrings.dir/all] Error 2
make: *** [Makefile:141: all] Error 2

This error persists until a C++ block is added to the module. It seems like cmake doesn't have a way to handle not having any pybind11 bindings.

**Comment by drmpeg** [comment]
Confirmed here. @mormj
