### ISSUE TITLE
Packet Header Generator block does not accept Default Header Format Obj.

### ISSUE THREAD

**Issue by csylvain** [gnuradio/gnuradio#3827]
packet header generator does not appear to have proper prototype to accept a header format object. "Default Header Format Obj." block was used and Id set to 'pkt_hdr'. "Packet Header Generator" block was used and "Formatter Object" was set to 'pkt_hdr'.

error generated at runtime was:
`self.digital_packet_headergenerator_bb_0 = digital.packet_headergenerator_bb(pkt_hdr, "packet_len")
  File "/usr/lib/python3/dist-packages/gnuradio/digital/digital_swig2.py", line 2179, in make
    return _digital_swig2.packet_headergenerator_bb_make(*args)
TypeError: Wrong number or type of arguments for overloaded function 'packet_headergenerator_bb_make'.
  Possible C/C++ prototypes are:
    gr::digital::packet_headergenerator_bb::make(gr::digital::packet_header_default::sptr const &,std::string const &)
    gr::digital::packet_headergenerator_bb::make(long,std::string const &)
`

[GR 3.8.1.0]

**Comment by marcusmueller** [comment]
Can't reproduce; also, not using SWIG anymore, so, with a heavy heart, closing.

If this persists, don't hesitate to reopen!
