### ISSUE TITLE
Vocoder blocks don't show up in GRC

### ISSUE THREAD

**Issue by michael-roe** [gnuradio/gnuradio#3836]
The vocoder blocks don't show up in GRC. Some of them I can get to by searching for them by name (CVSD Encoder/Decoder, Alaw Encoder/Decoder, ulaw Encoder/Decoder) but some of them I can't access at all (e.g. CODEC2, which is the one I really wanted).

**Comment by drmpeg** [comment]
If you built from source, you have to have the CODEC2 dependency installed.

```sudo apt-get install libcodec2-dev```

**Comment by michael-roe** [comment]
I didn't have libcodec2-dev installed. But even after I installed it and rebuilt gnuradio, I stil don't see the biock,

I was using pybombs to build gnuradio. Any suggestions for what I should
do to force it to completely reconfigure and rebuild to pick up the new dependency?

**Comment by csylvain** [comment]
find the .yml file(s) for your blocks and make sure they've been installed in /usr/local/share/gnuradio/grc/blocks

**Comment by michael-roe** [comment]
Now that I have installed libcodec2-dev and recompiled from source (not using pybombs) I can see the codec2 block if I search for it by now.

However, none of the vocoder blocks appear in the block picker on the right hand side of the screen in gnuradio-companion. I think this is a bug.

**Comment by drmpeg** [comment]
Yes, it's a bug. The block tree file isn't being installed for gr-vocoder. The vocoder blocks are supposed to be in "Audio". Here's what it should look like:

![image](https://user-images.githubusercontent.com/5397196/96495875-57100d80-11fd-11eb-8571-3c036ee506e8.png)

I'll submit a pull request to fix it.
