### ISSUE TITLE
Missing plutosdr blocks

### ISSUE THREAD

**Issue by pablogarzon** [gnuradio/gnuradio#3873]
Can't find after reinstalling gr the plutosdr blocks, I've already tried with pybombs but the problems persist,
and if I look at the blocks folder, with:
 `$: ls ~/prefix-3.8/share/gnuradio/grc/blocks | grep pluto` 
I can't get any results if I search for Pluto

**Comment by dkozel** [comment]
Hi @pablogarzon. The Pluto blocks are included in gr-iio and not part of the main GNU Radio code. Do you have gr-iio installed?
https://wiki.analog.com/resources/tools-software/linux-software/gnuradio

Analog Devices provides help in their EngineeringZone forum, and I'd recommend joining the GNU Radio mailing list or chat channel to get quicker help. The GitHub issue tracker isn't good for this and it's much preferred to try and work through installation or usage questions on the chat or email.
https://wiki.gnuradio.org/index.php/Chat
https://wiki.gnuradio.org/index.php/MailingLists
