### ISSUE TITLE
Pybind: Module loading failures get masked in the init 

### ISSUE THREAD

**Issue by mormj** [gnuradio/gnuradio#3884]
If there is some linker error, or another issue with the pybind in an OOT, this gets masked because of 

```
except ImportError:
    pass
```
in `__init__.py`

There are some situations where the ImportErrors should be caught and ignored, such as a python only module (which is why the pass is there).  But in other situations, the underlying error should be displayed

**Comment by marcusmueller** [comment]
we really should get rid of this. When people port their modules to pybind/GR 3.9, we'll have loads of these errors, and the first time we'll always tell people is to remove these two lines.

**Comment by marcusmueller** [comment]
Proposal: special handling for "can't find the module" vs any other error:

* Any other error: gets bubbled up
* failure to find module: log and pass

Question is whether we can rely on GR logging facilities in `__init__.py`.
