### ISSUE TITLE
Osmocom Blocks not Available

### ISSUE THREAD

**Issue by KyyB** [gnuradio/gnuradio#3888]
Hi everyone,

I cannot seem to find the Osmocom source & other blocks related to osmocom. Why is that?

**Comment by willcode** [comment]
Please include GNU Radio version and other information. Are you trying to build/install the gr-osmosdr out-of-tree module?

**Comment by KyyB** [comment]
GNU Radio Companion 3.8.2.0 and osmocom block and source block were not part of the package

**Comment by dkozel** [comment]
Hi Kyyb. The Osmocom blocks aren't part of the main GNU Radio code. You need to install gr-osmosdr separately.
https://osmocom.org/projects/gr-osmosdr/wiki

I hope you're able to get it installed and running. The GNU Radio chat and mailing list are both good places to ask questions, and Osmocom have their own chat and mailing lists as well if you have questions about Osmocom blocks.
