### ISSUE TITLE
`wfm_rcv_pll` constructor has `audio_decimation` parameter, but doesn't use it

### ISSUE THREAD

**Issue by marcusmueller** [gnuradio/gnuradio#3921]
... and the docstring is inappropriate too, therefore.

Either fix by removing argument, or implement decimation.

Probably just replacing the `1` in 

```
        self.fft_filter_xxx_3 = filter.fft_filter_fff(1, stereo_carrier_filter_coeffs_0, 1)
```

with `audio_decimation` + writing a test case.

**Comment by marcusmueller** [comment]
Also, that flow graph could have used some more descriptive (and shorter) block naming!

**Comment by dave-pi** [comment]
`demod_rate` is also unused, effectively forcing the input sample rate to 3840000.
