### ISSUE TITLE
Add gtk.LinkButton to Documentation tab of GRC block properties

### ISSUE THREAD

**Issue by duggabe** [gnuradio/gnuradio#3931]
When a user has a GRC flowgraph open, clicks on a block, selects Properties, and selects the Documentation tab, it displays "Wiki Page for this Block:" with a URL. However, that link is not clickable.

I propose adding a gtk.LinkButton to the Documentation tab in addition to the SimpleTextDisplay. That link would contain the URL for the Wiki page and could be clicked.

For reference, see https://lists.gnu.org/archive/html/discuss-gnuradio/2020-11/msg00103.html

**Comment by willcode** [comment]
@duggabe I did a prototype of this using GtkLabel.

**Comment by duggabe** [comment]
fixed by https://github.com/gnuradio/gnuradio/pull/3933
