### ISSUE TITLE
QT GUI Toggle Switch is backwards

### ISSUE THREAD

**Issue by duggabe** [gnuradio/gnuradio#3939]
While testing the QT GUI Toggle Switch, I tried to replicate the similar and very familiar toggle switch used on an iPhone. However, the left / right orientation of the 'off' and 'on' seem to be backwards. See https://wiki.gnuradio.org/index.php/File:Test_toggleswitch2_out.png as an example. The flowgraph is in https://github.com/gnuradio/gnuradio/blob/master/gr-qtgui/examples/test_toggleswitch2.grc

**Comment by willcode** [comment]
The if/else is swapped here:
https://github.com/gnuradio/gnuradio/blob/b39c64d7efcf2a54f92dc4eacc67b52e4cd708a5/gr-qtgui/python/qtgui/toggleswitch.py#L138
