### ISSUE TITLE
QT GUI Frequency Sink Traces Map Color Wrong

### ISSUE THREAD

**Issue by MountainLogic** [gnuradio/gnuradio#3950]
Using https://wiki.gnuradio.org/index.php/QT_GUI_Frequency_Sink in 3.8.2.0 (Python 3.7.9) installed from Ports to a Mac running Catalina 10.15.7 (19H2). I am seeing a incorrect color mapping of the scope traces seen in the displayed output vs what is requested in the input with multiple inputs.

STEPS TO REPRODUCE:
<img width="300" alt="image" src="https://user-images.githubusercontent.com/13784198/99429679-2fc06500-28bd-11eb-926c-2d5895f54038.png">
Set Freq Sink to 3 inputs.  
Provide an input to the three input that are different
Set trace 1 to Red
Set trace 2 to Green
Set trace 3 to Blue
Set Legends to On (optional)
Run 

BUG:
<img width="463" alt="image" src="https://user-images.githubusercontent.com/13784198/99429593-11f30000-28bd-11eb-9729-9d22e198f354.png">
Observe in the legend and on the scope that trace 1 is teal when red was expected
Observe in the legend and on the scope that trace 2 is bright purple when green was expected
Observe in the legend and on the scope that trace 3 is dark purple when blue was expected

**Comment by MountainLogic** [comment]
Example flow:
<img width="1074" alt="image" src="https://user-images.githubusercontent.com/13784198/99430230-ede3ee80-28bd-11eb-83d6-268ad0ed945e.png">

**Comment by ChristopheSeg** [comment]
Could this behaviour be related to using gnuradio themes (may be projector.qss in this case) ?
I don't know how GNURadio handle/modify color in case some theme is used.

**Comment by marcusmueller** [comment]
Yep, there's a qss loaded which explicitly overloads these colors
