### ISSUE TITLE
grc: fix save prompt behaviour

### ISSUE THREAD

**Issue by japm48** [gnuradio/gnuradio#3957]
I just realized that my PR #3287 reversed the fix introduced in #3172, my apologies. The correct implementation should be a combination of both approaches.

To clarify, the desired behaviour is:
* If no change has been made in a new tab (including the initial one), the save prompt should not appear on close.
* But also, in that case, File->Save should not be greyed out and Ctrl-S should work, even if no changes have been made.

This should be pretty easy to achieve, but unfortunately I'm not able to create a patch and test it right now (my dev computer is in another country...).

**Comment by marcusmueller** [comment]
This seems to work now!
