### ISSUE TITLE
Virustotal.com detected 2 new trojans from Win10 GNUradio3.8.2.exe installer.

### ISSUE THREAD

**Issue by YalekW5435** [gnuradio/gnuradio#3984]
Microsoft defender antivirus detected one of them as Ymacco trojan horse, unknown if its a false positive:

![cap1](https://user-images.githubusercontent.com/23326973/101295041-19853500-37e9-11eb-85ee-8f71ca70505b.PNG)

**Comment by YalekW5435** [comment]
![cap2](https://user-images.githubusercontent.com/23326973/101295465-d5476400-37eb-11eb-8059-6d3e00d7381d.PNG)

The Microsoft defender antivirus detection.

System info can be provided if needed later on.

**Comment by Tails98** [comment]
Probably just a false positive!

**Comment by YalekW5435** [comment]
wheres the proof at that its a false positive?

**Comment by noc0lour** [comment]
This binary is neither distributed from a gnuradio.org domain nor via our releases page. In fact it can stem from various places. Please contact wherever you found this binary if you have doubts about its origin. In general, GNU Radio is FOSS, you are encouraged to request a copy of the source code if you got the binary code from someone else.

**Comment by YalekW5435** [comment]
thanks.
