### ISSUE TITLE
GRC seg.fault on clicking osmocom source block

### ISSUE THREAD

**Issue by huobb0** [gnuradio/gnuradio#4001]
GRC reproducibly crashes when I click on an output of an osmocomm Source box.

zed@dacookiemonsta-2 $~ gnuradio-companion                                                                 WARNING:gnuradio.grc.core.platform:Slow YAML loading (libyaml not available)
<<< Welcome to GNU Radio Companion 3.8.2.0 >>>

Block paths
	/usr/local/share/gnuradio/grc/blocks
2020-12-18 14:59:29.861 Python[57449:2530017] unlockFocus called too many times. Called on <GdkQuartzView: 0x7ffe12111760>.
[1]    57449 segmentation fault  gnuradio-companion

Using OSX 10.15.7 Catalina, GRC 3.8.2.0 (Python 3.9.1).

What am I missing here?

**Comment by nickoe** [comment]
As far as I can tell, you are missing information about how you got the build and a backtrace. :)
