### ISSUE TITLE
broken .yml for digital_constellation_block.yml

### ISSUE THREAD

**Issue by marcusmueller** [gnuradio/gnuradio#4007]
https://github.com/gnuradio/gnuradio/commit/947800c52f2fcb2b149cfd2809148afcfdb8b79a seems to have broken something, says @drmpeg

**Comment by drmpeg** [comment]
https://user-images.githubusercontent.com/5397196/102756987-7e7e7600-4325-11eb-934f-05959dee45e2.mp4

**Comment by drmpeg** [comment]
https://user-images.githubusercontent.com/5397196/102757261-e92fb180-4325-11eb-9523-b5b75ad03ff1.mp4
