### ISSUE TITLE
Broken PFB Channelizer flowgraph

### ISSUE THREAD

**Issue by mormj** [gnuradio/gnuradio#4015]
![image](https://user-images.githubusercontent.com/34754695/102778298-53654800-4360-11eb-9e60-fff5516b70f1.png)

Output from one of the channelizer channels in 3.9
![image](https://user-images.githubusercontent.com/34754695/102778360-6ed05300-4360-11eb-87f6-f6340d705793.png)

Output in 3.8 looks fine
![image](https://user-images.githubusercontent.com/34754695/102778404-81e32300-4360-11eb-8b78-1657c67dd632.png)

**Comment by drmpeg** [comment]
If you use custom taps (low-pass filter), it works okay.

**Comment by willcode** [comment]
Replacing the Hierarchical Polyphase Channelizer block with the Polyphase Channelizer block works. Why do we have both of these?

**Comment by mormj** [comment]
Not sure the reasoning there.

Taking the lazy approach in the background of trying different commits:
a56c3a7f4908133dc6ceb93ffd3b2f9e1dda8e0e - hosed
1d60888071 — good

**Comment by mormj** [comment]
572428babb6db488cc17bfe2ada63ffc23a50d63 appears to be the culprit

**Comment by willcode** [comment]
That's what caused the problem addressed in https://github.com/gnuradio/gnuradio/pull/4021 too.
