### ISSUE TITLE
Unable to send pmt done messages (d_pmt_done) on d_system_port

### ISSUE THREAD

**Issue by martynvdijke** [gnuradio/gnuradio#4020]
Hi,

I have an OOT block with only pmt messages ports going in and out of the block.
And upon completion, I want to terminate the thread in order for the entire flowgraph (consisting of more OOT blocks) to be completed and to exit in the end.

However, I can not get this to work with `d_system_port`, from my understanding the `d_system_port` defined in block.cc should be used for this case, by sending `d_pmt_done` on `d_system_port` i.e. just a normal message publication on the system port : `message_port_pub(d_system_port, d_pmt_done);` 
Doing this should inform all neighboring blocks in the `block::notify_msg_neighbors()` function to also set their work state as being done.

Yet this method does not seem to work, because the `d_system_port` is in block.cc defined as: 
`message_port_register_in(d_system_port) `
And from basic_block.cc, it's only possible to send pmt messages on outgoing pmt ports (`message_port_register_out`) and thus sending pmt messages on `d_system_port` will result in an run time error: 
`thread[thread-per-block[1]: <block data_source(14)>]: port does not exist`

I tried a local source version of gnuradio (3.8) and changing the `message_port_register_in(d_system_port) `
to `message_port_register_out(d_system_port) ` in block.cc , this however works fine for gnuradio itself (as far as I can see) but I ran into some troubles in one of my OOT modules, system handler not being defined on the right port), (it could be there are still bugs in my code).

So my question is 

1. Is this the right way to set a block with only pmt message ports going in and out of the block, to exit the thread, and setting the states of all neighboring blocks to be done?
2. Am I right to believe the definition of the d_system_port in block.cc is wrong and it should be an message_port_out ?

**Comment by willcode** [comment]
@martynvdijke this is a bit of a guess: `notify_msg_neighbors()` might do what you need.
