### ISSUE TITLE
Can GNU Radio used to decode 433Mhz Waveform?

### ISSUE THREAD

**Issue by GF-Huang** [gnuradio/gnuradio#4039]
I'm new to radio. 

I use a `raspberry pi 4`, a [mx-05v 433Mhz receiver](https://www.geekbuying.com/item/MX-05V-433MHZ-RF-Wireless-Receiver-Module-MX-FS-03V-Transmitter-Module-Kit-For-Arduino-Raspberry-Pi-AVR-ARM-344591.html) and [piscope](http://abyz.me.uk/rpi/pigpio/piscope.html) to record my RF remote control signals. Then I got the following waveform:

![image](https://user-images.githubusercontent.com/4510984/103529654-fe2d4880-4ec0-11eb-8149-08d42d5c0396.png)

then zoom in:

![image](https://user-images.githubusercontent.com/4510984/103529749-2f0d7d80-4ec1-11eb-9901-64fb0fd68370.png)

This software can export samples as `VCD (value change dump)` format.

Can GNU Radio read VCD format then decode the waveform? Can it tell me what encoding the waveform using?

**Comment by willcode** [comment]
Please try the mailing list or chat.gnuradio.org for general help. The issue tracker is used for bugs and feature requests.
