### ISSUE TITLE
GRC block doesn't disappear on disable as expected

### ISSUE THREAD

**Issue by mormj** [gnuradio/gnuradio#4075]
When the "Hide Disable Blocks" option is enabled, disabling a block causes the connections to disappear but not the block.  The block will then disappear when somewhere else on the canvas is clicked. 

This is on current master (tagged 3.10 but very close to 3.9).  This does not occur on 3.8

**Comment by nickoe** [comment]
Do you have a screenshot?

**Comment by haakov** [comment]
Bisected, found https://github.com/gnuradio/gnuradio/commit/b3cf5e471305a1921946c09df113ec43ae2fccf8

Suggested fix: https://github.com/gnuradio/gnuradio/pull/4079
