### ISSUE TITLE
Move from log4cpp (implement GREP 0013)

### ISSUE THREAD

**Issue by marcusmueller** [gnuradio/gnuradio#4134]
https://github.com/gnuradio/greps/blob/master/grep-0013-remove-log4cpp.md specifies we want to move away from log4cpp.

Hottest replacement candidate seems to be spdlog (which Marcus, Martin and others have worked with before, so not a blind guess). That depends on fmtlib, which in itself could replase `boost::format` in a lot of places, and as its contained in `std::format` (nearly completely) in C++20, one day become a zero-overhead-dependency.

**Comment by dkozel** [comment]
Putting a comment here to link log4cpp work/issues.

PR to remove log4cpp:
https://github.com/gnuradio/gnuradio/pull/4981

Issues:
https://github.com/gnuradio/gnuradio/issues/4681
