### ISSUE TITLE
Use pybind functionality enabled by c++14

### ISSUE THREAD

**Issue by mormj** [gnuradio/gnuradio#4137]
Since our pybind11 integrations were developed when master was still on c++11, we missed out on some of the syntactical niceties such as:

https://pybind11.readthedocs.io/en/stable/classes.html?highlight=overloaded#overloaded-methods

where
```c++
py::class_<Pet>(m, "Pet")
   .def(py::init<const std::string &, int>())
   .def("set", static_cast<void (Pet::*)(int)>(&Pet::set), "Set the pet's age")
   .def("set", static_cast<void (Pet::*)(const std::string &)>(&Pet::set), "Set the pet's name");
```
becomes
```
py::class_<Pet>(m, "Pet")
    .def("set", py::overload_cast<int>(&Pet::set), "Set the pet's age")
    .def("set", py::overload_cast<const std::string &>(&Pet::set), "Set the pet's name");
```

This can be done in the in-tree bindings, but more importantly should be updated in the modtool template and bindtool

**Comment by marcusmueller** [comment]
we're doing this here and there in the tree right now! :heart:
