### ISSUE TITLE
GNUradio3.7(from binary)+UHD4.0 in ubuntu 18.04 

### ISSUE THREAD

**Issue by CrisWu210** [gnuradio/gnuradio#4146]
Using apt-get install gnuradio, i installed the gnuradio 3.7. I found the uhd version is 3.10 in gnuradio-companion, which is quite old I think. From the https://github.com/EttusResearch/uhd, the lastest is uhd 4.0 and the oldest version is 3.11. 

Can I force  gnuradio-companion to use uhd 4.0?

I tried to make install uhd4.0 in "/usr" path and overrides the uhd files created by gnuradio 3.7, not work. 
I also tried to install GNURadio 3.7 from source, also failed during the make procedure.

**Comment by dkozel** [comment]
Hi @CrisWu210

No, it is not possible to change the version of UHD that the binary install of GNU Radio uses. The UHD version is fixed at compile time. Do you have a reason that UHD 3.10 will not work for you?

You should be able to compile GNU Radio from source. UHD 4.0 was released long after GNU Radio 3.7 so it is possible that the two can not be used together, but I would be surprised if UHD 3.15 would not work. You will have to build UHD from source or use Ettus Research's PPA and then build GNU Radio from source.

Best would be to use a newer GNU Radio, but I know that many out of tree modules have not been updated in many years so only work with GNU Radio 3.7. If you have the option, you could update to Ubuntu 20.04 which has UHD 3.15 and GNU Radio 3.8.1.0 in the main repositories.

The wiki has instructions on building GNU Radio from source and other options of installing.
https://wiki.gnuradio.org/index.php/InstallingGR

Ettus Research has some instructions that are three years old now, but may still be helpful.
https://kb.ettus.com/Building_and_Installing_the_USRP_Open-Source_Toolchain_(UHD_and_GNU_Radio)_on_Linux

If you have more questions or have further issues while installing I recommend joining the chat room at https://chat.gnuradio.org or the discuss-gnuradio mailing list. The Github issue tracker we try to keep for bugs in the code or new feature development.
