### ISSUE TITLE
uhd_packet_tx.grc doesn't work in gnuradio 3.8.2

### ISSUE THREAD

**Issue by seuliang** [gnuradio/gnuradio#4155]
I run the official example uhd_packet_tx.grc at digital/packet with USRP b210 by UHD 4.0.0. 
The output of gnuradio 3.8.2 is "U" and no signal received by uhd_poacket_rx.grc. 
How can i fix this problem.
should I use gnuradio 3.7 ?

**Comment by mohmmadd** [comment]
There is an unknown bug in the volk submodule which causes this problem.
you can solve it manually with https://github.com/qradiolink/qradiolink/issues/74

**Comment by seuliang** [comment]
Thank you for reply.
I changed the file and can receive signal now at receiver side, but still get U at tx side.

**Comment by mohmmadd** [comment]
Maybe it is for the sample rate is not matched with your SDR capability.

**Comment by seuliang** [comment]
I see. thank you!
