### ISSUE TITLE
How does Constellation Modulator block work

### ISSUE THREAD

**Issue by seuliang** [gnuradio/gnuradio#4162]
the wiki page says  Constellation Modulator block  is a Hierarchical block which i can't open it.
so I'd like to know how this block works.
![image](https://user-images.githubusercontent.com/10756488/106232253-81c32680-622e-11eb-9f28-6ac534f75f24.png)
for example, how can i get the same function that Constellation Modulator block in picture above with basic blocks in follow picture.
![image](https://user-images.githubusercontent.com/10756488/106232359-ccdd3980-622e-11eb-9877-27ad7027d5bc.png)

**Comment by dkozel** [comment]
Hi @seuliang 

The source code of the Constellation Modulator block is here:
https://github.com/gnuradio/gnuradio/blob/4849af9ad83bc16d21e2c63ab95bab1755289c2f/gr-digital/python/digital/generic_mod_demod.py#L67

The documentation page describes the blocks inside the Constellation Modulator. I hope that will answer your questions.
https://www.gnuradio.org/doc/doxygen/page_digital.html

If you have other questions about how specific blocks work or how to set them up I would like to invite you to join the chatroom where it is easier to ask and answer questions.
https://chat.gnuradio.org

**Comment by seuliang** [comment]
thank you @dkozel 
this is exactly what I want.

**Comment by seuliang** [comment]
hi, @dkozel 
I have read the source code of generic_mod_demod.py and used blocks that in class generic_mod(gr.hier_block2). 
The blocks like blow.
![image](https://user-images.githubusercontent.com/10756488/108404233-95284700-725a-11eb-9e5f-5d361f88dcc5.png)
However, I can't get right output. the real part of the block's output is 
![image](https://user-images.githubusercontent.com/10756488/108404692-1ed81480-725b-11eb-84f3-fd9a81a78753.png)

the right real part output of qpsk is
![image](https://user-images.githubusercontent.com/10756488/108405025-9017c780-725b-11eb-91a9-4f1ead992140.png)

Is there anything I missed?
