### ISSUE TITLE
Supported SDR Boards

### ISSUE THREAD

**Issue by ahmedshahein** [gnuradio/gnuradio#4170]
Hi,

May I ask which boards are supported with the 3.9 release?I have the ADALM Pluto which I have been using with the 3.7 release. However, I can't find it in the 3.9 release. What about the RTL-SDR or the Hacker One?

Regards.

**Comment by dkozel** [comment]
Hello,

The ADALM Pluto blocks are written by Analog Devices and live in the gr-iio out of tree module.
https://github.com/analogdevicesinc/gr-iio

There is work going on to update gr-iio to work with GNU Radio 3.9.
https://github.com/analogdevicesinc/gr-iio/pull/96

The RTL-SDR and HackRF blocks are included in gr-osmocom.
https://osmocom.org/projects/gr-osmosdr/wiki

It looks like the very latest code works with GNU Radio 3.9, but it usually takes the various code maintainers a few weeks to add support for the latest GNU Radio releases.

If you have more questions about specific support or changes in the releases I recommend joining the chat rooms.
https://chat.gnuradio.org
