### ISSUE TITLE
Can't install 3.8

### ISSUE THREAD

**Issue by ahmedshahein** [gnuradio/gnuradio#4172]
I have updated from 3.7 to 3.9, than I am reverting back to 3.8 as advised. For 3.7 and 3.9 I used sudo apt-get install gnuradio. However, for 3.8 I am installing it from the source. I have Ubuntu 18.04.
I am getting the following error when running the cmake command:

Scanning dependencies of target trellis_swig0
[ 90%] Building CXX object gr-trellis/swig/CMakeFiles/trellis_swig0.dir/CMakeFiles/trellis_swig0.dir/trellis_swig0PYTHON_wrap.cxx.o
/home/shahein/gnuradio/build/gr-trellis/swig/CMakeFiles/trellis_swig0.dir/trellis_swig0PYTHON_wrap.cxx: In function ‘PyObject* _wrap_constellation_base(PyObject*, PyObject*)’:
/home/shahein/gnuradio/build/gr-trellis/swig/CMakeFiles/trellis_swig0.dir/trellis_swig0PYTHON_wrap.cxx:6247:29: error: no match for ‘operator=’ (operand types are ‘SwigValueWrapper<std::shared_ptr<gr::digital::constellation> >’ and ‘gr::digital::constellation_sptr {aka boost::shared_ptr<gr::digital::constellation>}’)
       result = (arg1)->base();
                             ^
/home/shahein/gnuradio/build/gr-trellis/swig/CMakeFiles/trellis_swig0.dir/trellis_swig0PYTHON_wrap.cxx:32:21: note: candidate: SwigValueWrapper<T>& SwigValueWrapper<T>::operator=(const SwigValueWrapper<T>&) [with T = std::shared_ptr<gr::digital::constellation>]
   SwigValueWrapper& operator=(const SwigValueWrapper<T>& rhs);

**Comment by curtcorum** [comment]
@ahmedshahein 
It is hard to tell from the information you provide.
Also this looks like output from 'make' command.

`<pre>... wavelet_swig
... pygen_gr_wavelet_python_wavelet_301a9
... gnuradio-zeromq
... zeromq_swig_swig_doc
... _zeromq_swig_doc_tag
... zeromq_swig
... zeromq_swig_swig_compilation
... pygen_gr_zeromq_swig_98ce4
... pygen_gr_zeromq_python_zeromq_aba78
<font color="#8AE234"><b>curt@green</b></font>:<font color="#729FCF"><b>~/src/gnuradio/build</b></font>$ make trellis_swig
trellis_swig0                    trellis_swig0_swig_doc/          trellis_swig1_swig_doc           trellis_swig2_swig_compilation/  trellis_swig3_swig_compilation
trellis_swig0/                   trellis_swig1                    trellis_swig1_swig_doc/          trellis_swig2_swig_doc           trellis_swig3_swig_compilation/
trellis_swig0_swig_compilation   trellis_swig1/                   trellis_swig2                    trellis_swig2_swig_doc/          trellis_swig3_swig_doc
trellis_swig0_swig_compilation/  trellis_swig1_swig_compilation   trellis_swig2/                   trellis_swig3                    trellis_swig3_swig_doc/
trellis_swig0_swig_doc           trellis_swig1_swig_compilation/  trellis_swig2_swig_compilation   trellis_swig3/                   
<font color="#8AE234"><b>curt@green</b></font>:<font color="#729FCF"><b>~/src/gnuradio/build</b></font>$ make trellis_swig0
[  0%] Built target _pmt_swig_doc_tag
[  0%] Built target pmt_swig_swig_doc
[  0%] Built target pmt_swig_swig_compilation
[  7%] Built target volk_obj
[  7%] Built target volk
[ 10%] Built target gnuradio-pmt
[ 23%] Built target gnuradio-runtime
[ 23%] Built target pmt_swig
[ 26%] Built target _runtime_swig_doc_tag
[ 26%] Built target runtime_swig_swig_doc
[ 26%] Built target runtime_swig_swig_compilation
[ 26%] Built target runtime_swig
[ 26%] Built target _trellis_swig0_doc_tag
[ 26%] Built target trellis_swig0_swig_doc
[ 26%] Built target trellis_swig0_swig_compilation
[ 60%] Built target gnuradio-blocks
[ 63%] Built target gnuradio-fft
[ 71%] Built target gnuradio-filter
[ 76%] Built target gnuradio-analog
[ 92%] Built target gnuradio-digital
[ 97%] Built target gnuradio-trellis
[100%] Built target trellis_swig0
<font color="#8AE234"><b>curt@green</b></font>:<font color="#729FCF"><b>~/src/gnuradio/build</b></font>$ cmake ..
-- Build type not specified: defaulting to release.
-- Build type set to Release.
-- 
-- The build system will automatically enable all components.
-- Use -DENABLE_DEFAULT=OFF to disable components by default.
-- 
-- Configuring testing-support support...
--   Enabling testing-support support.
--   Override with -DENABLE_TESTING=ON/OFF
-- Extracting version information from git describe...
-- Compiler Version: cc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
Copyright (C) 2017 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
-- Compiler Flags: /usr/bin/cc:::-O3 -DNDEBUG  -fvisibility=hidden -Wsign-compare -Wall -Wno-uninitialized
/usr/bin/c++:::-O3 -DNDEBUG  -fvisibility=hidden -Wsign-compare -Wall -Wno-uninitialized
CMake Warning (dev) in CMakeLists.txt:
  A logical block opening on the line

    /home/curt/src/gnuradio/CMakeLists.txt:299 (if)

  closes on the line

    /home/curt/src/gnuradio/CMakeLists.txt:303 (endif)

  with mis-matching arguments.
This warning is for project developers.  Use -Wno-dev to suppress it.

-- ADDING PERF COUNTERS
-- Boost version: 1.65.1
-- Found the following Boost libraries:
--   date_time
--   program_options
--   filesystem
--   system
--   regex
--   thread
--   unit_test_framework
--   chrono
--   atomic
-- User set python executable /usr/bin/python3.6
-- Found PythonInterp: /usr/bin/python3.6 (found suitable version &quot;3.6.9&quot;, minimum required is &quot;2.7.6&quot;) 
-- Python checking for six - python 2 and 3 compatibility library - found
-- 
-- Checking for module SWIG
-- Found SWIG version 3.0.12.
-- 
-- Configuring python-support support...
--   Dependency PYTHONLIBS_FOUND = TRUE
--   Dependency SWIG_FOUND = TRUE
--   Dependency SWIG_VERSION_CHECK = TRUE
--   Dependency SIX_FOUND = TRUE
--   Enabling python-support support.
--   Override with -DENABLE_PYTHON=ON/OFF
-- 
-- Configuring VOLK support...
-- Build type set to Release.
-- Extracting version information from git describe...
-- 
-- Python checking for python &gt;= 2.7
-- Python checking for python &gt;= 2.7 - found
-- 
-- Python checking for mako &gt;= 0.4.2
-- Python checking for mako &gt;= 0.4.2 - found
-- 
-- Python checking for six - python 2 and 3 compatibility library
-- Python checking for six - python 2 and 3 compatibility library - found
-- Boost version: 1.65.1
-- Found the following Boost libraries:
--   filesystem
--   system
-- Checking for module &apos;orc-0.4 &gt; 0.4.11&apos;
--   No package &apos;orc-0.4&apos; found
-- orc files (missing: ORC_LIBRARY ORC_INCLUDE_DIR ORCC_EXECUTABLE) 
-- QA Testing is enabled.
--   Modify using: -DENABLE_TESTING=ON/OFF
-- System profiling is disabled.
--   Modify using: -DENABLE_PROFILING=ON/OFF
-- Compiler name: GNU
-- x86* CPU detected
-- Compiler doesn&apos;t support NEON, Overruled arch neon
-- Compiler doesn&apos;t support NEON, Overruled arch neonv7
-- Compiler doesn&apos;t support NEON, Overruled arch neonv8
-- ORC support not found, Overruled arch orc
-- CPU width is 64 bits, Overruled arch 32
-- Available architectures: generic;64;3dnow;abm;popcount;mmx;fma;sse;sse2;norc;sse3;ssse3;sse4_a;sse4_1;sse4_2;avx;avx2;avx512f;avx512cd
-- Available machines: generic;sse2_64_mmx;sse3_64_mmx;ssse3_64_mmx;sse4_a_64_mmx;sse4_1_64_mmx;sse4_2_64_mmx;avx_64_mmx;avx2_64_mmx;avx512f_64_mmx;avx512cd_64_mmx
-- BUILD TYPE = RELEASE
-- Base cflags = -O3 -DNDEBUG  -fvisibility=hidden -Wsign-compare -Wall -Wno-uninitialized -Wall
-- BUILD INFO ::: generic ::: GNU ::: -O3 -DNDEBUG  -fvisibility=hidden -Wsign-compare -Wall -Wno-uninitialized -Wall 
-- BUILD INFO ::: sse2_64_mmx ::: GNU ::: -O3 -DNDEBUG  -fvisibility=hidden -Wsign-compare -Wall -Wno-uninitialized -Wall -m64 -mmmx -msse -msse2
-- BUILD INFO ::: sse3_64_mmx ::: GNU ::: -O3 -DNDEBUG  -fvisibility=hidden -Wsign-compare -Wall -Wno-uninitialized -Wall -m64 -mmmx -msse -msse2 -msse3
-- BUILD INFO ::: ssse3_64_mmx ::: GNU ::: -O3 -DNDEBUG  -fvisibility=hidden -Wsign-compare -Wall -Wno-uninitialized -Wall -m64 -mmmx -msse -msse2 -msse3 -mssse3
-- BUILD INFO ::: sse4_a_64_mmx ::: GNU ::: -O3 -DNDEBUG  -fvisibility=hidden -Wsign-compare -Wall -Wno-uninitialized -Wall -m64 -mmmx -msse -msse2 -msse3 -msse4a -mpopcnt
-- BUILD INFO ::: sse4_1_64_mmx ::: GNU ::: -O3 -DNDEBUG  -fvisibility=hidden -Wsign-compare -Wall -Wno-uninitialized -Wall -m64 -mmmx -msse -msse2 -msse3 -mssse3 -msse4.1
-- BUILD INFO ::: sse4_2_64_mmx ::: GNU ::: -O3 -DNDEBUG  -fvisibility=hidden -Wsign-compare -Wall -Wno-uninitialized -Wall -m64 -mmmx -msse -msse2 -msse3 -mssse3 -msse4.1 -msse4.2 -mpopcnt
-- BUILD INFO ::: avx_64_mmx ::: GNU ::: -O3 -DNDEBUG  -fvisibility=hidden -Wsign-compare -Wall -Wno-uninitialized -Wall -m64 -mmmx -msse -msse2 -msse3 -mssse3 -msse4.1 -msse4.2 -mpopcnt -mavx
-- BUILD INFO ::: avx2_64_mmx ::: GNU ::: -O3 -DNDEBUG  -fvisibility=hidden -Wsign-compare -Wall -Wno-uninitialized -Wall -m64 -mmmx -msse -msse2 -msse3 -mssse3 -msse4.1 -msse4.2 -mpopcnt -mavx -mfma -mavx2
-- BUILD INFO ::: avx512f_64_mmx ::: GNU ::: -O3 -DNDEBUG  -fvisibility=hidden -Wsign-compare -Wall -Wno-uninitialized -Wall -m64 -mmmx -msse -msse2 -msse3 -mssse3 -msse4.1 -msse4.2 -mpopcnt -mavx -mfma -mavx2 -mavx512f
-- BUILD INFO ::: avx512cd_64_mmx ::: GNU ::: -O3 -DNDEBUG  -fvisibility=hidden -Wsign-compare -Wall -Wno-uninitialized -Wall -m64 -mmmx -msse -msse2 -msse3 -mssse3 -msse4.1 -msse4.2 -mpopcnt -mavx -mfma -mavx2 -mavx512f -mavx512cd
-- Compiler Version: cc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
Copyright (C) 2017 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
-- c flags:  -fvisibility=hidden -Wsign-compare -Wall -Wno-uninitialized -Wall;
-- asm flags:  
-- c flags:  -fvisibility=hidden -Wsign-compare -Wall -Wno-uninitialized -Wall;
-- asm flags:   
-- Did not find liborc and orcc, disabling orc support...
-- Loading version 2.0 into constants...
-- Using install prefix: /usr/local
-- 
-- Configuring volk support...
--   Enabling volk support.
--   Override with -DENABLE_VOLK=ON/OFF
--   Override with -DENABLE_INTERNAL_VOLK=ON/OFF
  Version 2.0.0 of VOLK was detected. Applying workaround for broken rotator kernel.
-- Checking for module &apos;gmp&apos;
--   No package &apos;gmp&apos; found
-- Checking for module &apos;mpir &gt;= 3.0&apos;
--   No package &apos;mpir&apos; found
-- Could NOT find MPIR (missing: MPIRXX_LIBRARY MPIR_LIBRARY MPIR_INCLUDE_DIR) 
-- Could NOT find Sphinx (missing: SPHINX_EXECUTABLE) 
-- 
-- Configuring doxygen support...
--   Dependency DOXYGEN_FOUND = YES
--   Enabling doxygen support.
--   Override with -DENABLE_DOXYGEN=ON/OFF
-- 
-- Configuring sphinx support...
--   Dependency SPHINX_FOUND = FALSE
--   Disabling sphinx support.
--   Override with -DENABLE_SPHINX=ON/OFF
-- Checking for module &apos;gmp&apos;
--   No package &apos;gmp&apos; found
-- Checking for module &apos;mpir &gt;= 3.0&apos;
--   No package &apos;mpir&apos; found
-- Could NOT find MPIR (missing: MPIRXX_LIBRARY MPIR_LIBRARY MPIR_INCLUDE_DIR) 
-- 
-- Configuring gnuradio-runtime support...
--   Dependency Boost_FOUND = 1
--   Dependency ENABLE_VOLK = ON
--   Dependency PYTHONINTERP_FOUND = TRUE
--   Dependency MPLIB_FOUND = TRUE
--   Dependency LOG4CPP_FOUND = TRUE
--   Enabling gnuradio-runtime support.
--   Override with -DENABLE_GNURADIO_RUNTIME=ON/OFF
-- 
-- Configuring gr-ctrlport support...
--   Dependency Boost_FOUND = 1
--   Dependency SWIG_FOUND = TRUE
--   Dependency SWIG_VERSION_CHECK = TRUE
--   Dependency ENABLE_GNURADIO_RUNTIME = ON
--   Enabling gr-ctrlport support.
--   Override with -DENABLE_GR_CTRLPORT=ON/OFF
-- Loading build date Mon, 01 Feb 2021 22:29:28 into constants...
-- Loading version v3.8.2.0-59-gd2129cff into constants...
-- Checking for module &apos;thrift&apos;
--   No package &apos;thrift&apos; found
-- Binary &apos;thrift&apos; not found.
-- TRY_SHM_VMCIRCBUF set to ON.
-- 
-- Python checking for python2 &gt;= 2.7.6 or python3 &gt;= 3.6.5 - found
-- Python checking for PyYAML &gt;= 3.10 - found
-- Python checking for mako &gt;= 0.9.1 - found
-- Python checking for pygobject &gt;= 2.28.6 - found
-- Python checking for Gtk (GI) &gt;= 3.10.8 - found
-- Python checking for Cairo (GI) &gt;= 1.0 - found
-- Python checking for PangoCairo (GI) &gt;= 1.0 - found
-- Python checking for numpy - found
-- 
-- Configuring gnuradio-companion support...
--   Dependency ENABLE_GNURADIO_RUNTIME = ON
--   Dependency ENABLE_PYTHON = ON
--   Dependency PYTHON_MIN_VER_FOUND = TRUE
--   Dependency PYYAML_FOUND = TRUE
--   Dependency MAKO_FOUND = TRUE
--   Dependency PYGI_FOUND = TRUE
--   Dependency GTK_GI_FOUND = TRUE
--   Dependency CAIRO_GI_FOUND = TRUE
--   Dependency PANGOCAIRO_GI_FOUND = TRUE
--   Dependency NUMPY_FOUND = TRUE
--   Enabling gnuradio-companion support.
--   Override with -DENABLE_GRC=ON/OFF
-- 
-- Configuring gr-blocks support...
--   Dependency Boost_FOUND = 1
--   Dependency ENABLE_VOLK = ON
--   Dependency ENABLE_GNURADIO_RUNTIME = ON
--   Enabling gr-blocks support.
--   Override with -DENABLE_GR_BLOCKS=ON/OFF
-- 
-- Configuring gr-fec support...
--   Dependency ENABLE_VOLK = ON
--   Dependency Boost_FOUND = 1
--   Dependency ENABLE_GNURADIO_RUNTIME = ON
--   Dependency ENABLE_GR_BLOCKS = ON
--   Enabling gr-fec support.
--   Override with -DENABLE_GR_FEC=ON/OFF
-- 
-- Configuring gr-fft support...
--   Dependency ENABLE_VOLK = ON
--   Dependency Boost_FOUND = 1
--   Dependency ENABLE_GNURADIO_RUNTIME = ON
--   Dependency ENABLE_GR_BLOCKS = ON
--   Dependency FFTW3f_FOUND = TRUE
--   Enabling gr-fft support.
--   Override with -DENABLE_GR_FFT=ON/OFF
-- 
-- Configuring gr-filter support...
--   Dependency ENABLE_VOLK = ON
--   Dependency Boost_FOUND = 1
--   Dependency ENABLE_GNURADIO_RUNTIME = ON
--   Dependency ENABLE_GR_FFT = ON
--   Dependency ENABLE_GR_BLOCKS = ON
--   Enabling gr-filter support.
--   Override with -DENABLE_GR_FILTER=ON/OFF
-- 
-- Configuring gr-analog support...
--   Dependency Boost_FOUND = 1
--   Dependency ENABLE_VOLK = ON
--   Dependency ENABLE_GNURADIO_RUNTIME = ON
--   Dependency ENABLE_GR_BLOCKS = ON
--   Dependency ENABLE_GR_FFT = ON
--   Dependency ENABLE_GR_FILTER = ON
--   Enabling gr-analog support.
--   Override with -DENABLE_GR_ANALOG=ON/OFF
-- 
-- Configuring gr-digital support...
--   Dependency Boost_FOUND = 1
--   Dependency ENABLE_VOLK = ON
--   Dependency ENABLE_GNURADIO_RUNTIME = ON
--   Dependency ENABLE_GR_FFT = ON
--   Dependency ENABLE_GR_FILTER = ON
--   Dependency ENABLE_GR_BLOCKS = ON
--   Dependency ENABLE_GR_ANALOG = ON
--   Enabling gr-digital support.
--   Override with -DENABLE_GR_DIGITAL=ON/OFF
-- 
-- Configuring gr-dtv support...
--   Dependency Boost_FOUND = 1
--   Dependency ENABLE_GNURADIO_RUNTIME = ON
--   Dependency ENABLE_GR_ANALOG = ON
--   Dependency ENABLE_GR_FILTER = ON
--   Dependency ENABLE_GR_FEC = ON
--   Dependency ENABLE_VOLK = ON
--   Enabling gr-dtv support.
--   Override with -DENABLE_GR_DTV=ON/OFF
-- 
-- Configuring gr-audio support...
--   Dependency Boost_FOUND = 1
--   Dependency ENABLE_GNURADIO_RUNTIME = ON
--   Enabling gr-audio support.
--   Override with -DENABLE_GR_AUDIO=ON/OFF
-- Found ALSA 1.1.3
-- Found jack: /usr/lib/x86_64-linux-gnu/libjack.so
-- 
-- Configuring gr-channels support...
--   Dependency ENABLE_VOLK = ON
--   Dependency Boost_FOUND = 1
--   Dependency ENABLE_GNURADIO_RUNTIME = ON
--   Dependency ENABLE_GR_BLOCKS = ON
--   Dependency ENABLE_GR_FFT = ON
--   Dependency ENABLE_GR_FILTER = ON
--   Dependency ENABLE_GR_ANALOG = ON
--   Enabling gr-channels support.
--   Override with -DENABLE_GR_CHANNELS=ON/OFF
-- Python checking for PyQt5 - found
-- Checking for module &apos;Qt5Qwt6&apos;
--   No package &apos;Qt5Qwt6&apos; found
-- QWT Version: 6.1.3
-- 
-- Configuring gr-qtgui support...
--   Dependency Boost_FOUND = 1
--   Dependency QT_FOUND = 1
--   Dependency QWT_FOUND = TRUE
--   Dependency ENABLE_VOLK = ON
--   Dependency ENABLE_GNURADIO_RUNTIME = ON
--   Dependency ENABLE_GR_FFT = ON
--   Dependency ENABLE_GR_FILTER = ON
--   Dependency PYTHONLIBS_FOUND = TRUE
--   Dependency PYQT5_FOUND = TRUE
--   Enabling gr-qtgui support.
--   Override with -DENABLE_GR_QTGUI=ON/OFF
-- 
-- Configuring gr-trellis support...
--   Dependency Boost_FOUND = 1
--   Dependency ENABLE_GNURADIO_RUNTIME = ON
--   Dependency ENABLE_GR_ANALOG = ON
--   Dependency ENABLE_GR_BLOCKS = ON
--   Dependency ENABLE_GR_DIGITAL = ON
--   Enabling gr-trellis support.
--   Override with -DENABLE_GR_TRELLIS=ON/OFF
-- 
-- Configuring gr-uhd support...
--   Dependency Boost_FOUND = 1
--   Dependency UHD_FOUND = TRUE
--   Dependency ENABLE_GNURADIO_RUNTIME = ON
--   Dependency ENABLE_GR_FILTER = ON
--   Dependency ENABLE_GR_BLOCKS = ON
--   Dependency ENABLE_GR_ANALOG = ON
--   Enabling gr-uhd support.
--   Override with -DENABLE_GR_UHD=ON/OFF
--   UHD Version: 3.15.0.0-62-g7a3f1516
-- Python checking for Mako &gt;= 0.4.2 - found
-- Python checking for click - found
-- Python checking for click-plugins - found
-- 
-- Configuring gr-utils support...
--   Dependency ENABLE_GNURADIO_RUNTIME = ON
--   Dependency ENABLE_PYTHON = ON
--   Dependency MAKO_FOUND = TRUE
--   Enabling gr-utils support.
--   Override with -DENABLE_GR_UTILS=ON/OFF
-- 
-- Configuring gr_modtool support...
--   Dependency ENABLE_GNURADIO_RUNTIME = ON
--   Dependency ENABLE_PYTHON = ON
--   Dependency CLICK_FOUND = TRUE
--   Dependency CLICK_PLUGINS_FOUND = TRUE
--   Enabling gr_modtool support.
--   Override with -DENABLE_GR_MODTOOL=ON/OFF
-- Could NOT find SDL (missing: SDL_LIBRARY SDL_INCLUDE_DIR) 
-- 
-- Configuring gr-video-sdl support...
--   Dependency SDL_FOUND = FALSE
--   Dependency Boost_FOUND = 1
--   Dependency ENABLE_GNURADIO_RUNTIME = ON
--   Disabling gr-video-sdl support.
--   Override with -DENABLE_GR_VIDEO_SDL=ON/OFF
-- 
-- Configuring gr-vocoder support...
--   Dependency Boost_FOUND = 1
--   Dependency ENABLE_GNURADIO_RUNTIME = ON
--   Dependency ENABLE_GR_FFT = ON
--   Dependency ENABLE_GR_BLOCKS = ON
--   Dependency ENABLE_GR_FILTER = ON
--   Dependency ENABLE_GR_ANALOG = ON
--   Enabling gr-vocoder support.
--   Override with -DENABLE_GR_VOCODER=ON/OFF
-- Could NOT find Codec2 (missing: LIBCODEC2_LIBRARIES LIBCODEC2_INCLUDE_DIRS) 
-- Could NOT find GSM (missing: LIBGSM_LIBRARIES LIBGSM_INCLUDE_DIRS) 
-- 
-- Configuring gr-wavelet support...
--   Dependency Boost_FOUND = 1
--   Dependency ENABLE_GNURADIO_RUNTIME = ON
--   Dependency ENABLE_GR_BLOCKS = ON
--   Dependency ENABLE_GR_ANALOG = ON
--   Dependency GSL_FOUND = TRUE
--   Enabling gr-wavelet support.
--   Override with -DENABLE_GR_WAVELET=ON/OFF
-- 
-- Configuring gr-zeromq support...
--   Dependency Boost_FOUND = 1
--   Dependency ENABLE_GNURADIO_RUNTIME = ON
--   Dependency ZEROMQ_FOUND = TRUE
--   Enabling gr-zeromq support.
--   Override with -DENABLE_GR_ZEROMQ=ON/OFF
-- 
-- ######################################################
-- # Gnuradio enabled components                         
-- ######################################################
--   * testing-support
--   * python-support
--   * volk
--   * doxygen
--   * gnuradio-runtime
--   * gr-ctrlport
--   * gnuradio-companion
--   * gr-blocks
--   * gr-fec
--   * gr-fft
--   * gr-filter
--   * gr-analog
--   * gr-digital
--   * gr-dtv
--   * gr-audio
--   * * alsa
--   * * oss
--   * * jack
--   * * portaudio
--   * gr-channels
--   * gr-qtgui
--   * gr-trellis
--   * gr-uhd
--   * gr-utils
--   * gr_modtool
--   * gr-vocoder
--   * gr-wavelet
--   * gr-zeromq
-- 
-- ######################################################
-- # Gnuradio disabled components                        
-- ######################################################
--   * sphinx
--   * gr-video-sdl
-- 
-- Using install prefix: /usr/local
-- Building for version: v3.8.2.0-59-gd2129cff / 3.8.2git
-- Configuring done
-- Generating done
-- Build files have been written to: /home/curt/src/gnuradio/build
</pre>`

**Comment by mbr0wn** [comment]
Please don't post support questions on this issue tracker.

**Comment by tkircher** [comment]
I'm having the same issue. It's not a support question, it's a bug in gnuradio that this doesn't build correctly.
