### ISSUE TITLE
Can't access the blocks which has accidentally moved beyond left or top boundary

### ISSUE THREAD

**Issue by surpscare** [gnuradio/gnuradio#4178]
The new interface has the ability to create flow graphs of unlimited size by adaptive canvas expanding. However, the canvas can't expand to the left or up, and there is no "overshoot protection" for blocks being moved beyond the left or top boundary. This leads to losing access to the block groups which have been moved too far because the screen can not scroll to them being visible. I want to delete and re-create them, but I can't select them from GUI. Is there any way to edit the GRC file correctly without breaking it? Also, boundary protection needs to be added.
![image](https://user-images.githubusercontent.com/63161216/106686740-893e5300-65d3-11eb-8ced-f30aace2028e.png)

**Comment by dkozel** [comment]
That's a bit funny. Thank you for the report. This seems like something that can be fixed pretty easily with a check for negative coordinates.

To manually edit the file search for all `coordinate: [7, 6]` parameters and make any negative values 0 or positive.

I don't have a running copy of GNU Radio right at the moment, but can you use Ctrl-a to select all the blocks and drag them?

**Comment by dkozel** [comment]
Looks like we can sanitize the coordinates here.
https://github.com/gnuradio/gnuradio/blob/master/grc/gui/canvas/block.py#L61

**Comment by 85ayush** [comment]
I would love to work on this issue, I am new to open source contribution, can you please guide me?

**Comment by jasonuher** [comment]
@85ayush the minimum viable solution would be to edit the linked section of code as described by @dkozel. You could add bounds checking on the coordinates and limiting their range prior to returning.  That is "if less than 0, set to 0".  This would have the effect that all infringing blocks would be clumped at the edges.  It's not ideal, but it's better than having to manually edit the *ML to find your blocks.
