### ISSUE TITLE
Errors trying to install 3.7 version

### ISSUE THREAD

**Issue by diegomm6** [gnuradio/gnuradio#4182]
Hi, I'm trying to install gnuradio version 3.7 cause i need to use a csi tool that requires this specific version (https://github.com/qiank10/gr-csitool). I have tried using PPA but i get the following error:   
```
Latest legacy 3.7 maintenance release of GNU Radio
More info: https://launchpad.net/~gnuradio/+archive/ubuntu/gnuradio-releases-3.7
Press [ENTER] to continue or Ctrl-c to cancel adding it.

Get:1 http://security.ubuntu.com/ubuntu focal-security InRelease [109 kB]
Hit:2 http://cl.archive.ubuntu.com/ubuntu focal InRelease                                           
Ign:3 http://ppa.launchpad.net/gnuradio/gnuradio-releases-3.7/ubuntu focal InRelease                
Get:4 http://cl.archive.ubuntu.com/ubuntu focal-updates InRelease [114 kB]                                                      
Hit:5 http://ppa.launchpad.net/myriadrf/drivers/ubuntu focal InRelease                                                                     
Hit:6 https://qgis.org/debian focal InRelease                                                                                              
Get:7 http://cl.archive.ubuntu.com/ubuntu focal-backports InRelease [101 kB]                   
Hit:8 http://ppa.launchpad.net/qbittorrent-team/qbittorrent-stable/ubuntu focal InRelease
Get:9 http://cl.archive.ubuntu.com/ubuntu focal-updates/main amd64 DEP-11 Metadata [264 kB]
Get:10 http://cl.archive.ubuntu.com/ubuntu focal-updates/universe amd64 DEP-11 Metadata [301 kB]
Err:11 http://ppa.launchpad.net/gnuradio/gnuradio-releases-3.7/ubuntu focal Release            
  404  Not Found [IP: 91.189.95.85 80]
Get:12 http://cl.archive.ubuntu.com/ubuntu focal-updates/multiverse amd64 DEP-11 Metadata [2.468 B]
Get:13 http://cl.archive.ubuntu.com/ubuntu focal-backports/universe amd64 DEP-11 Metadata [1.768 B]
Reading package lists... Done                                                  
N: Skipping acquire of configured file 'main/binary-i386/Packages' as repository 'https://qgis.org/debian focal InRelease' doesn't support architecture 'i386'
E: The repository 'http://ppa.launchpad.net/gnuradio/gnuradio-releases-3.7/ubuntu focal Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
```

Alternatively, I tried also installing from source code, but i keep getting the lpthreads error for which I couldn't find a solution.

I tried installing in Ubuntu 20.04 and Raspbian, but I couldn't get any result or find any solution.

I hope someone can help, it has been days I am trying to install it.

Thanks!

**Comment by dkozel** [comment]
Hello @diegomm6 

The PPA for GNU Radio 3.7 only has builds for Ubuntu 18.04 and 19.04 (now past end of life). That is why you see the error in your output.

Building GNU Radio 3.7 on newer operating systems such as Ubuntu 20.04 is becoming more difficult as some dependencies like Qt4 are not provided by default. There are some PPAs that supply Qt4 and I think there may be patches in some earlier versions of Debian or Ubuntu. Even bigger though is that Python 2 is unsupported.

The ideal fix here is for you or the original author to update the CSI tool out of tree modules to GNU Radio 3.8, or even to 3.9.
https://wiki.gnuradio.org/index.php/GNU_Radio_3.8_OOT_Module_Porting_Guide

If that isn't an option, then I'd look at using an older version of Ubuntu that has GNU Radio 3.7 in it's default repositories. That's probably the fastest, but does mean changing your entire OS. Whether that's easy or hard depends on your situation.

I suggest joining the GNU Radio chatroom where it is a bit easier to talk over setups and options.
https://chat.gnuradio.org
