### ISSUE TITLE
gnuradio 3.9.0.0 - not possible to build from source - Ubuntu 20.04

### ISSUE THREAD

**Issue by 76nic** [gnuradio/gnuradio#4193]
Hello,
I was trying to build gnuradio 3.9.0.0 from source on Ubuntu 20.04 but run into errors. I followed the instructions laid out on that site: https://wiki.gnuradio.org/index.php/InstallingGR#From_Source
Was someone able to build 3.9. on Ubuntu 20.04? If so, could you please post the instructions?
Many thanks!
Best regards,
76nic

**Comment by mbr0wn** [comment]
@76nic you can follow what our CI system is doing. See, e.g., https://github.com/gnuradio/gnuradio-docker/blob/master/ci/ci-ubuntu-20.04-3.9/Dockerfile, or https://github.com/gnuradio/gnuradio-buildbot/blob/public/worker/ubuntu-20.04.Dockerfile.
