### ISSUE TITLE
Set GRC default values

### ISSUE THREAD

**Issue by duggabe** [gnuradio/gnuradio#4202]
Currently the default values for 'show block comments' and 'snap to grid' are both set to OFF. Often, tutorials and example flowgraphs have valuable information in the 'Comments' field which only shows up if 'show block comments' is enabled. Many beginning users are not aware of this.

Even though 'snap to grid' is not essential, it makes much nicer looking flowgraphs.

I request enabling both items as default values.

**Comment by drmpeg** [comment]
Already been done on master. Commit https://github.com/gnuradio/gnuradio/commit/be21c29995a7cfdee731cc4cf1daa715d0caac11 (and https://github.com/gnuradio/gnuradio/commit/306d889f1b2cd39567bb5c2b50a34fb7230173c7) needs to be backported.
