### ISSUE TITLE
gr-uhd: Tags not sent on "tune" message

### ISSUE THREAD

**Issue by seldad8** [gnuradio/gnuradio#4204]
When tuning the USRP using the message port interface, the rx_freq, rx_time, rx_rate tags are not sent to the downstream blocks.  They are sent properly when calling usrp_source_impl::set_samp_rate(), usrp_source_impl::set_center_freq().

**Comment by seldad8** [comment]
I'm able to work around this issue by sending a "tag" command on the message port, after sending the "tune" message.

**Comment by seldad8** [comment]
This is a duplicate of #1357 .

**Comment by willcode** [comment]
Should be fixed by the referenced PR. Did not auto-close.
