### ISSUE TITLE
gnuradio 3.9 Docker container?

### ISSUE THREAD

**Issue by ReverseControl** [gnuradio/gnuradio#4238]
Is there a gnuradio 3.9 docker container ready to go? I am having a hard time installing gnuradio 3.9 from source  in a docker container.

**Comment by mbr0wn** [comment]
No, but you can see how we do it in the CI system https://github.com/gnuradio/gnuradio-docker/tree/master/ci

**Comment by bistromath** [comment]
if you just want an image: https://hub.docker.com/repository/docker/bistromath/gnuradio
