### ISSUE TITLE
Graph messages with "QT GUI MESSAGE Edit Box" and LoRa blocks

### ISSUE THREAD

**Issue by GuilleA97** [gnuradio/gnuradio#4242]
Hello everyone,

I have been testing the LoRaWan blocks on GNU Radio. My goal is that when writing a message using "QT GUI Message Edit Box" the message can be represented graphically thanks to the LoRa coding. The message is sent since I have checked it with the "Message Debug", but the graphs are kept at 0. Can someone tell me how I can do it?

Thanks.

![image](https://user-images.githubusercontent.com/79115431/107996591-052b9880-6fe1-11eb-9225-88d9150f79a0.png)

**Comment by marcusmueller** [comment]
That's a problem with the LoRa Encoder, which isn't part of GNU Radio itself, so I'm afraid this is the wrong bug tracker!

I'm not 100% sure which LoRa toolkit you're using; if I remember correctly, rpp0's gr-lora is GNU Radio 3.8 compatible, and you're showing a GNU Radio 3.7 flow graph, so if you're using that, maybe update your GNU Radio (it's easy! GNU Radio 3.8 is installable on almost all systems from package repositories) and get a current version of rrp0's gr-lora, and see whether the problem persists.

If the problem does indeed persist, r you're using something else, I guess going through the bug tracker or that, or, always welcome in any form!, drop a message in the GNU Radio chat (you can sign up on https://chat.gnuradio.org ) or the discuss-gnuradio mailing list.
