### ISSUE TITLE
runtime: setting a blocks alias to the current value causes an error

### ISSUE THREAD

**Issue by jacobagilbert** [gnuradio/gnuradio#4282]
This was identified in #4176 because three examples in gr-digital explicitly set a block's alias to the default value causing an error:

```python
RuntimeError: symbol already exists, can not re-use!
```

This fails back to at least 3.8. Also, a 4th example in that directory fails due to range() changing behavior in python2 --> python3.

This brings up a couple questions:

1. Should this fail? I sort of do not think so... if not, the correct fix is here in runtime as this issue suggests. If it _should_ fail, a simple update to 4 example GRC files resolves this.
2. How can the project do better to keep examples up to date? One will fail in any python3 API, and the three with the alias issue have failed for at least years. How many others are lurking?

**Comment by marcusmueller** [comment]
> Should this fail? I sort of do not think so... if not, the correct fix is here in runtime as this issue suggests. If it should fail, a simple update to 4 example GRC files resolves this.

I sort of think it does. Question: why would someone ever want to set an alias to its current value? That *sounds* like you're doing what these examples do wrong!

> How can the project do better to keep examples up to date? One will fail in any python3 API, and the three with the alias issue have failed for at least years. How many others are lurking?

Some, hopefully not too many. We should track this in a different issue, though!
