### ISSUE TITLE
QT GUI: Time sink segfault

### ISSUE THREAD

**Issue by jacobagilbert** [gnuradio/gnuradio#4396]
The master branch QT GUI Time sink segfaults in complex PDU mode when when the number of elements in the PDU does not match the Number of Points set in the block config.

The Number of Points entry box is hidden when in either of the PDU modes are configured as the input type, and they should not be used to set behavior which should be controlled by the number of elements (and is for float type PDUs it appears).

Flowgraph: 

![image](https://user-images.githubusercontent.com/7121282/111231522-0daacb00-85af-11eb-8d3f-5a7d8c3cc8e4.png)

[pdu_test.grc.txt](https://github.com/gnuradio/gnuradio/files/6144952/pdu_test.grc.txt)

**Comment by jacobagilbert** [comment]
I can confirm that after reverting 4b7006db (and 371ea713) the issue is gone, so its somewhere in there. 

I don't think this is severe enough to warrant rolling these back, @ThomasHabets if you have a few minutes to take a look at this I'd appreciate it. I'll post here if I make any progress.

**Comment by ThomasHabets** [comment]
Yeah, my bad. PR coming in a few minutes.

**Comment by ThomasHabets** [comment]
PR #4399 in flight.

Thanks for the minimal test case to reproduce!
