### ISSUE TITLE
GNURadio-3.8 on Windows - Generate the flow graph fail for all UHD-based examples

### ISSUE THREAD

**Issue by fradaxx** [gnuradio/gnuradio#4398]
I installed GNURadio 3.8 on a Windows 10 PC using the available binary installer and started exploring some of the available examples and building someone new following online tutorials. 
All's gone (almost) well until I developed my applications using an HackRF-One to capture RF signals.
I would like also to test a National Instruments' USRP-2952R by Ettus Research; however when I try to generate the flow graph of the available examples or when I try to build any flow graph from scratch using the UHD blocks, I receive a bunch of errors.
I attach the console dump with the errors I receive when I try to generate flow graph of uhd_wbfm_receiver.grc:

[uhd_wbfm_receive.txt](https://github.com/gnuradio/gnuradio/files/6149576/uhd_wbfm_receive.txt)

This is a small extract of the file:
```
Generating: 'C:\\\\Program Files\\\\GNURadio-3.8\\\\share\\\\gnuradio\\\\examples\\\\uhd\\uhd_wbfm_receive.py'
Generate Error: (NameError("'len_tag_name' is not defined"), 'uhd.usrp_source(\n    ",".join((${dev_addr}, ${dev_args})),\n    uhd.stream_args(\n        cpu_format="${type}",\n  ....
....
>>> Failure
```
Similar errors arise when I try to use anyone of the UHD blocks in my flow graphs.

I can guess that there is some issue related to the Python version, but I am unable to find and solve it by myself.

Can I ask for some hint to solve this problem which prevent me to use the USRP I own with GNU Radio?

Thanks in advance for any answer.

Regards

**Comment by marcusmueller** [comment]
seems to work, we have people using the examples on windows.
