### ISSUE TITLE
Error receiving byte array

### ISSUE THREAD

**Issue by GuilleA97** [gnuradio/gnuradio#4419]
Hello everyone,

I am doing a string to byte array converter with the 'Embedded Python Block'. The idea is to write a message with 'QT GUI Message Edit Box' of type String and do the conversion in the Python Block. The problem I have is that when the following block has to receive the message, this message appears:

**thread [thread-per-block [1]: <block encode (4)>]: pmt_cdr: wrong_type # [Hello]**

I have created the byte array using the bytearray () function and sending the result to the output port, is this the correct way? I attach code. Thanks.

![image](https://user-images.githubusercontent.com/79115431/111855786-de85b800-8926-11eb-96de-d33fd855838e.png)

**Comment by willcode** [comment]
Likely that a receiver is expecting a different type of message than was sent. Closing - please mail the list or ask more questions at chat.gnuradio.org.
