### ISSUE TITLE
New Hier Block (QT GUI) creates incomplete .py code

### ISSUE THREAD

**Issue by joncnist** [gnuradio/gnuradio#4431]
I created a hier block with a bunch of LEDs and put it in a flowgraph.  It fails to run with error: 
NameError: name 'Qt' is not defined
If I edit the .py code created by GRC and add a line:
`from PyQt5 import Qt`
then the hier block runs with no problems.

[led_array.py.block.zip](https://github.com/gnuradio/gnuradio/files/6184659/led_array.py.block.zip)

**Comment by mormj** [comment]
I think you can/should add the `from PyQt5 import Qt' to the imports section under templates in the block yml.

**Comment by joncnist** [comment]
The yml is autogenerated when the hier block is saved.  It has this line:
flags: need_qt_gui
Shouldn't that cause the proper import to be added?

**Comment by mormj** [comment]
Ah I didn't catch that the hier block was created with GRC - yes that should be added then.

**Comment by petrushy** [comment]
Can confirm this bug in GNU Radio version: 3.9.2.0 as well. Is there a workaround to be able to add this import statement so it is included in the autogenerated code?

**Comment by mormj** [comment]
Can you add an import block in GRC with `from PyQt5 import Qt`

**Comment by marcusmueller** [comment]
Seems fixed
![repro3738](https://github.com/gnuradio/gnuradio/assets/958972/94858c25-d6b6-4619-86b0-56a7c9e03518)
https://gist.github.com/marcusmueller/372a4419168282f8f36a9e1b43427abd
