### ISSUE TITLE
CC_decoder does not work

### ISSUE THREAD

**Issue by dagronplayer** [gnuradio/gnuradio#4466]
Hi, I want to do a file transceiver by using fec_extended decoder, but the result is random. does anyone know why? 
![image](https://user-images.githubusercontent.com/72313621/112718697-9d496580-8f2f-11eb-8f0e-26917f250f7b.png)

**Comment by mormj** [comment]
This appears to be the same issue as: https://github.com/gnuradio/gnuradio/issues/3376

There is a workaround in that thread.  It seems to be a volk issue that only shows up in the usage with gnu radio.

closing this as duplicate.
