### ISSUE TITLE
Return code error-11

### ISSUE THREAD

**Issue by vnnspace** [gnuradio/gnuradio#4474]
Please help I can not find what is it?
When this error is appear?
I am now making UDP receiver and put information from GQRX to the File. But code happen....
![image](https://user-images.githubusercontent.com/58883080/113105553-af334d00-923c-11eb-8444-170a7e7231fd.png)

**Comment by willcode** [comment]
@vnnspace There is not enough information here to even tell what you are trying to do. Please reopen the issue if you have a better description.

**Comment by nsj23** [comment]
Have you solved it? I have the same problem
