### ISSUE TITLE
Getting `Assertion `s < d_bufsize' failed` error

### ISSUE THREAD

**Issue by rsandler00** [gnuradio/gnuradio#4515]
Hi, I am running some simulations w/ GNURadio where I run top blocks repeatedly inside a nested for loop in python. e.g.:

```
for scheme_set in range(len(schemes)):
    name = scheme_names[scheme_set]
    for snr_set in snr_list:
        print(color.GREEN + 'Starting modulation scheme: ' + name + ' at SNR: ' + str(snr_set) + color.END)

        tb = top_block_cls(ota=False)
        tb.set_file_num_and_scheme(name, snr_set)
        tb.start()
        tb.wait()
```

I randomly get this error:
```
python3: /build/gnuradio-sO0YW3/gnuradio-3.8.2.0-0~gnuradio~bionic/gnuradio-runtime/lib/../include/gnuradio/buffer.h:193: unsigned int gr::buffer::index_add(unsigned int, unsigned int): Assertion `s < d_bufsize' failed.
Aborted (core dumped)
```

The weird thing is that it happens at totally random iterations of the for loop - sometimes in the 1st iteration, sometimes at the 10th, which makes me think that the flowgraph is fine, but there is a GNURadio issue. 

Does anyone have any insight into the nature of this error?

Thanks!

**Comment by mbr0wn** [comment]
@rsandler00 we probably can't do anything about this. I've seen this before, and it's probably related to Python garbage collection (which we don't control). The "right" way to do this is to create on flow graph and keep it alive, and let it do tasks every time there is new data.
