### ISSUE TITLE
My computer freezes while compiling GNU Radio

### ISSUE THREAD

**Issue by rodrirq** [gnuradio/gnuradio#4580]
Hello, I am building GNU Radio from source for an ARM processor.

I am using PetaLinux SDK as a cross-compilation environment.

The thing is that when I do the make command, it reaches 59% but then my computer freezes. If I move the mouse, it moves a few seconds later, so it is not completely frozen. I left my computer on for 12 hours, and the make was in the same step as it was the day before.

I am NOT working from a virtual machine, and my computer has 8 GB RAM.

I hope someone can help.

**Comment by mormj** [comment]
@rodrirq - please seek help for issues that are not necessarily issues with gnu radio itself on the mailing list - https://lists.gnu.org/mailman/listinfo/discuss-gnuradio - there are more people monitoring that list for things like this than the github issue tracker
