### ISSUE TITLE
Do these failing tests and missing headers mean anything?

### ISSUE THREAD

**Issue by NeuroForLunch** [gnuradio/gnuradio#4597]
```
-- Looking for C++ include io.h - not found
-- Looking for C++ include malloc.h - not found
-- Performing Test HAVE_SSLEEP - Failed
-- Performing Test HAVE_VALLOC - Failed
-- Performing Test HAVE_CREATEFILEMAPPING - Failed
-- Performing Test HAVE_SHM_OPEN - Failed
-- Performing Test HAVE_SINCOS - Failed
-- Performing Test HAVE_SINCOSF - Failed
-- Performing Test HAVE_SCHED_SETSCHEDULER - Failed
```

At the end everything is enabled and it says `-- Generating done` so its confusing as to the meaningfulness of the tests.
This is on MacOS Big Sur and gnuradio 3.8-maint

**Comment by dkozel** [comment]
Hi @NeuroForLunch Those errors are fine. They are part of the build system configuring itself to the environment. If there was a blocking issue then some modules would be disabled at the end or the generate process would stop before completion.
