### ISSUE TITLE
When install from src gnuradio-companion bin not created

### ISSUE THREAD

**Issue by izabarovsky** [gnuradio/gnuradio#4605]
gnuradio installed from sources according to https://wiki.gnuradio.org/index.php/InstallingGR
All required dependencies is satisfied
But binary gnuradio-companion not found, only gnuradio-config-info
System Debian 5.10.28-1 (2021-04-09) x86_64 GNU/Linux

**Comment by willcode** [comment]
If some of the dependencies were not found, gnuradio-companion could have been disabled. Check the output of cmake. Otherwise, it could be a path issue, multiple installations, etc. This is well tested - do you have any more info?

**Comment by izabarovsky** [comment]
> Have you tried looking in the `grc/scripts/` subdirectory?

Yeah, found here, tnx
