### ISSUE TITLE
Interleave / Deinterleave GRC block: inconsistent naming of parameters

### ISSUE THREAD

**Issue by marcusmueller** [gnuradio/gnuradio#4615]
These blocks use "Vec Length" instead of "vector length" AND this is not documented on the [wiki page](https://wiki.gnuradio.org/index.php/Deinterleave)s. It's really just a multiplier for the itemsize.

To fix this, 

- [x] Fix the GRC .block.yml files to use the canonical "vector size" / "vector length" (look that up)
- [x] Modify the wiki pages for the deinterleave / interleave blocks, explaining what the effect actually is, maybe make a figure / drawing to understand what the interleaver does when you set vector size >1.

**Comment by solomonbstoner** [comment]
I notice sometimes "vector size" is used to refer to "vector length". Shall I change em to "vector length" or is "vector size" ok? Is the goal of this issue just to standardize "vec" to "vector" in the documentation?

![Screenshot from 2021-05-18 23-22-35](https://user-images.githubusercontent.com/24548334/118679106-2db96d80-b830-11eb-80cc-609cae1e48d4.png)

**Comment by solomonbstoner** [comment]
We're left with part 2 of this issue:

> Modify the wiki pages for the deinterleave / interleave blocks, explaining what the effect actually is, maybe make a figure / drawing to understand what the interleaver does when you set vector size >1.
