### ISSUE TITLE
How can I decode broadcast 3G (UMTS) traffic?

### ISSUE THREAD

**Issue by Al3x4n** [gnuradio/gnuradio#4626]
How can I decode broadcast 3G (UMTS) traffic?

**Comment by marcusmueller** [comment]
Not a bug report, closing.

Please don't use the GNU Radio issue tracker for questions; if you have a GNU Radio-specific question, please sign up for the [discuss-gnuradio](https://lists.gnu.org/mailman/listinfo/discuss-gnuradio) mailing list, or join us on [Matrix chat #gnuradio:gnuradio.org](https://chat.gnuradio.org).
