### ISSUE TITLE
Gnuradio 3.8 AttributeError: 'top_block_sptr' object has no attribute 'tabid_grid_layout_0'

### ISSUE THREAD

**Issue by Letiel-88** [gnuradio/gnuradio#4631]
In this simple flowgraph:
![image](https://user-images.githubusercontent.com/66081177/118505903-22c9e480-b72d-11eb-97bd-ab10130bd46d.png)
![image](https://user-images.githubusercontent.com/66081177/118505966-31180080-b72d-11eb-8e84-f4511a8479c9.png)
![image](https://user-images.githubusercontent.com/66081177/118506048-42610d00-b72d-11eb-8cc8-acb85ee0a58e.png)

I'm getting the following error:
Traceback (most recent call last):
  File "/home/aaa/Desktop/Prova.py", line 196, in <module>
    main()
  File "/home/xxx/Desktop/Prova.py", line 172, in main
    tb = top_block_cls()
  File "/home/aaa/Desktop/Prova.py", line 128, in __init__
    self.Tab_grid_layout_0.addWidget(self._qtgui_time_sink_x_0_win, 1, 1, 1, 1)
  File "/home/aaa/sdr/lib/python3/dist-packages/gnuradio/gr/hier_block2.py", line 93, in __getattr__
    return getattr(self._impl, name)
AttributeError: 'top_block_sptr' object has no attribute 'Tab_grid_layout_0'

>>> Done (return code 1)

Gnuradio Companion Version: v3.8.2.0-118-g8b2012ab (Python 3.6.9)

**Comment by ChristopheSeguinot** [comment]
This is a bug currently under investigation ( see Pull Request #4629). 
A simple temporary workaround is to add a GUI Hint in every QT GUI Tab widget for example `0,0` in yours

**Comment by dl1ksv** [comment]
This error happens on the master branch, too.

**Comment by willcode** [comment]
Related PRs merged. Please re-open if there is still a problem.
