### ISSUE TITLE
Interleave block: Unable to modify Vector Length

### ISSUE THREAD

**Issue by solomonbstoner** [gnuradio/gnuradio#4634]
I was just playing around with vectors to learn something about it. I tried to change the interleaver block from Vector Length of 3 to Vector Length of 1. I was not allowed to directly change the Vector Lengths for all the blocks from 3 to 1. Doing so gave me the error below for the bottom vector source:

> Source IO size "12" does not match sink IO size "4".

![Screenshot from 2021-05-18 22-37-52](https://user-images.githubusercontent.com/24548334/118671097-c3053380-b829-11eb-89b0-4f6a375e56c8.png)

Instead, to make the change, I had to go the long route. So, back to beginning, everything is fine with Vector Length of 3.

![Screenshot from 2021-05-18 22-34-57](https://user-images.githubusercontent.com/24548334/118670749-7883b700-b829-11eb-8f10-a00b975f72d8.png)

I change Vector Length of 3 to 1 in the Interleave block only. The others are not changed yet. Only the upper input and output ports have changed from vector length of 3 to 1, shown in the red arrow indicating an error. The bottom input port somehow still has a vector length of 3.

![Screenshot from 2021-05-18 22-35-11](https://user-images.githubusercontent.com/24548334/118671446-0cee1980-b82a-11eb-83ce-a1a8a064d5a0.png)

I change the Vector Length only for the blocks with the errors. Now there are _no more errors_ . Note that the vector source at the bottom still have a Vector Length of 3. All other blocks have their Vector Length changed from 3 to 1. I can generate the flowgraph and run, but _nothing gets shown_. The QT Time sink does not show.

![Screenshot from 2021-05-18 22-35-28](https://user-images.githubusercontent.com/24548334/118671589-327b2300-b82a-11eb-8e7a-41a3236e4b03.png)

If I were to manaully change the Vector Length of the bottom vector source myself, an error appears. I cannot make that change even though I had specified all the blocks to have Vector Length of 1.

![Screenshot from 2021-05-18 22-37-52](https://user-images.githubusercontent.com/24548334/118671915-71a97400-b82a-11eb-8ac3-446fa0424ebb.png)

The only way I could was to double click on the Interleave block to enter its properties, then click "Cancel". Clicking on "Ok" does not work. Only then does the error go away and the program runs properly (ie QT Time sink appears).

**Comment by solomonbstoner** [comment]
Imma try to fix this issue myself

**Comment by willcode** [comment]
There's something very strange going on in the GRC connection validator code. I tried out this example and a couple similar ones and couldn't make sense of what it was doing.

**Comment by solomonbstoner** [comment]
Interesting. It appears like the Interleave block is not the only block. Even the Add and Subtract blocks have the same issue. 

And also tested with 3 and 4 inputs. Same issue. Only the top input and the output port gets updated while every other port is left unchanged

![Screenshot from 2021-05-19 19-56-05](https://user-images.githubusercontent.com/24548334/118808647-50a15b80-b8dc-11eb-931f-0240077e7a47.png)
