### ISSUE TITLE
Getting an error when linking - display_qt

### ISSUE THREAD

**Issue by fiend138** [gnuradio/gnuradio#4636]
I'm trying to build gnuradio from source v3.9.1.0, on Ubuntu 20.04 and I'm getting this error:

```
[ 98%] Linking CXX executable display_qt
[100%] Built target qtgui_python
/usr/bin/ld: /lib/libqwt-qt5.so: undefined reference to `qt_version_tag@Qt_5.12'
collect2: error: ld returned 1 exit status
make[2]: *** [gr-qtgui/examples/c++/CMakeFiles/display_qt.dir/build.make:126: gr-qtgui/examples/c++/display_qt] Error 1
make[1]: *** [CMakeFiles/Makefile2:6479: gr-qtgui/examples/c++/CMakeFiles/display_qt.dir/all] Error 2
make: *** [Makefile:141: all] Error 2
```

I've installed all the dependencies required (at least I think so...), does anybody know what the problem might be?

Here's what I have installed:
```
libqwt-qt5-6/focal,now 6.1.4-1.1build1 amd64 [installed]
libqwt-qt5-dev/focal,now 6.1.4-1.1build1 amd64 [installed]
libqwtplot3d-qt5-0/focal,now 0.2.7+svn191+gcc7-3build1 amd64 [installed,automatic]
libqwtplot3d-qt5-dev/focal,now 0.2.7+svn191+gcc7-3build1 amd64 [installed]
```
Any help would be appreciated.

NOTE: I need to use a higher version of UHD than 3.15, so installing from a package manager isn't an option, I need to install from source.

Thanks!

**Comment by willcode** [comment]
I just built 3.9.1.0 in an Ubuntu 20.04 container, and did not see this error. The display_qt example built fine.

Since this is an environment problem of some sort, I'll close the Issue. Feel free to put questions on the mailing list or chat.gnuradio.org to see if someone can give you some help debugging the build.
