### ISSUE TITLE
gr-soapy: Custom sink Center Freq fails with one channel selected.

### ISSUE THREAD

**Issue by drmpeg** [gnuradio/gnuradio#4656]
The block requires than the center freq for channel 1 also be set, but it's impossible to do that.

**Comment by willcode** [comment]
Which module?

**Comment by willcode** [comment]
Can not duplicate. Tried the Soapy Custom Sink with both PlutoSDR and BladeRF, configured like this:

![1](https://user-images.githubusercontent.com/1258295/119394869-bad14c00-bca0-11eb-969e-0980ff429777.png)
![2](https://user-images.githubusercontent.com/1258295/119394880-bdcc3c80-bca0-11eb-8ab7-3977f884a8b0.png)

and also tested with periodic frequency change messages:

![3](https://user-images.githubusercontent.com/1258295/119394916-ca509500-bca0-11eb-8470-6f659b6eb797.png)

Any more info on your setup?

**Comment by drmpeg** [comment]
Try it without a variable named "freq".
