### ISSUE TITLE
Python module in GNU Radio companion 3.7

### ISSUE THREAD

**Issue by juriguen** [gnuradio/gnuradio#4669]
Hi there

I am having problems trying to add Python code via a Python module in GNU Radio 3.7, under Windows 10. I know this is not the latest version, but I am using it due to it working fine with SDRplay.

The issue I face is that the module's ID is not recognized elsewhere, and thus I cannot use the output of the module within the flow. Is this a known issue? How can I solve it?

Thanks in advance

![sweep_test_2_issue](https://user-images.githubusercontent.com/5476552/119628453-69929b00-be0d-11eb-9dd9-cbdfae350e71.png)

**Comment by willcode** [comment]
We are no longer maintaining 3.7, and the issue tracker is for bugs and feature requests for maintained versions. Please use the mailing list or chat.gnuradio.org for help.
