### ISSUE TITLE
SDRplay with GNU Radio in Ubuntu

### ISSUE THREAD

**Issue by juriguen** [gnuradio/gnuradio#4673]
Hi!

I'm trying to make an SDRplay module by Franco Venturi work in GNU Radio but, after installing the latest app version for Ubuntu and following the instructions of his readme file to build the block, I try to run a very simple example and get the error: ModuleNotFoundError: No module named 'sdrplay3'

![Screenshot from 2021-05-27 11-10-30](https://user-images.githubusercontent.com/5476552/119799603-83e77a00-bedc-11eb-86c9-64c863c4d76c.png)

Any ideas what might I be doing wrong?

Thanks!

**Comment by willcode** [comment]
Help requests are via the mailing list or chat.gnuradio.org. Closing.

**Comment by juriguen** [comment]
I don't understand why issues related to GNU radio cannot be here
