### ISSUE TITLE
FindLOG4CPP doesn't use pkg-config, hardcodes paths

### ISSUE THREAD

**Issue by marcusmueller** [gnuradio/gnuradio#4681]
As #4635 uncovered, there's something not as good about FindLOG4CPP as other Find-modules.

My suspicion is that the combination of trying to find the header file path with hard-coded candidates only, together with the absence of an attempt to ask pkg-config, is to blame.

Hoping the reporter of #4635 will clarify whether setting the variables explicitly helps, so we can investigate this.

**Comment by mormj** [comment]
Good Riddance Log4CPP!!!
