### ISSUE TITLE
string == "0.0" isn't sufficient for testing zeroness of string

### ISSUE THREAD

**Issue by marcusmueller** [gnuradio/gnuradio#4742]
Soapy Python bindings do this:

https://github.com/gnuradio/gnuradio/blob/f29be5398081e78ed0edeaf712cc608e770f2523/gr-soapy/python/soapy/bindings/soapy_common.cc#L57-L66

this will be hilarious if someone tries 0e0, -0, or +0 and gets something different than if they use 0.0.

Let's not have that much hilarity in our lives :D

**Comment by willcode** [comment]
I remember leaving that one for latter ... and forgetting. Thanks for catching it.

**Comment by willcode** [comment]
@ncorgan what do you think, since this was copied from the 0.8.0 code?

**Comment by marcusmueller** [comment]
I illustrate what I'd recommend in #4743, together with upstreaming these changes in https://github.com/pothosware/SoapySDR/pull/313 to keep things consisten.
