### ISSUE TITLE
GnuRadio 3.8 PPA does not contain  release file for Hirsute (Ubuntu 21.4)

### ISSUE THREAD

**Issue by Spartan-II-117** [gnuradio/gnuradio#4750]
The repository 'http://ppa.launchpad.net/gnuradio/gnuradio-releases-3.8/ubuntu hirsute Release' does not have a Release file.

**Comment by marcusmueller** [comment]
Remark: Hirsute comes with 3.8.2.0 by itself; a PPA would only serve to bridge the time between release of a new 3.8.x.y release and adoption by Ubuntu.

**Comment by Spartan-II-117** [comment]
Ok, thanks, I thought it came with 3.9.

**Comment by www2000** [comment]
I have the same problem with gnuradio master ppa on ubuntu 21.04

**Comment by mormj** [comment]
Closing this as a GR Code issue.  Generally we could use more support with PPA packaging if anyone is interested in taking it on.
