### ISSUE TITLE
Python invalid syntax- inserting extra comma

### ISSUE THREAD

**Issue by suciokhan** [gnuradio/gnuradio#4757]
Building low-pass-filter through the GUI results in this (_note the extra comma after 75000_) which throws a Python error:
```
self.low_pass_filter_0 = filter.fir_filter_ccf(
            20,
            firdes.low_pass(
                1,
                4000000,
                75000,
                ,
                firdes.WIN_HAMMING,
                6.76))
```
Here is what the error looks like:
![image](https://user-images.githubusercontent.com/23055812/121705729-f2166a00-caa2-11eb-9b31-26ce87ce0ef6.png)

Here is my low-pass-filter config in the GUI:
![image](https://user-images.githubusercontent.com/23055812/121705477-aa8fde00-caa2-11eb-9f30-9775bc8fc3bb.png)

Note: Every time I execute it, the Transition Width gets blanked-out.

**Comment by willcode** [comment]
What version of gnuradio?

Does this happen with a new flowgraph?

**Comment by suciokhan** [comment]
'3.8.1.0'

Hmmm...after closing down gnuradio_commpanion, I manually fixed the Python script using vim, and now when I open it up I can hit play and it works.

**Comment by willcode** [comment]
Good, closing. Probably a stale value that got stuck in a grc file after a gnuradio update.
