### ISSUE TITLE
Convert remaining code to logging 

### ISSUE THREAD

**Issue by marcusmueller** [gnuradio/gnuradio#4765]
largest occurrence of cout is in hier_block2_detail, for no good reason!

would be relatively easy to replace with `GR_LOG_INFO(d_logger,…)`, but it's mechanic. When done, remove all remainders of debug `#if`s and `#include <iostream>` from the files

Partially addresses #4763 

Files to be fixed:

- [x] hier_block2_detail 
- [x] qa_blocks_tags.cc
- [x] polar_decoder_common.cc (at least settle on *either* `printf` or `cout`, not both)

**Comment by ronalddadds** [comment]
Hi @marcusmueller, I've reviewed the work that needs to be completed and I'm happy to take this work on. Can you assign this issue to me?

I'll use PR #4764 as an example to work from.

**Comment by dkozel** [comment]
Hi @ronalddadds. Thanks! If you have any questions here or https://chat.gnuradio.org are the best places to ask.

**Comment by ronalddadds** [comment]
Thank you @dkozel for assigning this to me, I'll be sure to ask questions either here or on the GNU Radio chat link you provided.

**Comment by ronalddadds** [comment]
I encountered a registration error on chat.gnuradio.org (an error on sending a validation email - and I double-checked my email!), but I will still communicate here.

My current method is to replace std::cout messages with GR_LOG_INFO as below:
``` diff
if (HIER_BLOCK2_DETAIL_DEBUG)
-    std::cout << "connect: dst is hierarchical, setting parent to " << this
-              << std::endl;
+    GR_LOG_INFO(d_logger,
+        boost::str(boost::format("connect: dst is hierarchical, setting parent to %s") % this));
```

Is this in line with expectations for this issue?

**Comment by marcusmueller** [comment]
it really is! Thank you!

**Comment by ronalddadds** [comment]
You're welcome! There was a _make test_ issue in my pull request #4810, so I'll fix that and let you know when it's done!

**Comment by SWITCHin2** [comment]
@marcusmueller Hi there, i have tried to accomplish the 3rd sub-task mentioned in this issue and raised the PR for the same #7186 kindly look into it

**Comment by SWITCHin2** [comment]
@marcusmueller I have raised a new PR with all the changes that you have asked to do , PR : #7188

**Comment by StudHamza** [comment]
I think we can close this issue, PR #7188 fixed the last bullet point
