### ISSUE TITLE
Flowgraph doesn't update properly if samp_rate is controlled by another variable

### ISSUE THREAD

**Issue by drmpeg** [gnuradio/gnuradio#4781]
If the samp_rate variable is a function of another variable, the flow graph is not updated properly when the variable is changed (and OK is clicked). Here's the example flow graph. samp_rate is set to (symbol_rate * 2). When symbol_rate is changed (in this case from 32k to 48k), Sample Rate in all the blocks is not updated.

I've bisected this behavior to commit https://github.com/gnuradio/gnuradio/commit/c4f46bfa6d790c57018f9c6fca264bb9e01a2854

![image](https://user-images.githubusercontent.com/5397196/122407214-4eabd600-cf36-11eb-96b6-2a36d1035d8d.png)

**Comment by solomonbstoner** [comment]
I can replicate your described behavior when I press the `Ok` button immediately after changing `symbol_rate`. 
When I click `Apply` then `Ok` after changing `symbol_rate`, the Sample Rate in all the blocks get updated. Is it the same behavior on your side?

**Comment by drmpeg** [comment]
Yes, that's correct. Only happens when just ```OK``` is clicked. But that's how I normally use the dialog.

**Comment by solomonbstoner** [comment]
Wasnt suggesting you change how you use the dialog haha. Im trying to narrow down the behavior.
So it appears that `Apply` correctly applies the change in Symbol Rate to all the Sample Rate parameters in the blocks regardless of whether I press `Ok` or `Cancel` afterwards. So we can narrow the search to the difference between the `Ok` behavior and `Apply` behavior. Ill take a look at this issue too with you
