### ISSUE TITLE
Header/Payload Demux in Packet Rx, incompatible constructor arguments

### ISSUE THREAD

**Issue by jth0078** [gnuradio/gnuradio#4809]
Running any topology with Packet Rx block generates following error. This error did not occur on older flowgraphs that were working before v3.10. Generating the flowgraph produces no warnings for Header/Payload Demux block either. I'm assuming its something small that I'm not understanding, so any help is appreciated.

TypeError: __init__(): incompatible constructor arguments. The following argument types are supported:
    1. gnuradio.digital.digital_python.header_payload_demux(header_len: int, items_per_symbol: int = 1, guard_interval: int = 0, length_tag_key: str = 'frame_len', trigger_tag_key: str = '', output_symbols: bool = False, itemsize: int = 8, timing_tag_key: str = '', samp_rate: float = 1.0, special_tags: List[str] = [], header_padding: int = 0)

Invoked with: 96, 1, 0, 'payload symbols', 'time_est', True, 8, 'rx_time', 1, '', 0

**Comment by willcode** [comment]
The second to last arg should be a tuple/list. From the block yaml file:
```
-   id: special_tags
    label: Special Tag Keys
    dtype: raw
    default: (,)
```
In GRC, put `[]` in the `special_tags` entry in the block params.

For questions, please start with chat.gnuradio.org or the mailing list. If this turns out to be a bug, reopen this issue.
