### ISSUE TITLE
gr-iio re-introduces logging to stderr, Should use GNU Radio logging facilities

### ISSUE THREAD

**Issue by marcusmueller** [gnuradio/gnuradio#4816]
During a small architectural discussion with an anonymous intern, we spotted wide-spread use of std::cerr in iio blocks. Please don't introduce such things - we're trying very hard to unify the way GNU Radio logs!

**Comment by willcode** [comment]
Fixed by https://github.com/gnuradio/gnuradio/pull/4823.
