### ISSUE TITLE
gr_modtool bind support for template classes

### ISSUE THREAD

**Issue by NZSmartie** [gnuradio/gnuradio#4824]
Creating this issue here as it's not tracked and not sure if it's being actively worked on. 
A nice to have, especially for existing OOT modules as they migrated to 3.9 and would minimise the effort involved with template based bindings

> Current issue is that pygccxml (which blocktool uses under the hood) does not populate template classes with enough info to generate the expanded classes (e.g. multiply_const_{ss,ii,ff,cc}).   So these have to be done manually.  There are about 30 of them in gr-blocks so it's not terrible, but for OOTs it will be a manual step that we should be able to identify when they run modtool/blocktool and flag that the bindings will have to be done manually.

_Originally posted by @mormj in https://github.com/gnuradio/gnuradio/issues/3004#issuecomment-577713349_

**Comment by marcusmueller** [comment]
I'd love that, but it sounds impossible with reasonable effort – that's really down to the complexity of what symbols template classes might or might not introduce, and our method of detecting what needs wrapping.
