### ISSUE TITLE
from 3.7 to 3.8?

### ISSUE THREAD

**Issue by liumaolin-931** [gnuradio/gnuradio#4842]
Hi,
I am studying the file transfer process recently, I found an open source project https://github.com/BogdanDIA/gr-dvbt, I want to install and use it, but it is built on version 3.7, my gnuradio version is 3.8.2.0, when I mkdir build and execute cmake, there is no unexpected error, so how should I install it to the existing 3.8 version correctly? I took a look at the official tutorial, but it’s really too short and I don’t understand how to do it. Can anyone help me?

**Comment by drmpeg** [comment]
All of gr-dvbt has been integrated into GNU Radio. Take a look in the Digital Television category of GNU Radio Companion. The example flow graphs are in <install_directory>/share/gnuradio/examples/dtv.

You can find your install directory with ```gnuradio-config-info --prefix```

![image](https://user-images.githubusercontent.com/5397196/124804536-429cae00-df0f-11eb-970f-990d536d2898.png)

**Comment by willcode** [comment]
Help request - closing. Please use chat.gnuradio.org or the mailing list if you need additional help.

**Comment by liumaolin-931** [comment]
thanks a lot!






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "gnuradio/gnuradio"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年7月8日(星期四) 凌晨1:39
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [gnuradio/gnuradio] from 3.7 to 3.8? (#4842)





 
All of gr-dvbt has been integrated into GNU Radio. Take a look in the Digital Television category of GNU Radio Companion. The example flow graphs are in <install_directory&gt;/share/gnuradio/examples/dtv.
 
You can find your install directory with gnuradio-config-info --prefix
