### ISSUE TITLE
gnuradio 3.10 - Python Module 'Id' mixed up with 'Name'

### ISSUE THREAD

**Issue by Phil67ago** [gnuradio/gnuradio#4844]
Properties in 'Python Module' has two entries: 'Id' and 'Code'
You should be able to use your code by the ID
As documentation says:
****
If you put

    a = 2

    def double(arg):
        return 2 * arg

in a Python Module Block with the ID 'stuff' you can use code like

    stuff.a  # evals to 2
    stuff.double(3)  # evals to 6

to set parameters of other blocks in your flowgraph.
****
But 'Id' in properties dialog modify 'name' not 'id'!

**Comment by willcode** [comment]
Is the issue just that it is called `id` in the dialog and `name` in the grc file? True that this is confusing, but most people do not look at the grc file. If you set `id` to `stuff`, then the grc contains
```
- name: stuff
  id: epy_block
```
where `id` is the block type (embedded python block here). In the generated code, you see
```
        self.stuff = stuff.blk(example_param=1.0)
```
This is the intended behavior.

Please reopen if there is a specific problem.
