### ISSUE TITLE
cmake: Static build fails

### ISSUE THREAD

**Issue by voibit** [gnuradio/gnuradio#4859]
Why is library creation with GR_LIBRARY_FOO guarded with "if(BUILD_SHARED_LIBS)" in some modules, when building statically? 

Cmake fails, and removing the guards in the files cmake complains about fixes the issue,
however the different module libraries do not get compiled if not the guard is removed from module/lib/CMakeLists,txt as well.. 

Wondering if there is a reason behind it.

**Comment by willcode** [comment]
Building static libraries was reported to be broken in https://github.com/gnuradio/gnuradio/issues/4452, and still is as far as I know. `GR_LIBRARY_FOO` is intended to be for shared libraries.
