### ISSUE TITLE
I have question about Soapy & BladeRF v2.0

### ISSUE THREAD

**Issue by vnnspace** [gnuradio/gnuradio#4890]
I made a scheme in GNURadio with Soapy BladeRF and try to compile but I have an error

**Generating: '/home/ground/Documents/GNURadio/bpsk_BladeRF.py'

Executing: /usr/bin/python3 -u /home/ground/Documents/GNURadio/bpsk_BladeRF.py

[INFO] bladerf_open_with_devinfo()
[INFO] bladerf_get_serial() = e54225adb4af464aafaa25cbeccf67e9
[INFO] setSampleRate(Rx, 0, 4.000000 MHz), actual = 4.000000 MHz
[INFO] setSampleRate(Tx, 0, 4.000000 MHz), actual = 4.000000 MHz
[INFO] setSampleRate(Rx, 0, 2.600000 MHz), actual = 2.600000 MHz

>>> Done (return code -11)
**

I am tried to find such an error in the GNUradio tutorial but can not please help me 
What I should do?

**Comment by willcode** [comment]
Please use chat.gnuradio.org or the mailing list for questions and help. The issue tracker is used for bugs and feature requests.
