### ISSUE TITLE
gr-digital/examples/ofdm/tx_ofdm.grc example is broken (on master branch).

### ISSUE THREAD

**Issue by drmpeg** [gnuradio/gnuradio#4937]
@dl1ksv Looks like commit https://github.com/gnuradio/gnuradio/commit/fbab6c383d6f86ab0de42a90a9182d22637a5b96 has a side effect. It breaks this flow graph in gr-digital.

![image](https://user-images.githubusercontent.com/5397196/126315528-4dfbff92-45c0-493a-8767-c874d04085df.png)

**Comment by dl1ksv** [comment]
@drmpeg  Worked for me. The error was not in fbab6c3 but in  98cadbf3d54176b474d8257ae0f2ae6f7c01fc3a.
But I see, you have already found it and fixed this issue

**Comment by dl1ksv** [comment]
After I aplying #4936 the flowgraph still fails. The first time I probably tested a wrong branch. Sorry for that.
But now #4949 should fix this issue.

**Comment by drmpeg** [comment]
Thanks for re-checking. I'll give https://github.com/gnuradio/gnuradio/pull/4949 a test.
