### ISSUE TITLE
GFSK Mod hier block unnecessarily adds packed to unpacked

### ISSUE THREAD

**Issue by solomonbstoner** [gnuradio/gnuradio#4939]
Because of that, I cannot craft my own non-byte aligned bit stream and mod it with the GFSK Mod block. 

There is no unpacked to packed in the demodulator - possibly because sometimes the received bit stream is not necessarily byte aligned. 

For example, I have a flow graph to modulate a bit sequence (0, 0, 0, 1, 1, 1, 0, 1, 1). The block totally ruins my bit stream.

![Screenshot from 2021-07-20 23-26-06](https://user-images.githubusercontent.com/24548334/126353074-300a4fdb-5758-4ace-aee4-c9991e0f8df4.png)

![Screenshot from 2021-07-20 23-25-58](https://user-images.githubusercontent.com/24548334/126353083-920c4ba4-1f87-4cdd-bbd0-a2d49390022e.png)

I propose we remove the packed to unpacked component of the GFSK Mod hier block. It is, in my opinion, more intuitive to add a packed to unpacked component in the flowgraph if needed than to have it baked into the hier block.

**Comment by willcode** [comment]
A backward compatible way would be to have a param that contols this behavior and defaults to the current way.
