### ISSUE TITLE
Rename default branch

### ISSUE THREAD

**Issue by mormj** [gnuradio/gnuradio#4963]
Following the move across the open source community as described and executed here: https://github.com/gnuradio/volk/issues/461 for the volk database

This needs to be done at a convenient time so as to not disrupt any impending release - preferable right after our 3.10 release, or if that is deferred then the next set of maint branch releases

As a side note, the github default is `main` - but since we make heavy use of `maint-` this will make tab completion slightly more cumbersome.  Perhaps a `devel` or `default`, though that would depart from the standard `main`

**Comment by willcode** [comment]
If we change it, `devel` would be more accurate.
