### ISSUE TITLE
interdependent objects in GRC stopped working reliably

### ISSUE THREAD

**Issue by marcusmueller** [gnuradio/gnuradio#4966]
Test case: packet_loopback_hier complains about an undefined `Const_PLD`, even if it's there; renaming and replacing does fix things at first, at some point this breaks again.

Must have been a change merged into master in the last month or so :( Very hard to bisect.

![packet_loopback_hier](https://user-images.githubusercontent.com/958972/127666788-4e81bc48-a89a-4b78-892b-279550c33b81.png)

I'm really stumbling in the dark here. I'd be very thankful for any leads, @haakov or @skoslowski ?

(git 25c233e65 / master on Python 3.95 on F34)

**Comment by haakov** [comment]
I'll take a look at it :smile:

**Comment by drmpeg** [comment]
It's been fixed already. See https://github.com/gnuradio/gnuradio/issues/4937 and https://github.com/gnuradio/gnuradio/pull/4949

**Comment by haakov** [comment]
Yep that seems to fix it for me too

**Comment by mormj** [comment]
closed by #4949
