### ISSUE TITLE
Missing appropriate blocks: QT and UDH

### ISSUE THREAD

**Issue by rolledankle1000** [gnuradio/gnuradio#4973]
Hi Everyone, I have just downloaded and started GNURadio-Companion, and upon my inspection, I am missing a few blocks that I need. I am operating GNU Radio with a string of USRP x310's. I am missing the blocks needed to operate and use these devices, such as "usrp sink" etc. Anyone know how to go about getting these? I have downloaded GNU Radio via the Ettus manual say-so, along with UHD. Would it be possible that I need to add the UHD directory into the GNU Radio one? let me know what you think. 

-Thanks!

**Comment by willcode** [comment]
Please use chat.gnuradio.org or the mailing list for help requests. GitHub Issues is used for bug reports and feature requests.
