### ISSUE TITLE
Diffie hellman key exchange algorithm using GNU Radio

### ISSUE THREAD

**Issue by athulkannan2000** [gnuradio/gnuradio#4979]
I have a project idea to develop a secure communication network. For the first trial, I would like to develop my idea by using GNU Radio. How can I implement the diffie hellman key exchange algorithm in this platform i's an urgent matter please ping me if anyone knows about it.

**Comment by marcusmueller** [comment]
Hi, this is the GNU Radio bug tracker. For discussions, please see the mailing list or the chat: https://wiki.gnuradio.org/index.php/HowToGetInvolved
