### ISSUE TITLE
gr-video-sdl: clean up sink

### ISSUE THREAD

**Issue by willcode** [gnuradio/gnuradio#4993]
In the SDL sinks:
- [ ] `d_format` is not used (video format is inferred from number of inputs). This could be removed from the API. The block yml always sets it to `0`.
- [ ] `if (1)` code can be removed, was probably an experiment 2+ years ago.

**Comment by solomonbstoner** [comment]
Didnt see any PR for this. Ill do this. Will open a PR in a very short while
