### ISSUE TITLE
GRC Error

### ISSUE THREAD

**Issue by ik8ozv** [gnuradio/gnuradio#4996]
PHello All,
please i am noticing that when i receive something, at the end of the data i can read:

Error while submitting telemetry: <urlopen error [Errno -3] Errore temporaneo nella risoluzione del nome>

Please how to avoid it?
Thanks
Enzo

**Comment by dkozel** [comment]
Hi @ik8ozv,

That is (probably) an error with gr-satellites and uploading telemetry to SatNOGS, we won't be able to help here. The error says there's some problem resolving the URL. If you can find out what that URL is and check it outside of the application that will tell more about the issue. I hope you are able to solve it.
