### ISSUE TITLE
xmlrpc_client block doesn't accept address/callback parameters 

### ISSUE THREAD

**Issue by muaddib1984** [gnuradio/gnuradio#5006]
xmlrpc client block has variables for address and callback that were changed to dtype raw [here](https://github.com/gnuradio/gnuradio/pull/3554#issue-430591489) which worked in 3.8, now in 3.9 the raw dtype doesn't seem to be evalutated correctly. 
![xmlrpc_block_toplevel](https://user-images.githubusercontent.com/70996692/129451426-dcd1bda7-a68f-4a26-83e4-32b1b0137465.png)
![xmlrpc_client_variables](https://user-images.githubusercontent.com/70996692/129451436-a924a277-7749-4770-905f-65622804cd0f.png)

if the variables are quoted as strings in the block, the flowgraph can be generated, but the parameters as strings breaks the xmlrpc behavior in the generated flowgraph shown here:
`self.xmlrpc_client_0 = ServerProxy('http://"localhost":8080')`
`...`
`self.xmlrpc_client_0."set_freq"(self.freq)

the desired output would be

`self.xmlrpc_client_0 = ServerProxy('http://localhost:8001')`
`...`
`self.xmlrpc_client_0.set_freq(self.freq)`

i'm submitting a pull request for what i think is the best temporary solution, but it requires that the callback and local variable share the same name.

**Comment by muaddib1984** [comment]
Yes, we fixed this. Sorry for the dangling open issue.<end transmission>On Jan 29, 2024, at 07:47, Marcus Müller ***@***.***> wrote:﻿
https://gist.github.com/marcusmueller/f2b343e1e23e8fc903708c75d2df766d
repro5006.svg (view on web)
can't reproduce, seems to be fixed through #5008

**Comment by marcusmueller** [comment]
no worries! Was so happy to a) see it fixed and b) knowing it was your first PR :)
