### ISSUE TITLE
gr::log :INFO: packet_headerparser_b0 - Detected an invalid packet at item 48

### ISSUE THREAD

**Issue by wsx000** [gnuradio/gnuradio#5041]
when i try to run the example of **rx_ofdm/tx_ofdm** in **gr_digital/examples/ofdm** , it can't received what i transmitted, and reported as following:
```
gr::log :INFO: packet_headerparser_b0 - Detected an invalid packet at item 0
gr::log :INFO: header_payload_demux0 - Parser returned #f
gr::log :INFO: packet_headerparser_b0 - Detected an invalid packet at item 48
gr::log :INFO: header_payload_demux0 - Parser returned #f
gr::log :INFO: packet_headerparser_b0 - Detected an invalid packet at item 96
gr::log :INFO: header_payload_demux0 - Parser returned #f
gr::log :INFO: packet_headerparser_b0 - Detected an invalid packet at item 144
gr::log :INFO: header_payload_demux0 - Parser returned #f
gr::log :INFO: packet_headerparser_b0 - Detected an invalid packet at item 192
gr::log :INFO: header_payload_demux0 - Parser returned #f
gr::log :INFO: packet_headerparser_b0 - Detected an invalid packet at item 240
gr::log :INFO: header_payload_demux0 - Parser returned #f
......
```
do anyone met the same problem? i can't find the solution.

**Comment by willcode** [comment]
@wsx000 please head over to chat.gnuradio.org or the mailing list ... the issue tracker is used for bugs and feature requests. If this turns out to be a bug, reopen this issue with more info.

**Comment by mmmmmaple** [comment]
did you solve this problem?I met the same problem and I want to know how to solve this problem if you get rid of it

**Comment by zzy111-1** [comment]
Did you solve this problem now?I slightly modified ofdm_tx and rx in the official example, added usrp, and slightly modified parameters such as sampling rate and packet length, so this problem occurred. I searched online and still couldn't solve the problem, so I would like to ask you Any solution ideas?

**Comment by YamalQRA** [comment]
hi. did anyone solve the problem? my hardware is usrp b200mini-i
grc in zip attached
[test_codec2)ofdm.zip](https://github.com/user-attachments/files/17692836/test_codec2.ofdm.zip)

**Comment by marcusmueller** [comment]
I'm locking this thread. People, you're doing wireless communications – a packet containing error is not inherently a sign of a software bug.

And even more so, we already said that if you need help with something, you should head over to chat or mailing list. `packet_headerparser` has significantly been worked on since 2021, so clearly this specific issue should remain closed Thank you for understanding!
