### ISSUE TITLE
why when i use gnuradio for USRP with UHD for high sample rate record file is not work

### ISSUE THREAD

**Issue by stackprogramer** [gnuradio/gnuradio#5083]
I use a USRP x300, when i want to use uhd  and file sink in gnuradio , for high sample rate like 60M or 80M gnuradio can not record file.Gnuradio print some character on log: i want to record a sample not any other thing.
Is there any way that i can record with high sample rate in gnuradio?

my system is powerful:
Core i7
RAM 16
`
OOOOOOOOOOOOOO
`

**Comment by willcode** [comment]
Please use chat.gnuradio.org or the mailing list for help requests. The issue tracker is used for bug reports and feature requests.

**Comment by stackprogramer** [comment]
I got my answer, i shared it for futures.

`
Well if you’re recording complex float samples, that’s 8 bytes each. At 60msps that’s 480Mbyte/second. Not too many disk subsystems can keep up at that rate. 

You might try short recordings into a RAM disk filesystem. 
`
