### ISSUE TITLE
How to manipulate data with "channel model"？

### ISSUE THREAD

**Issue by liumaolin-931** [gnuradio/gnuradio#5087]
I am testing the "channel model" module, and I have created the following flow diagram:
![image](https://user-images.githubusercontent.com/75609643/134303041-802a42b6-5319-4057-81d1-8ab7b4322bb5.png)
I set Taps to 1, the others remain unchanged
I observed input data and output data, input (0,1,2,3,...198,199), output is (3,4,5,6,...192,193,194), And 195~199 and 0~2 of input data were discarded，The first small part and the next small part of the input sequence are discarded,Why does this happen? I can't understand，does anyone know? thanks

**Comment by willcode** [comment]
This can be unexpected, but is how GNU Radio works. There is no guarantee that all samples will be flushed before the flowgraph stops. Blocks have "history" and "output multiples", which can cause samples to be unprocessed. Please continute the conversation on chat (I see that you are there already).

**Comment by liumaolin-931** [comment]
Okay, thank you very much for your reply, I will return to the chat




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "gnuradio/gnuradio"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年9月22日(星期三) 晚上9:00
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [gnuradio/gnuradio] How to manipulate data with "channel model"？ (#5087)





 
This can be unexpected, but is how GNU Radio works. There is no guarantee that all samples will be flushed before the flowgraph stops. Blocks have "history" and "output multiples", which can cause samples to be unprocessed. Please continute the conversation on chat (I see that you are there already).
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
