### ISSUE TITLE
Qt GUI Dial - weird behaviour

### ISSUE THREAD

**Issue by bernerus** [gnuradio/gnuradio#5107]
The Qt GUI Dial default value seems to be the exact value returned when read from other blocks, not the knob position. This works OK if the scale factor is 1.
 
If it is, say 0.01, the knob is initially set to a 1/100th of angle that represents the default value when the scale factor is applied, and the displayed value is also 1/100th of the default value.

Conversely, if the default value is interpreted as the initial knob position, the returned value does not account for the scale factor - until the knob is moved.

It needs to be documented whether the default value refers to the actual value or the knob position and then either divide with the scale factor to set the initial position or apply the scale factor when setting the default value.

**Comment by madhavpcm** [comment]
Hello, I would like to contribute to this issue. It would be great if I know where to begin.

**Comment by dkozel** [comment]
@madhavpcm Here is the main source code file for the Dial.
https://github.com/gnuradio/gnuradio/blob/master/gr-qtgui/python/qtgui/dialgauge.py

If you are new to GNU Radio this documentation page about the structure of blocks might be useful, though this bug is probably a straightforward math error in the code.
https://wiki.gnuradio.org/index.php/BlocksCodingGuide
https://wiki.gnuradio.org/index.php/Tutorials

@bernerus Could you supply an example flowgraph? And/or some screenshots showing the current incorrect behavior? Thank you!

**Comment by bernerus** [comment]
[qt_gui_dial_weirdness.grc.zip](https://github.com/gnuradio/gnuradio/files/7274174/qt_gui_dial_weirdness.grc.zip)

Here is an example flowgraph and two screenshots.
The dial min and max is 0-100, and the scale factor is 0.1 which means that the actual values should be between 0 and 10. The default value is 5. 

When starting, the dial value says 0.5 but the actual value is 5, then click the dial and move it just a tiny bit, the dial value changes to, say 0.70 and the actual value changes from 5 to 700m. Then set the dial to the mid position, the dial says 5.00 and the actual value says 5.0. 
The problem occurs only upon start, but once the dial has been moved, everything is OK.

<img width="500" alt="image" src="https://user-images.githubusercontent.com/4038167/135764718-fa79f715-6574-4108-a2b6-3fdfda61f1d5.png">

<img width="484" alt="image" src="https://user-images.githubusercontent.com/4038167/135764782-8edcb596-d580-4087-96b5-291f6b938c02.png">

**Comment by furiousluck** [comment]
hi , i want to know how to test my code if i have made some changes?

**Comment by bernerus** [comment]
Well, the expected behaviour in the example I supplied would be that when starting, the knob would point straight up showing the value 5.00, then if the knob is turned left, the text for the knob should decrease smoothly and if turning right it should increase smoothly, an in all cases the values shown should be the same, value-wise, i.e. 0.9 may be shown as 900m

**Comment by marcusmueller** [comment]
Still present, still a bug.
