### ISSUE TITLE
pybind11 on ubuntu18

### ISSUE THREAD

**Issue by jackdondy** [gnuradio/gnuradio#5124]
The default version of **pybind11-dev** and **python3-pybind11** of ubuntu18.04 is 2.0.1-4, which is too old to satisfy the version requirement of gnuradio3.9 (version 2.4 or higher, mentioned in issue #3845 ).
I downloaded [pybind11-dev_2.6.2-1_all.deb](https://packages.debian.org/bullseye/pybind11-dev) and [python3-pybind11_2.6.2-1_all.deb](https://packages.debian.org/bullseye/python3-pybind11) from debian.org, then ran the following commands:
```
sudo dpkg -i pybind11-dev_2.6.2-1_all.deb
sudo dpkg -i python3-pybind11_2.6.2-1_all.deb
```
This solve the problem.
Maybe [installing gnuradio3.9 from gnuradio-master PPA](https://wiki.gnuradio.org/index.php/InstallingGR)  don't have this problem, but I haven't take a try.

**Comment by willcode** [comment]
Glad that works. This does not look like a bug, so closing.
