### ISSUE TITLE
Waveform Generators - Waveform label shows options rather than option_labels

### ISSUE THREAD

**Issue by Karl-Keller** [gnuradio/gnuradio#5126]
Newbie alert.  I've followed the suggestions for posting questions and found nothing on this. 

Installed (conda) and running version Python 3.8.1.1 (reports primary version as 3.9.2.0) in Anaconda 2.0.4. Running on Windows 10, with .Net 5.0.10 x64.  Have tried various other .Net variations including x86 and the dotnet runtime for x64. (I had them because of SDR#)

On startup of gnuradio-companion from the command prompt and recreating the base tutorial example with Signal Source, error (red) shown with Waveform options rather than labels.  e.g.  Waveform: analog.GR_COS_WAVE.  Confirmed this data by looking at the analog_sig_source_x.block.yml.

The error reported is:  Param - Waveform(waveform):
	Value "analog.GR_COS_WAVE" cannot be evaluated:
	name 'analog' is not defined

Which led me to path inspections to find analog - both Path and PYTHONPATH expose the Anaconda3/Lib/site-packages and .../envs/radio/Lib/site-packages along with the DLL paths that might be involved.

Any insight much appreciated.

**Comment by willcode** [comment]
Please use chat.gnuradio.org or the mailing list for help requests. The issue tracker is used for bugs and feature requests. Thanks.
