### ISSUE TITLE
ModToolException: Could not find gr-newmod source dir.

### ISSUE THREAD

**Issue by stackprogramer** [gnuradio/gnuradio#5140]
In Gnuradio-dev 3.9 when I want to create a block I am faced with this error...  how can solve it...

`
gr_modtool newmod tutorial
ModToolException: Could not find gr-newmod source dir.
`

**Comment by willcode** [comment]
Please ask for help on chat.gnuradio.org or the mailing list. The issue tracker is used for bug reports and feature requests. Thanks.

**Comment by mormj** [comment]
I think this is a real issue - reproduced on a fresh Ubuntu 20.04 docker with GR installed from the PPA

gr_modtool newmod indeed returns that error.

It should find the template from the prefix, but gnuradio-config-info returns
`./`

the conf files in /etc point to the right place. I'm guessing this is a PPA deb file configuration issue - would be curious if the same issue exists under Debian

**Comment by willcode** [comment]
OK. For reference, with maint-3.9 and master on F34:
```
$ gr_modtool newmod tutorial
Creating out-of-tree module in ./gr-tutorial...
Done.
Use 'gr_modtool add' to add a new block to this currently empty module.
```

**Comment by lofaldli** [comment]
Running this worked for me on Ubuntu 20.04:
```
$ cd /usr/share/gnuradio/modtool/templates/gr-newmod
$ sudo py3clean .
```
Source: https://wiki.gnuradio.org/index.php/InstallingGR#Modtool_on_Ubuntu
