### ISSUE TITLE
qtgui: Qt digital number control output message lags input message by one

### ISSUE THREAD

**Issue by bernerus** [gnuradio/gnuradio#5141]
Well, it's hard to find a suitable heading sometimes. Whatever, when I tick the numbers on the GUI, the new frequency is sent on the output port, but If I send a new frequency to the dial, via the input port,  the dial then sends the *old* frequency on its output port. This may be intended behaviour, but feels a bit nonintuitive to me.
Actually, when looking into the code it seems like the intention is to send the new frequency. I suspect this happens because there is a race condition somewhere.

Adding a demo flowgraph. You may have to expand its window when running. See the console log as well.
The TX FREQUENCY dial is there just to show what RX frequency sends.

[dncbug.grc.zip](https://github.com/gnuradio/gnuradio/files/7285827/dncbug.grc.zip)

Initial view:
<img width="1169" alt="image" src="https://user-images.githubusercontent.com/4038167/136023912-b0134da3-c580-4719-8ec2-ecdf75a30386.png">

After clicking the red bar:

<img width="1147" alt="image" src="https://user-images.githubusercontent.com/4038167/136024084-5a60697e-680b-4f35-b6c2-dd02aca7ab28.png">

Clicking again:
<img width="1144" alt="image" src="https://user-images.githubusercontent.com/4038167/136024181-f3920c95-a7f7-47a2-96ce-a1928e1b8ada.png">

**Comment by marcusmueller** [comment]
Tried, really seems closed through #5592
