### ISSUE TITLE
Gnuradio with UHD 4

### ISSUE THREAD

**Issue by stackprogramer** [gnuradio/gnuradio#5142]
Hi, I had a question with Gnuradio 3.7.10 or 3.8, UHD version that is used is 3.13 or 3.15. I used the apt-get install command...
How can install UHD 4 on Debian ubuntu without compiling it...
All work with USRP is in Gnuradio...

**Comment by willcode** [comment]
Please use chat.gnuradio.org or the mailing list for help requests. The issue tracker is used for bug reports and feature requests. Thanks.
