### ISSUE TITLE
GRC Errors list displays "default" instead of "Options"

### ISSUE THREAD

**Issue by dkozel** [gnuradio/gnuradio#5150]
The Options block name is not correctly shown in the Errors list.

![Screenshot from 2021-10-07 09-37-01](https://user-images.githubusercontent.com/253888/136349737-b681bb74-22b8-48d4-a7c1-49f2108e03be.png)

**Comment by mpentler** [comment]
Only issue I've just realised is that the generated .py file takes that id entry for its name, so maybe we need to change it to something else. "new_file", "new_flow_graph" - for example. But it can't be options as it will get confusing for users.

**Comment by marcusmueller** [comment]
The id blacklisting, the default ID and the conflict handling have been extensively worked over, plus, the UI aspect of this would be subject to Qt-GRC's interaction paradigms; closing for now.
