### ISSUE TITLE
Choose Editor menu needs to stay above parent dialog

### ISSUE THREAD

**Issue by dkozel** [gnuradio/gnuradio#5151]
In default Ubuntu configurations the GTK dialogs are forcibly locked to the center of their parent window. This means that if someone opens the properties on an Embedded Python Block, clicks "Open in Editor", and then clicks anywhere else other than the Choose Editor dialog it can end up hidden behind the Embedded Python Block properties dialog. This results it it being impossible to close the dialog, or even GRC, as all interactions with the lower layers are prevented while the Choose Editor dialog is open.

The fix is to lock the Choose Editor dialog to stay above the parent dialog (Embedded Python Properties).
https://github.com/gnuradio/gnuradio/blob/1a0be2e6b54496a8136a64d86e372ab219c6559b/grc/gui/Dialogs.py#L400

I believe the Gtk `set_keep_above()` function will solve this.

![Screenshot from 2021-10-07 09-49-20](https://user-images.githubusercontent.com/253888/136352768-c98aff96-c0a3-4e2b-b57a-45090634a428.png)

**Comment by mpentler** [comment]
@Jsiddareddi-intuit do you have something ready to go for this? Don’t want to step on your toes!

I think it’d go before the .run() @ L189 and then it’s fixed for every call?

https://github.com/gnuradio/gnuradio/blob/master/grc/gui/Dialogs.py#L189

**Comment by mpentler** [comment]
Well - I’ve tried it @ L189,  but it didn’t work at all on my Ubuntu VM.
