### ISSUE TITLE
modtool: support tab completions

### ISSUE THREAD

**Issue by mormj** [gnuradio/gnuradio#5206]
### Feature Description

would be very nice to have tab completions with modtool, for example

gr_modtool <tab>
would print out 
newmod add ...

### Feature Urgency

low (just an idea)

**Comment by marcusmueller** [comment]
b0912d31f1a2cfea93a5588898cae0c652cd89d4

really just need better application to everything!

**Comment by AsriFox** [comment]
This seems to be relatively easy, because Click has this feature built-in ([docs](https://click.palletsprojects.com/en/latest/shell-completion/)). It works for me in bash.
Trying to figure out how to call `_GR_MODTOOL_COMPLETE=bash_source gr_modtool` from CMake.
