### ISSUE TITLE
gr_modtool makeyaml produces some invalid fields 

### ISSUE THREAD

**Issue by mormj** [gnuradio/gnuradio#5222]
### What happened?

gr_modtool makeyaml produces some invalid fields due to the regex parsing of the impl files

### System Information

OS: Ubuntu 20.10
GR Installation Method: source

### GNU Radio Version

3.10-git (master)

### Specific Version

395-gc3c411be

### Steps to Reproduce the Problem

1) Create a block with gr_modtool
2) gr_modtool makeyaml myblock

The output yaml has a few issues - see log output

### Relevant log output

```shell
id: cudademo_multiply_const
label: multiply const
category: '[Cudademo]'
templates:
  imports: import cudademo
  make: cudademo.multiply_const(${k})
parameters:
- id: k
  label: K
  dtype: float
inputs:
- label: in
  domain: stream
  dtype: raw
  multiplicity: 1 /* max inputs */
outputs:
- label: out
  domain: stream
  dtype: raw
  multiplicity: 1 /*max outputs */
file_format: 1
```

**Comment by catkira** [comment]
I have the same problem, any chance this will be fixed?

**Comment by marcusmueller** [comment]
@catkira as soon as someone finds the time to try! Wanna give it a go?

**Comment by marcusmueller** [comment]
Still reproduces. Small script to test this (we could upstream that as unit test once gr_modtool can create blocks without QA without manual interaction) included: 

https://gist.github.com/marcusmueller/f03ff708e0975c82dc80c06156c1ae3b
