### ISSUE TITLE
qa: take_skip_to_pdu_X failed in CI

### ISSUE THREAD

**Issue by mormj** [gnuradio/gnuradio#5258]
### What happened?

On Centos8.4 runner - see log output below

### System Information

OS: Centos8.4 CI runner
GR Installation Method: source

### GNU Radio Version

3.10-git (master)

### Steps to Reproduce the Problem

Run through the CI

### Relevant log output

```shell
======================================================================
ERROR: test_003_s_2_11_7 (__main__.qa_take_skip_to_pdu_X)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/__w/gnuradio/gnuradio/gr-pdu/python/pdu/qa_take_skip_to_pdu.py", line 83, in test_003_s_2_11_7
    actual = self.debug.get_message(7)
RuntimeError: message_debug: index for message out of bounds.
```

**Comment by marcusmueller** [comment]
CI currently runs all tests successfully, CentOS8 currently hard to support -> close
