### ISSUE TITLE
Type error in QT GUI Range Widget

### ISSUE THREAD

**Issue by ruurdjan** [gnuradio/gnuradio#5341]
### What happened?

Using the QT GUI Range widget in either Counter, Slider or Counter+Slider mode causes a Type Error, regardless of Widget Type.

### System Information

OS: Fedora Linux 35 (Workstation Edition)
GR Installation Method: native distro packages - 3.9.2.0 (Python 3.10.0)

### GNU Radio Version

3.9 (maint-3.9)

### Specific Version

9.3.2.0

### Steps to Reproduce the Problem

Use a QT GUI Range widget in either Counter, Slider or Counter+Slider mode.

### Relevant log output

```shell
Traceback (most recent call last):
  File "/home/ruurdjan/rangetest.py", line 199, in <module>
    main()
  File "/home/ruurdjan/rangetest.py", line 177, in main
    tb = top_block_cls()
  File "/home/ruurdjan/rangetest.py", line 87, in __init__
    self._freq_win = RangeWidget(self._freq_range, self.set_freq, 'Frequency', "counter_slider", int, QtCore.Qt.Horizontal)
  File "/usr/lib64/python3.10/site-packages/gnuradio/qtgui/range.py", line 121, in __init__
    self.d_widget = self.CounterSlider(self, self.range, self.notifyChanged, rangeType, orientation)
  File "/usr/lib64/python3.10/site-packages/gnuradio/qtgui/range.py", line 262, in __init__
    self.slider = RangeWidget.Slider(parent, ranges, self.sliderChanged, rangeType, orientation)
  File "/usr/lib64/python3.10/site-packages/gnuradio/qtgui/range.py", line 161, in __init__
    self.setRange(0, ranges.nsteps - 1)
TypeError: setRange(self, int, int): argument 2 has unexpected type 'float'
```

**Comment by willcode** [comment]
There's already a PR in to fix this ... linked it to this issue. This should be fixed in the next releases.

**Comment by ruurdjan** [comment]
Thanks! I couldn't for the life of me find it in the Issue tracker but didn't search the commits.

**Comment by willcode** [comment]
Sometimes the fix gets in with no issue. You can do a search like this:

https://github.com/gnuradio/gnuradio/issues?q=is%3Aopen+range+
