### ISSUE TITLE
libfmt dependency

### ISSUE THREAD

**Issue by michael-roe** [gnuradio/gnuradio#5352]
### What happened?

gnuradio now depends on libfmt-dev, but the cmake machinery doesn't check whether it's installed.

### System Information

OS: Ubuntu 20.04
GR Installation Method: source

### GNU Radio Version

3.10-git (master)

### Specific Version

0.0.0.0

### Steps to Reproduce the Problem

mkdir build
cd build
cmake -DCMAKE_BUILD_TYPE=Release -DPYTHON_EXECUTABLE=/usr/bin/python3 ../

**Comment by michael-roe** [comment]
This issue is the same as an existing issue.

**Comment by dkozel** [comment]
Existing issue: https://github.com/gnuradio/gnuradio/issues/5349
