### ISSUE TITLE
Variable Config does not handle runtime changes to "section" correctly

### ISSUE THREAD

**Issue by willcode** [gnuradio/gnuradio#5359]
### What happened?

If the "section" parameter is controlled by another variable (e.g., a Chooser) at runtime, it generates unexpected code. In response to a change in "section", the variable is unconditionally written to the new section. The semantics of this block are unclear. User "Elmore's" reports on the mailing list that this is not what they think the block should do.

Here is the section change handler code generated for a couple of variables:
```
    def set_section(self, section):
        self.section = section
        self._freq_config_config = configparser.ConfigParser()
        self._freq_config_config.read('/tmp/testconfig.ini')
        if not self._freq_config_config.has_section(self.section):
                self._freq_config_config.add_section(self.section)
        self._freq_config_config.set(self.section, 'freq', str(self.freq))
        self._freq_config_config.write(open('/tmp/testconfig.ini', 'w'))
        self._lna_config_config = configparser.ConfigParser()
        self._lna_config_config.read('/tmp/testconfig.ini')
        if not self._lna_config_config.has_section(self.section):
                self._lna_config_config.add_section(self.section)
        self._lna_config_config.set(self.section, 'lna', str(self.lna))
        self._lna_config_config.write(open('/tmp/testconfig.ini', 'w'))
        self._section_callback(self.section)
```

### System Information

All

### GNU Radio Version

3.9 (maint-3.9)

### Specific Version

0.0.0.0

### Steps to Reproduce the Problem

Create a Variable Config with writeback. Specify an external control (e.g., chooser) as the value for "section". Changes sections at runtime and view the ini file.

**Comment by marcusmueller** [comment]
https://gist.github.com/marcusmueller/d1048c4655584f9195c42ab6626ace6e
![repro5359](https://github.com/gnuradio/gnuradio/assets/958972/493c6dcb-02f4-4bf4-bae4-82d72b010009)

defaults.ini after setting the section twice:
```ini
[bar]
value = 0

[baz]
value = 0

```

Looks pretty expected to me. If I change the section, I need the value to be written to the new section.

Still should be better documented, but that's not a correctness bug
