### ISSUE TITLE
examples/filter/filter_taps.grc

### ISSUE THREAD

**Issue by cinaeds** [gnuradio/gnuradio#5368]
### What happened?

Exited with error. 

File "./filter_taps.py", line 172
    self.set_br_taps(firdes.<class 'type'>(

SyntaxError: invalid syntax

### System Information

Debian 10 buster - GR was built from source code.

### GNU Radio Version

3.8 (maint-3.8)

### Specific Version

3.8.40

### Steps to Reproduce the Problem

Simple run the ./examples/filter/filter_taps.grc code shipped with the source code. 

To fix the problem I replaced 

   self.set_br_taps(firdes.<class 'type'>(...) 

with 

  self.set_br_taps(firdes.band_reject(...)

**Comment by willcode** [comment]
Thanks for the report. There was a bug in the grc yml file for that block.

**Comment by willcode** [comment]
Fixed on maint-3.8. Versions 3.9+ were already ok.
