### ISSUE TITLE
self.setRange argument has 2 unexpected type 'float'

### ISSUE THREAD

**Issue by blackwiz4rd** [gnuradio/gnuradio#5401]
### What happened?

When running a program with QT GUI Range set to float (python3.10) the following message appears:
```
 File "/usr/lib/python3.10/site-packages/gnuradio/qtgui/range.py", line 161, in __init__
    self.setRange(0, ranges.nsteps - 1)
TypeError: setRange(self, int, int): argument 2 has unexpected type 'float'
```
A temporary solution might be setting Options/Run Command to `/usr/bin/python3.9 -u {filename}` after installing the older python.

### System Information

OS: Arch Linux
GR Installation Method: pacman

### GNU Radio Version

3.9 (maint-3.9)

### Specific Version

3.9.4.0

### Steps to Reproduce the Problem

Run program with float QT GUI Range

**Comment by willcode** [comment]
Thanks for the report. This was fixed recently (#5343 #5287 ) and the fix will be in the upcoming releases.
