### ISSUE TITLE
QT GUI Number Control 'value out' emits previous value for 'value in' messages or variable changes

### ISSUE THREAD

**Issue by muaddib1984** [gnuradio/gnuradio#5412]
### What happened?

In the QT GUI digital number control widget example in GNURadio 3.9, the 'value out' port emits it's previously stored value when either a new input message arrives or (if) a variable is used in the 'value' field and it's changed from another source (i.e. range widget).

### System Information

OS: Ubuntu20.04
GR Installation Method: pybombs

### GNU Radio Version

3.9 (maint-3.9)

### Specific Version

3.9.4.0

### Steps to Reproduce the Problem

Using the Digital Number Control example [here:](https://github.com/gnuradio/gnuradio/blob/master/gr-qtgui/examples/test_digitalnumcontrol.grc)
Start with 90e6 as the initial value of 'freq'  for both the message edit box and the number control, then change the value of 'freq' in the message edit box to 95e6. The number control display will change to 95,000,000 but the message emitted from the 'value out' port will be 90e6. If you change the edit box again, now 95e6 will be emitted from the 'value out' port.

**Comment by willcode** [comment]
The problem has to do with `self.cur_freq` not being set immediately when the frequency is set by the message handler.
