### ISSUE TITLE
Windows installer - malformed shebang path

### ISSUE THREAD

**Issue by davezap** [gnuradio/gnuradio#5419]
### What happened?

Windows 10 21H1
Installed from: http://www.gcndevelopment.com/gnuradio/downloads/installers/v3.8.2.1/gnuradio_3.8.2.0_win64.msi

### System Information

OS: (Linux Distro, Mac, Windows)
GR Installation Method: (native distro packages - apt, rpm, etc., Conda, Source

### GNU Radio Version

3.8 (maint-3.8)

### Specific Version

v3.8.2.0-57-gd71cd177

### Steps to Reproduce the Problem

Fresh installation to c:\gn\
Run 
C:\gn\bin>gr_modtool.py
Unable to create process using 'C:\gr\src-stage1-dependencies♂cpkg\installedd-windows   ools\python3\python.exe "C:\gn\bin\gr_modtool.py" '

Notice weird unicode character? Looks to me like some string copy error.

If I open gr_modtool.py the first line
```
#!C:\gr\src-stage1-dependenciescpkg\installedd-windows	ools\python3\python.exe
```

This should read 
`#!C:\gn\tools\python3\python.exe`

shebang in 105 other .py files has the same thing, I won't list them all.

If I make this change manually gr_modtool.py works, well not really but it does not throw an error. I get Windows support for these scrips is minimal.

**Comment by mormj** [comment]
The windows packages as hosted on gcndevelopment.com are not maintained by the project, so it will be hard to address anything from within this repo.  Please reach out to the maintainer of the Windows packages
