### ISSUE TITLE
issue / bug report template doesn't contain maint-3.10

### ISSUE THREAD

**Issue by marcusmueller** [gnuradio/gnuradio#5427]
### What happened?

A bug happened! Ans so I reported it. It struck me that you can't select maint-3.10!

### System Information

--

### GNU Radio Version

3.10-git (master)

### Specific Version

--

### Steps to Reproduce the Problem

report bug via github's web interface

**Comment by mormj** [comment]
Closing as your changes to the template got copied via another PR
