### ISSUE TITLE
Weird pulse shaping (RRC) with the constellation modulator

### ISSUE THREAD

**Issue by GillesC** [gnuradio/gnuradio#5449]
### What happened?

Strange behavior of the pulse shaping for the constellation modulator block. 

### System Information

OS: Ubuntu 20.04
GR Installation Method: apt

### GNU Radio Version

3.9 (maint-3.9)

### Specific Version

3.9.4.0

### Steps to Reproduce the Problem

Create a QPSK/BPSK modulator block with the constellation modulator with any RRC parameters and check the imaginary and real part of the outputted complex signal.
I would expect that for the BSPK symbol 0 (non-differential), the imaginary part would be zero, and the real part would have a pulse (shaped according to the RRC) with a negative amplitude. However, the real part is just -1, so no pulse shaping is applied.

![image](https://user-images.githubusercontent.com/8626571/148543782-8523da29-19aa-4b72-89c0-fe044e932153.png)
![image](https://user-images.githubusercontent.com/8626571/148543864-b86975d2-f75f-49b3-9908-3be0c08abb61.png)

For symbol 1 (BPSK) the following is outputted from the block.
![image](https://user-images.githubusercontent.com/8626571/148544476-02b39b2b-eb5c-4b6c-bab6-183b02b261cb.png)
I would also have expected that the pulses were situated (crossing) at 0, instead of -1 as shown here.

**Comment by willcode** [comment]
It's the total I/Q signal that matters, since they are not transmitted or processed separately.

**Comment by aoweis** [comment]
Hi,
I have the same question and could not really understand the provided answer. For a zero symbol, the output of the constellation modulator should be:
Real: an RRC pulse with negative amplitude
Imaginary: zero.

However, the output as shown in GillesC question has a constant real part at -1. Why is not convolved with the RRC pulse shape?
I'm not sure I understand the given answer, the I and Q samples are combined in the RF signal but then separated again at the receiver baseband, and the decision of the value of the symbol is taken based on value of Real and Imaginary parts together.
