### ISSUE TITLE
Bus ports not working for Polyphase Channelizer under gnuradio 3.9

### ISSUE THREAD

**Issue by akoun** [gnuradio/gnuradio#5490]
### What happened?

Giving a bus specification for a 5 output Polyphase Channelizer: [[0,1], [2,3,4]]
and then toggling the busport view results in only one busport.

My experience comes from the same path as reported in:
https://dsp.stackexchange.com/questions/75516/gnuradio-busports-and-channel-map-for-polyphase-channelizer-block

I think PFB are especially useful when the number of channels is large and in that case working busports is a must have.

The image below illustrates what's happening (the busport spec works for the Null source but does not for the Polyphase channelizer.

![image_2022-01-17_121801](https://user-images.githubusercontent.com/28650382/149760388-650f0602-264a-4a9b-84a0-4fa6aeb5322f.png)

best regards
aK

### System Information

OS: Debian bookworm
GR Installation Method: distro packages

### GNU Radio Version

3.9 (maint-3.9)

### Specific Version

3.9.4.0

### Steps to Reproduce the Problem

Instantiate a Polyphase Channelizer
set channels to 5
set bus connections to [[0,1,2],[3,4]]
toggle bus source

**Comment by mormj** [comment]
Thank you for sharing this issue - busports are a grc specific feature which probably leads to them getting broken and not super tested.  But this is something that needs investigating
