### ISSUE TITLE
cmake is missing checks for components required to build gnuradio

### ISSUE THREAD

**Issue by balister** [gnuradio/gnuradio#5510]
### What happened?

With a new F35 install, I build gnuradio by compiling and installing packages to clear cmake failures and turn on enough components to be useful. After a good cmake run, the compile failed. After installing the following packages the build worked and passed QA checks.

python3-zmq (for zmq block QA)
python3-devel (for Python.h)

### System Information

Fedora 35

### GNU Radio Version

3.11-git (main)

### Specific Version

HEAD

### Steps to Reproduce the Problem

See above

**Comment by drmpeg** [comment]
The python3-zmq for QA issue has been around for as long as I can remember.

**Comment by drmpeg** [comment]
On Ubuntu, python3-dev gets installed with libboost-all-dev (as part of libboost-python-dev).

**Comment by willcode** [comment]
Help request - use chat.gnuradio.org or the mailing list for further help.
