### ISSUE TITLE
grc: write out grc_version based on actual version

### ISSUE THREAD

**Issue by willcode** [gnuradio/gnuradio#5521]
### Feature Description

In grc files, `grc_version` is statically set to `3.8.0` in `grc/core/default_flow_graph.grc`.

Write out the actual version, in `a.b.c.d` form when saved by GRC.

### Feature Urgency

medium (would be nice to have in the near future)

**Comment by marcusmueller** [comment]
I'd actually call this a bug!

**Comment by dkozel** [comment]
Some quick notes about the areas that this would need to be implemented in.

An example of an in-tree example from maint-3.7 that has the GRC version in the XML.
https://github.com/gnuradio/gnuradio/blob/maint-3.7/gr-blocks/examples/peak_detector2.grc#L2

Where in the GRC XML->YAML converter it'd read the GRC version.
https://github.com/gnuradio/gnuradio/blob/942aff023d2c8152623aacb433ba2ce9a99ad3df/grc/converter/flow_graph.py#L25

Where the file_format is currently set:
https://github.com/gnuradio/gnuradio/blob/942aff023d2c8152623aacb433ba2ce9a99ad3df/grc/core/FlowGraph.py#L398

GR version is available in a flowgraph object in `self.parent.config.version` I'm pretty sure. The `FlowGraph` parent is `Platform` so in the actual save_flowgraph function it could be accessed as `self.config.version`.
https://github.com/gnuradio/gnuradio/blob/942aff023d2c8152623aacb433ba2ce9a99ad3df/grc/core/platform.py#L349
