### ISSUE TITLE
Some gr-digital/examples/packet do not produce expected tags

### ISSUE THREAD

**Issue by duggabe** [gnuradio/gnuradio#5528]
### What happened?

While testing https://github.com/gnuradio/gnuradio/blob/main/gr-digital/examples/packet/example_corr_est_and_clock_sync.grc I found that there are no signals on the QT GUI Time traces. They are set for tag trigger on `corr_est` and `corr_start` tags, but there don't seem to be any tags. If I change to Auto trigger, the data can be seen, but no tags at all.

A similar problem exists with https://github.com/gnuradio/gnuradio/blob/main/gr-digital/examples/packet/example_corr_est_and_phase_sync.grc

### System Information

OS: Ubuntu 20.04.3
GR Installation Method: Source

### GNU Radio Version

3.10 (maint-3.10)

### Specific Version

v3.10.1.0-rc1

### Steps to Reproduce the Problem

Execute the example grc files.

**Comment by dl1ksv** [comment]
@duggabe This behaviour seems to be correct but the examples are malformed. In both examples the correlation estimator produces no tags, as the threshold value is selected improper.
Just change the threshold method from absolute to dynamic or reduce the threshold value from 0.999 to 0.1.

Then you'll see all expected tags.
