### ISSUE TITLE
Custom Buffers breaks DVB-T receiver flow graph.

### ISSUE THREAD

**Issue by drmpeg** [gnuradio/gnuradio#5542]
### What happened?

A bug happened!

### System Information

OS: Ubuntu 20.04, 21.10
GR Installation Method: Source

### GNU Radio Version

3.11-git (main)

### Specific Version

tip of main

### Steps to Reproduce the Problem

Run the example flow graph gr-dtv/examples/dvbt_rx_8k.grc. The flow graph fails because it can't allocate enough input items for a block. However, the request is not large and worked fine before.

I've bisected the bug to commit https://github.com/gnuradio/gnuradio/commit/f3c558d88bc68d865f823c31e7d9aa78b3feab59

The test file for dvbt_rx_8k.grc can be downloaded here:

https://www.w6rz.net/adv16.cfile

@mormj @dsorber 

### Relevant log output

```shell
block_executor :error: sched: <block dvbt_demod_reference_signals (9)> is requesting more input data  than we can provide.  ninput_items_required = 2  max_possible_items_available = 1  If this is a filter, consider reducing the number of taps.
```

**Comment by mormj** [comment]
Unfortunately that's a huge commit to pinpoint a specific change, but I'll start debugging ....
