### ISSUE TITLE
Phase modulator block

### ISSUE THREAD

**Issue by R8LBL** [gnuradio/gnuradio#5555]
### Feature Description

Hello...
Need to get phase modulated signal with external information inputs
In simple, need block which will implement this function:
![image](https://user-images.githubusercontent.com/85429698/152502501-f477e448-9139-4b1e-b838-898ed06a9aed.png)
where "x" is external carrier and "p" is external audio signal
Thanks in advance

### Feature Urgency

medium (would be nice to have in the near future)

**Comment by willcode** [comment]
The feature you need is most likely already supported by GNU Radio. Please join chat.gnuradio org or ask for help on the mailing list. Closing, at this appears to be a supported feature.
