### ISSUE TITLE
python-zmq dependency inconsistent between Debian and RPM packaging

### ISSUE THREAD

**Issue by charles-dyfis-net** [gnuradio/gnuradio#5558]
### What happened?

The Debian package for GNU radio [lists python3-zmq as a mandatory dependency](https://github.com/gnuradio/gnuradio/blob/120268de56dbf1a1ab01e27c601cd7d1342afaf7/.packaging/debian/control#L59).

The Fedora package [lists only cppzmq-devel and zeromq-devel](https://github.com/gnuradio/gnuradio/blob/120268de56dbf1a1ab01e27c601cd7d1342afaf7/.packaging/fedora/gnuradio.spec), but does not list `python3-zmq`.

This inconsistency is in part relevant because the NixOS package maintainer is asking for an official declaration from upstream on whether the Python ZeroMQ packaging should be considered a mandatory dependency; discussion in NixOS/nixpkgs#158070

---

Ideally, there would be a a decision that this _should_ be a dependency everywhere, _shouldn't_ be a dependency anywhere, or that the Fedora ecosystem is a special case (maybe there are inconsistently named packages for python3-zmq across distro releases consuming these RPMs?)

### System Information

N/A

### GNU Radio Version

3.11-git (main)

### Specific Version

0.0.0.0

### Steps to Reproduce the Problem

N/A

**Comment by marcusmueller** [comment]
definitely a dependencey on `probe_manager.py`, `rpc_manager.py` (and a test dependency).

Also, Debian 12 depends on python3-zmq, so this seems to be solved!
