### ISSUE TITLE
Faiure of source build with pybombs recipe gnuradio-default with swig arguments

### ISSUE THREAD

**Issue by john-g8cqx** [gnuradio/gnuradio#5590]
### What happened?

build failed with swig argument errors flagged...
[transcript.txt](https://github.com/gnuradio/gnuradio/files/8103706/transcript.txt)

### System Information

ubuntu 20.04.3
GR Installation Method: pybomb
[transcript.txt](https://github.com/gnuradio/gnuradio/files/8103717/transcript.txt)
s

### GNU Radio Version

3.8  (maint-3.8)

### Specific Version

0.0.0.0

### Steps to Reproduce the Problem

[transcript.txt](https://github.com/gnuradio/gnuradio/files/8103718/transcript.txt)

**Comment by jmfriedt** [comment]
Same issue with Debian/testing (bookworm)

**Comment by mormj** [comment]
Since this appears to be an issue with pybombs itself, please open the issue under github.com/gnuradio/pybombs
