### ISSUE TITLE
Misinformation in fft filter header file

### ISSUE THREAD

**Issue by srmnw** [gnuradio/gnuradio#5741]
Not really a bug, but the fft_filter.h file ist documenting the FFT filtering is done by usage of the overlap-save algorithm. 

https://github.com/gnuradio/gnuradio/blob/b554eeab2e70cad520d85dd190eac862cefc9bd0/gr-filter/include/gnuradio/filter/fft_filter.h#L31

In fact, as far as I see, the filtering is done using the overlap-add algorithm.

**Comment by DevanshRaizada** [comment]
Hello @marcusmueller, I would like to work on this issue.

**Comment by Ansha4** [comment]
I want to work on this issue. @marcusmueller can you please provide more info about this issue?
