### ISSUE TITLE
TypeError: primitive_connect(): incompatible function arguments

### ISSUE THREAD

**Issue by ivannunyadambiz** [gnuradio/gnuradio#5752]
### What happened?

got
`TypeError: primitive_connect(): incompatible function arguments. The following argument types are supported:
    1. (self: gnuradio.gr.gr_python.hier_block2_pb, block: gnuradio.gr.gr_python.basic_block) -> None
    2. (self: gnuradio.gr.gr_python.hier_block2_pb, src: gnuradio.gr.gr_python.basic_block, src_port: int, dst: gnuradio.gr.gr_python.basic_block, dst_port: int) -> None
`

### System Information

OS: Ubuntu 21.10
GR Installation Method: apt

### GNU Radio Version

3.10 (maint-3.10)

### Specific Version

3.10.1.1

### Steps to Reproduce the Problem

installed gnuradio on ubuntu 21.10 as described on https://wiki.gnuradio.org/index.php/UbuntuInstall
added an RTL-SDR Source and a QT GUI Sink. Edit: and obviously connected them.
pressed 'execute'

### Relevant log output

```shell
Generating: '/home/ivan/defaultdd.py'

Executing: /usr/bin/python3 -u /home/ivan/defaultdd.py

gr-osmosdr 0.2.0.0 (0.2.0) gnuradio 3.8.2.0
built-in source types: file fcd rtl rtl_tcp uhd hackrf bladerf rfspace airspy airspyhf soapy redpitaya freesrp 
[INFO] [UHD] linux; GNU C++ version 10.2.1 20201207; Boost_107400; UHD_3.15.0.0-4build1
Found Rafael Micro R820T tuner
Using device #0 Realtek RTL2838UHIDIR SN: 00000001
Found Rafael Micro R820T tuner
[R82XX] PLL not locked!
Invalid sample rate: 32000 Hz
Traceback (most recent call last):
  File "/home/ivan/defaultdd.py", line 171, in <module>
    main()
  File "/home/ivan/defaultdd.py", line 149, in main
    tb = top_block_cls()
  File "/home/ivan/defaultdd.py", line 120, in __init__
    self.connect((self.rtlsdr_source_0, 0), (self.qtgui_sink_x_0, 0))
  File "/usr/lib/python3/dist-packages/gnuradio/gr/hier_block2.py", line 39, in wrapped
    func(self, src, src_port, dst, dst_port)
  File "/usr/lib/python3/dist-packages/gnuradio/gr/hier_block2.py", line 106, in connect
    self.primitive_connect(*args)
TypeError: primitive_connect(): incompatible function arguments. The following argument types are supported:
    1. (self: gnuradio.gr.gr_python.hier_block2_pb, block: gnuradio.gr.gr_python.basic_block) -> None
    2. (self: gnuradio.gr.gr_python.hier_block2_pb, src: gnuradio.gr.gr_python.basic_block, src_port: int, dst: gnuradio.gr.gr_python.basic_block, dst_port: int) -> None

Invoked with: <gnuradio.gr.gr_python.top_block_pb object at 0x7f62c7900430>, <Swig Object of type 'gr::basic_block_sptr *' at 0x7f62c78720c0>, 0, <gnuradio.gr.gr_python.basic_block object at 0x7f62c7c42870>, 0
swig/python detected a memory leak of type 'gr::basic_block_sptr *', no destructor found.

>>> Done (return code 1)
```

**Comment by marcusmueller** [comment]
Since you've installed a GNU Radio 3.10, whatever module you're using cannot be using SWIG.

So, this means you've installed gr-osmosdr in a 3.8 version, which is not compatible with GNU Radio 3.10. You might be mixing multiple binary installation methods.
