### ISSUE TITLE
Unuseful QT GUI Chooser

### ISSUE THREAD

**Issue by zhanght34** [gnuradio/gnuradio#5756]
### What happened?

    I create oot block named 'Link16MsgV2',use it to receive the value defined by 'QT GUI chooser' and then output the corresponding PDU.
    But ,when I run my grc and change the choose of ‘QT GUI chooser’ ,it is invalid. In other words, when I run grc, the value of the modified ‘QT GUI chooser’ doesn’t pass to my oot block.The value of ‘QT GUI chooser’ is always default optin.
    Does anyone know the problem with this? Thanks very much!!!
    This is my first time asking a question. If you feel that there is something I didn't express clearly, I will add an explanation.
![1](https://user-images.githubusercontent.com/102239404/162348059-d3d53f26-46c2-4b1f-a291-768d7158acf7.jpg)
![2](https://user-images.githubusercontent.com/102239404/162348077-8af939a2-8330-46b4-b12d-ab80facabf06.jpg)
![3](https://user-images.githubusercontent.com/102239404/162348105-7a74e069-e150-4b85-b6d9-622d9ab48990.jpg)
![4](https://user-images.githubusercontent.com/102239404/162348109-3b986e37-938e-4778-949a-da166a93e6ab.jpg)

### System Information

OS: (Linux Ubuntu 20.04)
GR Installation Method: (follow the official website of  GNU Radio)

### GNU Radio Version

3.11-git (main)

### Specific Version

3.11.0.0

### Steps to Reproduce the Problem

1. create grc like this
![1](https://user-images.githubusercontent.com/102239404/162348287-cdc80099-e92d-467f-bb5b-d1ee0344928f.jpg)
2.'Link16MsgV2' BLOCK like this
![2](https://user-images.githubusercontent.com/102239404/162348369-b646a7cb-7bc5-454e-8d78-a2785fedd526.jpg)
3.run this grc
![3](https://user-images.githubusercontent.com/102239404/162348411-55d611f9-f88b-4e57-a29e-d20f8f560f65.jpg)
4.when i chang the chooser of timeslot,the printf debuge is no changed
![4](https://user-images.githubusercontent.com/102239404/162348537-cb3d0d08-6b99-4a90-944a-a5b2626ebba3.jpg)

**Comment by willcode** [comment]
@zhanght34 Thanks for your question. We use the issue tracker for bug reports and feature requests. For help, please use chat.gnuradio.org or the mailing list.

**Comment by zhanght34** [comment]
> please use chat.gnuradio.org or the mailing list.

okok,understand，thanks.
