### ISSUE TITLE
chunks_to_symbols crashing with Dimension = 16

### ISSUE THREAD

**Issue by cclamb** [gnuradio/gnuradio#5758]
### What happened?

I use code derived ieee802-15-4 project. In the physical layer for this project, we use the chunks_to_symbols block with Dimensions = 16. This currently segfaults. If I use Dimensions = 1, 2, 4, or 8, it will not. The bug seems to have been introduced in a commit on July 27 (either f6b3295ae29e3ee3c2c8fc3c6738ee4561ca194b or 592b0f4f37d59dc8a11b1fea75f6016f2118e15b, but I believe it likely to have been the latter).

From what I can see, I believe the problem is here:

```
            for (const auto& tag : tags) {
                for (; in_count < tag.offset; ++in_count) {
                    auto key = static_cast<unsigned int>(*in) * d_D;
                    for (unsigned int idx = 0; idx < d_D; ++idx) {
                        *out = d_symbol_table[key + idx];
                        ++out;
                    }
                    ++in;
                }
                if (tag.key == symbol_table_key) {
                    handle_set_symbol_table(tag.value);
                }
            }

            // after the last tag, continue working on the remaining items
            for (; in < reinterpret_cast<const IN_T*>(input_items[m]) + noutput_items;
                 ++in) {
                auto key = static_cast<unsigned int>(*in) * d_D;
                for (unsigned int idx = 0; idx < d_D; ++idx) {
                    *out = d_symbol_table[key + idx];
                    ++out;
                }
            }
```

According to GDB, the error is occurring in the the vector::[] operation; I think the cause is this line:
```
 *out = d_symbol_table[key + idx];
```
Which did not exist in this block until the refactor on 7/27/2021. I haven't been able to confirm this though.

### System Information

OS: Ubuntu 20.04.4 LTS
GR Installation Method: Pybombs/Source

### GNU Radio Version

3.9  (maint-3.9)

### Specific Version

v3.9.5.0-62-gf520c346

### Steps to Reproduce the Problem

(1) Download the IEEE802-15-4 project: https://github.com/bastibl/gr-ieee802-15-4
(2) Build the project, then compile the flowgraphs in the examples directory.
(3) Attempt to run the transceiver_OQPSK.grc flowgraph.
--> This will segfault, and generate a core file.

**Comment by argilo** [comment]
This looks like the same issue as #6210, which was fixed in #6223.
