### ISSUE TITLE
cmd time errors with UHD USRP Sink

### ISSUE THREAD

**Issue by zhanght34** [gnuradio/gnuradio#5778]
### What happened?

I'm playing with gnuradio and an USRP X410 device.
I connect pc with USRP X410 by QFSP.I want to test how fast the QFSP port transfer rate is.
Then in gnuradio grc,i have connected two block:Sig Source and USRP Sink. Details as shown
![8098F69F0935B53399DC38B892C9DFA0](https://user-images.githubusercontent.com/102239404/164641593-7d00337e-9673-4467-a8f3-d630bcd86570.jpg)
：
When i run this grc,and set samp_ate to 30MHz，gnuradio printfs"cmd time errors".How to slove it?
![527D0BDBC9AA975898CBA6CED7EB0114](https://user-images.githubusercontent.com/102239404/164643201-e0666291-1e9e-49b5-be0d-81d272499575.jpg)

### System Information

i9-11900F @ 2.50GHz
Ubuntu20.04
GNU Radio 3.10.1.1
Python 3.8.10
UHD 4.2.00-rc1

### GNU Radio Version

3.10 (maint-3.10)

### Specific Version

3.10.1.1

### Steps to Reproduce the Problem

1.Run this grc
2.click ‘samp_rate’ up button to 30MHz.

Then,gnuradio printfs"
                 Susrp_sink :error: In the last 28292 ms, 1 cmd time errors occurred.
                 SSSSSSSSUusrp_sink :error: In the last 28298 ms, 1 underflows occurred.
"
At the same time, the light on the usrp x410 showing the RF transmit go off.

### Relevant log output

```shell
Susrp_sink :error: In the last 28292 ms, 1 cmd time errors occurred.
SSSSSSSSUusrp_sink :error: In the last 28298 ms, 1 underflows occurred.
```

**Comment by marcusmueller** [comment]
These are not GNU Radio bugs, please don't report them here! The usrp-users mailing list might be a better place :) 

Also I pointed you to setting the `master_clock_rate` before, it seems that hasn't worked!

**Comment by zhanght34** [comment]
Thanks ,help me very very timely.Meanwhile, I'm sorry for my wrong approach.
