### ISSUE TITLE
Adding node sets `state: true` disabling and enabling it sets `state: enabled`

### ISSUE THREAD

**Issue by nils-werner** [gnuradio/gnuradio#5779]
### What happened?

When I add a node to my flowgraph, the `.grc` file will contain a line

```
state: true
```

If I disable that node, the line switches to

```
state: disabled
```

and if I re-enable the node, it switches to

```
state: enabled
```

I think the value `true` is incorrect and it should be `enabled` instead.

### System Information

OS: Arch Linux
GR Installation Method: Conda

### GNU Radio Version

3.10 (maint-3.10)

### Specific Version

3.10.1.1

### Steps to Reproduce the Problem

1. Add a node. The file says `state: true`
2. Disable it. The file says `state:disabled`
3. Enable it. The file says `state:enabled`

**Comment by haakov** [comment]
You're right! This is the culprit:
https://github.com/gnuradio/gnuradio/blob/c6d094d79e420c34f7726b893691fdb43eab7360/grc/core/blocks/block.py#L79-L80

**Comment by Sthyarala** [comment]
@nils-werner I will be happy to take this issue.

**Comment by dkozel** [comment]
@Sthyarala If you would like to fix this problem and open a pull request that would be great, please do!
