### ISSUE TITLE
find alternative modules like packet decoder/encoder in GRC3.7

### ISSUE THREAD

**Issue by YHG-kk** [gnuradio/gnuradio#5785]
### Feature Description

**Is there any modules can play a same role like packet decoder/encoder in GRC3.7?it have been delete in GNU3.8.**

### Feature Urgency

medium (would be nice to have in the near future)

### More Information

**Is there any modules can play a same role like packet decoder/encoder in GRC3.7?it have been delete in GNU3.8.**

**Comment by marcusmueller** [comment]
duplicates https://github.com/gnuradio/gnuradio/issues/5284
