### ISSUE TITLE
object has no attribute 'to_basic_block'

### ISSUE THREAD

**Issue by catkira** [gnuradio/gnuradio#5801]
### What happened?

I ported a GNU Radio 3.8 script to GNU Radio 3.11.
When I run it I get this error
```
AttributeError: 'hrpt.hrpt_python.noaa_hrpt_deframer' object has no attribute 'to_basic_block'
```
A detailed log is attached below.

The .py file is attached here.
[hrpt_noaa_decoder.zip](https://github.com/gnuradio/gnuradio/files/8604790/hrpt_noaa_decoder.zip)

### System Information

OS: Linux
GR Installation Method: Source

### GNU Radio Version

3.11-git (main)

### Specific Version

v3.11.0.0git-128-gfa8953de

### Steps to Reproduce the Problem

Run the example [Offline_NOAA_Decoder GQRX.grc](https://github.com/catkira/gr-hrpt/blob/master/examples/Offline_NOAA_Decoder%20GQRX.grc) from https://github.com/catkira/gr-hrpt.

### Relevant log output

```shell
Executing: /usr/bin/python3 -u /mnt/d/git/gr-hrpt/examples/hrpt_noaa_decoder.py

QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-benja'
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/gnuradio/gr/hier_block2.py", line 33, in wrapped
    endp = [(p.to_basic_block(), 0) if hasattr(p, 'to_basic_block')
  File "/usr/local/lib/python3.8/dist-packages/gnuradio/gr/hier_block2.py", line 34, in <listcomp>
    else (p[0].to_basic_block(), p[1]) for p in points]
AttributeError: 'hrpt.hrpt_python.noaa_hrpt_deframer' object has no attribute 'to_basic_block'
```

**Comment by mormj** [comment]
Hi @catkira - this does not appear to be a GR bug, but an issue specific to your OOT.  Please reach out on chat: https://wiki.gnuradio.org/index.php?title=Chat or the mailing list to get more timely help.
