### ISSUE TITLE
ImportError: cannot import name 'customModule' from 'gnuradio' how to fix this issue?

### ISSUE THREAD

**Issue by unurbayar** [gnuradio/gnuradio#5817]
Hi,
I have followed this guide https://wiki.gnuradio.org/index.php?title=Creating_Python_OOT_with_gr-modtool. When I try to run this ImportError  occured. How do I solve this issue.
```
Generating: '/home/t-rex/Documents/create.py'

Executing: /usr/bin/python3 -u /home/t-rex/Documents/create.py

Warning: failed to XInitThreads()
Traceback (most recent call last):
  File "/home/t-rex/Documents/create.py", line 29, in <module>
    from gnuradio import customModule
ImportError: cannot import name 'customModule' from 'gnuradio' (/usr/lib/python3/dist-packages/gnuradio/__init__.py)

>>> Done (return code 1)
```

GNU radio version: GNU Radio Companion 3.8.2.0
OS: 5.15.0-15parrot1-amd64

**Comment by mormj** [comment]
Hi @unurbayar - this appears to be a usage issue, in which case you will definitely get more timely help via the mailing list or the Matrix chat: https://wiki.gnuradio.org/index.php?title=Chat
