### ISSUE TITLE
Want to modify the build-in block "ofdm_chanest"

### ISSUE THREAD

**Issue by changshunyu** [gnuradio/gnuradio#5886]
### What happened?

For OFDM-MIMO scenario, Multiple sync sequences are required， but the ofdm_chanest block only have two sync sequences, so i want to modify this block. I update the _impl.cc and _impl.h files in the lib directory(/gnuradio/gr-digital/lib), update the .h file in the include directory(/gnuradio/gr-digital/include/gnuradio/digital), and update the .yml file in the grc dir(/gnuradio/gr-digital/grc). 
I rerun command cmake ..
but it reported an error:

CMake Error at cmake/Modules/GrPybind.cmake:86 (message):
  Python bindings for ofdm_chanest_vcvc.h are out of sync
Call Stack (most recent call first):
  gr-digital/python/digital/bindings/CMakeLists.txt:95 (GR_PYBIND_MAKE_CHECK_HASH)

what should i do? can you help me, thank you

### System Information

OS: Ubuntu 20.04

### GNU Radio Version

3.10 (maint-3.10)

### Specific Version

0.0.0.0

### Steps to Reproduce the Problem

update the _impl.cc and _impl.h files in the lib directory(/gnuradio/gr-digital/lib), 
update the .h file in the include directory(/gnuradio/gr-digital/include/gnuradio/digital),
and update the .yml file in the grc dir(/gnuradio/gr-digital/grc). 

Rerun command cmake ..

**Comment by willcode** [comment]
@changshunyu The issue tracker is used for bug reports and feature requests. Please ask for help on Matrix (chat.gnuradio.org) or the mailing list.
