### ISSUE TITLE
QT GUI Frequency Sink dimensions

### ISSUE THREAD

**Issue by murray-lang** [gnuradio/gnuradio#5953]
I'm using GRC on a Raspberry Pi, and want to display my flowgraph GUI on a 7" touchscreen. However, I cannot find a way to reduce the size of the QT GUI Frequency Sink so as to fit the other GUI widgets on the screen. Setting the GUI Hint row span to one has no influence on the size.

How do I make it smaller please?

**Comment by marcusmueller** [comment]
This is a bug tracker; for usage questions, please refer to our chat and mailing list
