### ISSUE TITLE
Is there a way to adjust max_noutput_items size?

### ISSUE THREAD

**Issue by vinhtran144** [gnuradio/gnuradio#5955]
### Feature Description

Hey there. I'm not too sure if this isn't the right place to ask, so I'm sorry if this issue doesn't fit. I'm looking to run gnuradio on a Raspberry Pi, but it has some allocating memory issues. In short, the Raspberry Pi I'm running the program on is a Raspberry Pi 3B, so it only has 1GB of RAM. I can also confirm that I've installed everything correctly as when I move the SD card to Raspberry Pi 4 with 8GB of RAM, everything runs normally. The error I got is as follows:

>  File "/usr/local/lib/python3.9/dist-packages/gnuradio/gr/top_block.py", line 98, in start
>   top_block_start_unlocked(self._impl, max_noutput_items)
> MemoryError: std::bad_alloc

I followed the directory into `top_block.py`.py and found that `def start(self, max_noutput_items=10000000):`. I'm assuming that if I decrease the value, I should be able to run this program on Raspberry Pi 3B. Is there a way I can do that? I can't edit the file directly so I'm not sure how I can edit this value

For more detailed information on what I've done, I've installed PiSDR image [https://github.com/luigifcruz/pisdr-image](here), so gnuradio has been already installed with ver 3.9. I then install [https://github.com/bastibl/gr-ieee802-11](gr-ieee802-11) (along with gr-foo) with the maint-3.9 branch. After setting kernel.shmmax and running volk-profile, I run the `wifi_loopback` example, here's the full console

> set_min_output_buffer on block 7 to 207744
> set_min_output_buffer on block 9 to 2077440
> set_min_output_buffer on block 11 to 2077440
> set_min_output_buffer on block 12 to 207744
> set_min_output_buffer on block 13 to 415488
> set_min_output_buffer on block 14 to 207744
> set_min_output_buffer on block 30 to 960000
> gr::log :ERROR: gr::vmcircbuf - shmget (1): Cannot allocate memory
> gr::log :ERROR: gr::vmcircbuf - shmget (1): Cannot allocate memory
> gr::log :ERROR: gr::vmcircbuf - shmget (1): Cannot allocate memory
> gr::log :ERROR: buffer - gr::buffer::allocate_buffer: failed to allocate buffer of size 1038720 KB
> gr::log :ERROR: gr::vmcircbuf - shmget (1): Cannot allocate memory
> gr::log :ERROR: gr::vmcircbuf - shmget (1): Cannot allocate memory
> gr::log :ERROR: gr::vmcircbuf - shmget (1): Cannot allocate memory
> gr::log :ERROR: buffer - gr::buffer::allocate_buffer: failed to allocate buffer of size 1038720 KB
> Traceback (most recent call last):
>   File "/home/pi/Documents/Experiments/gr-ieee802-11/examples/wifi_loopback.py", line 351, in <module>
>     main()
>   File "/home/pi/Documents/Experiments/gr-ieee802-11/examples/wifi_loopback.py", line 331, in main
>     tb.start()
>   File "/usr/local/lib/python3.9/dist-packages/gnuradio/gr/top_block.py", line 98, in start
>     top_block_start_unlocked(self._impl, max_noutput_items)
> MemoryError: std::bad_alloc

1038720 KB is just above 1GB, so that's why I'm assuming it's because of the RAM issue.

### Feature Urgency

low (just an idea)

**Comment by marcusmueller** [comment]
Hi! This is indeed a bug tracker, not a place to ask usage questions; I'm hence closing the issue.

However, you're most welcome to ask e.g. on our mailing list! You'll find the methods of contacting when you go to https://www.gnuradio.org/ and scroll to the bottom to "contact us".

However, GNU Radio itself tends to not build buffers significantly larger than immediately necessary, so reducing that number might simply mean your flow graph can't work any more. Also, the Rpi3 is probably quite a bit too slow for gr-ieee802-11, but I have no specific experience with that.
