### ISSUE TITLE
QT Frequency Sink does not update 

### ISSUE THREAD

**Issue by JayKickliter** [gnuradio/gnuradio#6000]
### What happened?

QT Frequency sink renders only once then never updates.

### System Information

OS: macOS 12.2.1 Monterey, Apple M1 Pro
GR Installation Method: Both Homebrew and from-source build show the same behavior.

### GNU Radio Version

3.10 (maint-3.10)

### Specific Version

3.10.1.0

### Steps to Reproduce the Problem

Create a flow graph of a [random noise source] -> [throttle] -> [QT Frequency Sink]

### Relevant log output

```
Generating: '/Users/jay/forks/gnuradio/build/untitled.py'

Executing: /opt/homebrew/opt/python@3.9/bin/python3.9 -u /Users/jay/forks/gnuradio/build/untitled.py

log :warning: Matplotlib is a required dependency to use DistanceRadar and AzElPlot.  Please install matplotlib to use these blocks (https://matplotlib.org/)
Volk warning: no arch found, returning generic impl
Volk warning: no arch found, returning generic impl
Volk warning: no arch found, returning generic impl
Volk warning: no arch found, returning generic impl
Volk warning: no arch found, returning generic impl
Volk warning: no arch found, returning generic impl
Volk warning: no arch found, returning generic impl

>>> Done (return code -11)
```

**Comment by JayKickliter** [comment]
Following up, it's not just the freq sink. All QT GUI sinks I've tried so far freeze after a single render.

**Comment by mormj** [comment]
Could be fixed by recent commit: https://github.com/gnuradio/gnuradio/commit/3db403b3dcf272eebd85ac2c15934fa3ade12abd

Are you able to try the latest maint-3.10?

**Comment by JayKickliter** [comment]
> Are you able to try the latest maint-3.10?

yep, that did it.

Fixed by https://github.com/gnuradio/gnuradio/commit/3db403b3dcf272eebd85ac2c15934fa3ade12abd

**Comment by JayKickliter** [comment]
Fixed by https://github.com/gnuradio/gnuradio/commit/3db403b3dcf272eebd85ac2c15934fa3ade12abd

**Comment by JayKickliter** [comment]
Fixes
