### ISSUE TITLE
GRU module removed, what can I do without it ?

### ISSUE THREAD

**Issue by f5gkw** [gnuradio/gnuradio#6017]
**I think it is not a bug, I don't know where I can find some help ..**

Hello,
first of all I am surly not a gnuradio guru, not a python guru.
I use some scripts written by other peoples
Until last week, all was ok.
After an update ( Kali on raspberry).. 
I have remove gnuradio, python3.8 ...
and after apt install ( gnuradio, gnuradio-dev python3 ..)

I still get the error cannot import gru module.
To check, I start by hand in python3 the other imports from gnuradio. All work except "gru"
As I can see, after hours and hours,  this module is removed from gnuradio.
(for the moment I don't understand gnuradio / modules and their goals)

What can I do please ?

Thank you

### System Information

OS:  raspi-kali 5.15.44 Debian Kali-pi (2022-07-03)
GR Installation Method: apt install ( gnuradio, gnuradio-dev python3 ..)

### GNU Radio Version

3.10 (maint-3.10)

### Specific Version

3.10.2.0

### Steps to Reproduce the Problem

To check, I start by hand in python3 the other imports from gnuradio. All work except "gru"

**Comment by willcode** [comment]
Please ask for help on chat or email (https://www.gnuradio.org/get-involved). The issue tracker is used for bug reports and feature requests.
