### ISSUE TITLE
GRC Display issues on macOS

### ISSUE THREAD

**Issue by dxxx9** [gnuradio/gnuradio#6101]
### What happened?

This issue was reported before, but the proposed solutions didn't work for me. See:
#5613
#5654
[#4814 reply](https://github.com/gnuradio/gnuradio/pull/4814\#issuecomment-925190019)

A flickering/not reacting screen sadly makes it impossible to work with the grc interface. (see image below)

<img width="1301" alt="grc" src="https://user-images.githubusercontent.com/62398752/185477629-3f474fed-44ce-421d-b127-7135daa19d7f.png">

### System Information

OS: macOS Monterey 12.3
GR Installation Method: brew

### GNU Radio Version

3.10 (maint-3.10)

### Specific Version

3.10.3.0

### Steps to Reproduce the Problem

What I've done:
I updated (with homebrew) to from `3.9.3.0` to `3.10.3.0` and the flickering/black screen appears when I open a new flowgraph.

I had this issue before (with an older version of grc). As it is some time ago, I'm not exactly sure how I fixed it, but I can remember adding
```
xterm_executable = /usr/X11R6/bin/xterm
```
to the `[grc]` in the config file.

I'm very thankful for any help!

**Comment by dxxx9** [comment]
So after testing things the issue disappeared somehow. Might be that restarting the iTerm2 application fixed this.

I'll reopen this issue if I can provide detailed steps to reproduce that bug.

**Comment by dkozel** [comment]
@dxxx9 That would be great, understanding the cause and/or fix would be useful info to anyone looking to solve this more permanently.
