### ISSUE TITLE
Is there any HoRNDIS alternative for macOS?

### ISSUE THREAD

**Issue by altitudedashboard** [gnuradio/gnuradio#6174]
### Feature Description

HoRNDIS seems to be a dead project, building it on macOS arm64 (M1) requires disabling SIP which is not convenient for some users. In order to use the ADALM-PLUTO with gnuradio, HoRNDIS is required. But is there any alternative?

### Feature Urgency

medium (would be nice to have in the near future)

**Comment by willcode** [comment]
This sounds more like a question than a GNU Radio feature request. Please try chat.gnuradio.org or the mailing list to see if someone has ideas.
