### ISSUE TITLE
4.0: constrain input/output type combinations

### ISSUE THREAD

**Issue by samwhiting** [gnuradio/gnuradio#6195]
### Feature Description

For templatized blocks, we should consider how to constrain what combinations of ports are valid. For example, the decimating FIR block supports many combinations of inputs and outputs, but not all combinations of complex, float, and short.

![image](https://user-images.githubusercontent.com/23368909/192877454-452ccf5c-1b5e-4fab-ac7f-3cd030926763.png)

How do we constrain types like this in the YAML?

### Feature Urgency

low (just an idea)

**Comment by mormj** [comment]
Currently this is enforced in the yml generation with the `type_inst` field.  Check out `fir_filter.yml` to see how it works
