### ISSUE TITLE
4.0: Modtool should generate boilerplate QA files

### ISSUE THREAD

**Issue by joshjab** [gnuradio/gnuradio#6200]
### Feature Description

The old modtool had this feature, and in the workflow of creating more blocks I noticed it didn't make it into this script yet. Will help with porting the new blocks over.

### Feature Urgency

medium (would be nice to have in the near future)

### More Information

 Example unit tests are included in the `tests/` directory

**Comment by mormj** [comment]
Fixed with #6216
