### ISSUE TITLE
Segmentation fault when starting benchmark_rx.py before benchmark_tx.py

### ISSUE THREAD

**Issue by Trevor16gordon** [gnuradio/gnuradio#6310]
### What happened?

I have a problem in gnuradio 3.7 and gnuradio 3.8 where my receiver consistently gets segmentation faults

- If the receiver starts before the transmitter this will happen
- If the pair is exchanging successfully but I move the transmitter to another frequency then back, I get a segmentation fault
- It seems the commonality here is if the receiver ever doesn't have good packets, it will error once it gets good ones again.

**Additional Information**

I did some further digging into the error.
In gnuradio 3.8 I tried using digital_bert_rx.py / digital_bert_tx.py from the gnuradio 3.8 examples and it also throws a segmentation fault if the rx get's into a state where it doesn't have packets then it gets them again
In [this thread](https://lists.gnu.org/archive/html/discuss-gnuradio/2016-03/msg00192.html) from 2016 I found two people debugging a segmentation fault similar to mine in volk. volk_32fc_x2_multiply_32fc . 
They appeared to solve their issue by changing the .volk/volk_config file. They thought there was an error with some memory addresses.
I learned that volk is a vector operation kernel library and it turns out it's common to specify specific kernels that match well with different CPU architectures. Here is a [page](https://wiki.gnuradio.org/index.php/VOLK_Guide) on GNURadio explaining it. It's nice because the kernel preference can be changed in the config file.
I was able to change my kernel for volk_32fc_32f_dot_prod_32fc where the error is coming from. I was also able to see this reflected in the core dump stack trace. 
I was able to try for the default volk_32fc_32f_dot_prod_32fc_a_sse and another one. Both still resulting in the segmentation faults
Here is a [related pull request](https://github.com/gnuradio/volk/issues/25) on gnuradio/volk from 2015 relating to these errors:

Found the exact same issue in this thread: https://www.ruby-forum.com/t/segmentation-fault-in-narrowband-benchmark-rx-py/239449
No solution though.

Found the same core-dump stack trace in this thread:
https://lists.gnu.org/archive/html/discuss-gnuradio/2014-02/msg00345.html
No solution.

### System Information

My Details:
GNURadio Version:
3.7.13.5
Apr 20, 2019

Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.5 LTS
Release:	18.04
Codename:	bionic

### GNU Radio Version

3.7  (maint-3.7)

### Specific Version

3.7.13.5

### Steps to Reproduce the Problem

In one terminal, start benchmark_rx.py using something like:
```./benchmark_rx.py -f 2.0e9 -m bpsk --rx-gain 5 -r .50M -a addr=10.10.23.4 -v```

Wait a few seconds

In another terminal start benchmark_tx.py using something like:
```./benchmark_tx.py --args "addr=10.10.23.2" --modulation bpsk --bitrate 0.5M --tx-gain 15 --freq 2.0e9 -M 20 --tx-amplitude 0.5 -v```

### Relevant log output

```shell
This is the trace I received on 3.7: (I've received similar ones on 3.8)

I grabbed a core dump using gdb

[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Core was generated by `python ./benchmark_rx_modified.py -f 2.0e9 -m bpsk --rx-gain 5 -r .50M -a addr='.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00007f4a93f34619 in volk_32fc_32f_dot_prod_32fc_a_avx () from /usr/local/lib/libvolk.so.1.4
[Current thread is 1 (Thread 0x7f4a637fe700 (LWP 7786))]
(gdb) bt
#0  0x00007f4a93f34619 in volk_32fc_32f_dot_prod_32fc_a_avx () from /usr/local/lib/libvolk.so.1.4
#1  0x00007f4a80b40de9 in gr::filter::kernel::fir_filter_ccf::filter(std::complex<float> const*) () from /usr/local/lib/libgnuradio-filter-3.7.13.5.so.0.0.0
#2  0x00007f4a81144e8c in gr::digital::pfb_clock_sync_ccf_impl::general_work(int, std::vector<int, std::allocator<int> >&, std::vector<void const*, std::allocator<void const*> >&, std::vector<void*, std::allocator<void*> >&) () from /usr/local/lib/libgnuradio-digital-3.7.13.5.so.0.0.0
#3  0x00007f4a94e86007 in gr::block_executor::run_one_iteration() () from /usr/local/lib/libgnuradio-runtime-3.7.13.5.so.0.0.0
#4  0x00007f4a94ed3c98 in gr::tpb_thread_body::tpb_thread_body(boost::shared_ptr<gr::block>, boost::shared_ptr<boost::barrier>, int) ()
   from /usr/local/lib/libgnuradio-runtime-3.7.13.5.so.0.0.0
#5  0x00007f4a94ec4ca4 in boost::detail::function::void_function_obj_invoker0<gr::thread::thread_body_wrapper<gr::tpb_container>, void>::invoke(boost::detail::function::function_buffer&) () from /usr/local/lib/libgnuradio-runtime-3.7.13.5.so.0.0.0
#6  0x00007f4a94e6c892 in boost::detail::thread_data<boost::function0<void> >::run() () from /usr/local/lib/libgnuradio-runtime-3.7.13.5.so.0.0.0
#7  0x00007f4a93678bcd in ?? () from /usr/lib/x86_64-linux-gnu/libboost_thread.so.1.65.1
#8  0x00007f4a964f26db in start_thread (arg=0x7f4a637fe700) at pthread_create.c:463
#9  0x00007f4a9682b71f in __GI_epoll_pwait (epfd=1266209952, events=0x7f4a863e71c0, maxevents=1266252832, timeout=24, set=0x7f4a863e71c0)
    at ../sysdeps/unix/sysv/linux/epoll_pwait.c:42
#10 0x0000000000000000 in ?? ()
```

**Comment by marcusmueller** [comment]
end-of-life versions; sorry, won't be fixed.
