### ISSUE TITLE
[HELP] I want to convert analog signal

### ISSUE THREAD

**Issue by asahi638** [gnuradio/gnuradio#6331]
### Feature Description

I want to convert analog signal to digtal signal,and analysis with python.
this signals peak to peak voltage is 5v,and continue while 150second.
I want to know best devices.
pleas somebody help me or advice me.

### Feature Urgency

medium (would be nice to have in the near future)

**Comment by dkozel** [comment]
Hello. It's possible that GNU Radio could work for you, but it's hard to know without more information about the bandwidth of your signal and what you want to do with the signal after you digitize it. I recommend either joining the GNU Radio chat or the 1BitSquared Discord which has many rooms for talking about electronics and programming.

https://discord.gg/w8Vzjt3z

https://app.element.io/#/room/#gnuradio:gnuradio.org

This issue tracker isn't going to be a good place to talk so I'm closing this, but hope to talk to you on one of those chat servers.
