### ISSUE TITLE
gnuradio install fails with in make at gnuradio-runtime

### ISSUE THREAD

**Issue by mberry28** [gnuradio/gnuradio#6414]
### What happened?

While executing `make -j3` gnuradio install fails, see below.

```
[ 32%] Building CXX object gnuradio-runtime/lib/CMakeFiles/gnuradio-runtime.dir/math/random.cc.o
[ 33%] Building CXX object gnuradio-runtime/lib/CMakeFiles/gnuradio-runtime.dir/math/sincos.cc.o
[ 33%] Linking CXX shared library libgnuradio-runtime.so
[ 33%] Built target gnuradio-runtime
make: *** [Makefile:146: all] Error 2
```

### System Information

OS: Redhat  8.7
GR Installation Method: Install from source. 

### GNU Radio Version

3.10 

### Specific Version

3.10.4

### Steps to Reproduce the Problem

Had to install boost and log4cpp from source. 
Installed gmp via yum. `yum install gmp-devel`

Method for installing gnuradio:
```
mkdir build
cd build
cmake ../
make -j3
```
Seemed to be installing ok until:

```
[ 32%] Building CXX object gnuradio-runtime/lib/CMakeFiles/gnuradio-runtime.dir/math/random.cc.o
[ 33%] Building CXX object gnuradio-runtime/lib/CMakeFiles/gnuradio-runtime.dir/math/sincos.cc.o
[ 33%] Linking CXX shared library libgnuradio-runtime.so
[ 33%] Built target gnuradio-runtime
make: *** [Makefile:146: all] Error 2
```

Any suggestions?

**Comment by willcode** [comment]
The error is probably many lines above where make stopped. In any case please send an email on the list, or post a link to your build log along with an explanation on chat.gnuradio.org. Likely a build environment error, so closing. Feel free to reopen the issue if you have more info and think there is a problem with GNU Radio itself.
