### ISSUE TITLE
"make" errors

### ISSUE THREAD

**Issue by SpongeBobaa** [gnuradio/gnuradio#6421]
### What happened?

make failed.

### System Information

OS: ubuntu 16.04
GR Installation Method:Source

### GNU Radio Version

3.7  (maint-3.7)

### Specific Version

3.7.10.1

### Steps to Reproduce the Problem

`sudo make -j4`

### Relevant log output

```shell
gr-uhd/swig/CMakeFiles/_uhd_swig.dir/build.make:68: recipe for target 'gr-uhd/swig/CMakeFiles/_uhd_swig.dir/uhd_swigPYTHON_wrap.cxx.o' failed
make[2]: *** [gr-uhd/swig/CMakeFiles/_uhd_swig.dir/uhd_swigPYTHON_wrap.cxx.o] Error 1
CMakeFiles/Makefile2:13014: recipe for target 'gr-uhd/swig/CMakeFiles/_uhd_swig.dir/all' failed
make[1]: *** [gr-uhd/swig/CMakeFiles/_uhd_swig.dir/all] Error 2
make[1]: *** 正在等待未完成的任务....
[ 98%] Linking CXX shared module _video_sdl_swig.so
[ 98%] Built target _video_sdl_swig
[ 98%] Linking CXX shared module _channels_swig.so
[ 98%] Built target _channels_swig
[ 98%] Linking CXX shared module _digital_swig.so
[ 98%] Built target _digital_swig
Makefile:160: recipe for target 'all' failed
make: *** [all] Error 2
```

**Comment by mormj** [comment]
Lots of things can go wrong when building a project from source, especially with `swig` (which is why we moved away from it).  Need more information, but likely not a bug in GNU Radio.  Please either request help on the mailing list or chat.gnuradio.org
