### ISSUE TITLE
https://github.com/gnuradio/gnuradio/issues/6415

### ISSUE THREAD

**Issue by reshma07mr** [gnuradio/gnuradio#6427]
Thank you for your response. I was able to manage it. 

But now I have another issue. I had tried to recreate the OFDM tranmsitter sample flowgraph available in the gnuradio/examples/digital/ofdm/tx_ofdm.grc. I tried to plot the constellation plot from different points, but the thing is that, when the output is taken from the repack bits (both from header and payload), it shows that they are not centered at zero. they are shifted towards the positive axis. A sample is attached herealong. Any help or suggestions provided will be appreciated.
![Screenshot (71)](https://user-images.githubusercontent.com/59593136/205657679-118624ef-05e1-4ce6-8e65-8db79dfe0e2f.png)

_Originally posted by @reshma07mr in https://github.com/gnuradio/gnuradio/issues/6415#issuecomment-1337437677_

**Comment by willcode** [comment]
Please use the mailing list or chat.gnuradio.org for help. The issue tracker is used for bug reports and feature requests.

**Comment by reshma07mr** [comment]
Thank you, it is already reported there.
