### ISSUE TITLE
Extra Parenthesis in uhd_rfnoc_graph.block.yml

### ISSUE THREAD

**Issue by jpalladino** [gnuradio/gnuradio#6437]
### What happened?

There is a syntax error in an rfnoc flowgraph, due to an error in uhd_rfnoc_graph.block.yml. On line 24 [here](https://github.com/gnuradio/gnuradio/blob/maint-3.10/gr-uhd/grc/uhd_rfnoc_graph.block.yml), there is an extra closing parenthesis:
`      self.rfnoc_graph = ${id} = uhd.rfnoc_graph(uhd.device_addr("${graph_args}")))`
You can see 2 opening parentheses and 3 closing parentheses. 

I noticed this on gr-ettus's github repo and posted an issue [there](https://github.com/EttusResearch/gr-ettus/issues/69), but another user pointed out that the exact same issue is present in uhd_rfnoc_graph.block.yml.

### System Information

OS: Ubuntu 20.04
GR Installation Method: Source

### GNU Radio Version

3.10 (maint-3.10)

### Specific Version

3.10.4.0

### Steps to Reproduce the Problem

Create any rfnoc flowgraph using rfnoc_graph and try to run it. A syntax error will be present.

**Comment by willcode** [comment]
@mbr0wn this is from a recent PR

**Comment by mbr0wn** [comment]
Fixed with 7efa9c6e5a2800bc5ab16fbdeb770b1768f0f08b
