### ISSUE TITLE
Correlate Access Code - Packet Length Mask Error (easy typo fix)

### ISSUE THREAD

**Issue by jwkunz** [gnuradio/gnuradio#6440]
The packet length in this stream is supposed to be 16 bits.  The mask in line 117 of

https://github.com/gnuradio/gnuradio/blob/master/gr-digital/lib/correlate_access_code_bb_ts_impl.cc

currently is 0x0fff.  This mask should be all 16 bits 0xffff.

The completed change should look like this:

int correlate_access_code_bb_ts_impl::header_payload()
{
    return (d_hdr_reg >> 16) & 0xffff;  // Change made here
}

**Comment by willcode** [comment]
I can't think of any reason the top 4 bits would be masked off. @marcusmueller do you remember if this is intended?

**Comment by jwkunz** [comment]
Could this be a rudimentary protection against requesting a buffer larger than 2^28 bytes?

**Comment by willcode** [comment]
There's no buffer, so I don't see any reason for that. Probably it's never been tested with large frames.

**Comment by jwkunz** [comment]
Using "large frames" is exactly how I found it in the first place (after several hours of confusion).  Thanks for the quick support.

**Comment by willcode** [comment]
There are a couple different header formats defined in GR, and one of them has a 12-bit length. This was probably a cut/paste error, but lets wait until @marcusmueller or other original authors weigh in before changing `correlate_access_code_bb_ts_impl.cc` and `correlate_access_code_ff_ts_impl.cc`.

The blocks that use 12-bit lengths pack the bits, and these blocks do not, so I suspect the 0x0fff is unintended.

**Comment by mbr0wn** [comment]
Yeah this is wrong. @marcusmueller and I just checked this together.
