### ISSUE TITLE
Empty Python Snippet causes invalid rendered python

### ISSUE THREAD

**Issue by mormj** [gnuradio/gnuradio#6444]
### What happened?

If I plop down a snippet block, but don't put any code in the block, the rendered python looks like:

```
def snipfcn_snippet_0(self):


def snippets_main_after_init(tb):
    snipfcn_snippet_0(tb)
```

Which will cause a python parsing error.  

GRC should have the logic to put a `pass` in there, or not add the snippet if it is empty

### System Information

OS: (Linux Distro, Mac, Windows)
GR Installation Method: (native distro packages - apt, rpm, etc., Conda, Source

### GNU Radio Version

3.11-git (main)

### Specific Version

0.0.0.0

### Steps to Reproduce the Problem

Drop an empty python snippet block in GRC and render the flowgraph

**Comment by cwgreene** [comment]
What is a snippet block?
