### ISSUE TITLE
DTV dvbs2_modulator_bc_impl.cc

### ISSUE THREAD

**Issue by FranBoric** [gnuradio/gnuradio#6459]
I noticed that one of the constants is actually different than then in DVB-S2X standard. 

It is coded here.
https://github.com/gnuradio/gnuradio/blob/0becf06a397edc1b2dcf440785e40b73f76433ad/gr-dtv/lib/dvbs2/dvbs2_modulator_bc_impl.cc#L500

In this implementation of MOD_4_8_4_16APSK, case C140_180, it says that 
r2 = r1 * 2.6 
and it should be 
r2 = r1 * 2.8 
and as such it produces quite wrong result!

The standard referenced is
https://www.etsi.org/deliver/etsi_en/302300_302399/30230702/01.01.01_20/en_30230702v010101a.pdf

**Comment by willcode** [comment]
Fixed in #6460
