### ISSUE TITLE
grc_setup_freedesktop created unconditionally (in the wrong location)

### ISSUE THREAD

**Issue by dvzrv** [gnuradio/gnuradio#6464]
### What happened?

Hi! I'm currently improving the gnuradio package for Arch Linux.

I noticed that the file `usr/libexec/gnuradio/grc_setup_freedesktop` is created unconditionally and its location can not be changed.
On Arch we do not use or support /usr/libexec/ (everything is /usr/lib/).

I have tried `-DENABLE_POSTINSTALL=OFF`, `-DGR_LIBEXEC_DIR=lib` and `-DGR_PKG_LIBEXEC_DIR=lib/gnuradio/` but the file is always installed.

Since we already get the XDG integration in the correct location I believe the script serves no purpose and could be omitted altogether.

 Currently I revert to just removing the entirety of usr/libexec from the package contents.

### System Information

OS: Arch Linux
GR Installation Method: Source

### GNU Radio Version

3.10 (maint-3.10)

### Specific Version

3.10.5.0

### Steps to Reproduce the Problem

```
  local cmake_options=(
    -D CMAKE_INSTALL_PREFIX=/usr
    -D CMAKE_BUILD_TYPE=None
    -D ENABLE_GR_ANALOG=ON
    -D ENABLE_GR_AUDIO=ON
    -D ENABLE_GR_BLOCKS=ON
    -D ENABLE_GR_BLOCKTOOL=ON
    -D ENABLE_GR_CHANNELS=ON
    -D ENABLE_GR_CTRLPORT=ON
    -D ENABLE_GR_DIGITAL=ON
    -D ENABLE_GR_DTV=ON
    -D ENABLE_GR_FEC=ON
    -D ENABLE_GR_FFT=ON
    -D ENABLE_GR_FILTER=ON
    -D ENABLE_GR_IIO=ON
    -D ENABLE_GR_MODTOOL=ON
    -D ENABLE_GR_NETWORK=ON
    -D ENABLE_GR_PDU=ON
    -D ENABLE_GR_QTGUI=ON
    -D ENABLE_GR_SOAPY=ON
    -D ENABLE_GR_TRELLIS=ON
    -D ENABLE_GR_UHD=ON
    -D ENABLE_GR_UTILS=ON
    -D ENABLE_GR_VIDEO_SDL=ON
    -D ENABLE_GR_VOCODER=ON
    -D ENABLE_GR_WAVELET=ON
    -D ENABLE_GR_ZEROMQ=ON
    -D ENABLE_GRC=ON
    -D ENABLE_POSTINSTALL=OFF  # we distribute freedesktop integration directly
    -W no-dev
    -B build
    -S $pkgbase-$pkgver
  )

  cmake "${cmake_options[@]}"
  cmake --build build --verbose
  DESTDIR="$pkgdir" cmake --install build
```

**Comment by dl1ksv** [comment]
At the moment GR_LIBEXEC_DIR ist hardcoded to libexec. With this patch the libexec is only created if -DENABLE_POSTINSTALL=ON

Is this sufficient, or should GR_LIBEXEC_DIR be settable by the user.
