### ISSUE TITLE
ofdm transceiver using hackrf one not successful.

### ISSUE THREAD

**Issue by reshma07mr** [gnuradio/gnuradio#6475]
tried to transmit and receive audio and video signals via ofdm and gnu radio. Even though the receiver hackrf detects the signal, the remaining demodulation of the signal is not carried out well, I am not able to recover back the transmitted signal. what can be the reason ? Any help provided will be appreciated.

I have seen a similar experience in https://github.com/greatscottgadgets/hackrf/issues/476 also refers the same, so it means that this error still exixts. can someone know how we can solve this ?

I have mentioned this in the hackrf account also as https://github.com/greatscottgadgets/hackrf/issues/1258. 
Hereby attaching the screenshot of the flowgraph and the results I have seen in this 
![212080356-86e4947b-57c5-4d05-a026-b95cc5e8b81e](https://user-images.githubusercontent.com/59593136/212883406-ebae7448-f964-41bb-8a75-f3a3265d6503.png)
![212080362-a99d7476-b60b-4556-b8e7-3037089460c0](https://user-images.githubusercontent.com/59593136/212883411-afdaa95d-2212-4994-8aaf-e83bbd622135.png)

**Comment by mormj** [comment]
For usage issues with GNU Radio, please utilize the [mailing list](https://lists.gnu.org/mailman/listinfo/discuss-gnuradio) - the issue tracker is reserved for things that have been narrowed down to issues with the GNU Radio code itself.
