### ISSUE TITLE
QT GUI Histogram Sink produces implausible results

### ISSUE THREAD

**Issue by reald** [gnuradio/gnuradio#6494]
### What happened?

A sequence of 10 equidistant values should produce an even histogram (10 bins, 10 values) => 1 value per bin.

### System Information

OS: Ubuntu 22.04
GR Installation Method: native distro packages

### GNU Radio Version

3.10 (maint-3.10)

### Specific Version

3.10.1.1

### Steps to Reproduce the Problem

1. Create flow graph:

![test](https://user-images.githubusercontent.com/1385404/215331891-24ef25e4-d063-41d5-bd9a-c68aff8a2c08.png)

10 different source values of same distance (0..9), 10 bins, number of points: 10.

2. Expected behaviour:

All 10 bins should have 1 as count. Distance between bins should be exactly 1.

3. Observed behaviour:

Some bins have more values, some have no values inside. Distribution not even. Distance between bins is not 1:
[0.0, 1.1, 2.2, 3.3, 4.4, 5.5, 6.6, 7.7, 8.8, 9.9, ??]

![Screenshot_20230129_150941](https://user-images.githubusercontent.com/1385404/215332189-ffae8288-fe89-4677-877b-1b818b587288.png)

**Comment by willcode** [comment]
The code that's causing is here
https://github.com/gnuradio/gnuradio/blob/e1a7a9a5e9201ef54cc2cf0275a8e32a49d7dc22/gr-qtgui/lib/HistogramDisplayPlot.cc#L193
I think it's trying to make sure that min and max values will fall into a bin. For many uses, where the x range is very large compared to the number of bin, this should work fine, except for maybe some odd numbers on the x axis. For the example shown here, it gives unexpected results.
