### ISSUE TITLE
Missing object attribute in gfsk.py

### ISSUE THREAD

**Issue by Gemikro1** [gnuradio/gnuradio#6517]
### What happened?

Using the GFSK Demod block throws an error in the function `def _print_verbage(self):` because the attribute `_mu` is missing. This attribute seems to have been deprecated but is still used in the function:

```
    def _print_verbage(self):
        print("bits per symbol = %d" % self.bits_per_symbol())
        print("Symbol Sync M&M omega = %f" % self._omega)
        print("Symbol Sync M&M gain mu = %f" % self._gain_mu)
        print("M&M clock recovery mu (Unused) = %f" % self._mu)
        print("Symbol Sync M&M omega rel. limit = %f" %
              self._omega_relative_limit)
        print("frequency error = %f" % self._freq_error)

```
Removing line 273 `print("M&M clock recovery mu (Unused) = %f" % self._mu)` fixes the error ...

### System Information

OS: Windows
GR Installation Method: RadioConda

### GNU Radio Version

3.10 (maint-3.10)

### Specific Version

3.10.5.0

### Steps to Reproduce the Problem

In RadioConda:
Add a `GFSK Demod` block, set `verbose` to `on` 
Execute 

### Relevant log output

```shell
AttributeError: 'gnuradio.gr.gr_python.hier_block2_pb' object has no attribute '_mu'
```

**Comment by willcode** [comment]
@Gemikro1 thanks for reporting. I've put in a PR to fix this.
