### ISSUE TITLE
How can I get rid of "Warning: failed to XInitThreads()"?

### ISSUE THREAD

**Issue by nau4k** [gnuradio/gnuradio#6525]
### What happened?

I tried to make a simple FM receiver using RTL-SDR r820t2 using the diagram as shown in the picture then when I run the program a warning appears like this.

![](https://wiki.gnuradio.org/images/3/39/RTLSDR_receive_fg.png)

>>>Warning: failed to XInitThreads()
gr-osmosdr 0.2.0.0 (0.2.0) gnuradio 3.8.2.0
built-in source types: file fcd rtl rtl_tcp uhd hackrf bladerf rfspace airspy airspyhf soapy redpitaya freesrp 
[INFO] [UHD] linux; GNU C++ version 9.2.1 20200304; Boost_107100; UHD_3.15.0.0-2build5
[INFO] Using format CF32.
Done (return code -11)

### System Information

OS: (Linux Distro, Mac, Windows)
GR Installation Method: (native distro packages - apt, rpm, etc., Conda, Source

### GNU Radio Version

3.8  (maint-3.8)

### Specific Version

3.8.2.0

### Steps to Reproduce the Problem

I tried to make a simple FM receiver using RTL-SDR r820t2 using the diagram as shown in the picture then when I run the program a warning appears like this.

**Comment by marcusmueller** [comment]
So, short answer: it's just a warning. Ignore it – all is well. 

The fact that you've not even filled out the "System Information" field means we can't even tell you what goes wrong or right. We can infer from your output that this is quite likely Linux distro that's not debian, but it might also be WSL? Not sure. Might all be alright – you might be running on wayland or similar.

Long answer:

We're in the process of removing the whole step of even calling XInitThreads in the Python template for programs generated through GRC from the current development head, and from the maint-3.10 series, as for these, it's safe that the underlying graphics toolkit/library takes care of that, anyways (#6506).

For 3.8, there will be no backport of that – it's just a warning; we'd rather not touch the ultra-stable 3.8 series just to silence a warning.

---

So, I'm afraid: for your GNU Radio 3.8, there's, short of editing your generated .py file to remove that warning itself, no way to get rid of that, sorry. The good news is that chances are you really don't need to worry about it.
