### ISSUE TITLE
grc: some filter blocks fail in building flowgrap

### ISSUE THREAD

**Issue by dl1ksv** [gnuradio/gnuradio#6526]
### What happened?

After apllying  #6523 filter blocks fail that use a window parameter due to a missing import statement that was removed in the option block.

### System Information

OS: FC37
GR Installation Method: Source

### GNU Radio Version

3.11-git (main)

### Specific Version

v3.11.0.0git-392-gf00dd77c

### Steps to Reproduce the Problem

Signal source -> Low Pass Filter -> Null Sink

This can be fixed by either
-  Adding an import block to the flowgraph with "from gnuradio.fft import window" by the user
-  Adding "from gnuradio.fft import window" to the import section in low_pass_filter.block.yml (This has to be done to each yml file the references a window type)
- Adding  again "from gnuradio.fft import window" to the template section in options.block.yml

What's the preferred way to fix this issue?
 

### Relevant log output

```shell
Param - Window(win):
	Value "window.WIN_HAMMING" cannot be evaluated:
	name 'window' is not defined
```

**Comment by willcode** [comment]
I'll revert that PR. Seemed like a good idea. There are many mysteries hidden in GRC.
