### ISSUE TITLE
Double free or corruption error when two instances of an OOT block is called in GRC

### ISSUE THREAD

**Issue by graceyeung68** [gnuradio/gnuradio#6528]
### What happened?

I have an out-of-tree block in c++ that runs fine in GRC but when I have two of them running simultaneously in a flowgraph, I am getting a "double free or corruption" error. I am not using any free() functions in my code. I use std::vector's in the code which should handle the dynamic memory allocation automatically. The only place I can see in the code is the definition of the make function that calls new to return an sptr as indicated below. What might be the cause of this error? Thank you.

      probeExtract::sptr
      probeExtract::make(const char* filtName, const char* maskName, int mlsrM, int numChan, int sampPerBit, int Tblock, int edgeBufferSize, int structureType)
      {
          return gnuradio::get_initial_sptr
          (new probeExtract_impl(filtName, maskName, mlsrM, numChan, sampPerBit, Tblock, edgeBufferSize, structureType));
      }
      

### System Information

OS: Ubuntu 20.04
GR Installation Method: apt?

### GNU Radio Version

3.8  (maint-3.8)

### Specific Version

3.8.1.0

### Steps to Reproduce the Problem

Two instances of OOT block running simultaneously.

### Relevant log output

```shell
double free or corruption (!prev)
```

**Comment by willcode** [comment]
@graceyeung68 This is probably something that has to be fixed in the OOT block. There is nothing in the GNU Radio core that limits how many of a certain type of block can exist. There are many flowgraphs in use that have more than one of a certain block. You could post a link to your code on chat.gnuradio.org or the mailing list to see whether someone can help debug.

We can leave this issue open for now in case the error is shown to be in GR. Please close otherwise.

**Comment by graceyeung68** [comment]
Thank you. So is the "new" function indicated above that returns the sptr for the class object automatically taken care of internally by python and I won't need to worry about free'ing or deleting any pointers that might be the cause of the error?

Thank you.

**Comment by willcode** [comment]
Smart pointers automatically delete the internal object when the refcount reaches 0. No explicit free is required. See
https://cplusplus.com/reference/memory/shared_ptr/

Closing, since this is not a GNU Radio bug.

**Comment by graceyeung68** [comment]
Thank you Marcus for the detailed explanation. I will give the debugger a try. One thing I do notice is the flowgraph crashes at different points in the code in each successive run after each crash giving a different error message such as:
corrupted size vs. prev size while consolidating
double free or corruption (!prev)
double free or corruption (top)
double free or corruption (fasttop)
double free or corruption (out)
malloc(): unsorted double linked list corrupted
or just an error code without a message. And nowhere in my code do I use malloc() or free(). That's why I was wondering if it is something internal or under the hood... Thank you.

**Comment by graceyeung68** [comment]
Backtracing shows the crash happens in an fftw3f library function used in the code. Is the fftw3f package compatible with GR? Thank you.

(gdb) bt
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
#1  0x00007ffff7dd1859 in __GI_abort () at abort.c:79
#2  0x00007ffff7e3c26e in __libc_message (action=action@entry=do_abort, fmt=fmt@entry=0x7ffff7f66298 "%s\n") at ../sysdeps/posix/libc_fatal.c:155
#3  0x00007ffff7e442fc in malloc_printerr (str=str@entry=0x7ffff7f68628 "double free or corruption (fasttop)") at malloc.c:5347
#4  0x00007ffff7e45c65 in _int_free (av=0x7fffac000020, p=0x7fffac55a8d0, have_lock=0) at malloc.c:4266
#5  0x00007fffefe830d9 in ?? () from /lib/x86_64-linux-gnu/libfftw3f.so.3
#6  0x00007fffefe83c44 in ?? () from /lib/x86_64-linux-gnu/libfftw3f.so.3
#7  0x00007fffefe83fc4 in fftwf_mkplan_d () from /lib/x86_64-linux-gnu/libfftw3f.so.3
#8  0x00007fffefe88e5d in ?? () from /lib/x86_64-linux-gnu/libfftw3f.so.3
#9  0x00007fffefe8380b in ?? () from /lib/x86_64-linux-gnu/libfftw3f.so.3
#10 0x00007fffefe83a03 in ?? () from /lib/x86_64-linux-gnu/libfftw3f.so.3
#11 0x00007fffefe83fc4 in fftwf_mkplan_d () from /lib/x86_64-linux-gnu/libfftw3f.so.3
#12 0x00007fffefe8d95c in ?? () from /lib/x86_64-linux-gnu/libfftw3f.so.3
#13 0x00007fffefe8380b in ?? () from /lib/x86_64-linux-gnu/libfftw3f.so.3
#14 0x00007fffefe83a03 in ?? () from /lib/x86_64-linux-gnu/libfftw3f.so.3
#15 0x00007fffefe83fc4 in fftwf_mkplan_d () from /lib/x86_64-linux-gnu/libfftw3f.so.3
#16 0x00007fffefe84043 in fftwf_mkplan_f_d () from /lib/x86_64-linux-gnu/libfftw3f.so.3
#17 0x00007fffefe887a3 in ?? () from /lib/x86_64-linux-gnu/libfftw3f.so.3
#18 0x00007fffefe8380b in ?? () from /lib/x86_64-linux-gnu/libfftw3f.so.3
#19 0x00007fffefe83a03 in ?? () from /lib/x86_64-linux-gnu/libfftw3f.so.3
#20 0x00007fffefe83fc4 in fftwf_mkplan_d () from /lib/x86_64-linux-gnu/libfftw3f.so.3
#21 0x00007fffefe88e5d in ?? () from /lib/x86_64-linux-gnu/libfftw3f.so.3
#22 0x00007fffefe8380b in ?? () from /lib/x86_64-linux-gnu/libfftw3f.so.3
#23 0x00007fffefe83a03 in ?? () from /lib/x86_64-linux-gnu/libfftw3f.so.3
#24 0x00007fffeff4a583 in ?? () from /lib/x86_64-linux-gnu/libfftw3f.so.3
#25 0x00007fffeff4a758 in fftwf_mkapiplan () from /lib/x86_64-linux-gnu/libfftw3f.so.3
#26 0x00007fffeff4ddd7 in fftwf_plan_many_dft () from /lib/x86_64-linux-gnu/libfftw3f.so.3
#27 0x00007fffeff4d09b in fftwf_plan_dft () from /lib/x86_64-linux-gnu/libfftw3f.so.3
#28 0x00007fffeff4cd9a in fftwf_plan_dft_1d () from /lib/x86_64-linux-gnu/libfftw3f.so.3
#29 0x00007fffe99b04d5 in gr::customModule::probeExtract_impl::ApplyFilterBank(int, gr::customModule::probeExtract_impl::FilterBank, std::vector<std::complex<float>, std::allocator<std::complex<float> > >&, int, int, int, std::vector<float, std::allocator<float> >&, int, int, int) ()
   from /usr/local/lib/x86_64-linux-gnu/libgnuradio-customModule.so.1.0.0git
#30 0x00007fffe99b1f69 in gr::customModule::probeExtract_impl::general_work(int, std::vector<int, std::allocator<int> >&, std::vector<void const*, std::allocator<void const*> >&, std::vector<void*, std::allocator<void*> >&) () from /usr/local/lib/x86_64-linux-gnu/libgnuradio-customModule.so.1.0.0git
#31 0x00007ffff0799c03 in gr::block_executor::run_one_iteration() () from /lib/x86_64-linux-gnu/libgnuradio-runtime.so.3.8.1
#32 0x00007ffff07ed59a in gr::tpb_thread_body::tpb_thread_body(boost::shared_ptr<gr::block>, boost::shared_ptr<boost::barrier>, int) ()
   from /lib/x86_64-linux-gnu/libgnuradio-runtime.so.3.8.1
#33 0x00007ffff07dd818 in ?? () from /lib/x86_64-linux-gnu/libgnuradio-runtime.so.3.8.1
#34 0x00007ffff07fc4e8 in ?? () from /lib/x86_64-linux-gnu/libgnuradio-runtime.so.3.8.1
#35 0x00007ffff010343b in ?? () from /lib/x86_64-linux-gnu/libboost_thread.so.1.71.0
#36 0x00007ffff7d94609 in start_thread (arg=<optimized out>) at pthread_create.c:477
#37 0x00007ffff7ece133 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

**Comment by graceyeung68** [comment]
Hi, I understand this issue has been closed. But from the previous comment, grc breaks during a call to fftw. I'd like to know if there is anything special that I should watch out for if I am simply trying to use fftw to perform a forward/backward transform. The double free error is occurring during a call to fftw. Thanks!

**Comment by Contemplationliferay-623** [comment]
> [@willcode](https://github.com/willcode) [@marcusmueller](https://github.com/marcusmueller) Hi, I understand this issue has been closed. But from the previous comment, grc breaks during a call to fftw. I'd like to know if there is anything special that I should watch out for if I am simply trying to use fftw to perform a forward/backward transform. The double free error is occurring during a call to fftw. Thanks!





https://sabredav299.github.io/QGP8HaIbnSVUTqebOEg3e8RJdV04a03tQ2Wk6PyNfnKtSGkm/
