### ISSUE TITLE
header_format_crc.h incorrect information in doc section

### ISSUE THREAD

**Issue by duggabe** [gnuradio/gnuradio#6550]
### What happened?

In the documentation section of the include file, the generated header format is described as:
 * \verbatim
     |  0 -- 11 | 12 -- 23 | 24 -- 31 |
     |    len   | pkt len  |   CRC8   |
   \endverbatim

However, the actual created format is:
8 bits - LSB of packet length
4 bits - LSB of packet number
4 bits - MSB of packet length
8 bits - MSB of packet number
8 bits - CRC8

### System Information

OS: XUbuntu 22.10
GR Installation Method: from source

### GNU Radio Version

3.10 (maint-3.10)

### Specific Version

3.10.5.1

### Steps to Reproduce the Problem

I changed the packet_len in pkt_12.grc   https://pastebin.com/ZmykNrAX and observed the output using a large input text file to create lots of packets.

### Relevant log output

```shell
***** VERBOSE PDU DEBUG PRINT ******
()
pdu length =          4 bytes
pdu vector contents = 
0000: 26 a1 06 77 
************************************
```

**Comment by duggabe** [comment]
The subject file is in https://github.com/gnuradio/gnuradio/blob/main/gr-digital/include/gnuradio/digital/header_format_crc.h

**Comment by willcode** [comment]
Here are the first 3 prints from the provided flowgraph, to make it easier to see the sequence. The serializer in `header_buffer.cc` packs one byte at a time, defaulting to LSB first. This has the effect of mixing up bitfields that span bytes.
```
***** VERBOSE PDU DEBUG PRINT ******
()
pdu length =          4 bytes
pdu vector contents = 
0000: 26 01 00 00 
************************************
***** VERBOSE PDU DEBUG PRINT ******
()
pdu length =          4 bytes
pdu vector contents = 
0000: 26 11 00 15 
************************************
***** VERBOSE PDU DEBUG PRINT ******
()
pdu length =          4 bytes
pdu vector contents = 
0000: 26 21 00 2a 
************************************
```
The second debug print corresponds to the 24-bit `0x001126` plus crc `0x15`, with packet number 0x001 and packet length 0x126 (290 byte payload plus 4 byte header). So, once the 24-bit value is de-serialized the documentation applies. That's not any of the (multiple) ways the documentation would usually be interpreted.

This is a pretty confusing OTW format, if we meant it to be interoperable with other system, but that was probably not a consideration when this was written 8+ years ago.

I can't think of a useful way to document this OTW format, even if we could make it correct.

**Comment by duggabe** [comment]
a) Lines 60-66 have a better format, so we could use that,  **-OR-**
b) the code could be corrected to produce the documented layout
