### ISSUE TITLE
channel model default taps

### ISSUE THREAD

**Issue by jsallay** [gnuradio/gnuradio#6576]
### What happened?

The `Channel Model` and `Channel Model 2` blocks have default channel taps of `1 +j1`.  In the Documentation it states: `Taps of a FIR filter to emulate a multipath delay profile. Default is 1+1j meaning a single tap, and thus no multipath.`  This doesn't apply multipath, but it does rotate the data and increase its magnitude.  Here is an example of a simple BPSK signal.
  
![image](https://user-images.githubusercontent.com/31416796/225328223-ffd8889e-815d-4209-bf39-0d84003f00ea.png)

I think that the default taps should be changed to `1+j0`.  I'm happy to submit a PR for this.

### System Information

OS: all
GR Installation Method: Source

### GNU Radio Version

3.10 (maint-3.10)

### Specific Version

3.10.4.0

### Steps to Reproduce the Problem

Create a flowgraph with a `Constellation Modulator` and a `Channel Model`.  Input BPSK symbols and see that the output when using the default values is rotated and scaled.

**Comment by willcode** [comment]
@jsallay yes, please submit a PR.
