### ISSUE TITLE
Improper Explanation of Differential Phasor

### ISSUE THREAD

**Issue by DevanshRaizada** [gnuradio/gnuradio#6625]
### Feature Description

Not really a bug, but the definition of Differential Phasor in 'Category: Block Docs' is short and unclear and doesn't have an example to explain it. 
[Link](https://wiki.gnuradio.org/index.php?title=Differential_Phasor)

### Feature Urgency

medium (would be nice to have in the near future)

**Comment by marcusmueller** [comment]
Hi @DevanshRaizada! Seeing that's a wiki page: do you feel up to the task to improving that documentation?

**Comment by DevanshRaizada** [comment]
@marcusmueller Yes, surely I would love to improve that documentation.

**Comment by marcusmueller** [comment]
Ha, wonderful! @DevanshRaizada then please do that: on the wiki page you've linked to, there's an "Edit" link (somewhere on the top right). Unless you have a wiki account already, you can make an edit, and then one of the moderator wiki users has to click on "this edit is OK". Then we'll have fixed the issue in no time!

**Comment by DevanshRaizada** [comment]
@marcusmueller Thank you for th guidance.

**Comment by DevanshRaizada** [comment]
I have updated the page and now I am closing the issue.

**Comment by marcusmueller** [comment]
Thank you so much, @DevanshRaizada !

**Comment by DevanshRaizada** [comment]
@marcusmueller No need I'm actually looking for meaningful ways of contributing.
