### ISSUE TITLE
Rx OFDM example in gr-digital gives only half of the packet input at the output.

### ISSUE THREAD

**Issue by Abrahamma97** [gnuradio/gnuradio#6643]
### What happened?

A bug happened!

### System Information

OS: (Linux Distro, Mac, Windows)
GR Installation Method: (native distro packages - apt, rpm, etc., Conda, Source
Os Linux

### GNU Radio Version

3.10 (maint-3.10)

### Specific Version

0.0.0.0

### Steps to Reproduce the Problem

I tried with a vector source with 96 values ranging from 0 to 255 and got only 48 values

**Comment by marcusmueller** [comment]
duplicate: https://github.com/gnuradio/gnuradio/issues/6891
