### ISSUE TITLE
[MSVC] 'sscanf()' and "%m"

### ISSUE THREAD

**Issue by gvanem** [gnuradio/gnuradio#6648]
### Feature Description

Building **gnuradio-qtgui.dll** on MSVC (with OpenGL support), I noted this important warning:
```c
QFosphorColorMapper.cc(67): warning C4476: 'sscanf' : unknown type field character 'm' in format specifier
QFosphorColorMapper.cc(67): warning C4474: 'sscanf' : too many arguments passed for format string
QFosphorColorMapper.cc(67): note: placeholders and their parameters expect 1 variadic arguments, but 2 were provided
```

A support for `%m` seems Linux specific too me. Ref:  http://linux.die.net/man/3/scanf 

No word on this on [MSDN](https://learn.microsoft.com/en-us/cpp/c-runtime-library/scanf-type-field-characters?view=msvc-170). Not sure if MinGW-w64 supports this. 

For MSVC, that code will crash at runtime; `free()` of an illegal pointer.

I tried this feeble attempt instead:
```diff
--- a/gr-qtgui/lib/QFosphorColorMapper.cc 2023-04-26 15:19:11
+++ b/gr-qtgui/lib/QFosphorColorMapper.cc 2023-05-04 13:47:35
@@ -64,7 +64,13 @@

         /* Are we in a palette ? */
         if (kp < 0) {
+#ifdef _WIN32
+            char buf[41] = { '\0' };
+            name = buf;
+            sscanf(line.constData(), "%d %40s", &kp, buf);
+#else
             sscanf(line.constData(), "%d %ms", &kp, &name);
+#endif

             if (kp)
                 gradient = new QLinearGradient();
@@ -75,8 +81,10 @@

             addPalette(name, pixmap);

+#ifdef _WIN32
             /* Release name & prepare for next */
             free(name);
+#endif
             name = NULL;

             kp = -1;
@@ -96,7 +104,9 @@
                 delete gradient;
                 gradient = NULL;

+#ifdef _WIN32
                 free(name);
+#endif
                 name = NULL;

                 kp = -1;
```

Must be a better way.

### Feature Urgency

high (impacts broad portion of ecosystem)

**Comment by marcusmueller** [comment]
Elevating this to bug status. Yeah, also, why are we doing `sscanf` in a C++ program…

**Comment by willcode** [comment]
Related to #6515 
@mbr0wn @gmeyerho can we replace the `sscanf()` functions with a safe alternative?

**Comment by willcode** [comment]
Keep cool!

**Comment by marcusmueller** [comment]
@gvanem do you think #6676 works for you?
