### ISSUE TITLE
GNU Radio for el9 EPEL repository

### ISSUE THREAD

**Issue by kb6ibb** [gnuradio/gnuradio#6693]
### Feature Description

Create and place a rpm for el9 Linux in the  EPEL - 9 (stable) repository.  

### Feature Urgency

high (impacts broad portion of ecosystem)

### More Information

Red Hat Enterprise Linux 9 and subsequent branches thereof have been released now for a year.   Many systems are beginning to update from el8 to el9.    Currently GNU Radio does not exist within the EPEL-9 repositories.

**Comment by willcode** [comment]
In general, GNU Radio does not provide packages for distributions, only source code. Packaging is done by distro-specific maintainers. If you can not find GNU Radio in your distro's repos, please request that your distro add it.
