### ISSUE TITLE
Cannot output audio when using Raspberry Pi

### ISSUE THREAD

**Issue by 01778680** [gnuradio/gnuradio#6695]
I have successfully referenced my audio device in the audio_sink block, however, this did not result in any sound. I tried different sampling rates, which had no effect. I tested the audio output using the speaker-test utility included in ALSA, and it is outputting audio perfectly fine. I even bought a separate audio card for the raspberry pi with no luck. I am not receiving any error messages. 

Is there something I should be aware of with GNURadio in regards to the Raspberry Pi? I have successfully ran my program on two other Linux devices without issue using their default audio devices.

**Comment by willcode** [comment]
Audio works on my RPi4, Ubuntu 22.04, with the built in audio. Please use chat.gnuradio.org or the mailing list for help requests. If you find a specific bug, feel free to report it here.
