### ISSUE TITLE
Attribute error 

### ISSUE THREAD

**Issue by pallavi-7220** [gnuradio/gnuradio#6719]
File "C:\Users\IISc_\radioconda\lib\site-packages\gnuradio\digital\generic_mod_demod.py", line 105, in __init__
    self.pre_diff_code = int(pre_diff_code and self._constellation.apply_pre_diff_code())
AttributeError: 'int' object has no attribute 'apply_pre_diff_code'
 
I am getting this error when I run a GRC flowgraph. can you help me resolve it. 
![Capture](https://github.com/gnuradio/gnuradio/assets/86345953/b6412ee0-ff26-415b-b6d9-0b7fe9c89786)

The above GRC flowgraph does 3CAT2 satellite decoding

### System Information

OS: Windows
GR Installation Method: (https://github.com/ryanvolz/radioconda/releases)

### GNU Radio Version

3.10 (maint-3.10)

### Specific Version

3.10.5.1 (Python 3.10.9)

### Steps to Reproduce the Problem

No idea

**Comment by willcode** [comment]
Please ask for help using chat.gnuradio.com or the mailing list. If this turns out to be a bug, or if you have a feature request, reopen this issue.
