### ISSUE TITLE
usrp_source_impl::work() in gr-uhd/lib/usrp_source_impl.cc can overflow the stack

### ISSUE THREAD

**Issue by jasonbarkdull** [gnuradio/gnuradio#6721]
### What happened?

In usrp_source_impl::work(), in the case ::uhd::rx_metadata_t::ERROR_CODE_OVERFLOW clause, the work() function is called recursively.  if repeated ERROR_CODE_OVERFLOW errors occur, the stack will overflow, trashing other threads.
A quick fix: add a tag/label "again:" at the beginning of the work() and the replace the recursive call to work with a "goto again;"

### System Information

OS: Linux, Ubuntu 20.4
GR Installation Method: locally compiled source

### GNU Radio Version

3.10 (maint-3.10)

### Specific Version

3.10.5.0

### Steps to Reproduce the Problem

cripple the speed of your USRP radio's connection: reduce the bit rate of the interface and/or increase the sample rate causing overflows.
then run any simple grc containing a USRP source block: e.g. USRP source block connect to a Null sink.
Compile it in the gr-companion and then run it in the companion or at commandline.
Should see lots of overflow messages: "usrp_source :error: In the last 808 ms, 8 overflows occurred."
attach via gdb, find the thread running the usrp work() function and then do "backtrace"; should see recursive calls in the stack, if it hasn't gone to far and trashed lot of other memory.

### Relevant log output

```shell
DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDODDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDusrp_source :error: In the last 804 ms, 115 overflow occurred.
DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDODDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDusrp_source :error: In the last 804 ms, 115 overflow occurred.DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDODDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDusrp_source :error: In the last 804 ms, 115 overflow occurred.DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDODDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDusrp_source :error: In the last 804 ms, 115 overflow occurred.DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDODDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDusrp_source :error: In the last 804 ms, 115 overflow occurred.
```

**Comment by willcode** [comment]
PR #6688 (in progress) addresses this.
