### ISSUE TITLE
Errors during evaluation of "hide" cause faulty input fields to be hidden

### ISSUE THREAD

**Issue by eltos** [gnuradio/gnuradio#6726]
### What happened?

If for any reason the expression used to calculate the `hide` property of a block parameter fails, `hide` defaults to `all`, causing the input to be hidden which can make it impossible for the user to fix the error (other than manually editing the grc file with a text editor).

### System Information

OS: Ubuntu 20.04 LTS
GR Installation Method: compiled from source

### GNU Radio Version

3.10 (maint-3.10)

### Specific Version

3.10.5.1

### Steps to Reproduce the Problem

Consider the python snipped block, which defines the following parameter via its [`snippet.block.yml`](https://github.com/gnuradio/gnuradio/blob/main/grc/blocks/snippet.block.yml) file:
```yml
-   id: priority
    label: Priority
    dtype: int
    default: "0"
    hide: ${'part' if priority <= 0 else 'none'}
```
The definition of hide is chosen such that the visual block component is not cluttered with defaults.

Now consider that a user creates a flow graph with a Python Snipped block and then opens the blocks properties window and changes the value of priority. By accident, the user types "r" instead of "5" and then changes focus to the next input field.

![grafik](https://github.com/gnuradio/gnuradio/assets/19860638/aeebcc7a-b525-4191-a1b1-c961cd11cb21)

This causes the evaluation `${'part' if priority <= 0 else 'none'}` to be performed, failing with 
```
Value "r" cannot be evaluated: name 'r' is not defined
```

While the error is expected, it causes `hide` to default to `all`.
**As a result, the input field for priority is hidden, making it impossible for the user to fix the typo.**

![grafik](https://github.com/gnuradio/gnuradio/assets/19860638/ff02a72b-7996-4758-a6b4-961906cd2f1d)

To mitigate such issues, `hide` must default to `none` if its value cannot be determined for any reason.

### Relevant log output

```shell
None
```

**Comment by marcusmueller** [comment]
Seems to be solved:
https://gist.github.com/marcusmueller/ed45515e099b0e2bcd16b392447317f0
 
![repro6726](https://github.com/gnuradio/gnuradio/assets/958972/11ec9ade-ae99-405a-bb5e-611f21b2dd10)

reopening the props:

![property dialog showing the property](https://github.com/gnuradio/gnuradio/assets/958972/7c2b649e-4929-4e16-99dd-5b1407da31e6)
