### ISSUE TITLE
usrp - the images directory cannot be located 

### ISSUE THREAD

**Issue by cipriancircu** [gnuradio/gnuradio#6731]
### What happened?

Hello.
I have installed gnuradio and uhd on Ubuntu 22.0.4 following source installation. 

Both installations were successful, and I'm able to detect the usrp (b200mini) when running the uhd_find_devices and its serial number.
However, despite having all the images extracted when trying to run an application, I am met with the following message:
"[WARNING][B200]EnvironmentError: IOError: Could not find path for image: usrp_b200_fw.hex
Using images directory: <no images directory located>
Set the environment variable 'UHD_IMAGES_DIR' appropriately or follow the bellow instructions to download the images package"

From what I understand, USRP source cannot point to the correct image (currently I have downloaded all images using uhd_images_downloader.py in the /usr/local/share/uhd/images)

On different forums a fix was to change the path where UHD_IMAGES_DIR points to the path that I've currently set in place. But it does not work for me.

I was hoping someone has found the fix for this issue. 

Hope you're all having a good day. :) 

### System Information

OS: UBUNTU 22.0.4
GR Installation Method: Source

### GNU Radio Version

4.0-git (dev-4.0)

### Specific Version

0.0.0.0

### Steps to Reproduce the Problem

Connect the USRP to the device. 
Point using the UHD USRP block to the serial number of the device "serial=xyzw".
Run the graph.

**Comment by willcode** [comment]
Please ask for help on chat.gnuradio.org or the mailing list. The issue tracker is used for bug reports and feature requests. Also, this is a USRP, not a GNU Radio setup question.
