### ISSUE TITLE
’gr_modtool bind‘ an existing module is faulty

### ISSUE THREAD

**Issue by GuanQiQ** [gnuradio/gnuradio#6741]
### Feature Description

I installed Gnuradio3.10, and I want to modify some modules based on the existing modules, so I need to change the header files in the include, and I need to re-bind them.
For example, `gt_modtool bind ofdm_chanest_vcvc` will display an error:
“gnuradio.modtool.core.base.ModToolException: No GNU Radio module found in the given directory.
"
I see in this file describes the "https://gitlab.com/opencpi/gnuradio/-/blob/gvanem-master/docs/PYBIND11.md"
I try to use the command "`python3 bind_gr_module. Py -- prefix/home/kali/workarea/gnuradio/digital`" but quote us such a mistake again
“Writing binding code to /tmp/gnuradio/digital/bindings/ofdm_serializer_vcc_python.cc
Writing binding code to /tmp/gnuradio/digital/bindings/docstrings/ofdm_serializer_vcc_pydoc_template.h
Error: Can't parse input signature.
Error: Can't parse output signature.
Writing binding code to /tmp/gnuradio/digital/bindings/ofdm_sync_sc_cfb_python.cc
Writing binding code to /tmp/gnuradio/digital/bindings/docstrings/ofdm_sync_sc_cfb_pydoc_template.h
Can't open some of the files necessary to parse  /home/kali/workarea/gnuradio/gr-digital/lib/packet_header_default_impl.cc.
Can't open some of the files necessary to parse /home/kali/workarea/gnuradio/gr-digital/lib/packet_header_ofdm_impl.cc.
Writing binding code to /tmp/gnuradio/digital/bindings/packet_headergenerator_bb_python.cc
Writing binding code to /tmp/gnuradio/digital/bindings/docstrings/packet_headergenerator_bb_pydoc_template.h
"

### Feature Urgency

high (impacts broad portion of ecosystem)

**Comment by willcode** [comment]
Please ask for help at chat.gnuradio.org or on the mailing list.
