### ISSUE TITLE
Attempting to use an osmocom Source on Ubuntu 20.04 gives RuntimeError: logger_set_level: Bad level type

### ISSUE THREAD

**Issue by 46cv8** [gnuradio/gnuradio#6757]
### What happened?

Any attempt to use an osmocom Source, causes the error "RuntimeError: logger_set_level: Bad level type.". when one attempts to execute the flow graph.

### System Information

OS: (Ubuntu 20.04)
GR Installation Method: 
```
Fresh ubuntu 20.04 install followed by
sudo apt update
sudo apt upgrade
sudo add-apt-repository ppa:gnuradio/gnuradio-releases
sudo apt update
sudo apt-get install gnuradio gr-osmosdr libhackrf-dev hackrf
```

### GNU Radio Version

3.8  (maint-3.8)

### Specific Version

3.8.1.0

### Steps to Reproduce the Problem

1) Made a very simple flow graph with Signal Source and QT GUI Frequency Sink and execute the flow graph and everything looks and works fine.
2) Swap out the Signal Source for a osmocom Source, attempt to execute the flow graph, you get an error relating to "RuntimeError: logger_set_level: Bad level type.". 

I believe this may be an issue specific to the osmocom osmosdr but I'm unsure if it is some form of version incompatibility or what with this specific gnuradio version or what. Any assistance would be a big help as I can't even find the line of code that calls logger_set_level anywhere in https://github.com/osmocom/gr-osmosdr/tree/master Googling for "logger_set_level" returns only 3 hits, one of which is in the gnuradio issue base #1771 and pertains to an incorrect version of log4cpp being installed causing a failure to build from src. It doesn't seem directly related but that is why I thought maybe someone here could help.

### Relevant log output

```shell
Generating: '/home/user/Documents/GNURadio/test/default.py'

Executing: /usr/bin/python3 -u /home/user/Documents/GNURadio/test/default.py

Qt GUI: Could not restore geometry: restoreGeometry(self, Union[QByteArray, bytes, bytearray]): argument 1 has unexpected type 'NoneType'
gr-osmosdr 0.2.0.0 (0.2.0) gnuradio 3.8.1.0
built-in source types: file osmosdr fcd rtl rtl_tcp uhd miri hackrf bladerf rfspace airspy airspyhf soapy redpitaya freesrp 
Traceback (most recent call last):
  File "/home/user/Documents/GNURadio/test/default.py", line 190, in <module>
    main()
  File "/home/user/Documents/GNURadio/test/default.py", line 168, in main
    tb = top_block_cls()
  File "/home/user/Documents/GNURadio/test/default.py", line 114, in __init__
    self.osmosdr_source_0 = osmosdr.source(
  File "/usr/lib/python3/dist-packages/osmosdr/osmosdr_swig.py", line 1074, in make
    return _osmosdr_swig.source_make(*args, **kwargs)
RuntimeError: logger_set_level: Bad level type.


>>> Done (return code 1)
```

**Comment by willcode** [comment]
GR 3.8 is no longer supported and there have been no recent changes. You may be able to get help with this at chat.gnuradio.org or on the mailing list.

It's possible that the PPA and stock Ubuntu 20.04 installations are conflicting, or that a dependency has changed.

**Comment by marcusmueller** [comment]
> It's possible that the PPA and stock Ubuntu 20.04 installations are conflicting

correctly so, the 

     apt-get install  gr-osmosdr 

will downgrade the GNU Radio from our PPA (3.10.7.0) back to Ubuntu 20.04's version, i.e. 3.8.1.0, because it depends on that version.

Solutions:

First, you need to `sudo apt-get remove gr-osmosdr`, followed by `sudo apt-get upgrade gnuradio` (and read the output to make sure you're actually getting GNU Radio 3.10.7.0!)

- Either, *don't use gr-osmosdr*, but replace it with gr-soapysdr, which the PPA's GNU Radio 3.10 ships with
- Or, rebuild `gr-osmosdr` from source, instead of using Ubuntu's `gr-osmosdr` package.

**Comment by 46cv8** [comment]
Thanks @marcusmueller removing gr-osmosdr and using soapy fixed the problem :) I didn't even need to install gr-soapysdr as the sources as installed by default. Thanks a bunch :)
