### ISSUE TITLE
RTLSDR

### ISSUE THREAD

**Issue by saaketh2074** [gnuradio/gnuradio#6773]
### What happened?

I want to use GNUradio to program an RTL-SDR. I have tries installing all the drivers that i could find in chatgpt. Ive installed the following packages.

gr-osmodr

rtl-sdr

gr-rtl-sdr

I have also installed the required libraries but i still cant find the rtlsdr bloack in GNUradio. What do i do?

### System Information

OS: Linux(Ubuntu)
GR Installation Method: apt

### GNU Radio Version

3.8  (maint-3.8)

### Specific Version

3.8.5.0

### Steps to Reproduce the Problem

Download GNUradio
install 
gr-osmodr

rtl-sdr

gr-rtl-sd

Then install the library required.

**Comment by willcode** [comment]
Please ask for help at chat.gnuradio.org or on the mailing list. The issue tracker is used for bug reports and feature requests.
