### ISSUE TITLE
"Embedded Python Block," Not searchable via "Embedded" String

### ISSUE THREAD

**Issue by GentlemanSch** [gnuradio/gnuradio#6779]
### Feature Description

The GNU Radio tutorial describes this block 
<img width="198" alt="image" src="https://github.com/gnuradio/gnuradio/assets/25441680/1c182547-9229-49d3-9a52-921cd2bb5906">
as an "Embedded Python Block," 

<img width="503" alt="image" src="https://github.com/gnuradio/gnuradio/assets/25441680/832b0a4e-7d18-4d44-862b-7c5ac63ff9d1">

However, finding the block via CTRL + F, is is just called "Python Block."

<img width="216" alt="image" src="https://github.com/gnuradio/gnuradio/assets/25441680/725c7fd2-6e3b-4edf-a7c2-b2da071a9451">

Should these match?

### Feature Urgency

medium (would be nice to have in the near future)

**Comment by willcode** [comment]
This is incorrect. The block name, as shown on the canvas, is determined by the Python code in the embedded block.
