### ISSUE TITLE
About having an undefined symbol when connecting in OOT block

### ISSUE THREAD

**Issue by ForIn2you** [gnuradio/gnuradio#6810]
### What happened?

My OOT  can run make and install the module to gnuradio successfully, but I can't run the flow diagram. It occus error below:
ImportError: /usr/local/lib/x86_64-linux-gnu/libgnuradio-newmod.so.1.0.0: undefined symbol: _ZN2gr6filter6firdes8low_passEddddNS_3fft6window8win_typeEd
It seems .o (dynamic library) has a problem. I tried many methods, but none of them worked

### System Information

Linux 
gnuradio3.10.1.1 (Python 3.10.12)
uhd 4.1.0.5-3

### GNU Radio Version

3.10 (maint-3.10)

### Specific Version

3.10.1.1

### Steps to Reproduce the Problem

Execute after connecting to source

### Relevant log output

```shell
Warning: failed to XInitThreads()
Traceback (most recent call last):
  File "/home/zy/ce5.py", line 37, in <module>
    from gnuradio import newmod
  File "/usr/local/lib/python3.10/dist-packages/gnuradio/newmod/__init__.py", line 18, in <module>
    from .newmod_python import *
ImportError: /usr/local/lib/x86_64-linux-gnu/libgnuradio-newmod.so.1.0.0: undefined symbol: _ZN2gr6filter6firdes8low_passEddddNS_3fft6window8win_typeEd

>>> Done (return code 1)
```

**Comment by willcode** [comment]
Please ask for help on chat.gnuradio.org or the mailing list. The issue tracker is used for bug reports and feature requests.
