### ISSUE TITLE
Error while building gnuradio source code --> error: ‘RECV_MODE_ONE_PACKET’ is not a member of ‘uhd::device’

### ISSUE THREAD

**Issue by markibonge** [gnuradio/gnuradio#6829]
### What happened?

A bug happened! While I was trying to build the gnu radio source code on my ubuntu 18.04.06

Below is the error message I kept getting. I looked up and it seems like there were similar issues in the past. But I couldn't find a solution for the specific error message below. Please let me know what I can do to solve this issue. 

/usr/include/c++/7/bits/unique_ptr.h:51:28: note: declared here
   template<typename> class auto_ptr;
                            ^~~~~~~~
In file included from /home/opnear/workarea/gnuradio/gr-uhd/lib/usrp_source_impl.h:24:0,
                 from /home/opnear/workarea/gnuradio/gr-uhd/lib/usrp_source_impl.cc:24:
/home/opnear/workarea/gnuradio/gr-uhd/include/gnuradio/uhd/usrp_source.h:31:19: error: redefinition of ‘struct uhd::stream_args_t’
 struct GR_UHD_API stream_args_t {
                   ^~~~~~~~~~~~~
In file included from /home/opnear/workarea/gnuradio/gr-uhd/lib/gr_uhd_common.h:26:0,
                 from /home/opnear/workarea/gnuradio/gr-uhd/lib/usrp_source_impl.cc:23:
/usr/local/include/uhd/stream.hpp:47:16: note: previous definition of ‘struct uhd::stream_args_t’
 struct UHD_API stream_args_t
                ^~~~~~~~~~~~~
/home/opnear/workarea/gnuradio/gr-uhd/lib/usrp_source_impl.cc: In constructor ‘gr::uhd::usrp_source_impl::usrp_source_impl(const uhd::device_addr_t&, const uhd::stream_args_t&, bool)’:
/home/opnear/workarea/gnuradio/gr-uhd/lib/usrp_source_impl.cc:74:7: error: class ‘gr::uhd::usrp_source_impl’ does not have any field named ‘_recv_timeout’
       _recv_timeout(0.1), // seconds
       ^~~~~~~~~~~~~
/home/opnear/workarea/gnuradio/gr-uhd/lib/usrp_source_impl.cc:75:7: error: class ‘gr::uhd::usrp_source_impl’ does not have any field named ‘_recv_one_packet’
       _recv_one_packet(true),
       ^~~~~~~~~~~~~~~~
/home/opnear/workarea/gnuradio/gr-uhd/lib/usrp_source_impl.cc: In member function ‘virtual void gr::uhd::usrp_source_impl::set_recv_timeout(double, bool)’:
/home/opnear/workarea/gnuradio/gr-uhd/lib/usrp_source_impl.cc:464:5: error: ‘_recv_timeout’ was not declared in this scope
     _recv_timeout = timeout;
     ^~~~~~~~~~~~~
/home/opnear/workarea/gnuradio/gr-uhd/lib/usrp_source_impl.cc:464:5: note: suggested alternative: ‘set_recv_timeout’
     _recv_timeout = timeout;
     ^~~~~~~~~~~~~
     set_recv_timeout
/home/opnear/workarea/gnuradio/gr-uhd/lib/usrp_source_impl.cc:465:5: error: ‘_recv_one_packet’ was not declared in this scope
     _recv_one_packet = one_packet;
     ^~~~~~~~~~~~~~~~
/home/opnear/workarea/gnuradio/gr-uhd/lib/usrp_source_impl.cc:465:5: note: suggested alternative: ‘one_packet’
     _recv_one_packet = one_packet;
     ^~~~~~~~~~~~~~~~
     one_packet
/home/opnear/workarea/gnuradio/gr-uhd/lib/usrp_source_impl.cc: In member function ‘void gr::uhd::usrp_source_impl::flush()’:
/home/opnear/workarea/gnuradio/gr-uhd/lib/usrp_source_impl.cc:512:29: error: ‘using element_type = class uhd::device {aka class uhd::device}’ has no member named ‘recv’
         _dev->get_device()->recv(outputs,
                             ^~~~
/home/opnear/workarea/gnuradio/gr-uhd/lib/usrp_source_impl.cc:516:49: error: ‘RECV_MODE_FULL_BUFF’ is not a member of ‘uhd::device’
                                  ::uhd::device::RECV_MODE_FULL_BUFF,
                                                 ^~~~~~~~~~~~~~~~~~~
/home/opnear/workarea/gnuradio/gr-uhd/lib/usrp_source_impl.cc: In member function ‘virtual int gr::uhd::usrp_source_impl::work(int, gr_vector_const_void_star&, gr_vector_void_star&)’:
/home/opnear/workarea/gnuradio/gr-uhd/lib/usrp_source_impl.cc:600:44: error: ‘using element_type = class uhd::device {aka class uhd::device}’ has no member named ‘recv’
     size_t num_samps = _dev->get_device()->recv(output_items,
                                            ^~~~
/home/opnear/workarea/gnuradio/gr-uhd/lib/usrp_source_impl.cc:604:64: error: ‘RECV_MODE_FULL_BUFF’ is not a member of ‘uhd::device’
                                                 ::uhd::device::RECV_MODE_FULL_BUFF,
                                                                ^~~~~~~~~~~~~~~~~~~
/home/opnear/workarea/gnuradio/gr-uhd/lib/usrp_source_impl.cc:608:41: error: ‘using element_type = class uhd::device {aka class uhd::device}’ has no member named ‘recv’
         num_samps = _dev->get_device()->recv(output_items,
                                         ^~~~
/home/opnear/workarea/gnuradio/gr-uhd/lib/usrp_source_impl.cc:612:61: error: ‘RECV_MODE_ONE_PACKET’ is not a member of ‘uhd::device’
                                              ::uhd::device::RECV_MODE_ONE_PACKET,
                                                             ^~~~~~~~~~~~~~~~~~~~
gr-uhd/lib/CMakeFiles/gnuradio-uhd.dir/build.make:86: recipe for target 'gr-uhd/lib/CMakeFiles/gnuradio-uhd.dir/usrp_source_impl.cc.o' failed
make[2]: *** [gr-uhd/lib/CMakeFiles/gnuradio-uhd.dir/usrp_source_impl.cc.o] Error 1
CMakeFiles/Makefile2:14760: recipe for target 'gr-uhd/lib/CMakeFiles/gnuradio-uhd.dir/all' failed
make[1]: *** [gr-uhd/lib/CMakeFiles/gnuradio-uhd.dir/all] Error 2
Makefile:162: recipe for target 'all' failed
make: *** [all] Error 2

### System Information

OS: (Linux Distro)
GR Installation Method: Source

### GNU Radio Version

3.7  (maint-3.7)

### Specific Version

0.0.0.0

### Steps to Reproduce the Problem

Building and installing GNU Radio from source code

As with UHD, GNU Radio is open-source and is hosted on GitHub. You can browse the code online at the link below, which points to version v3.7.13.4, which is the the latest release at the time of this writing.

    GNU Radio repository on GitHub

Note: GNU Radio is currently transitioning from major branches of 3.7.x.x to 3.8.x.x. It is generally recommend at this time to use either the v3.7.13.4 or maint-3.7 branch of GNU Radio. The master branch includes many major changes such as converting to use Python 3 and may be unstable.

As with UHD, there are several good reasons to build GNU Radio from source code, especially for doing development and prototyping. It it enables an easy way to customize the location of the installation, and to install multiple GNU Radio versions in parallel, and switch between them. It also provides much more flexibility in upgrading and downgrading versions, and allows the user to modify the code and create customized versions, which could possibly include a patch or other bug-fix.

Similar to the process for UHD, to build GNU Radio from source code, clone the GitHub repository, check out a branch or tagged release of the repository, and build and install. Please follow the steps below. Make sure that no USRP device is connected to the system at this point.

First, make a folder to hold the repository.

   cd $HOME
   cd workarea

Next, clone the repository.

   git clone --recursive https://github.com/gnuradio/gnuradio

Next, go into the repository and check out the desired GNU Radio version.

   cd gnuradio

To checkout the v3.7.13.4 branch:

   git checkout v3.7.13.4

Or to checkout the maint-3.7 branch:

   git checkout maint-3.7

Next, update the submodules:

   git submodule update --init --recursive

Next, create a build folder within the repository, invoke CMake, and build GNU Radio:

   mkdir build
   cd build
   cmake ../
   make

### Relevant log output

```shell
usr/include/c++/7/bits/unique_ptr.h:51:28: note: declared here
   template<typename> class auto_ptr;
                            ^~~~~~~~
In file included from /home/opnear/workarea/gnuradio/gr-uhd/lib/usrp_source_impl.h:24:0,
                 from /home/opnear/workarea/gnuradio/gr-uhd/lib/usrp_source_impl.cc:24:
/home/opnear/workarea/gnuradio/gr-uhd/include/gnuradio/uhd/usrp_source.h:31:19: error: redefinition of ‘struct uhd::stream_args_t’
 struct GR_UHD_API stream_args_t {
                   ^~~~~~~~~~~~~
In file included from /home/opnear/workarea/gnuradio/gr-uhd/lib/gr_uhd_common.h:26:0,
                 from /home/opnear/workarea/gnuradio/gr-uhd/lib/usrp_source_impl.cc:23:
/usr/local/include/uhd/stream.hpp:47:16: note: previous definition of ‘struct uhd::stream_args_t’
 struct UHD_API stream_args_t
                ^~~~~~~~~~~~~
/home/opnear/workarea/gnuradio/gr-uhd/lib/usrp_source_impl.cc: In constructor ‘gr::uhd::usrp_source_impl::usrp_source_impl(const uhd::device_addr_t&, const uhd::stream_args_t&, bool)’:
/home/opnear/workarea/gnuradio/gr-uhd/lib/usrp_source_impl.cc:74:7: error: class ‘gr::uhd::usrp_source_impl’ does not have any field named ‘_recv_timeout’
       _recv_timeout(0.1), // seconds
       ^~~~~~~~~~~~~
/home/opnear/workarea/gnuradio/gr-uhd/lib/usrp_source_impl.cc:75:7: error: class ‘gr::uhd::usrp_source_impl’ does not have any field named ‘_recv_one_packet’
       _recv_one_packet(true),
       ^~~~~~~~~~~~~~~~
/home/opnear/workarea/gnuradio/gr-uhd/lib/usrp_source_impl.cc: In member function ‘virtual void gr::uhd::usrp_source_impl::set_recv_timeout(double, bool)’:
/home/opnear/workarea/gnuradio/gr-uhd/lib/usrp_source_impl.cc:464:5: error: ‘_recv_timeout’ was not declared in this scope
     _recv_timeout = timeout;
     ^~~~~~~~~~~~~
/home/opnear/workarea/gnuradio/gr-uhd/lib/usrp_source_impl.cc:464:5: note: suggested alternative: ‘set_recv_timeout’
     _recv_timeout = timeout;
     ^~~~~~~~~~~~~
     set_recv_timeout
/home/opnear/workarea/gnuradio/gr-uhd/lib/usrp_source_impl.cc:465:5: error: ‘_recv_one_packet’ was not declared in this scope
     _recv_one_packet = one_packet;
     ^~~~~~~~~~~~~~~~
/home/opnear/workarea/gnuradio/gr-uhd/lib/usrp_source_impl.cc:465:5: note: suggested alternative: ‘one_packet’
     _recv_one_packet = one_packet;
     ^~~~~~~~~~~~~~~~
     one_packet
/home/opnear/workarea/gnuradio/gr-uhd/lib/usrp_source_impl.cc: In member function ‘void gr::uhd::usrp_source_impl::flush()’:
/home/opnear/workarea/gnuradio/gr-uhd/lib/usrp_source_impl.cc:512:29: error: ‘using element_type = class uhd::device {aka class uhd::device}’ has no member named ‘recv’
         _dev->get_device()->recv(outputs,
                             ^~~~
/home/opnear/workarea/gnuradio/gr-uhd/lib/usrp_source_impl.cc:516:49: error: ‘RECV_MODE_FULL_BUFF’ is not a member of ‘uhd::device’
                                  ::uhd::device::RECV_MODE_FULL_BUFF,
                                                 ^~~~~~~~~~~~~~~~~~~
/home/opnear/workarea/gnuradio/gr-uhd/lib/usrp_source_impl.cc: In member function ‘virtual int gr::uhd::usrp_source_impl::work(int, gr_vector_const_void_star&, gr_vector_void_star&)’:
/home/opnear/workarea/gnuradio/gr-uhd/lib/usrp_source_impl.cc:600:44: error: ‘using element_type = class uhd::device {aka class uhd::device}’ has no member named ‘recv’
     size_t num_samps = _dev->get_device()->recv(output_items,
                                            ^~~~
/home/opnear/workarea/gnuradio/gr-uhd/lib/usrp_source_impl.cc:604:64: error: ‘RECV_MODE_FULL_BUFF’ is not a member of ‘uhd::device’
                                                 ::uhd::device::RECV_MODE_FULL_BUFF,
                                                                ^~~~~~~~~~~~~~~~~~~
/home/opnear/workarea/gnuradio/gr-uhd/lib/usrp_source_impl.cc:608:41: error: ‘using element_type = class uhd::device {aka class uhd::device}’ has no member named ‘recv’
         num_samps = _dev->get_device()->recv(output_items,
                                         ^~~~
/home/opnear/workarea/gnuradio/gr-uhd/lib/usrp_source_impl.cc:612:61: error: ‘RECV_MODE_ONE_PACKET’ is not a member of ‘uhd::device’
                                              ::uhd::device::RECV_MODE_ONE_PACKET,
                                                             ^~~~~~~~~~~~~~~~~~~~
gr-uhd/lib/CMakeFiles/gnuradio-uhd.dir/build.make:86: recipe for target 'gr-uhd/lib/CMakeFiles/gnuradio-uhd.dir/usrp_source_impl.cc.o' failed
make[2]: *** [gr-uhd/lib/CMakeFiles/gnuradio-uhd.dir/usrp_source_impl.cc.o] Error 1
CMakeFiles/Makefile2:14760: recipe for target 'gr-uhd/lib/CMakeFiles/gnuradio-uhd.dir/all' failed
make[1]: *** [gr-uhd/lib/CMakeFiles/gnuradio-uhd.dir/all] Error 2
Makefile:162: recipe for target 'all' failed
make: *** [all] Error 2
```

**Comment by willcode** [comment]
v3.7 is no longer supported, so closing this issue. You can still see if people on chat.gnuradio.org or the mailing list can help.

**Comment by markibonge** [comment]
I jeff,  I wasn't even running v7.

**Comment by willcode** [comment]
Hmm, the PR talks about v3.7 in multiple places.

**Comment by markibonge** [comment]
yes, but I was still in the downloading process. I haven't build my
gnuradio. The issue is happening before installation.
