### ISSUE TITLE
Errors when running Make (building from source)

### ISSUE THREAD

**Issue by gooloogreatking** [gnuradio/gnuradio#6843]
Hey everyone,

I am building GNURadio from the source & got following errors when running Make:

/usr/bin/ld: /home/d331/anaconda3/lib/libQt5Core.so.5.15.2: undefined reference to `std::__exception_ptr::exception_ptr::_M_release()@CXXABI_1.3.13'
/usr/bin/ld: /home/d331/anaconda3/lib/libQt5Widgets.so.5.15.2: undefined reference to `std::__throw_bad_array_new_length()@GLIBCXX_3.4.29'
/usr/bin/ld: /home/d331/anaconda3/lib/libQt5Core.so.5.15.2: undefined reference to `std::__exception_ptr::exception_ptr::_M_addref()@CXXABI_1.3.13'
collect2: error: ld returned 1 exit status
make[2]: *** [gr-qtgui/examples/c++/CMakeFiles/display_qt.dir/build.make:120: gr-qtgui/examples/c++/display_qt] Error 1
make[1]: *** [CMakeFiles/Makefile2:7070: gr-qtgui/examples/c++/CMakeFiles/display_qt.dir/all] Error 2
make: *** [Makefile:141: all] Error 2

Appreciate the support!

jetson agx orin , ubuntu20.04

**Comment by willcode** [comment]
Please ask for help at chat.gnuradio.org or on the mailing list. The issue tracker is used for bug reports and feature requests. This looks like a build environment problem. Thanks.
