### ISSUE TITLE
gr-qtgui: QT GUI Msg Push Button add callback for Message Value

### ISSUE THREAD

**Issue by duggabe** [gnuradio/gnuradio#6869]
### Feature Description

Currently the QT GUI Msg Push Button sends a fixed 'Message Value' when the button is clicked. It would be very useful to have a Variable name in that  'Message Value' field so that some other block variable or a calculation of values could be sent in the message.

### Feature Urgency

medium (would be nice to have in the near future)

### More Information

The fact that the PMT value does not change has been tested with several different flowgraphs on GNU Radio versions 3.10.4.0, 3.10.6.0, and 3.11.0.0git

This was initially observed by @Akira25

**Comment by dl1ksv** [comment]
@duggabe Maybe I misunderstand something, but you can already use a variable in the 'Message Value' field.

I used a simple flowgraph with a Msg Push Button connected to a Message Debug block and a variable block named msg.

I tested different values for msg
3*4
3.1*4.2
'3*4'

If you adjust the type  accordingly, the button sends the expected result

**Comment by duggabe** [comment]
@dl1ksv The problem which triggered this issue was using a QT GUI Chooser and a Msg Push Button. When the user selected a different option, the Push Button did not change value from the one at the time the flowgraph was created.

**Comment by dl1ksv** [comment]
@duggabe Thanks for clarification. I provided a possible solution.
