### ISSUE TITLE
Need To Interface ADC and DAC In OFDM.

### ISSUE THREAD

**Issue by Yash-Varuni** [gnuradio/gnuradio#6878]
I need help. How can I interface DAC (connected on serial port) with OFDM Tx block and ADC (connected on serial port) with OFDM Rx. I couldn't find any block or tutorial on it. Also How can we change the frequency of the signal, I have 1MHz as sampling clock for ADC and DAC.

**Comment by marcusmueller** [comment]
This is a bug tracker, not a Question and Answer platform. Please refer to the mailing list!
