### ISSUE TITLE
AttributeError: module 'gnuradio.pdu' has no attribute 'socket_pdu'

### ISSUE THREAD

**Issue by Hermite123456** [gnuradio/gnuradio#6917]
### What happened?

~$ grgsm_decode -m BCCH -t 0 -c capture.cfile -v -p -f 870.4M -s 1e6 --ppm 1

Traceback (most recent call last):

  File "/usr/local/bin/grgsm_decode", line 389, in <module>
    tb = gsm_decoder(timeslot=options.timeslot, subslot=options.subslot, chan_mode=options.chan_mode,
  File "/usr/local/bin/grgsm_decode", line 121, in __init__
    self.socket_pdu_server = pdu.socket_pdu("UDP_SERVER", "127.0.0.1", "4729", 10000) #added in order to avoid generating ICMP messages

**AttributeError: module 'gnuradio.pdu' has no attribute 'socket_pdu'**

~$

### System Information

GNU Version: 3.10.1.1-2.

Operating System: Ubuntu 22.04.3 LTS              

Kernel: Linux 6.2.0-34-generic, Architecture: x86-64

Python 3.10.12

### GNU Radio Version

3.10 (maint-3.10)

### Specific Version

3.10.1.1

### Steps to Reproduce the Problem

grgsm_decode -m BCCH -t 0 -c capture.cfile -v -p -f 870.4M -s 1e6 --ppm 1

### Relevant log output

```shell
~$ grgsm_decode -m BCCH -t 0 -c capture.cfile -v -p -f 870.4M -s 1e6 --ppm 1

Traceback (most recent call last):

  File "/usr/local/bin/grgsm_decode", line 389, in <module>
    tb = gsm_decoder(timeslot=options.timeslot, subslot=options.subslot, chan_mode=options.chan_mode,
  File "/usr/local/bin/grgsm_decode", line 121, in __init__
    self.socket_pdu_server = pdu.socket_pdu("UDP_SERVER", "127.0.0.1", "4729", 10000) #added in order to avoid generating ICMP messages

**AttributeError: module 'gnuradio.pdu' has no attribute 'socket_pdu'**

~$
```

**Comment by willcode** [comment]
The traceback does not show a problem in GNU Radio code, and grgsm is not a part of gnuradio. If you are working on solving a problem in grgsm, you could look for help on chat.gnuradio.org or the mailing list.
