### ISSUE TITLE
3.10.8.0 build failure

### ISSUE THREAD

**Issue by chenrui333** [gnuradio/gnuradio#6927]
👋 trying to build the latest release, but run into some build issue. The error log is as below:

<details>
<summary>error build log</summary>

```
  /opt/homebrew/include/spdlog/fmt/fmt.h:27:14: fatal error: 'spdlog/fmt/bundled/core.h' file not found
  #    include <spdlog/fmt/bundled/core.h>
               ^~~~~~~~~~~~~~~~~~~~~~~~~~~
  1 error generated.
```

</details>

full build log, https://github.com/Homebrew/homebrew-core/actions/runs/6589047383/job/17902765159
relates to Homebrew/homebrew-core#151928

**Comment by willcode** [comment]
Homebrew fails with

/opt/homebrew/include/spdlog/fmt/fmt.h:27:14: fatal error: 'spdlog/fmt/bundled/core.h' file not found

**Comment by marcusmueller** [comment]
Ah I think I know what's happening. In io_signature.h, we

    #include <spdlog/fmt/fmt.h>

which is the right thing to do – that internally includes either the bundled fmt or the external, depending on how the system's spdlog is configured in its tweakme.h, where `SPDLOG_FMT_EXTERNAL` gets set (or not).

Now, other spdlog-bundled headers in  spdlog/fmt/ (for example, spdlog/fmt/bin_to_hex.h) do `#include <spdlog/common.h>`, which ensures that tweakme.h is included and so `SPDLOG_FMT_EXTERNAL` is correct.

I'm trying to upstream a fix. 

In the meantime, I'll work around this in GNU Radio, please stand by.

**Comment by marcusmueller** [comment]
@dpward  sadly, we have in the past encountered multiple systems where we couldn't rely on spdlogConfig.cmake, so that's sadly not an option in the current environment.
