### ISSUE TITLE
gr-uhd's FPGA FFT's label classes with gr-fft's FFT

### ISSUE THREAD

**Issue by marcusmueller** [gnuradio/gnuradio#6931]
### What happened?

@duggabe noticed that the gr-uhd FPGA FFT's documentation tab in GRC leads to the same URL as the gr-fft FFT's block.

That is caused by both having the same `label:` property in their block yaml. For in-tree blocks, GRC generates the wiki link from the label, and the label alone.

Note that I'd recommend changing the label. I'm not actually sure that block is still supported, though!

Since this issue unearthed the fact that, in case of different versions of GNU Radio having different labels for essentially the same block, we don't have a way to specify what the actual docs URL should be. Also, out-of-tree blocks don't get to have such a link at all! So, #6930 addresses that. 

### System Information

FPGA FFT is in there since GR 3.8.1.0, I think

### GNU Radio Version

3.11-git (main)

### Specific Version

0.0.0.0

### Steps to Reproduce the Problem

1. search for "FFT" in the GRC block library
2. add the FFT from the "RFNoC Image Builder" category
3. open its property dialog
4. go to documentation tab
5. click on link
6. find yourself on the "proper" FFT wiki page

**Comment by mbr0wn** [comment]
Actually this was fixed by @marcusmueller and already backported.
