### ISSUE TITLE
Building a block to implement multiplier in GNUradio

### ISSUE THREAD

**Issue by PHDsaoudi** [gnuradio/gnuradio#6936]
### Feature Description

dear Sir,

I'm creating module TUTORIAL, after that building and install the block named multiply with these instruction:
 gr_modtool newmod tutorial
cd gr-tutorial
 ls
 gr_modtool add -t sync -l python
mkdir build
cd build
cmake ..
make
sudo make install
sudo ldconfig
Thus; build an installation are done succefully:
 Installing: /usr/local/lib/python3.8/dist-packages/gnuradio/tutorial/__init__.pyc
-- Installing: /usr/local/lib/python3.8/dist-packages/gnuradio/tutorial/__init__.pyo
-- Installing: /usr/local/share/gnuradio/grc/blocks/tutorial_multiply.block.yml
However when I'm runnig Gnuradio 
When i run this command
~/gr-tutorial/build$ gnuradio-companion 
Configuration of block shows error:
yaml.scanner.ScannerError: mapping values are not allowed here
  in "/usr/local/share/gnuradio/grc/blocks/tutorial_multiply.block.yml"

What can i do to solve this problem

### Feature Urgency

high (impacts broad portion of ecosystem)

**Comment by willcode** [comment]
Please ask for help at chat.gnuradio.org or on the mailing list. We use the issue tracker for bug reports and feature requests. I see this labeled as Feature Request, but it is not.
