### ISSUE TITLE
Building a block to implment multiplier block in Gnuradio

### ISSUE THREAD

**Issue by PHDsaoudi** [gnuradio/gnuradio#6937]
### Feature Description

dear Sir,
I'm creating module TUTORIAL, after that building and install the block named multiply with these instruction:
gr_modtool newmod tutorial
cd gr-tutorial
ls
gr_modtool add -t sync -l python
mkdir build
cd build
cmake ..
make
sudo make install
sudo ldconfig
Thus; build an installation are done succefully:
Installing: /usr/local/lib/python3.8/dist-packages/gnuradio/tutorial/init.pyc
-- Installing: /usr/local/lib/python3.8/dist-packages/gnuradio/tutorial/init.pyo
-- Installing: /usr/local/share/gnuradio/grc/blocks/tutorial_multiply.block.yml

Taking account that i change my code in multiply.py

However when I'm runnig Gnuradio
When i run this command
~/gr-tutorial/build$ gnuradio-companion
Configuration of block shows error:
yaml.scanner.ScannerError: mapping values are not allowed here
in "/usr/local/share/gnuradio/grc/blocks/tutorial_multiply.block.yml"
What can i do to solve this problem

### Feature Urgency

high (impacts broad portion of ecosystem)

**Comment by willcode** [comment]
The issue tracker is used for bug reports and feature requests. This is a help request - please try chat.gnuradio.org or the mailing list for help.
