### ISSUE TITLE
Embedded Python Block failed to open codes window using Default Editor

### ISSUE THREAD

**Issue by lsk2141** [gnuradio/gnuradio#6947]
### What happened?

I double click Embedded Python Block>Code: Open In Editor > Use Default but the Code Window is nor coming out. THe roor Message is: >>> Unable to load the default editor. Please choose an editor.
>>> No editor selected.  It is not finctioning as in the tutorial, Is it a bug?

### System Information

OS: (Linux Distro, Mac, Windows)
GR Installation Method: (native distro packages - apt, rpm, etc., Conda, Source

Window 10 PC
Install using Window RadioConda Installer from: 
https://wiki.gnuradio.org/index.php/InstallingGR

### GNU Radio Version

3.10 (maint-3.10)

### Specific Version

3.10.7.0 (Python 3.10.12

### Steps to Reproduce the Problem

I double click Embedded Python Block>Code: Open In Editor > Use Default but the Code Window is nor coming out. THe roor Message is: >>> Unable to load the default editor. Please choose an editor.
>>> No editor selected.  It is not finctioning as in the tutorial, Is it a bug?

### Relevant log output

```shell
>>> Unable to load the default editor. Please choose an editor.
>>> No editor selected
```

**Comment by willcode** [comment]
Editor choice has been improved in #6785 and #6786 for 3.10.8.0, so closing.
