### ISSUE TITLE
GRC: Shortcut 'D' and selecting "Edit > Disable" deletes blocks from flowgraph instead of disabling them

### ISSUE THREAD

**Issue by lucab0212** [gnuradio/gnuradio#6952]
### What happened?

When using GNU Radio Companion, there is the option of disabling blocks in a flowgraph: Disabled blocks are still visible in the flowgraph but are greyed out and do not get compiled. This feature is helpful when trying out different blocks or debugging a flowgraph on a high level. In my version of GNU Radio (3.10.7.0, from source) however, when selecting "Edit > Disable" for a block, the block gets deleted from the flowgraph and is not visible anymore.

### System Information

OS: Debian 12
GR Installation Method: from Source

### GNU Radio Version

3.10 (maint-3.10)

### Specific Version

3.10.7.0

### Steps to Reproduce the Problem

Open GNU Radio companion and place a block in the flowgraph. Selecting the block and typing 'D' will delete the block instead of disabling it.

**Comment by willcode** [comment]
Check under the View menu for an option to show disable blocks.
