### ISSUE TITLE
gr_modtool generates cpp noblock that does not compile

### ISSUE THREAD

**Issue by AngelouDi** [gnuradio/gnuradio#6960]
### What happened?

I am trying to generate a noblock using gr_modtool.

```
gr_modtool newmod my_rfid

gr_modtool add testblock
GNU Radio module name identified: my_rfid
('sink', 'source', 'sync', 'decimator', 'interpolator', 'general', 'tagged_stream', 'hier', 'noblock')
Enter block type: noblock
Language (python/cpp): cpp
Language: C++
Block/code identifier: testblock
Please specify the copyright holder: none
Enter valid argument list, including default arguments: 
 
Add C++ QA code? [Y/n] n
Adding file 'lib/testblock.cc'...
Adding file 'include/gnuradio/my_rfid/testblock.h'...
Adding file 'python/my_rfid/bindings/docstrings/testblock_pydoc_template.h'...
Adding file 'python/my_rfid/bindings/testblock_python.cc'...
Adding file 'grc/my_rfid_testblock.block.yml'...
Editing grc/CMakeLists.txt...
```

When I attempt a build:

```
[ 70%] Built target my_rfid_docstrings
[ 80%] Building CXX object python/my_rfid/bindings/CMakeFiles/my_rfid_python.dir/testblock_python.cc.o
/home/mitsos/Documents/Diplomatiki/gr-my_rfid/python/my_rfid/bindings/testblock_python.cc: In function ‘void bind_testblock(pybind11::module&)’:
/home/mitsos/Documents/Diplomatiki/gr-my_rfid/python/my_rfid/bindings/testblock_python.cc:37:34: error: template argument 2 is invalid
   37 |         std::shared_ptr<testblock>>(m, "testblock", D(testblock))
      |                                  ^~
/home/mitsos/Documents/Diplomatiki/gr-my_rfid/python/my_rfid/bindings/testblock_python.cc:39:35: error: ‘make’ is not a member of ‘testblock’ {aka ‘gr::my_rfid::testblock’}
   39 |         .def(py::init(&testblock::make),
      |                                   ^~~~
make[2]: *** [python/my_rfid/bindings/CMakeFiles/my_rfid_python.dir/build.make:76: python/my_rfid/bindings/CMakeFiles/my_rfid_python.dir/testblock_python.cc.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:384: python/my_rfid/bindings/CMakeFiles/my_rfid_python.dir/all] Error 2
make: *** [Makefile:146: all] Error 2
```

### System Information

OS: Arch Linux x86_64
GR Installation Method: AUR: https://aur.archlinux.org/packages/gnuradio-git

### GNU Radio Version

3.11-git (main)

### Specific Version

v3.11.0.0git-576-g9fca5db4

### Steps to Reproduce the Problem

Generate a new gr module and add a cpp noblock. Then try to compile.

**Comment by willcode** [comment]
`noblock` doesn't seem to be documented, except as an option to `addblock`. This probably hasn't been tested recently. For anyone wondering, it creates a class in the module namespace that is not a block. This is of questionable usefulness.

**Comment by marcusmueller** [comment]
agreed, at the very least it needs to be better documented; don't think having a "skeleton" option that just adds empty source files and and entries to CMakeLists.txt is a bad thing, but then that really is what should happen.

**Comment by AngelouDi** [comment]
I am gonna check the version that we had used at work tomorrow (it works fine on that version).

They way we used it was a to store global variables (We are implementing the Gen2 EPC specification from scratch). So we used the noblock as it would generate all the files and CMake lines in one go.

**Comment by AngelouDi** [comment]
The version that works is 3.7.12.0

I don't know about later ones.

**Comment by marcusmueller** [comment]
Still present
