### ISSUE TITLE
PMT: Some Python bindings are broken

### ISSUE THREAD

**Issue by argilo** [gnuradio/gnuradio#6967]
While working on #6966, I noticed that several PMT Python bindings appear non-functional, printing the following error when invoked:

```
Did you forget to `#include <pybind11/stl.h>`? Or <pybind11/complex.h>,
<pybind11/functional.h>, <pybind11/chrono.h>, etc. Some automatic
conversions are optional and require extra headers to be included
when compiling your pybind11 module.
```

The affected functions are:

* `pmt.make_any`
* `pmt.any_ref`
* `pmt.any_set`
* `pmt.map`
* `pmt.read`
* `pmt.write`
* `pmt.serialize`
* `pmt.deserialize`

I performed this testing on the `main` branch.

When testing with GNU Radio 3.10, the first three functions do not print an error because they use `boost::any` instead of `std::any`, but I'm not sure whether it's possible to pass in a `boost::any` argument.

**Comment by themox** [comment]
Experiencing same issue; haven't tested other functions but can confirm exact behavior with pmt.serialize and pmt.deserialize.  

Using Python 3.10.12, GNURadio 3.10.7.0.2, installed via Brew on Mac

**Comment by myyxl** [comment]
I encounter the same issue while using `serialize` and `deserialize`.

Python 3.11.4, GNURadio 3.10.5.1 and installed using the package manager on Ubuntu.

**Comment by willcode** [comment]
serialize and deserialize take a streambuf arg, which is also apparently not mapped to the wrappers.

**Comment by willcode** [comment]
@mormj @jacobagilbert might have ideas here.

**Comment by marcusmueller** [comment]
wrapping std::any-consuming functions to Python isn't very sensible; so these should be removed.
