### ISSUE TITLE
Why does the number of inputs and outputs decrease in embedded Python blocks?

### ISSUE THREAD

**Issue by osmanmerty** [gnuradio/gnuradio#7042]
### What happened?

I'm writing my own embedded python blocks for OFDM. However, the size of the output and input arrays in the blocks begins to decrease over time. Why might this happen?

### System Information

OS: (Linux Distro, Mac, Windows)
GR Installation Method: (native distro packages - apt, rpm, etc., Conda, Source

### GNU Radio Version

3.8  (maint-3.8)

### Specific Version

3.8.1.0

### Steps to Reproduce the Problem

![Screenshot from 2024-01-03 08-35-23](https://github.com/gnuradio/gnuradio/assets/79969214/cd1983a3-67ac-4eac-9101-af69da3a97c4)

Over time, the size of the _**output_item**_ in the blocks decreases. What is the reason for this?

640 bytes of data comes out of the Pilot Adding block, but 520 bytes of data comes out to the Cyclic Prefix Adding block. What is the reason for this?

**Comment by willcode** [comment]
Please ask for help at chat.gnuradio.org (matrix) or on the mailing list. The issue tracker is used for bug reports and feature requests.
