### ISSUE TITLE
Clang Format helper script looks for the wrong version

### ISSUE THREAD

**Issue by dkozel** [gnuradio/gnuradio#7063]
### What happened?

Tried running https://github.com/gnuradio/gnuradio/blob/main/tools/clang_format.py and found it was looking for clang-format 7.0. Our CI uses version 14 so this is likely a simple fix to change the version it's looking for.

### System Information

OS: Ubuntu 22.04
GR Installation Method: Source

### GNU Radio Version

3.10 (maint-3.10)

### Specific Version

0.0.0.0

### Steps to Reproduce the Problem

Run ./tools/clang_format.py

**Comment by marcusmueller** [comment]
soooo annoying
