### ISSUE TITLE
light theme when using dark theme

### ISSUE THREAD

**Issue by marcusmueller** [gnuradio/gnuradio#7086]
### What happened?

GRC shows up in bright colors at first start, though the dark theme is selected by default

![qt-grc](https://github.com/gnuradio/gnuradio/assets/958972/bb350430-1080-49c5-8bbe-ff62b1ed990c)

Changes to dark them after switching to light, restarting grc, switching to dark, restarting GRC. 

### System Information

OS: fedora 39
GR Installation Method:

```shell
git clone -b feature-grc-qt https://github.com/gnuradio/gnuradio
cd gnuradio
python3 -m venv --system-site-packages .venv
source .venv/bin/activate
pip install QDarkStyle qtpy
mkdir build
cd build
cmake -DCMAKE_INSTALL_PREFIX=$VIRTUAL_ENV ..
make -j8
make install
```

```
source /path/to/gnuradio/.venv/bin/activate
export LD_LIBRARY_PATH=$VIRTUAL_ENV/lib/
export GRC_BLOCKS_PATH=$VIRTUAL_ENV/share/gnuradio/grc/blocks/
export PYTHONPATH=$VIRTUAL_ENV/lib/python3.11/site-packages

gnuradio-companion --qt
```

### GNU Radio Version

QT-based Companion branch (feature-grc-qt)

### Specific Version

GNU Radio v3.11.0.0git-625-g60817bdf (Python 3.11.7)

### Steps to Reproduce the Problem

start GRC

**Comment by marcusmueller** [comment]
~/.gnuradio/grc.log does not contain "Did not find QDarkstyle"

**Comment by haakov** [comment]
Does https://github.com/gnuradio/gnuradio/commit/c98d9243c9422325bd25c6d3b549aa534e505456 (current feature-grc-qt branch) fix the issue?

**Comment by luzpaz** [comment]
@marcusmueller :point_up_2:

**Comment by willcode** [comment]
@luzpaz are you saying it works for you?

**Comment by luzpaz** [comment]
I hadn't been able to reproduce on Manjaro. So i was wondering if it was a fedora related issues
