### ISSUE TITLE
gnuradio-companion is missing after building from source

### ISSUE THREAD

**Issue by aviadb** [gnuradio/gnuradio#7091]
### What happened?

I am trying to build gnuradio from source.
I followed the instructions 
https://wiki.gnuradio.org/index.php?title=LinuxInstall#From_Source

the make and make isntall completed successfully
however under the PREFIX dir all I see is this executable: gnuradio-config-info

### System Information

OS: Linux, Ubuntu 22.04.3 LTS
GR Installation Method: Source

### GNU Radio Version

3.11-git (main)

### Specific Version

0.0.0.0

### Steps to Reproduce the Problem

git clone git@github.com:gnuradio/gnuradio.git
cd gnuradio
mkdir build
cd build
cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/home/aviadb/apps/gnuradio/ -DENABLE_GR_QTGUI=ON -DENABLE_GR_FFT=ON -DENABLE_GR_FILTER=ON -DENABLE_GNURADIO_RUNTIME=ON -DENABLE_GR_IIO=ON -DPYTHON_EXECUTABLE=/home/aviadb/miniconda3/envs/env1/bin/python ../
make -j16
make test
make install

**Comment by willcode** [comment]
`gnuradio-companion` is installed under `$PREFIX/bin` if all goes well. If it is not there, then something in the build failed. Please ask for help at chat.gnuradio.org or on the mailing list.
