### ISSUE TITLE
QT GUI Constellation in radioconda need sample per symbol

### ISSUE THREAD

**Issue by mohammadsdtmnd** [gnuradio/gnuradio#7132]
### What happened?

When using QT GUI Constellation to check your constellation:
It can't show GMSK modulation output constellation since it's dont have parameter `sample/symbol`.
This block needs it, `sample per symbol`. I wonder how this big bug could be ... !

### System Information

OS: Windows
GR Installation Method: RadioConda

### GNU Radio Version

3.10-git (main)

### Specific Version

3.10.9.2

### Steps to Reproduce the Problem

Open this block, and you wont see that parameter.
If you do GMSK with sample per symol higher that 1, the constellation output will be wrong.

**Comment by willcode** [comment]
GMSK blocks have `Samples/Symbol` and it defaults to `2`.

**Comment by mohammadsdtmnd** [comment]
> GMSK blocks have `Samples/Symbol` and it defaults to `2`.
Updated, sorry for wrongly questioning!
I meant QT GUI Constellation doesn't have this parameter

**Comment by willcode** [comment]
This sink is just a x/y plot. It wouldn't know what to do with samples/symbol. It is common to see effects of oversampling on a constellation plot, too. If you really want to see one sample/symbol, try putting a decimating filter before the sink.

If you have a good description of a feature you'd like to see, please change the title/description and reopen.

**Comment by mohammadsdtmnd** [comment]
> This sink is just a x/y plot. It wouldn't know what to do with samples/symbol. It is common to see effects of oversampling on a constellation plot, too. If you really want to see one sample/symbol, try putting a decimating filter before the sink.
> 
> If you have a good description of a feature you'd like to see, please change the title/description and reopen.

The constellation interpret the data to symbols and view them on the plot, doesn't it? it must be aware that each symbol takes how much sample?

**Comment by willcode** [comment]
No, a constellation plot does not convert to symbols. It just plots I/Q data in X/Y form.

**Comment by mohammadsdtmnd** [comment]
> No, a constellation plot does not convert to symbols. It just plots I/Q data in X/Y form.

Then why simulink constellation viewer have this?

**Comment by willcode** [comment]
The simulink constellation diagram includes a downsampler, but it does not try to interpret symbols/samples. It does plot a reference constellation, which is a nice idea. It also has a "Trajectory" setting which probably results in the same display you see in GNU Radio.

The GR Constellation Sink does not include a downsampler. It would be added in front of the sink if desired.

Some simulink features might be nice to have in GR if someone want to work on them.
