### ISSUE TITLE
ImportError: libgnuradio-runtime.so.3.10.8: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by jzofe** [gnuradio/gnuradio#7146]
### What happened?

ImportError: libgnuradio-runtime.so.3.10.8: cannot open shared object file: No such file or directory

pls help

### System Information

OS: Arch Linux (Archcraft)
installation method : pacman + pikaur 

### GNU Radio Version

4.0-git (dev-4.0)

### Specific Version

3.10.9.2

### Steps to Reproduce the Problem

n/a

### Relevant log output

```shell
ImportError: libgnuradio-runtime.so.3.10.8: cannot open shared object file: No such file or directory
```

**Comment by willcode** [comment]
Please ask for help at chat.gnuradio.org or on the mailing list. The issue tracker is used for bug reports and feature requests. This is an enviroment/setup problem.
