### ISSUE TITLE
I can't start Astro-virgo GNU radio

### ISSUE THREAD

**Issue by EugeneHamRadio** [gnuradio/gnuradio#7161]
### What happened?

Please help me. When trying to run GNU Radio deployed on a Virtualbox Ubuntu virtual machine, the following error appears
![1](https://github.com/gnuradio/gnuradio/assets/162698584/be2d8a7c-f082-4502-bdd1-8ec877a9a384)

### System Information

OS: (Linux Distro, Mac, Windows)
GR Installation Method: (native distro packages - apt, rpm, etc., Conda, Source

### GNU Radio Version

3.8  (maint-3.8)

### Specific Version

3.8.2.0

### Steps to Reproduce the Problem

Done (return code -6)

### Relevant log output

```shell
Done (return code -6)
```

**Comment by marcusmueller** [comment]
Hi. This is not a help forum, but a software issue tracker for GNU Radio (and not for external modules). So, I'm afraid this isn't the place to discuss this – please refer to our mailing list [1] or our chat server [2]. Also, you filled in none of the system information fields, even in a face to face meeting someone who could help you would ask for these!

[1] https://lists.gnu.org/mailman/listinfo/discuss-gnuradio
