### ISSUE TITLE
Created a OOT module and while executing the grc got error "ModuleNotFoundError"

### ISSUE THREAD

**Issue by patilraj1707** [gnuradio/gnuradio#7234]
### What happened?

I created a OOT block and installed it using the steps given of the following [Link](https://wiki.gnuradio.org/index.php?title=Creating_Python_OOT_with_gr-modtool#Making_Changes). The block was updated in the GNURadio app but when I crreated a flow graph using the same block I got the following error.

Executing: /usr/bin/python3 -u /home/deadshot/test.py

Traceback (most recent call last):
  File "/home/deadshot/test.py", line 22, in <module>
    from gnuradio import myradar
  File "/usr/local/lib/python3.10/dist-packages/gnuradio/myradar/__init__.py", line 23, in <module>
    from .SignalSourceFMCW import SignalSourceFMCW
ModuleNotFoundError: No module named 'gnuradio.myradar.SignalSourceFMCW'

Done (return code 1)

![image](https://github.com/gnuradio/gnuradio/assets/81311326/b8d3a963-89f0-4604-807e-e73bcad94de9)

### System Information

OS: Ubuntu 22
GR Installation Method: Source

### GNU Radio Version

3.10 (maint-3.10)

### Specific Version

3.10.9.2

### Steps to Reproduce the Problem

Install the below module and create a simple flow graph as shown above.
[gr-myradar.zip](https://github.com/gnuradio/gnuradio/files/14817014/gr-myradar.zip)

**Comment by willcode** [comment]
This sounds like a path setup issue. Please ask for help at chat.gnuradio.org or on the mailing list. The issue tracker is used for bug reports and feature requests.
