### ISSUE TITLE
How do I make a custom signal source to output certain pattern

### ISSUE THREAD

**Issue by patrick-chen-98** [gnuradio/gnuradio#7241]
### What happened?

I would like to make a custom signal source to output a vector with a certain pattern such as (1,1,1,0.5,1,0.5).

I was told "could not broadcast input array from shape (6,) into shape (4096,)"

The code is shown here:
class Customize_Source(gr.sync_block):
    ''' '''

    def __init__(self):
        ''' '''
        self.count = 0
        gr.sync_block.__init__(
            self, name='Customize Source',
            in_sig=None, out_sig=[(np.complex64)])

    def work(self, input_items, output_items):
        output_items[0][:] = [1,1,1,0.5,1,0.5]
        length = 6
        return leng( output_items[0])

### System Information

OS: Windows
GR Installation Method: radioconda-2024.01.26-Windows-x86_64

### GNU Radio Version

3.10.9.2 (Python 3.11.7)

### Specific Version

0.0.0.0

### Steps to Reproduce the Problem

Just run my code, it should produce the same error

**Comment by willcode** [comment]
Please ask for help at chat.gnuradio.org (General Chat) or on the mailing list. The issue tracker is used for bug reports and feature requests.
