### ISSUE TITLE
importeror:libboost_program_options.so.1.73.0 can not open shared no such file or directory

### ISSUE THREAD

**Issue by 2444616578** [gnuradio/gnuradio#7251]
When I successfully build an OOT module with C++ language, I faile to use it when putting it into a grc file. When I try to run this script. It arises an imorterror:libboost_program_options.so.1.73.0. cannot open shared object file:No such file or dircectory. I try to install libboost by sudo apt-get install libboost-all-dev, but it shows that my libboost is the newest version 1.71.0. So I am comfused why I can not use an newly built OOT module. The OOT modules I built months ago can work successfully by the way. I guess may be other lib softwares were installed to my computer and unfortunately I can not determind which softwares are installed, upgraded or installed. Because there other people who were operating on this computer. I will appreciate it if I can get advice from the developers or other experienced users.

**Comment by willcode** [comment]
Please ask for help at chat.gnuradio.org (General Chat channel) or on the mailing list. The issue tracker is used for bug reports and feature requests.
