### ISSUE TITLE
one USRP two GNURadio

### ISSUE THREAD

**Issue by Felao** [gnuradio/gnuradio#7257]
### Feature Description

Can two different gnuradio programs use different ports of the same USRP? When I was testing, one program got stuck and had to be placed in the same flow diagram? Why?

### Feature Urgency

high (impacts broad portion of ecosystem)

**Comment by marcusmueller** [comment]
This is an issue tracker, not a question platform: we invite you to join our mailing list and/or chat platform, as described on our website: https://www.gnuradio.org/community/
