### ISSUE TITLE
 Frequency Sink ， spectrum is always symmetrical

### ISSUE THREAD

**Issue by Felao** [gnuradio/gnuradio#7258]
### Feature Description

When I use the QT GUI Frequency Sink module, the displayed spectrum is always symmetrical, and one amplitude is higher and the other is lower. What is the reason for this?
![b2b68d761d6fa63ba0a5a3243d4db06](https://github.com/gnuradio/gnuradio/assets/115784124/29ded13c-eb27-4887-8d82-e8a9e8ce1e32)

### Feature Urgency

high (impacts broad portion of ecosystem)

**Comment by marcusmueller** [comment]
Hi, that's very likely because your signal is like that. Also, this is an issue tracker, not a question platform: we invite you to join our mailing list and/or chat platform, as described on our website: https://www.gnuradio.org/community/
