### ISSUE TITLE
Automatic syncing of the TX and the RX pulses in GNURadio while using Pluto SDR.

### ISSUE THREAD

**Issue by patilraj1707** [gnuradio/gnuradio#7259]
### Feature Description

As while implementing radar system syncing of the pulses is very important to get the beat frequency, which requires the synchronization of the pulses.

### Feature Urgency

high (impacts broad portion of ecosystem)

**Comment by marcusmueller** [comment]
This is an issue tracker, not a question platform: we invite you to join our mailing list and/or chat platform, as described on our website: https://www.gnuradio.org/community/
