### ISSUE TITLE
grc-qt: a double clicking a connection deletes the connection but the fg stays valid 

### ISSUE THREAD

**Issue by dl1ksv** [gnuradio/gnuradio#7284]
### What happened?

Take a simple fg

signal source(float) -> audio sink

Double clicking the connection removes the connection but the fg stays valid and can even be generated. No errors are displayed and the fg is still marked as saved , so you can close the fg without further actions. The fg should be marked as changed and invalid.

Taking the same fg:
After a simple click on the connection you can delete the connection by the delete button. You can delete the connection by clicking the delete button. The fg is marked as invalid. Errors are displayed. Closing the fg requires either to discard or to save the changes.

### System Information

Linux, F39, build from scratch

### GNU Radio Version

3.11-git (main)

### Specific Version

0.0.0.0

### Steps to Reproduce the Problem

See description above

**Comment by willcode** [comment]
This is after #7278, right?

**Comment by dl1ksv** [comment]
Correct
