### ISSUE TITLE
gnuradio-companion --qt filename.grc doesn't open filename.grc

### ISSUE THREAD

**Issue by marcusmueller** [gnuradio/gnuradio#7291]
### What happened?

Tried to open a GRC flowgraph directly with QT GRC; it doesn't do that, doesn't throw an error. The same file works when opened via menu.

Doesn't work without the --qt if the default GRC variant is set to QT in the preferences, either.

### System Information

OS: linux
GR Installation Method: source

### GNU Radio Version

3.11-git (main)

### Specific Version

v3.11.0.0git-716-g77155087

### Steps to Reproduce the Problem

gnuradio-companion --qt filename.grc

**Comment by dl1ksv** [comment]
At the moment grc --qt does not care about filename.grc.
But should grc --qt add filename.grc to the list of recently opened files  or only open filename.grc?

**Comment by marcusmueller** [comment]
Both, I'd say: This is what I want to happen when people doubleclick a GRC file in their file manager.

**Comment by dl1ksv** [comment]
Is grc now behaveing as expected?
