### ISSUE TITLE
grc-qt Saving file blanks the file name in the file name tab

### ISSUE THREAD

**Issue by chrisjohgorman** [gnuradio/gnuradio#7297]
### What happened?

When saving a file the file name in the tab gets blanked.  I've attached a screenshot of before file save and after.  I expected the filename to stay in the tab.

![qt_file_name_tab_0](https://github.com/gnuradio/gnuradio/assets/29354995/f6d66d02-cd61-4593-91c4-5b598f4bcc53)
![qt_file_name_tab_1](https://github.com/gnuradio/gnuradio/assets/29354995/05742b3b-7185-435e-a8d8-8b38478831b4)

### System Information

OS: Arch Linux
GR Installation Method: Source

### GNU Radio Version

3.10 (maint-3.10)

### Specific Version

3.10.10.0

### Steps to Reproduce the Problem

1) open a grc file in the qt gnuradio-companion
2) make a small adjustment to a block.
3) save the file.

The filename is now blank.

**Comment by haakov** [comment]
Thank you for these bug reports! 

If someone tries to fix this bug before I do:
This bug occurs only with the light theme. The filename isn't blank, it is just white, which happens to be almost the same color as the tab background. These are the two lines that set the tab text to white: 

https://github.com/gnuradio/gnuradio/blob/72e21b54c44c360d511371420e74be4a6b2bfda6/grc/gui_qt/components/window.py#L996

https://github.com/gnuradio/gnuradio/blob/72e21b54c44c360d511371420e74be4a6b2bfda6/grc/gui_qt/components/window.py#L973

The text shouldn't be white, it should be `self.app().getCurrentStyleSheet().getStandardTextColor()` (or something like that :)
