### ISSUE TITLE
grc-qt block variables with long names exit the block enclosure

### ISSUE THREAD

**Issue by chrisjohgorman** [gnuradio/gnuradio#7298]
### What happened?

Under the gtk front end, the blocks do not have writing that exits their boundaries.  The qt blocks do if the variable name is long.  I've attached a screenshot of showing this with a signal source block.

![qt_block](https://github.com/gnuradio/gnuradio/assets/29354995/65c84f1f-0f5d-4c3c-b89b-8de4f77f5c05)

### System Information

OS: Arch Linux
GR Installation Method: Source

### GNU Radio Version

3.10 (maint-3.10)

### Specific Version

3.10.10.0

### Steps to Reproduce the Problem

1) Add either a lowpass filter block or a signal source block to a flowgraph.  The writing for window.WIN_HAMMING or  analog.GR_COS_WAVE exits the block.

**Comment by chrisjohgorman** [comment]
I see I may have been a little overzealous here.  Disabling `Show parameter expressions in block` fixes this for the most part.  I don't know whether or not the blocks should resize when this is enabled, perhaps this problem can be put to the bottom of the pile or closed.

![qt_block1](https://github.com/gnuradio/gnuradio/assets/29354995/d18e0f8a-2c78-4e31-8900-d8d54ad23148)

**Comment by marcusmueller** [comment]
I think this is fixed by now; making a value long "stretches" the block.
