### ISSUE TITLE
grc-qt File/Save does not automatically append a .grc extension to the file 

### ISSUE THREAD

**Issue by chrisjohgorman** [gnuradio/gnuradio#7301]
### What happened?

When saving a file the file/save code does not append a .grc extension to the saved file.  This causes a second issue, where the file saved cannot be found under linux as the search is for a file named `*.*`.  
Here is a picture of the first issue.
![qt_grc_file_save_0](https://github.com/gnuradio/gnuradio/assets/29354995/22d2e83e-ba29-46ed-aff9-e93496d7ae78)
This causes the second issue, where the file cannot be found even when searching for `*.*` as the filename has no `.` character in it.
![qt_grc_file_save_1](https://github.com/gnuradio/gnuradio/assets/29354995/52358ed3-7729-49c2-b5f3-456337c28ace)
The file saved in the first issue is not visible in the list of files, even though it was just saved.

### System Information

OS: Arch Linux
GR Installation Method: Source

### GNU Radio Version

3.10 (maint-3.10)

### Specific Version

3.10.10.0

### Steps to Reproduce the Problem

1) File/Save a filename without any extension.
2) Try to load that file from File/Open.

**Comment by dkozel** [comment]
@chrisjohgorman Thanks for taking the time to file all the GRC Qt reports! They'll help a lot in bringing it up to (and past) parity with the GTK version.

**Comment by chrisjohgorman** [comment]
@dkozel You're very welcome for the bug reports.  I've been keen to try out the new interface ever since I found out about it's availability in 3.10.10.0.  I'm sure the new interface will be in parity with the GTK version soon enough.  I have one more bug to report, but that will have to wait until tomorrow.  

One thing I do like about the QT interface is that it is quite quick in comparison to the GTK interface.
