### ISSUE TITLE
A problem happen when creating a C++ OOT block

### ISSUE THREAD

**Issue by HZX0748** [gnuradio/gnuradio#7303]
### What happened?
I am a newcomer learning on gnuradio. I try to create a OOT signal source block by following the [tutorials](https://wiki.gnuradio.org/index.php?title=Creating_C%2B%2B_OOT_with_gr-modtool). When trying to use cmake to complie my code, it came out with log like this:
```
~/gnuradio_demos/gr-mysource/build$ cmake ../
-- Build type not specified: defaulting to release.
-- Checking for module 'gmp'
--   No package 'gmp' found
-- Checking for module 'mpir >= 3.0'
--   No package 'mpir' found
-- Could NOT find MPIR (missing: MPIRXX_LIBRARY MPIR_LIBRARY MPIR_INCLUDE_DIR) 
-- Boost version: 1.65.1
-- Found the following Boost libraries:
--   date_time
--   program_options
--   filesystem
--   system
--   regex
--   thread
--   unit_test_framework
--   chrono
--   atomic
-- User set python executable /usr/bin/python3.6
-- Found PythonLibs: /usr/lib/x86_64-linux-gnu/libpython3.6m.so (found suitable exact version "3.6.9") 
-- Using install prefix: /usr/local
-- Building for version: v1.0-compat-xxx-xunknown / 1.0.0git
-- No C++ unit tests... skipping
-- Checking for module SWIG
-- Found SWIG version 3.0.12.
-- Found PythonLibs: /usr/lib/x86_64-linux-gnu/libpython3.6m.so (found version "3.6.9") 
-- Configuring done
-- Generating done
-- Build files have been written to: /home/hzx0748748/gnuradio_demos/gr-mysource/build
```

I don't see sytnax errors in my OOT blocks. I try to install gmp and mpir. But the problem still exist with same error logs. I also try to run sudo apt-get install libgmp3-dev. It did not fix the problem. Could someone give me a hand?

### System Information

OS: Linux ubuntu 18.04 LTS
GR Installation Method: sudo apt-get

### GNU Radio Version

3.8  (maint-3.8)

### Specific Version

3.8.0.0

### Steps to Reproduce the Problem

I install cmake3.18.2,UHD4.0.0,gnuradio3.8,osmosdr,gqrx,libvolk1-bin,gqrx-sdr. It happen when I complie my first C++ OOT block.I think the reason for the error is that some dependencies are missing from my current runtime environment, but I can't tell which dependency packages are missing

**Comment by dkozel** [comment]
Hello @HZX0748 

First, there is not critical error in your CMake generation log, you can move on to compile the code using `make`. You can see that the necessary files are generated at the end of the log.

```
-- Configuring done
-- Generating done
-- Build files have been written to: /home/hzx0748748/gnuradio_demos/gr-mysource/build
```

Second, the tutorial you have linked to is for the current release of GNU Radio, 3.10, and you are using a very old operating system with Ubuntu 18.04 and version of GNU Radio 3.8. Is it possible for you to use a more recent operating system and version of GNU Radio? If so, that is strongly recommended as you will find better documentation and fewer troubles. Particularily, support for C++ OOT modules has certainly improved in the past few years.

I'd recommend joining the GNU Radio chat server and you'll find folks able to give some feedback on using GNU Radio.
https://app.element.io/#/room/#gnuradio-space:gnuradio.org

This isn't a bug, and GNU Radio 3.8 is not actively supported on this bug tracker so I'll be closing the issue, but I hope to talk with you on the chat server or the email discussion list.
https://wiki.gnuradio.org/index.php?title=MailingLists
