### ISSUE TITLE
grc-qt Variable Editor window does not reinitialize when a new flowgraph is slected

### ISSUE THREAD

**Issue by chrisjohgorman** [gnuradio/gnuradio#7305]
### What happened?

A new flowgraph fails to refresh the variable editor window and populate the window with the variables from the new flowgraph.

### System Information

OS: Arch Linux
GR Installation Method: Source

### GNU Radio Version

3.10 (maint-3.10)

### Specific Version

3.10.10.0

### Steps to Reproduce the Problem

1) Open a flowgraph
2) Select the `new` button
3) The new flowgraph is displayed, but in the Variable Editor window the variables are from the old flowgraph.

**Comment by chrisjohgorman** [comment]
I just noticed an error in this bug report.  

Gnu Radio Version should be 3.10 (maint-3.10)

**Comment by haakov** [comment]
Looks like this has been fixed with https://github.com/gnuradio/gnuradio/pull/7287
