### ISSUE TITLE
`gr_modtool help` should consistently output what `gr_modtool --help` does

### ISSUE THREAD

**Issue by marcusmueller** [gnuradio/gnuradio#7310]
### Feature Description

s. title.

### Feature Urgency

low (just an idea)

### More Information
This would be a nice first modification for someone who wants  to get into improving the devops and user-facing Python tooling that GNU Radio comes with.

**Comment by ajitg25** [comment]
Can you elaborate more on this?

**Comment by sb424dat** [comment]
What is the difference in output?

**Comment by SWITCHin2** [comment]
@marcusmueller I would like to work on it, could assign it to me and also any reference to follow?

**Comment by marcusmueller** [comment]
@SWITCHin2  it's all yours to work on!

Reference to follow: Work against the `main` branch.

Stick with the general style of the code. Code formatting ideally done using pycodestyle or flake8; see the `.flake8` file in the gnuradio/ directory.

Python needs to be clean, generally, but we're not overly picky. Code needs to work with Python 3.7.2 ; when you open a PR, you'll see that we run CI on various platforms.

**Comment by marcusmueller** [comment]
@SWITCHin2 have you had any success?

**Comment by SWITCHin2** [comment]
@marcusmueller not yet!! was trying understand the flow but getting a bit confused, will try my best to fix it soon

**Comment by SWITCHin2** [comment]
Any possible area to look upon?  would be helpful

**Comment by marcusmueller** [comment]
@SWITCHin2 in gnuradio/gr-utils/modtool/cli you find all the implemented commands. Look for example at info.py. You can copy that file as `help.py`, and start changing it to do what it should!

**Comment by SWITCHin2** [comment]
Ok! Thanks :) So did this means currently there is no file like that for `help` command?I was actually for that.

**Comment by marcusmueller** [comment]
Hi! What's the state of things, @SWITCHin2

**Comment by hariharandakshnamurthy** [comment]
@marcusmueller  is this issue still open can i work on it?

**Comment by marcusmueller** [comment]
It says "Open", right :) So, yes, please go ahead!
And: if you have any problems, ask! (It's better to make progress and ask, then to be stuck and not ask :) ). I'm currently heading to bed, but there should be someone online most of the day on our chat, which is on matrix, [#gnuradio:gnuradio.org](https://app.element.io/#/room/#gnuradio:gnuradio.org).

**Comment by kmr-ankitt** [comment]
Can i work over this issue?

**Comment by marcusmueller** [comment]
@kmr-ankitt yes, as I told literally anyone else in here: any issue that's "open" is ready to be fixed :) Go ahead :) Looking forward to your pull request. See the comment above about how you can reach out to the community in case you need any help!
