### ISSUE TITLE
Function Probe is broken due to wrong order of code

### ISSUE THREAD

**Issue by nemanjan00** [gnuradio/gnuradio#7360]
### What happened?

I used Signal Probe and Probe Function blocks. 

Generated python code fails to run, due to `object has no attribute` error

### System Information

OS: Arch Linux
GR Installation Method: Native distro package (3.10.10.0-2)

### GNU Radio Version

3.10 (maint-3.10)

### Specific Version

3.10.10.0

### Steps to Reproduce the Problem

Use both of mentioned blocks

Generated code:

https://gist.github.com/nemanjan00/058d42e4a878c9f3a91e78461663f8af

Line 87 should be after 119 
Line 76 refers to `self.freq_pro` which is set only on 119

Or 76 can be moved into try block

Looking at the `grc/blocks/variable_function_probe.block.yml`, I do not see any way to make sure code is generated in the proper order

Looking a the `grc/core/generator/top_block.py`, looks like blocks are sorted by name (line 213)

### Explanation

The issue is that Function Probe block is generated before Probe Signal, so when thread starts reading Signal Probe, it is not defined on class...

**Comment by willcode** [comment]
@haakov @dl1ksv if you get a chance, this is a race condition in the python generated by GRC.

**Comment by willcode** [comment]
Additional notes in #7360 about potential solutions.
