### ISSUE TITLE
Where is GNU Radio 'conf.d' on Radioconda / Windows 10?

### ISSUE THREAD

**Issue by Hagtronics** [gnuradio/gnuradio#7413]
### What happened?

A 'sorrta bug' - I can't find 'conf.d' on Radioconda Windows 10.

Documentation page,
https://wiki.gnuradio.org/index.php/Configuration_Files

I'm using Radioconda Release 24.05.29

Anyone know where it is hidden?

### System Information

OS Windows 10 22H2
Radioconda installed through Github windows installer

### GNU Radio Version

4.0-git (dev-4.0)

### Specific Version

3.10.10.0

### Steps to Reproduce the Problem

Searched all over - could not find file.

### Relevant log output

```shell
N/A
```

**Comment by willcode** [comment]
Please ask for help at chat.gnuradio.org in the General Chat room, or on the mailing list. The issue tracker is used for bug reports and feature requests.
