### ISSUE TITLE
ImportError - Cannot Import Gnuradio - Generic_type: type "massage_msg_accepter" is already registered Error

### ISSUE THREAD

**Issue by AlperenJosephson** [gnuradio/gnuradio#7469]
### What happened?

When I try to start the GNU Radio Companion application, I encounter an ImportError. However, I am able to launch the application successfully by running gnuradio-companion from the terminal.

### System Information

OS: Linux Ubuntu 22.04.4
GR Installation Method:Source

### GNU Radio Version

3.10 (maint-3.10)

### Specific Version

3.10.7.0

### Steps to Reproduce the Problem

    1.Open the application menu or search bar on your system.
    2.Search for "GNU Radio Companion."
    3.Click on the application to launch it.
    4.Observe the ImportError that occurs, preventing the application from starting.

Observe the ImportError that occurs, preventing the application from starting.

Workaround:

    Running gnuradio-companion directly from the terminal successfully launches the application.

Additional Information

    Python Versions Installed:
        Python 2.7
        Python 3
        Python 3.8
        Python 3.10
        Python 3.11

    GNU Radio Installation:
        GNU Radio's Python modules and libraries are installed for Python 3.

    Environment Variables:
        PYTHONPATH is set to include the Python 3 paths where GNU Radio's modules are located.
        LD_LIBRARY_PATH is set to include the directories where GNU Radio's libraries are located.

Error Screenshot:
![Screenshot from 2024-08-14 15-56-56](https://github.com/user-attachments/assets/ce97d78a-ccae-4eb1-893b-44f8c8dd8ef8)

**Comment by willcode** [comment]
It sounds like this is a configuration issue - something to do with the desktop launcher file and the install path. The launcher may not see the same paths you see in the shell. We can keep the issue here while you experiment more, but I don't think this is a GNU Radio issue based on the description.
