### ISSUE TITLE
gr-vocoder/examples/loopback-codec2.grc flowgraph missing blocks

### ISSUE THREAD

**Issue by wavewalkerdsp** [gnuradio/gnuradio#7494]
### What happened?

In-tree flowgraph gr-vocoder/examples/loopback-codec2.grc is missing blocks vocoder_codec2_encode_sp, vocoder_codec2_decode_sp, blocks do not seem to exist.

![image](https://github.com/user-attachments/assets/7af7f016-ef04-48ec-9f42-2e5e9e53f417)

### System Information

OS: (Linux Distro, Mac, Windows)
GR Installation Method: (native distro packages - apt, rpm, etc., Conda, Source

### GNU Radio Version

3.11-git (main)

### Specific Version

v3.11.0.0git-809-g5c30d92b

### Steps to Reproduce the Problem

Viewable in flowgraph

**Comment by drmpeg** [comment]
Should also be resolved with installing libcodec2-dev.

**Comment by wavewalkerdsp** [comment]
@drmpeg yes thank you, also closing this one
