### ISSUE TITLE
USRP RIO session initialization problem 

### ISSUE THREAD

**Issue by flow233-ai** [gnuradio/gnuradio#7552]
### What happened?

I encounter a problem related with `uhd_usrp_probe`. The setting is Ubuntu 20.04+GNURadio 3.8+UHD 3.15
`GNU C++ version 9.4.0; Boost_107100; UHD_3.15.0.HEAD-0-gaea0e2de`

When I use the `uhd_find_devices`, the USRP can be detected correctly. But with the `uhd_usrp_probe`, the following errors occurs:
`Error: RuntimeError: x300_impl: Could not initialize RIO session. A memory allocation failed. Try again after rebooting. (Error code -52000)`. It is very confusing.

By the way, I installed the GNURadio3.8+UHD3.15 through Radioconda instead of build from the source. I wonder if it is the reason for this situation, or just the problem related with the UHD version.

### System Information

OS: Ubuntu20.04+GNURadio3.8+UHD3.15
GR Installation Method: Radioconda

### GNU Radio Version

3.8  (maint-3.8)

### Specific Version

3.8.2.0

### Steps to Reproduce the Problem

1) Install the Radioconda 2021.03.12.
2) Activate a conda environment.
3) use the command `uhd_usrp_probe` or `sudo uhd_usrp_probe`

**Comment by marcusmueller** [comment]
This is a UHD problem (or more specifically an NI RIO driver problem), I'm afraid, not a GNU Radio problem. Please raise this with NI support or on the USRP-Users mailing list.

Also, GNU Radio 3.8 is something that is unlikely to receive bugfixes by now.
