### ISSUE TITLE
In the MSYS2 environment of Windows, adding the oot module results in a runtime error

### ISSUE THREAD

**Issue by CP3164094** [gnuradio/gnuradio#7562]
### What happened?

When I input ninja, the error is as follows
![image](https://github.com/user-attachments/assets/f9e2e8d6-71ae-460a-8b80-bf1ce8008e4b)
![image](https://github.com/user-attachments/assets/887bd2ba-eef3-4a4d-bd2d-3f192d37e49f)
![image](https://github.com/user-attachments/assets/1d43e381-e876-44bd-9fc4-4093a6a1834e)

### System Information

OS: ( Windows)

### GNU Radio Version

3.10 (maint-3.10)

### Specific Version

3.10.11.0

### Steps to Reproduce the Problem

cmake -DPYTHON_EXECUTABLE="${MINGW_PREFIX}"/bin/python -DCMAKE_INSTALL_PREFIX="${MINGW_PREFIX}" ..
![image](https://github.com/user-attachments/assets/9bfab187-2d2b-4ec1-92be-1986f8aa00f3)
ninja
and then error as shown in the above figure
what should i do
Thanks

**Comment by marcusmueller** [comment]
Hi, as @chrisjohgorman said, it's better to post text than screenshots of text; we can't search for text in images.

**Comment by chrisjohgorman** [comment]
Hi @CP3164094, I'm willing to try to help you debug this, but would need a minimal failing example, or zip file (or tar ball) of your code to do much more.  I've tried both tutorials on making a gr-module and they build without error.  I also tried a bunch of other gr-modules (radar, osmosdr, correctiq and m2k) and none are showing your error.

**Comment by marcusmueller** [comment]
added the "clarification needed" label. Will close issue at the beginning of next year if we can't reproduce by then; also, still insufficient to just have screenshots of console text instead of text.

**Comment by CP3164094** [comment]
> Hi @CP3164094, I'm willing to try to help you debug this, but would need a minimal failing example, or zip file (or tar ball) of your code to do much more. I've tried both tutorials on making a gr-module and they build without error. I also tried a bunch of other gr-modules (radar, osmosdr, correctiq and m2k) and none are showing your error.

Sorry, it was my code issue and it just showed up like this. I have already resolved it. Thank you for your reply.
