### ISSUE TITLE
Variable Editor window shows "" for many variable values rather than a calculated value. 

### ISSUE THREAD

**Issue by marcusmueller** [gnuradio/gnuradio#7596]
### What happened?

spin-out of #6957

### System Information

a

### GNU Radio Version

3.11-git (main)

### Steps to Reproduce the Problem

GRC-Qt

### Relevant log output

```shell
For example a QT GUI Range block's variable.
```

**Comment by haakov** [comment]
Qt GUI Range seems to work, at least for the default case. Are there other examples of values that don't show up properly?

<img width="364" alt="Screenshot_select-area_20241228133733" src="https://github.com/user-attachments/assets/dc3a1324-59e0-477b-b92f-ea377833521d" />

**Comment by marcusmueller** [comment]
The field seems to show literal value, not calculated value. Which seems to be less confusing, and thus the UX-desirable thing. In that, it seems to be reliable, at least the few things I could test. So, closing.
