### ISSUE TITLE
gr-audio windows (source not implemented)

### ISSUE THREAD

**Issue by mbr0wn** [gnuradio/gnuradio#939]
At the moment audio_windows_source::work  has  an '#if 0' enclosing the contents of it's work function (i.e. the block does nothing).
We either need to make a decision to implement this, or delete the block.

**Comment by mbr0wn** [comment]
Author: Ben Reynwar
Date: Wed, 06 March 2013 17:22:25

**Comment by mbr0wn** [comment]
Author: Balint Seeber
Date: Thu, 07 March 2013  0:39:03

**Comment by mbr0wn** [comment]
Author: Johnathan Corgan
Date: Sat, 22 June 2013 13:51:14

**Comment by mbr0wn** [comment]
Author: Johnathan Corgan
Date: Tue, 16 July 2013 18:55:34

**Comment by mbr0wn** [comment]
Author: Johnathan Corgan
Date: Fri, 30 August 2013  6:18:46

**Comment by mbr0wn** [comment]
Author: Johnathan Corgan
Date: Thu, 01 May 2014 20:24:43

**Comment by jmcorgan** [comment]
@gnieboer Can you take a look at this?  It is ancient code and unclear if it was ever working.

**Comment by gnieboer** [comment]
Can do.  It's been on my list but haven't quite gotten there.

**Comment by gnieboer** [comment]
Pull request ready for review.

**Comment by jmcorgan** [comment]
Fixed in #1051
