### ISSUE TITLE
top_block.unlock() deadlock when flow graph contains Python sync_block

### ISSUE THREAD

**Issue by mbr0wn** [gnuradio/gnuradio#943]
When a flow graph contains a sync_block written in Python, calling top_block.lock() and then top_block.unlock() always freezes.

Simple debugging shows the hang is caused by a thread calling sem_wait().

The attached file contains a simple repro.

**Comment by mbr0wn** [comment]
Author: Johnathan Corgan
Date: Sat, 21 September 2013 15:02:32

**Comment by mbr0wn** [comment]
Author: Johnathan Corgan
Date: Thu, 26 September 2013 17:46:52

**Comment by mbr0wn** [comment]
Author: Tom Rondeau
Date: Sun, 29 September 2013 18:40:42

**Comment by mbr0wn** [comment]
Author: Johnathan Corgan
Date: Tue, 30 September 2014 17:24:46

**Comment by mbr0wn** [comment]
Author: Jiří Pinkava
Date: Thu, 12 March 2015  8:21:31

**Comment by mbr0wn** [comment]
Author: Jiří Pinkava
Date: Thu, 12 March 2015  8:23:31

**Comment by mbr0wn** [comment]
Author: Kevin Reid
Date: Thu, 12 March 2015 15:47:24

**Comment by mbr0wn** [comment]
Author: Jiří Pinkava
Date: Sun, 15 March 2015 14:54:09

**Comment by mbr0wn** [comment]
Author: Jiří Pinkava
Date: Sun, 15 March 2015 21:47:09

**Comment by jmcorgan** [comment]
I am unable to replicate this bug with current 3.7.10.1 using the unconnect_test.py from the original bug report 594 in Redmine. @pinkavaj can you retest now and see if the underlying issue has been resolved somewhere along the way?

**Comment by pinkavaj** [comment]
This one should be fixed few months, see test_34a_lock_unlock, test_34b_lock_unlock in gr-blocks/python/blocks/qa_hier_block2.py

**Comment by jmcorgan** [comment]
Ah, yes.  Fixed in #485.
