### ISSUE TITLE
Clean up PSK blocks in GRC

### ISSUE THREAD

**Issue by mbr0wn** [gnuradio/gnuradio#945]
We have DPSK and PSK blocks in GRC but can set differential in the PSK blocks making the DPSK blocks redundant.

**Comment by mbr0wn** [comment]
Author: Tom Rondeau
Date: Tue, 30 September 2014 17:57:03

**Comment by jmcorgan** [comment]
I'd give this to @n-west; it's already been addressed by the 3.8/gr-digital plan he's working on.

**Comment by jmcorgan** [comment]
This is now being tracked in #1081
