### ISSUE TITLE
grc hier block message port issues

### ISSUE THREAD

**Issue by mbr0wn** [gnuradio/gnuradio#946]
When generating a hier block with message port outputs/inputs:
- wildcard pad source/sink blocks generate broken code (needs to be explicitly set to message type or it generates invalid python)
- optional should probably be enabled by default for message ports

**Comment by mbr0wn** [comment]
Author: Johnathan Corgan
Date: Mon, 21 April 2014 15:55:00

**Comment by mbr0wn** [comment]
Author: Johnathan Corgan
Date: Tue, 29 April 2014 16:01:17

**Comment by marcusmueller** [comment]
Since basically everything change regarding code generation, I feel it's Ok to close this.
