### ISSUE TITLE
Handle buffers which are not doubly-mapped appropriately

### ISSUE THREAD

**Issue by mbr0wn** [gnuradio/gnuradio#951]
In the case that a block requires a custom buffer allocator (#730), but is unable to provide a doubly-mapped buffer, this should be handled correctly by the scheduler: e.g. by ensuring that @work()@ is never called with a number of items that would cause the edge of the buffer to be crossed.

Based on discussions held during Co-Processor Working Group session(s) ([[GRCon14CoProc]], [[GRCon13Coprocessor]])

**Comment by mbr0wn** [comment]
Author: Michael Dickens
Date: Wed, 24 September 2014 12:26:09

**Comment by mbr0wn** [comment]
Author: Michael Dickens
Date: Wed, 26 August 2015 19:45:59

**Comment by mbr0wn** [comment]
@douggeiger

**Comment by jmcorgan** [comment]
This work was taken over by @sdh11 and is a work in progress.  Currently, is being tracked by PR #741

**Comment by mbr0wn** [comment]
This is being handled here: https://github.com/gnuradio/gnuradio-ngsched
