### ISSUE TITLE
Message controlled file/signal source

### ISSUE THREAD

**Issue by mbr0wn** [gnuradio/gnuradio#954]
Create a source that is controlled via a message interface. The intent is to make it easier to switch sources programmatically or via a GRC GUI. Currently, flowgraphcs need to be stopped/edited/started to change source. Includes some or all of these features:
1. Play a file, given file name, sample type, repeat/not, offset (in samples) and length to play (in samples)
2. Stop playing
3. Play a vector (signal, packet contents, etc.)
4. Emit a signal (cosine, DC, noise) using appropriate parameters
5. Queue commands to form a simple sequencer, e.g. DTMF. This could just be a queue of other "play" commands.
6. Other sources.

**Comment by marcusmueller** [comment]
I think this is a grad idea, but closing it for now, so many things have changed since then (what we'd probably want is a more useful way of defining a message-controlled FSM)
