### ISSUE TITLE
gnuradio-3.7.5.1/build/gr-vocoder/lib/codec2/codebookjnd.c:3491: possible bad literal ?

### ISSUE THREAD

**Issue by mbr0wn** [gnuradio/gnuradio#956]
gnuradio-3.7.5.1/build/gr-vocoder/lib/codec2/codebookjnd.c:3491:5: warning: implicit conversion from 'double' to 'int' changes value from 11.7181 to 11 [-Wliteral-conversion]

  /* /home/dcb/rpmbuild/BUILD/gnuradio-3.7.5.1/gr-vocoder/lib/codec2/codebook/lspjnd5-10.txt */
  {
    6,
    11.7181,

**Comment by jmcorgan** [comment]
This code is removed in 3.8 in preference to using the system packaged codec2 library, so closing this out.
