### ISSUE TITLE
skip head block should drop corresponding tags

### ISSUE THREAD

**Issue by mbr0wn** [gnuradio/gnuradio#959]
Currently it appears that tags are passed through skip head unmodified, whereas the first N should be dropped along with samples and the remaining offsets should be shifted back by -N

**Comment by pwicks86** [comment]
Made PR for this https://github.com/gnuradio/gnuradio/pull/1804.

**Comment by devnulling** [comment]
@mbr0wn @marcusmueller can this be closed out?

**Comment by mbr0wn** [comment]
Yeah.
