### ISSUE TITLE
PMT Inconsistencies

### ISSUE THREAD

**Issue by mbr0wn** [gnuradio/gnuradio#965]
I'd say these are bed enough they can be considered a bug. Here it goes:

```
P = pmt.cons(pmt.to_pmt('foo'), pmt.to_pmt(1))
if pmt.is_dict(P): # (1)
    length = pmt.length(pmt.dict_items(P)) # Fails
    keys = pmt.dict_keys(P) # Obviously fails
```

It's already annoying that (1) returns true. This makes it impossible to iterate over dicts, because such code doesn't work on pairs.

**Comment by marcusmueller** [comment]
This has been fixed in #3389
