### ISSUE TITLE
qt-gui crashes on OSX 10.10

### ISSUE THREAD

**Issue by mbr0wn** [gnuradio/gnuradio#974]
I don't see this issue on OSX 10.8, but it is repeatable about 50% of the time on 10.10. Marcus tested on his Linux (Fedora, 4.0.7-300.fc22.x86_64), and doesn't see it. But, we all see the "multiple delete" in tracebacks. It seems like a "double delete" works, while a "triple delete" does not work. Here's an example crash log from OSX 10.10:

{{{
Exception Type:        EXC_BAD_ACCESS (SIGSEGV)
Exception Codes:       EXC_I386_GPFLT
Thread 0 Crashed:: Dispatch queue: com.apple.main-thread
0   QtGui                           0x000000010c0e0967
QWidgetPrivate::close_helper(QWidgetPrivate::CloseMode) + 23
1   libgnuradio-qtgui.3.7.7.1.dylib 0x0000000114dc2595
gr::qtgui::time_sink_f_impl::~time_sink_f_impl() + 59
2   libgnuradio-qtgui.3.7.7.1.dylib 0x0000000114dc2682
gr::qtgui::time_sink_f_impl::~time_sink_f_impl() + 22
3   libgnuradio-qtgui.3.7.7.1.dylib 0x0000000114dc26d9
gr::qtgui::time_sink_f_impl::~time_sink_f_impl() + 15
4   _qtgui_swig.so                  0x0000000114c0d119
boost::detail::shared_count::~shared_count() + 45
5   _qtgui_swig.so                  0x0000000114b7aca4
_wrap_delete_time_sink_f_sptr(_object_, _object_) + 116
}}}

**Comment by mbr0wn** [comment]
Author: Michael Dickens
Date: Tue, 28 July 2015 17:24:36

**Comment by mbr0wn** [comment]
Author: Tom Rondeau
Date: Mon, 25 January 2016 10:36:56

**Comment by mbr0wn** [comment]
Author: Michael Dickens
Date: Sun, 31 January 2016  1:09:48

**Comment by mbr0wn** [comment]
@michaelld are there still known crashes of QT GUI on OS X?

**Comment by michaelld** [comment]
I do experience crashes in GR, but not necessarily because of the Qt GUI. Next time I do GR testing, I'll see whether I can track down such a crash & post back here.

**Comment by mbr0wn** [comment]
@michaelld If you can't find any, please close this issue.

**Comment by devnulling** [comment]
@michaelld do you think is still an outstanding issue with 3.8? or should we close this issue until it comes up again?

**Comment by michaelld** [comment]
IDK ... let me try & see what happens. Been a while since I used GRC in QtGUI mode ...

**Comment by marcusmueller** [comment]
Heuristically, I'd say we've had heard from this in the last 9.5 months if this was an outstanding issue, plus I had students working 3.8 on their macbook
