### ISSUE TITLE
gr.msg_queue delete_head_nowait crashes

### ISSUE THREAD

**Issue by mbr0wn** [gnuradio/gnuradio#976]
If a @gr.msg_queue@ contains no messages and the @delete_head_nowait@ method is used from Python, then the return value is a broken object which attempts to dereference a null pointer when used:

<pre>
>>> from gnuradio import gr
>>> q = gr.msg_queue(1)
>>> m = q.delete_head_nowait()
>>> m
<gnuradio.gr.runtime_swig.message_sptr; proxy of <Swig Object of type 'boost::shared_ptr< gr::message > *' at 0x105693ab0> >
>>> m.to_string()
Segmentation fault: 11
</pre>

It would seem most appropriate to return None, but I'm okay with anything as long as it doesn't crash and allows me to tell whether there was a message.

**Comment by marcusmueller** [comment]
This is implemented.
