### ISSUE TITLE
Tag propagation and stream_to_vector

### ISSUE THREAD

**Issue by mbr0wn** [gnuradio/gnuradio#980]
block_executor.cc/propagate_tags() handles offsets on rate changing blocks like this:

new_tag.offset = ((double)new_tag.offset \* rrate) + 0.5;

For the stream_to_vector block (and probably others), this potentially assigns tags from one group of input items to two different output items. The behavior is correct for streams, but doesn't account for groupings of items.

Original problem reported by David Halls.

**Comment by mbr0wn** [comment]
Author: Jeff Long
Date: Thu, 10 September 2015 23:20:08

**Comment by mbr0wn** [comment]
Author: Tom Rondeau
Date: Wed, 30 December 2015 17:22:08

**Comment by mbr0wn** [comment]
Author: Tom Rondeau
Date: Wed, 30 December 2015 21:50:25

**Comment by mbr0wn** [comment]
Author: Jeff Long
Date: Fri, 08 January 2016  0:53:28

**Comment by mbr0wn** [comment]
Author: Jeff Long
Date: Mon, 18 January 2016 21:19:11

**Comment by marcusmueller** [comment]
Tracked elsewhere
