### ISSUE TITLE
GRC pagin/scrolling from keyboard has inconsistent behavior

### ISSUE THREAD

**Issue by mbr0wn** [gnuradio/gnuradio#983]
Ctrl-PgUp and Ctrl-PgDn correctly cause tab switching in GRC when the currently displayed canvas has no horizontal scroll bar.  When there is a horizontal scroll bar, scrolling of the canvas takes over this key combination.  This is confusing to the user.

**Comment by mbr0wn** [comment]
Author: Sebastian Koslowski
Date: Wed, 06 April 2016  7:21:11

- **Status** changed from New to Feedback
Seems to be the default behavior of GTK here. Fixed by forwarding the event to the tab bar.

**Comment by jmcorgan** [comment]
@skoslowski Where was this fixed?

**Comment by skoslowski** [comment]
https://github.com/gnuradio/gnuradio/commit/34f03132741fe1f7aa4e3e29272dea1d25526fbb
