### ISSUE TITLE
Changing certain parameters to message-fed QT waterfall blanks display

### ISSUE THREAD

**Issue by mbr0wn** [gnuradio/gnuradio#988]
I recently did a patch to such_samples2 to add a few display improvements[1]. Along the way I found that if you change a parameter at runtime (eg. center frequency) the scale changes as expected, but the waterfall canvas blanks. Triggering a new bunch of samples to be fed refreshes the display.

[1] https://github.com/ckuethe/gr-pyqt/commit/dd9f94c73406db4a61880eaa90e74e6dcbe47892

**Comment by marcusmueller** [comment]
Can't be reproduced, so sadly closing
