### ISSUE TITLE
glError glOrtho invalid value

### ISSUE THREAD

**Issue by mbr0wn** [gnuradio/gnuradio#990]
Dear all

I noticed a weird issue with gnuradio on a recent Debian Jessie; a simple setup with an Audio Source, a Float-to-Complex and WX GUI Waterfall Sink is producing the following, and that after being functional for a long time already:

@Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/gnuradio/wxgui/plotter/plotter_base.py", line 181, in _on_paint
    GL.glOrtho(0, self.width, self.height, 0, 1, 0)
  File "/usr/lib/python2.7/dist-packages/OpenGL/error.py", line 208, in glCheckError
    baseOperation = baseOperation,
OpenGL.error.GLError: GLError(
        err = 1281,
        description = 'invalid value',
        baseOperation = glOrtho,
        cArguments = (0, 0, 23, 0, 1, 0)
@

If I just use a RTL-SDR Source and a WX GUI Waterfall Sink, everything works fine; nothing was changed on the system recently, it just stopped working.

kind regard
Pascal

**Comment by dkozel** [comment]
With my apologies to Pascal, this issue has rotted and WX is officially removed from active development. If anyone encounters this issue again on the maint-3.7 branch we can reopen and investigate as a maintenance bug fix.
