### ISSUE TITLE
Please integrate VMware tools inside GNU Radio Live SDR

### ISSUE THREAD

**Issue by mbr0wn** [gnuradio/gnuradio#992]
There are a lot of problems with GNU Radio Live SDR Environment under VMware without installed VMware tools.
Inside GNU Radio Live SDR Environment is not possible to install VMware tools, due to DVD file system is read only.
Please integrate VMware tools inside GNU Radio Live SDR Environment.

**Comment by devnulling** [comment]
Closing this as the LiveSDR environment is no longer supported. Recommended "live" version is https://github.com/bastibl/instant-gnuradio
